/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_declverdict_free: (a: number, b: number) => void;
export const __wbg_verifysession_free: (a: number, b: number) => void;
export const __wbg_verifysummary_free: (a: number, b: number) => void;
export const build_pins_json: () => [number, number];
export const declverdict_detail: (a: number) => [number, number];
export const declverdict_index: (a: number) => number;
export const declverdict_kind: (a: number) => [number, number];
export const declverdict_micros: (a: number) => number;
export const declverdict_ms: (a: number) => number;
export const declverdict_name: (a: number) => [number, number];
export const declverdict_verdict: (a: number) => [number, number];
export const kernel_kb_placeholder: () => number;
export const lean4export_commit: () => [number, number];
export const lean_toolchain: () => [number, number];
export const ndjson_format_version: () => [number, number];
export const verify_version: () => [number, number];
export const verifysession_byte_len: (a: number) => number;
export const verifysession_finish: (a: number, b: any, c: number, d: number) => [number, number, number];
export const verifysession_new: (a: number) => number;
export const verifysession_push_bytes: (a: number, b: number, c: number) => void;
export const verifysession_push_chunk: (a: number, b: number, c: number) => void;
export const verifysession_sha256: (a: number) => [number, number];
export const verifysummary_pins_json: (a: number) => [number, number];
export const verifysummary_rejected: (a: number) => number;
export const verifysummary_total: (a: number) => number;
export const verifysummary_unsupported: (a: number) => number;
export const verifysummary_verified: (a: number) => number;
export const verifysummary_wall_ms: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
