//! Multi-candidate answer fusion via voting and weighted aggregation.
//!
//! This module provides the [`AnswerAggregator`] that combines multiple
//! candidate answers generated by different RAG pipelines, models, or
//! retrieval strategies into a single high-quality answer using three
//! configurable strategies:
//!
//! - **`MajorityVote`**: keep sentences that appear across the most candidates.
//! - **`WeightedFusion`**: weight sentences by per-candidate confidence.
//! - **`Extractive`**: take the deduplicated union of all candidate sentences.

pub mod aggregator;
pub mod types;

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests;

pub use aggregator::AnswerAggregator;
pub use types::{
    AggregatedAnswer, AggregationConfig, AggregationError, AggregationStrategy, CandidateAnswer,
};
