#!/usr/bin/env bash
# Build the phop WebAssembly package for the browser demo AND for npm (@cooljapan/phop).
#
# Produces `pkg/` (web target) carrying the full verified pipeline: discovery + CAS (oxieml) +
# e-graph canonicalization (scirs2-symbolic) + SMT proofs (OxiZ). Everything is pure Rust compiled
# to wasm — no server, no native dependency.
#
# Usage:   ./build-wasm.sh
# Demo:    python3 -m http.server 8000   # from this crate dir, then open /www/
# Publish: (cd pkg && npm publish --access public)   # only when explicitly intended
set -euo pipefail

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$CRATE_DIR"

# `web` target so the package works both as a direct browser ES module (the demo) and via bundlers.
wasm-pack build . --target web --out-dir pkg --features smt,egraph

# wasm-pack derives the npm name from the crate (`phop-wasm`); rename to the published identity and
# enrich the metadata. (package.json is regenerated by every build, so this patch runs afterwards.)
node - "$CRATE_DIR/pkg/package.json" <<'NODE'
const fs = require("fs");
const path = process.argv[2];
const pkg = JSON.parse(fs.readFileSync(path, "utf8"));
pkg.name = "@cooljapan/phop";
pkg.homepage = "https://github.com/cool-japan/phop";
pkg.description =
  "Discover AND prove scientific laws entirely in the browser — symbolic regression + CAS + " +
  "SMT (OxiZ), pure Rust + WebAssembly, zero server, zero install.";
fs.writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
console.log("patched npm identity ->", pkg.name, pkg.version);
NODE

echo
echo "pkg/ ready."
echo "  demo:    (cd '$CRATE_DIR' && python3 -m http.server 8000)  then open http://localhost:8000/www/"
echo "  publish: (cd '$CRATE_DIR/pkg' && npm publish --access public)   # only on purpose"
