[package]
name = "oxiphysics-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "WebAssembly bindings for the OxiPhysics engine"
readme = "README.md"
categories = ["science", "simulation", "wasm"]
keywords = ["physics", "wasm", "webassembly", "simulation", "browser"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
serde-wasm-bindgen = { workspace = true }
oxiphysics-lbm = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
web-sys = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[package.metadata.docs.rs]
default-target = "wasm32-unknown-unknown"
rustdoc-args = ["--cfg", "docsrs"]
