//! Hermetic interoperability tests against real bzip2 (libbz2) streams.
//!
//! The `tests/data/python_*.bz2` golden vectors were generated ONCE at
//! development time with CPython's `bz2` module (libbz2); the committed
//! test suite never invokes external tools. The corresponding plaintexts
//! are regenerated deterministically in this file, so the vectors stay
//! small. To regenerate the vectors, evaluate with Python 3 (the
//! `xorshift_data` / `text_data` generators below have exact Python
//! equivalents: xorshift32 with state `0x9E3779B9`, shifts `<<13`, `>>17`,
//! `<<5` masked to 32 bits, 4 little-endian bytes per step; and
//! `"line %07d: the quick brown fox jumps over the lazy dog 0123456789\n"`
//! lines truncated to the target size):
//!
//! * `python_hello100_l9.bz2`   = `bz2.compress(b"hello bzip2 world\n" * 100, 9)`
//! * `python_xorshift64k_l9.bz2`= `bz2.compress(xorshift_data(65536), 9)`
//! * `python_text1m2_l9.bz2`    = `bz2.compress(text_data(1_200_000), 9)`
//! * `python_text250k_l1.bz2`   = `bz2.compress(text_data(250_000), 1)`
//! * `python_empty_l9.bz2`      = `bz2.compress(b"", 9)`
//!
//! The `tests/data/oxiarc_*.bz2` vectors are blessed outputs of this
//! crate's encoder that were verified byte-for-byte decodable by the
//! system `bzip2 -d` at development time (re-blessed 2026-07-13 for the
//! multi-table sendMTFValues encoder). They pin the encoder to a known
//! interoperable serialization: any change to these bytes must be
//! re-verified against a real bzip2 implementation before re-blessing
//! (the `bzip2-oracle` feature suite automates that check).
//!
//! The `tests/data/multistream_*.bz2` fixtures are concatenations of
//! streams produced by the system `bzip2` CLI (levels 9 and 1, plus an
//! empty stream), standing in for pbzip2/lbzip2/`cat` output. The
//! `tests/data/randomised_rep_l1.bz2` fixture carries the legacy
//! randomised-block bit (bzip2 <= 0.9.0 format); it was generated by this
//! crate's test-only randomised encoder and verified byte-identical via
//! `bzip2 -d` at development time (pinned to its generator by a unit
//! test).

use oxiarc_bzip2::{CompressionLevel, compress, decompress, decompress_with_limit};

/// `bz2.compress(b"hello bzip2 world\n" * 100, 9)`
const PY_HELLO100_L9: &[u8] = include_bytes!("data/python_hello100_l9.bz2");
/// `bz2.compress(xorshift_data(65536), 9)`
const PY_XORSHIFT64K_L9: &[u8] = include_bytes!("data/python_xorshift64k_l9.bz2");
/// `bz2.compress(text_data(1_200_000), 9)` — two blocks (>900 KB boundary).
const PY_TEXT1M2_L9: &[u8] = include_bytes!("data/python_text1m2_l9.bz2");
/// `bz2.compress(text_data(250_000), 1)` — several level-1 blocks.
const PY_TEXT250K_L1: &[u8] = include_bytes!("data/python_text250k_l1.bz2");
/// `bz2.compress(b"", 9)`
const PY_EMPTY_L9: &[u8] = include_bytes!("data/python_empty_l9.bz2");

/// Blessed output of `compress(b"hello bzip2 world\n" * 100, level 9)`.
const OXIARC_HELLO100_L9: &[u8] = include_bytes!("data/oxiarc_hello100_l9.bz2");
/// Blessed output of `compress(text_data(250_000), level 1)`.
const OXIARC_TEXT250K_L1: &[u8] = include_bytes!("data/oxiarc_text250k_l1.bz2");

/// `bzip2 -9 (stream_a) || bzip2 -1 (stream_b)` — real CLI streams.
const MULTISTREAM_A9_B1: &[u8] = include_bytes!("data/multistream_a9_b1.bz2");
/// Same with an empty `bzip2 -9` stream between the two.
const MULTISTREAM_A9_EMPTY_B1: &[u8] = include_bytes!("data/multistream_a9_empty_b1.bz2");
/// Legacy randomised-block stream (verified via `bzip2 -d`).
const RANDOMISED_REP_L1: &[u8] = include_bytes!("data/randomised_rep_l1.bz2");

/// Plaintext of the first multi-stream fixture member.
fn multistream_a() -> Vec<u8> {
    b"first stream: hello bzip2 multi-stream world\n".repeat(30)
}

/// Plaintext of the second multi-stream fixture member.
fn multistream_b() -> Vec<u8> {
    b"second stream payload 0123456789\n".repeat(40)
}

/// Deterministic xorshift32 byte stream; must match `gen_bz2_golden.py`.
fn xorshift_data(size: usize) -> Vec<u8> {
    let mut state: u32 = 0x9E37_79B9;
    let mut out = Vec::with_capacity(size + 4);
    while out.len() < size {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        out.extend_from_slice(&state.to_le_bytes());
    }
    out.truncate(size);
    out
}

/// Deterministic text stream; must match `gen_bz2_golden.py`.
fn text_data(size: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(size + 80);
    let mut i = 0usize;
    while out.len() < size {
        out.extend_from_slice(
            format!("line {i:07}: the quick brown fox jumps over the lazy dog 0123456789\n")
                .as_bytes(),
        );
        i += 1;
    }
    out.truncate(size);
    out
}

// ---------------------------------------------------------------------------
// Decompression of real libbz2 streams
// ---------------------------------------------------------------------------

#[test]
fn decodes_real_libbz2_text_stream() {
    let decoded = decompress(PY_HELLO100_L9).expect("decode libbz2 text stream");
    assert_eq!(decoded, b"hello bzip2 world\n".repeat(100));
}

#[test]
fn decodes_real_libbz2_binary_stream() {
    let decoded = decompress(PY_XORSHIFT64K_L9).expect("decode libbz2 binary stream");
    assert_eq!(decoded, xorshift_data(65536));
}

#[test]
fn decodes_real_libbz2_multiblock_over_900k() {
    // 1.2 MB at level 9 spans the 900 KB block boundary: two blocks whose
    // CRCs combine into the stream CRC.
    let decoded = decompress(PY_TEXT1M2_L9).expect("decode libbz2 multi-block stream");
    assert_eq!(decoded, text_data(1_200_000));
}

#[test]
fn decodes_real_libbz2_level1_blocks() {
    // 250 KB at level 1 produces several ~100 KB blocks.
    let decoded = decompress(PY_TEXT250K_L1).expect("decode libbz2 level-1 stream");
    assert_eq!(decoded, text_data(250_000));
}

#[test]
fn decodes_real_libbz2_empty_stream() {
    let decoded = decompress(PY_EMPTY_L9).expect("decode libbz2 empty stream");
    assert!(decoded.is_empty());
}

#[test]
fn rejects_corrupted_block_crc() {
    // Flip one bit inside the compressed payload; the block CRC must catch it.
    let mut corrupted = PY_HELLO100_L9.to_vec();
    let mid = corrupted.len() / 2;
    corrupted[mid] ^= 0x10;
    assert!(decompress(&corrupted[..]).is_err());
}

// ---------------------------------------------------------------------------
// Encoder output pinned to libbz2-verified serializations
// ---------------------------------------------------------------------------

#[test]
fn encoder_output_matches_blessed_interoperable_bytes_text() {
    let data = b"hello bzip2 world\n".repeat(100);
    let compressed = compress(&data, CompressionLevel::new(9)).expect("compress text");
    assert_eq!(
        compressed, OXIARC_HELLO100_L9,
        "encoder serialization drifted from the libbz2-verified blessed vector; \
         re-verify against a real bzip2 decoder before re-blessing"
    );
}

#[test]
fn encoder_output_matches_blessed_interoperable_bytes_multiblock() {
    let data = text_data(250_000);
    let compressed = compress(&data, CompressionLevel::new(1)).expect("compress level-1 blocks");
    assert_eq!(
        compressed, OXIARC_TEXT250K_L1,
        "encoder serialization drifted from the libbz2-verified blessed vector; \
         re-verify against a real bzip2 decoder before re-blessing"
    );
}

#[test]
fn encoder_empty_stream_matches_libbz2_layout() {
    // Header, EOS magic, zero combined CRC: identical to libbz2's empty
    // stream apart from the level digit.
    let compressed = compress(b"", CompressionLevel::new(9)).expect("compress empty");
    assert_eq!(compressed, PY_EMPTY_L9);
}

// ---------------------------------------------------------------------------
// Self round-trips (including the >900 KB multi-block encoder path)
// ---------------------------------------------------------------------------

#[test]
fn roundtrip_binary_data() {
    let data = xorshift_data(300 * 1024);
    let compressed = compress(&data, CompressionLevel::new(1)).expect("compress binary");
    let decoded = decompress(&compressed[..]).expect("decode own binary stream");
    assert_eq!(decoded, data);
}

#[test]
fn roundtrip_text_and_runs() {
    let mut data = "bzip2 round-trip with mixed content \u{65e5}\u{672c}\u{8a9e}\n"
        .repeat(64)
        .into_bytes();
    data.extend_from_slice(&[0xAA; 1000]); // long RLE1 run
    data.extend_from_slice(&[0x00; 4]); // exactly four in a row
    let compressed = compress(&data, CompressionLevel::new(9)).expect("compress text");
    let decoded = decompress(&compressed[..]).expect("decode own text stream");
    assert_eq!(decoded, data);
}

#[test]
fn roundtrip_multiblock_over_900k() {
    // Forces the encoder across its per-block input limit at level 9.
    let data = text_data(1_200_000);
    let compressed = compress(&data, CompressionLevel::new(9)).expect("compress 1.2 MB");
    let decoded = decompress(&compressed[..]).expect("decode own multi-block stream");
    assert_eq!(decoded, data);
}

#[test]
fn roundtrip_all_byte_values() {
    // Exercises a full 256-symbol alphabet (all sixteen symbol-map groups).
    let data: Vec<u8> = (0..=255u8).cycle().take(4096).collect();
    let compressed = compress(&data, CompressionLevel::new(5)).expect("compress all bytes");
    let decoded = decompress(&compressed[..]).expect("decode all-bytes stream");
    assert_eq!(decoded, data);
}

// ---------------------------------------------------------------------------
// Multi-stream (concatenated) decode — pbzip2 / lbzip2 / `cat a.bz2 b.bz2`
// ---------------------------------------------------------------------------

#[test]
fn decodes_multistream_real_cli_fixture() {
    // Two real bzip2 CLI streams at different levels: both must decode,
    // in order, exactly as `bzip2 -d` does.
    let mut expected = multistream_a();
    expected.extend_from_slice(&multistream_b());
    let decoded = decompress(MULTISTREAM_A9_B1).expect("decode two-stream fixture");
    assert_eq!(decoded, expected);
}

#[test]
fn decodes_multistream_with_empty_middle_stream() {
    let mut expected = multistream_a();
    expected.extend_from_slice(&multistream_b());
    let decoded = decompress(MULTISTREAM_A9_EMPTY_B1).expect("decode three-stream fixture");
    assert_eq!(decoded, expected);
}

#[test]
fn multistream_first_stream_only_is_data_loss_no_more() {
    // Regression guard for the original bug: the fixture holds strictly
    // more data than its first stream alone.
    let first_only = multistream_a();
    let decoded = decompress(MULTISTREAM_A9_B1).expect("decode two-stream fixture");
    assert!(decoded.len() > first_only.len());
    assert_eq!(&decoded[..first_only.len()], &first_only[..]);
}

#[test]
fn multistream_with_corrupted_second_stream_is_error() {
    // Corruption in the *second* stream must fail the whole decode.
    let mut corrupted = MULTISTREAM_A9_B1.to_vec();
    let last = corrupted.len() - 20;
    corrupted[last] ^= 0x40;
    assert!(decompress(&corrupted[..]).is_err());
}

#[test]
fn multistream_truncated_second_header_is_error() {
    // Chop the concatenation inside the second stream's 4-byte header:
    // that is a truncated stream, not a clean end of input.
    let first_len = 122; // length of the level-9 first member (see fixture provenance)
    let truncated = &MULTISTREAM_A9_B1[..first_len + 2];
    assert!(decompress(truncated).is_err());
}

#[test]
fn trailing_zero_padding_is_error_not_silent() {
    // Unlike `bzip2 -d` (which warns), a library must not silently ignore
    // trailing bytes: report them so callers can decide.
    let mut padded = multistream_fixture_first_member();
    padded.extend_from_slice(&[0u8; 8]);
    assert!(decompress(&padded[..]).is_err());
}

/// The first member of the two-stream fixture (a complete stream).
fn multistream_fixture_first_member() -> Vec<u8> {
    MULTISTREAM_A9_B1[..122].to_vec()
}

// ---------------------------------------------------------------------------
// Legacy randomised blocks (bzip2 <= 0.9.0)
// ---------------------------------------------------------------------------

#[test]
fn decodes_legacy_randomised_block_fixture() {
    // Fixture verified byte-identical via `bzip2 -d` at development time.
    let decoded = decompress(RANDOMISED_REP_L1).expect("decode randomised fixture");
    assert_eq!(decoded, b"repetitive repetitive repetitive!\n".repeat(64));
}

// ---------------------------------------------------------------------------
// Output-size limit (decompression-bomb guard)
// ---------------------------------------------------------------------------

#[test]
fn decompress_with_limit_accepts_within_budget() {
    let data = text_data(60_000);
    let compressed = compress(&data, CompressionLevel::new(1)).expect("compress");
    let decoded = decompress_with_limit(&compressed[..], 60_000).expect("decode under limit");
    assert_eq!(decoded, data);
}

#[test]
fn decompress_with_limit_rejects_over_budget() {
    let data = text_data(60_000);
    let compressed = compress(&data, CompressionLevel::new(1)).expect("compress");
    assert!(decompress_with_limit(&compressed[..], 59_999).is_err());
}

#[test]
fn multistream_every_truncation_errs_or_is_a_stream_boundary() {
    // Truncating the two-stream fixture at any point must never panic and
    // may only succeed at exact stream boundaries (first member: 122
    // bytes; whole fixture). Everything else is corruption.
    let first = multistream_a();
    let mut both = first.clone();
    both.extend_from_slice(&multistream_b());
    for len in 0..MULTISTREAM_A9_B1.len() {
        match decompress(&MULTISTREAM_A9_B1[..len]) {
            Ok(out) if len == 122 => assert_eq!(out, first),
            Ok(out) => panic!("prefix of {len} bytes decoded Ok ({} bytes out)", out.len()),
            Err(_) => {}
        }
    }
    assert_eq!(decompress(MULTISTREAM_A9_B1).expect("full fixture"), both);
}

#[test]
fn multistream_bit_corruptions_never_panic() {
    // Deterministic xorshift-driven single-byte corruptions across the
    // multi-stream fixture: decode must return (Ok or Err), never panic.
    let mut state: u32 = 0x1234_5678;
    let mut next = move || {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        state
    };
    for _ in 0..500 {
        let mut mutated = MULTISTREAM_A9_B1.to_vec();
        let pos = next() as usize % mutated.len();
        let bit = 1u8 << (next() % 8);
        mutated[pos] ^= bit;
        let _ = decompress(&mutated[..]);
    }
}

#[test]
fn decompress_with_limit_spans_multistream() {
    // The cap applies across concatenated streams, not per stream.
    let total = multistream_a().len() + multistream_b().len();
    let decoded =
        decompress_with_limit(MULTISTREAM_A9_B1, total).expect("decode multi-stream under limit");
    assert_eq!(decoded.len(), total);
    assert!(decompress_with_limit(MULTISTREAM_A9_B1, total - 1).is_err());
}
