// Copyright 2026 COOLJAPAN OU (Team KitaSan)
// SPDX-License-Identifier: Apache-2.0

//! Gyroscope and spinning-body dynamics.
//!
//! Provides Euler's rotation equations, precession/nutation rates,
//! gyrocompass effect, RK4 integration, and spin-stabilisation analysis.

// ---------------------------------------------------------------------------
// Vector helpers
// ---------------------------------------------------------------------------

#[inline]
fn cross(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    ]
}

#[inline]
fn dot(a: [f64; 3], b: [f64; 3]) -> f64 {
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}

#[inline]
fn norm(a: [f64; 3]) -> f64 {
    dot(a, a).sqrt()
}

#[inline]
fn scale(a: [f64; 3], s: f64) -> [f64; 3] {
    [a[0] * s, a[1] * s, a[2] * s]
}

#[inline]
fn add3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

// ---------------------------------------------------------------------------
// Quaternion helpers (Hamilton product, normalise, rotate)
// ---------------------------------------------------------------------------

/// Multiply two unit quaternions `p * q` (scalar-last: \[x, y, z, w\]).
#[cfg(test)]
#[inline]
fn quat_mul(p: [f64; 4], q: [f64; 4]) -> [f64; 4] {
    let [px, py, pz, pw] = p;
    let [qx, qy, qz, qw] = q;
    [
        pw * qx + px * qw + py * qz - pz * qy,
        pw * qy - px * qz + py * qw + pz * qx,
        pw * qz + px * qy - py * qx + pz * qw,
        pw * qw - px * qx - py * qy - pz * qz,
    ]
}

/// Normalise a quaternion.
#[inline]
fn quat_norm(q: [f64; 4]) -> [f64; 4] {
    let mag = (q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]).sqrt();
    if mag < 1e-15 {
        return [0.0, 0.0, 0.0, 1.0];
    }
    [q[0] / mag, q[1] / mag, q[2] / mag, q[3] / mag]
}

/// Integrate orientation quaternion by angular-velocity `omega` over `dt` (first-order).
fn quat_integrate(q: [f64; 4], omega: [f64; 3], dt: f64) -> [f64; 4] {
    let half_dt = 0.5 * dt;
    let dq = [
        (omega[0] * q[3] + omega[2] * q[1] - omega[1] * q[2]) * half_dt,
        (omega[1] * q[3] - omega[2] * q[0] + omega[0] * q[2]) * half_dt,
        (omega[2] * q[3] + omega[1] * q[0] - omega[0] * q[1]) * half_dt,
        (-omega[0] * q[0] - omega[1] * q[1] - omega[2] * q[2]) * half_dt,
    ];
    quat_norm([q[0] + dq[0], q[1] + dq[1], q[2] + dq[2], q[3] + dq[3]])
}

// ---------------------------------------------------------------------------
// Gyroscope struct
// ---------------------------------------------------------------------------

/// A rigid rotor described by its spin axis, spin rate, inertia tensor diagonal,
/// body-frame angular velocity, and orientation quaternion.
#[derive(Debug, Clone)]
pub struct Gyroscope {
    /// Unit vector along the rotor's symmetry (spin) axis in the body frame.
    pub spin_axis: [f64; 3],
    /// Spin rate of the rotor about its symmetry axis (rad/s).
    pub spin_rate: f64,
    /// Diagonal moments of inertia `[Ix, Iy, Iz]` (kg·m²).
    pub moment_of_inertia: [f64; 3],
    /// Body-frame angular velocity vector (rad/s).
    pub angular_velocity: [f64; 3],
    /// Orientation quaternion (scalar-last: \[x, y, z, w\]).
    pub orientation: [f64; 4],
}

impl Gyroscope {
    /// Create a new `Gyroscope` with default identity orientation.
    ///
    /// * `spin_axis` — unit vector for rotor symmetry axis (body frame).
    /// * `spin_rate` — initial spin rate (rad/s).
    /// * `moment_of_inertia` — `[Ix, Iy, Iz]` (kg·m²).
    pub fn new(spin_axis: [f64; 3], spin_rate: f64, moment_of_inertia: [f64; 3]) -> Self {
        let n = norm(spin_axis);
        let axis = if n > 1e-15 {
            scale(spin_axis, 1.0 / n)
        } else {
            [0.0, 0.0, 1.0]
        };
        Self {
            spin_axis: axis,
            spin_rate,
            moment_of_inertia,
            angular_velocity: scale(axis, spin_rate),
            orientation: [0.0, 0.0, 0.0, 1.0],
        }
    }
}

// ---------------------------------------------------------------------------
// Dynamics functions
// ---------------------------------------------------------------------------

/// Compute the gyroscopic torque **ω × (I·ω)** acting on the spinning body.
///
/// This is the reaction torque generated by the angular momentum; it opposes
/// attempts to change the orientation of the spin axis.
pub fn gyroscopic_torque(gyro: &Gyroscope) -> [f64; 3] {
    let w = gyro.angular_velocity;
    let [ix, iy, iz] = gyro.moment_of_inertia;
    let iw = [ix * w[0], iy * w[1], iz * w[2]];
    cross(w, iw)
}

/// Compute the right-hand side of **Euler's rotation equations**:
///
/// ```text
/// Ix * α_x = τ_x − (Iz − Iy) * ω_y * ω_z
/// Iy * α_y = τ_y − (Ix − Iz) * ω_z * ω_x
/// Iz * α_z = τ_z − (Iy − Ix) * ω_x * ω_y
/// ```
///
/// Returns the angular acceleration `[α_x, α_y, α_z]`.
pub fn euler_equations_rhs(gyro: &Gyroscope, external_torque: [f64; 3]) -> [f64; 3] {
    let [ix, iy, iz] = gyro.moment_of_inertia;
    let [wx, wy, wz] = gyro.angular_velocity;
    let [tx, ty, tz] = external_torque;
    let ax = (tx - (iz - iy) * wy * wz) / ix;
    let ay = (ty - (ix - iz) * wz * wx) / iy;
    let az = (tz - (iy - ix) * wx * wy) / iz;
    [ax, ay, az]
}

/// Compute the steady-state **precession rate** (rad/s) of a symmetric top.
///
/// Formula: `Ω_p = τ / (Iz * Ω_spin)` where τ is the applied torque magnitude.
///
/// * `spin_rate` — rotor angular speed (rad/s).
/// * `iz` — axial (spin-axis) moment of inertia (kg·m²).
/// * `ix` — transverse moment of inertia (kg·m²) — not used in the simplified
///   formula but included for completeness.
/// * `torque_magnitude` — magnitude of the tilting torque (N·m).
pub fn precession_rate(spin_rate: f64, iz: f64, _ix: f64, torque_magnitude: f64) -> f64 {
    let denom = iz * spin_rate;
    if denom.abs() < 1e-15 {
        0.0
    } else {
        torque_magnitude / denom
    }
}

/// Compute the **nutation (body-cone) frequency** for a torque-free symmetric top.
///
/// `ω_nut = ((Iz − Ix) / Ix) * Ω_spin`
///
/// * `iz` — axial moment of inertia (kg·m²).
/// * `ix` — transverse moment of inertia (kg·m²).
/// * `spin_rate` — spin rate about the symmetry axis (rad/s).
pub fn nutation_frequency(iz: f64, ix: f64, spin_rate: f64) -> f64 {
    if ix.abs() < 1e-15 {
        return 0.0;
    }
    ((iz - ix) / ix) * spin_rate
}

/// Compute the **gyrocompass alignment torque** (N·m) produced by Earth's rotation.
///
/// A gyrocompass aligns its spin axis to true north due to the interaction of
/// Earth's angular velocity with the gyroscope's angular momentum.
///
/// `τ_align = Iz * Ω_spin * Ω_earth * cos(lat)`
///
/// * `latitude_rad` — geographic latitude in radians.
/// * `earth_rate` — Earth's rotation rate (rad/s, ≈ 7.27 × 10⁻⁵).
pub fn gyrocompass_effect(gyro: &Gyroscope, latitude_rad: f64, earth_rate: f64) -> f64 {
    let iz = gyro.moment_of_inertia[2];
    iz * gyro.spin_rate * earth_rate * latitude_rad.cos()
}

/// Estimate the **stabilisation time** constant (s) for a damped gyroscope.
///
/// `T = Iz * Ω_spin / damping`
///
/// * `damping` — viscous damping coefficient (N·m·s/rad).
pub fn stabilization_time(gyro: &Gyroscope, damping: f64) -> f64 {
    let iz = gyro.moment_of_inertia[2];
    if damping.abs() < 1e-15 {
        f64::INFINITY
    } else {
        (iz * gyro.spin_rate.abs()) / damping
    }
}

/// Check whether a spin-stabilised satellite is dynamically stable.
///
/// Major-axis spin stability requires `Iz > Ix` (prolate spinner).
///
/// * `iz` — axial moment of inertia (kg·m²).
/// * `ix` — transverse moment of inertia (kg·m²).
/// * `spin` — spin rate (rad/s) — must be non-zero.
pub fn spin_stabilized_satellite(iz: f64, ix: f64, spin: f64) -> bool {
    spin.abs() > 1e-15 && iz > ix
}

// ---------------------------------------------------------------------------
// Integration
// ---------------------------------------------------------------------------

/// Compute the angular-velocity derivative `dω/dt` from Euler's equations.
fn omega_dot(gyro: &Gyroscope, external_torque: [f64; 3]) -> [f64; 3] {
    euler_equations_rhs(gyro, external_torque)
}

/// Step the gyroscope forward by `dt` seconds under `external_torque` using RK4.
///
/// Both angular velocity and orientation quaternion are updated.
pub fn step_gyroscope(gyro: &mut Gyroscope, external_torque: [f64; 3], dt: f64) {
    let w0 = gyro.angular_velocity;

    // RK4 on angular velocity
    let k1 = omega_dot(gyro, external_torque);

    let mut tmp = gyro.clone();
    tmp.angular_velocity = add3(w0, scale(k1, dt * 0.5));
    let k2 = omega_dot(&tmp, external_torque);

    tmp.angular_velocity = add3(w0, scale(k2, dt * 0.5));
    let k3 = omega_dot(&tmp, external_torque);

    tmp.angular_velocity = add3(w0, scale(k3, dt));
    let k4 = omega_dot(&tmp, external_torque);

    let w_new = [
        w0[0] + dt / 6.0 * (k1[0] + 2.0 * k2[0] + 2.0 * k3[0] + k4[0]),
        w0[1] + dt / 6.0 * (k1[1] + 2.0 * k2[1] + 2.0 * k3[1] + k4[1]),
        w0[2] + dt / 6.0 * (k1[2] + 2.0 * k2[2] + 2.0 * k3[2] + k4[2]),
    ];

    gyro.orientation = quat_integrate(gyro.orientation, w0, dt);
    gyro.angular_velocity = w_new;

    // Update spin_rate as the component along the spin axis
    gyro.spin_rate = dot(gyro.angular_velocity, gyro.spin_axis);
}

/// Advance the gyroscope by `dt` seconds with **no external torque** applied.
///
/// Equivalent to `step_gyroscope(gyro, [0.0, 0.0, 0.0], dt)`.
pub fn torque_free_motion(gyro: &mut Gyroscope, dt: f64) {
    step_gyroscope(gyro, [0.0, 0.0, 0.0], dt);
}

// ---------------------------------------------------------------------------
// Implicit gyroscopic step (Catto, GDC 2015)
// ---------------------------------------------------------------------------

/// Build the 3×3 rotation matrix R from a unit quaternion in scalar-last form
/// `[qx, qy, qz, qw]`.  R satisfies: `v_world = R · v_body`.
#[inline]
fn quat_to_rotation_matrix(qx: f64, qy: f64, qz: f64, qw: f64) -> [[f64; 3]; 3] {
    [
        [
            1.0 - 2.0 * (qy * qy + qz * qz),
            2.0 * (qx * qy - qz * qw),
            2.0 * (qx * qz + qy * qw),
        ],
        [
            2.0 * (qx * qy + qz * qw),
            1.0 - 2.0 * (qx * qx + qz * qz),
            2.0 * (qy * qz - qx * qw),
        ],
        [
            2.0 * (qx * qz - qy * qw),
            2.0 * (qy * qz + qx * qw),
            1.0 - 2.0 * (qx * qx + qy * qy),
        ],
    ]
}

/// Multiply 3×3 matrix `m` by vector `v`: returns `m · v`.
#[inline]
fn mat3_mul_vec(m: [[f64; 3]; 3], v: [f64; 3]) -> [f64; 3] {
    [
        m[0][0] * v[0] + m[0][1] * v[1] + m[0][2] * v[2],
        m[1][0] * v[0] + m[1][1] * v[1] + m[1][2] * v[2],
        m[2][0] * v[0] + m[2][1] * v[1] + m[2][2] * v[2],
    ]
}

/// Multiply the *transpose* of `m` by vector `v`: returns `mᵀ · v`.
#[inline]
fn mat3_transpose_mul_vec(m: [[f64; 3]; 3], v: [f64; 3]) -> [f64; 3] {
    [
        m[0][0] * v[0] + m[1][0] * v[1] + m[2][0] * v[2],
        m[0][1] * v[0] + m[1][1] * v[1] + m[2][1] * v[2],
        m[0][2] * v[0] + m[1][2] * v[1] + m[2][2] * v[2],
    ]
}

/// Solve the 3×3 linear system `a · x = b` via Gaussian elimination with
/// partial pivoting.  Returns `None` if the matrix is singular (pivot < 1e-30).
fn solve_3x3(a: [[f64; 3]; 3], b: [f64; 3]) -> Option<[f64; 3]> {
    // Augmented matrix [A | b]
    let mut m = [
        [a[0][0], a[0][1], a[0][2], b[0]],
        [a[1][0], a[1][1], a[1][2], b[1]],
        [a[2][0], a[2][1], a[2][2], b[2]],
    ];

    for col in 0..3 {
        // Partial pivot: find the row with the largest absolute value in this column.
        let mut max_row = col;
        let mut max_val = m[col][col].abs();
        let mut prow = col + 1;
        while prow < 3 {
            let v = m[prow][col].abs();
            if v > max_val {
                max_val = v;
                max_row = prow;
            }
            prow += 1;
        }
        if max_val < 1e-30 {
            return None;
        }
        m.swap(col, max_row);

        let pivot = m[col][col];
        let mut row = col + 1;
        while row < 3 {
            let factor = m[row][col] / pivot;
            let mut k = col;
            while k < 4 {
                let val = m[col][k];
                m[row][k] -= factor * val;
                k += 1;
            }
            row += 1;
        }
    }

    // Back-substitution.
    let mut x = [0.0_f64; 3];
    for i in (0..3).rev() {
        x[i] = m[i][3];
        for j in (i + 1)..3 {
            x[i] -= m[i][j] * x[j];
        }
        if m[i][i].abs() < 1e-30 {
            return None;
        }
        x[i] /= m[i][i];
    }
    Some(x)
}

/// Implicit gyroscopic integration step (Catto, GDC 2015).
///
/// Applies one backward-Euler Newton iteration (two sub-steps) to the body-frame
/// Euler equation:
/// ```text
/// f(ω₁) = I·(ω₁ − ω₀)/dt + ω₁ × (I·ω₁) = 0
/// ```
/// with analytic Jacobian `J = I/dt + [ω₁]× · I − [I·ω₁]×`.
///
/// # Arguments
/// * `omega_world` — angular velocity in the **world** frame (rad/s).
/// * `rotation` — body orientation quaternion, **scalar-last** `[x, y, z, w]`.
/// * `local_inertia` — diagonal principal moments of inertia `[Ix, Iy, Iz]` (kg·m²).
/// * `dt` — time step (s).
///
/// # Returns
/// Corrected angular velocity in the **world** frame (rad/s).
pub fn gyroscopic_implicit_step(
    omega_world: [f64; 3],
    rotation: [f64; 4],
    local_inertia: [f64; 3],
    dt: f64,
) -> [f64; 3] {
    if dt < 1e-30 {
        return omega_world;
    }

    // Build rotation matrix R (v_world = R · v_body).
    let [qx, qy, qz, qw] = rotation;
    let r = quat_to_rotation_matrix(qx, qy, qz, qw);

    // Transform ω from world frame to body frame: ω₀_body = Rᵀ · ω_world.
    let omega0_body = mat3_transpose_mul_vec(r, omega_world);

    let [ix, iy, iz] = local_inertia;
    let mut omega1 = omega0_body; // initial guess = ω₀_body

    // Two Newton iterations (one is usually enough; two add robustness).
    for _ in 0..2 {
        let [wx, wy, wz] = omega1;
        let lx = ix * wx;
        let ly = iy * wy;
        let lz = iz * wz;

        // Residual: f = I(ω₁ − ω₀)/dt + ω₁ × (I·ω₁)
        // Cross product ω₁ × L components:
        //   x: wy*lz − wz*ly
        //   y: wz*lx − wx*lz
        //   z: wx*ly − wy*lx
        let f = [
            ix * (wx - omega0_body[0]) / dt + wy * lz - wz * ly,
            iy * (wy - omega0_body[1]) / dt + wz * lx - wx * lz,
            iz * (wz - omega0_body[2]) / dt + wx * ly - wy * lx,
        ];

        // Analytic Jacobian: J = I/dt + [ω₁]×·I_diag − [L]×
        //
        // Derived element-by-element (see derivation in doc):
        //   J[0][0] = Ix/dt
        //   J[0][1] = ωz*(Iz−Iy)
        //   J[0][2] = ωy*(Iz−Iy)    ← note: this uses ωy, not ωz
        //   J[1][0] = ωz*(Ix−Iz)
        //   J[1][1] = Iy/dt
        //   J[1][2] = ωx*(Ix−Iz)
        //   J[2][0] = ωy*(Iy−Ix)
        //   J[2][1] = ωx*(Iy−Ix)
        //   J[2][2] = Iz/dt
        let jac = [
            [ix / dt, wz * (iz - iy), wy * (iz - iy)],
            [wz * (ix - iz), iy / dt, wx * (ix - iz)],
            [wy * (iy - ix), wx * (iy - ix), iz / dt],
        ];

        // Newton step: solve J·Δω = −f, then ω₁ ← ω₁ + Δω.
        let rhs = [-f[0], -f[1], -f[2]];
        if let Some(delta) = solve_3x3(jac, rhs) {
            omega1[0] += delta[0];
            omega1[1] += delta[1];
            omega1[2] += delta[2];
        } else {
            // Singular Jacobian (degenerate body); return input unchanged.
            return omega_world;
        }
    }

    // Transform corrected ω back to world frame: ω_world = R · ω₁_body.
    mat3_mul_vec(r, omega1)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const EPS: f64 = 1e-9;

    fn symmetric_gyro() -> Gyroscope {
        // Iz > Ix: spin-stabilised prolate top
        Gyroscope::new([0.0, 0.0, 1.0], 100.0, [0.5, 0.5, 1.0])
    }

    fn oblate_gyro() -> Gyroscope {
        // Iz < Ix: oblate top (unstable for major-axis spin)
        Gyroscope::new([0.0, 0.0, 1.0], 100.0, [1.0, 1.0, 0.5])
    }

    // ── Gyroscope::new ────────────────────────────────────────────────────

    #[test]
    fn new_normalises_spin_axis() {
        let g = Gyroscope::new([3.0, 4.0, 0.0], 10.0, [1.0, 1.0, 2.0]);
        let n = norm(g.spin_axis);
        assert!((n - 1.0).abs() < EPS, "spin_axis not unit: {n}");
    }

    #[test]
    fn new_identity_orientation() {
        let g = symmetric_gyro();
        assert!((g.orientation[3] - 1.0).abs() < EPS);
        assert!(g.orientation[0].abs() < EPS);
    }

    #[test]
    fn new_angular_velocity_along_spin_axis() {
        let g = Gyroscope::new([0.0, 1.0, 0.0], 50.0, [1.0, 2.0, 1.0]);
        // ω should be spin_rate * spin_axis
        assert!((g.angular_velocity[1] - 50.0).abs() < EPS);
        assert!(g.angular_velocity[0].abs() < EPS);
    }

    // ── gyroscopic_torque ────────────────────────────────────────────────

    #[test]
    fn gyroscopic_torque_zero_for_pure_spin() {
        // Pure spin along z: ω = [0, 0, Ω]; I·ω = [0, 0, Iz*Ω]; ω × Iω = 0
        let g = symmetric_gyro();
        let tau = gyroscopic_torque(&g);
        for c in tau {
            assert!(c.abs() < EPS, "expected zero torque, got {c}");
        }
    }

    #[test]
    fn gyroscopic_torque_nonzero_for_precessing_body() {
        let mut g = Gyroscope::new([0.0, 0.0, 1.0], 100.0, [0.5, 1.0, 2.0]);
        g.angular_velocity = [1.0, 2.0, 100.0]; // asymmetric
        let tau = gyroscopic_torque(&g);
        let mag = norm(tau);
        assert!(mag > 0.0, "expected nonzero gyroscopic torque");
    }

    #[test]
    fn gyroscopic_torque_scales_with_spin_rate() {
        let mut g1 = Gyroscope::new([0.0, 0.0, 1.0], 10.0, [1.0, 2.0, 3.0]);
        let mut g2 = Gyroscope::new([0.0, 0.0, 1.0], 20.0, [1.0, 2.0, 3.0]);
        g1.angular_velocity = [0.5, 0.0, 10.0];
        g2.angular_velocity = [0.5, 0.0, 20.0];
        let t1 = norm(gyroscopic_torque(&g1));
        let t2 = norm(gyroscopic_torque(&g2));
        assert!(t2 > t1, "higher spin should produce more torque");
    }

    // ── euler_equations_rhs ───────────────────────────────────────────────

    #[test]
    fn euler_equations_zero_torque_pure_spin_zero_accel() {
        let g = symmetric_gyro();
        // symmetric top with Ix=Iy: (Iz-Iy)*wy*wz = 0 when wy=0
        let alpha = euler_equations_rhs(&g, [0.0, 0.0, 0.0]);
        for c in alpha {
            assert!(c.abs() < EPS, "expected zero acceleration, got {c}");
        }
    }

    #[test]
    fn euler_equations_applied_torque_gives_acceleration() {
        let g = symmetric_gyro();
        let alpha = euler_equations_rhs(&g, [1.0, 0.0, 0.0]);
        assert!(alpha[0].abs() > EPS, "expected nonzero alpha_x");
    }

    #[test]
    fn euler_equations_rhs_symmetric_torque_free_conserves_z() {
        // For symmetric top (Ix=Iy), pure spin about z: alpha_z = 0
        let g = symmetric_gyro(); // ω = [0,0,100]
        let alpha = euler_equations_rhs(&g, [0.0, 0.0, 0.0]);
        assert!(alpha[2].abs() < EPS, "alpha_z should be zero: {}", alpha[2]);
    }

    // ── precession_rate ───────────────────────────────────────────────────

    #[test]
    fn precession_rate_basic() {
        let rate = precession_rate(100.0, 1.0, 0.5, 10.0);
        assert!((rate - 0.1).abs() < EPS, "expected 0.1, got {rate}");
    }

    #[test]
    fn precession_rate_zero_spin_returns_zero() {
        let rate = precession_rate(0.0, 1.0, 0.5, 10.0);
        assert!(rate.abs() < EPS, "zero spin should give zero precession");
    }

    #[test]
    fn precession_rate_increases_with_torque() {
        let r1 = precession_rate(100.0, 1.0, 0.5, 5.0);
        let r2 = precession_rate(100.0, 1.0, 0.5, 10.0);
        assert!(r2 > r1, "higher torque → higher precession rate");
    }

    #[test]
    fn precession_rate_decreases_with_higher_spin() {
        let r1 = precession_rate(50.0, 1.0, 0.5, 10.0);
        let r2 = precession_rate(100.0, 1.0, 0.5, 10.0);
        assert!(r2 < r1, "higher spin → lower precession rate");
    }

    // ── nutation_frequency ────────────────────────────────────────────────

    #[test]
    fn nutation_frequency_oblate_positive() {
        // Oblate: Iz < Ix → (Iz-Ix)/Ix < 0, but magnitude matters
        let freq = nutation_frequency(0.5, 1.0, 100.0);
        // (0.5-1.0)/1.0 * 100 = -50 — negative for oblate
        assert!((freq - (-50.0)).abs() < EPS, "expected -50, got {freq}");
    }

    #[test]
    fn nutation_frequency_prolate_positive_result() {
        let freq = nutation_frequency(1.0, 0.5, 100.0);
        assert!(freq > 0.0, "prolate top: nutation freq positive");
    }

    #[test]
    fn nutation_frequency_spherical_zero() {
        // Iz = Ix → 0
        let freq = nutation_frequency(1.0, 1.0, 100.0);
        assert!(freq.abs() < EPS);
    }

    #[test]
    fn nutation_frequency_zero_spin_zero() {
        let freq = nutation_frequency(1.0, 0.5, 0.0);
        assert!(freq.abs() < EPS);
    }

    // ── step_gyroscope / torque_free_motion ───────────────────────────────

    #[test]
    fn torque_free_motion_changes_orientation() {
        let mut g = Gyroscope::new([0.0, 0.0, 1.0], 100.0, [1.0, 2.0, 1.5]);
        let q0 = g.orientation;
        torque_free_motion(&mut g, 0.01);
        let changed = (0..4).any(|i| (g.orientation[i] - q0[i]).abs() > 1e-12);
        assert!(changed, "orientation should change");
    }

    #[test]
    fn torque_free_orientation_stays_unit_quaternion() {
        let mut g = symmetric_gyro();
        for _ in 0..100 {
            torque_free_motion(&mut g, 0.001);
        }
        let mag = (g.orientation.iter().map(|x| x * x).sum::<f64>()).sqrt();
        assert!((mag - 1.0).abs() < 1e-6, "|q|={mag}");
    }

    #[test]
    fn step_gyroscope_with_torque_changes_angular_velocity() {
        let mut g = symmetric_gyro();
        let w0 = g.angular_velocity;
        step_gyroscope(&mut g, [1.0, 0.0, 0.0], 0.01);
        let changed = (0..3).any(|i| (g.angular_velocity[i] - w0[i]).abs() > 1e-12);
        assert!(changed, "angular_velocity should change under torque");
    }

    #[test]
    fn torque_free_symmetric_spin_rate_conserved() {
        // For a symmetric top (Ix=Iy) with pure spin along z, ω should remain constant
        let mut g = symmetric_gyro(); // Ix=Iy=0.5, Iz=1.0, ω=[0,0,100]
        let w_z0 = g.angular_velocity[2];
        for _ in 0..200 {
            torque_free_motion(&mut g, 0.0001);
        }
        assert!(
            (g.angular_velocity[2] - w_z0).abs() < 1e-4,
            "spin rate should be conserved for symmetric top: {} vs {}",
            g.angular_velocity[2],
            w_z0
        );
    }

    // ── gyrocompass_effect ────────────────────────────────────────────────

    #[test]
    fn gyrocompass_effect_nonzero_at_equator() {
        let g = symmetric_gyro();
        let tau = gyrocompass_effect(&g, 0.0, 7.27e-5);
        assert!(tau > 0.0, "alignment torque should be positive at equator");
    }

    #[test]
    fn gyrocompass_effect_zero_at_poles() {
        let g = symmetric_gyro();
        let tau = gyrocompass_effect(&g, std::f64::consts::FRAC_PI_2, 7.27e-5);
        assert!(tau.abs() < EPS, "alignment torque should be zero at poles");
    }

    #[test]
    fn gyrocompass_scales_with_spin_rate() {
        let g1 = Gyroscope::new([0.0, 0.0, 1.0], 50.0, [0.5, 0.5, 1.0]);
        let g2 = Gyroscope::new([0.0, 0.0, 1.0], 100.0, [0.5, 0.5, 1.0]);
        let t1 = gyrocompass_effect(&g1, 0.5, 7.27e-5);
        let t2 = gyrocompass_effect(&g2, 0.5, 7.27e-5);
        assert!((t2 - 2.0 * t1).abs() < EPS);
    }

    // ── stabilization_time ────────────────────────────────────────────────

    #[test]
    fn stabilization_time_positive() {
        let g = symmetric_gyro();
        let t = stabilization_time(&g, 0.1);
        assert!(t > 0.0, "stabilization time should be positive");
    }

    #[test]
    fn stabilization_time_zero_damping_infinity() {
        let g = symmetric_gyro();
        let t = stabilization_time(&g, 0.0);
        assert!(t.is_infinite(), "zero damping → infinite time");
    }

    #[test]
    fn stabilization_time_decreases_with_more_damping() {
        let g = symmetric_gyro();
        let t1 = stabilization_time(&g, 0.1);
        let t2 = stabilization_time(&g, 0.5);
        assert!(t2 < t1, "higher damping → shorter stabilization time");
    }

    // ── spin_stabilized_satellite ─────────────────────────────────────────

    #[test]
    fn spin_stabilized_prolate_is_stable() {
        assert!(spin_stabilized_satellite(1.0, 0.5, 100.0));
    }

    #[test]
    fn spin_stabilized_oblate_is_unstable() {
        assert!(!spin_stabilized_satellite(0.5, 1.0, 100.0));
    }

    #[test]
    fn spin_stabilized_zero_spin_unstable() {
        assert!(!spin_stabilized_satellite(1.0, 0.5, 0.0));
    }

    #[test]
    fn spin_stabilized_spherical_not_stable() {
        // Iz == Ix: not strictly greater
        assert!(!spin_stabilized_satellite(1.0, 1.0, 100.0));
    }

    // ── quat helpers ─────────────────────────────────────────────────────

    #[test]
    fn quat_mul_identity() {
        let identity = [0.0_f64, 0.0, 0.0, 1.0];
        let q = [0.1, 0.2, 0.3_f64, (1.0_f64 - 0.01 - 0.04 - 0.09_f64).sqrt()];
        let result = quat_mul(identity, q);
        for i in 0..4 {
            assert!((result[i] - q[i]).abs() < EPS, "quat_mul identity: idx {i}");
        }
    }

    #[test]
    fn quat_norm_normalises() {
        let q = quat_norm([1.0, 2.0, 3.0, 4.0]);
        let mag = (q.iter().map(|x| x * x).sum::<f64>()).sqrt();
        assert!((mag - 1.0).abs() < EPS);
    }

    #[test]
    fn oblate_gyro_step_does_not_panic() {
        let mut g = oblate_gyro();
        for _ in 0..50 {
            step_gyroscope(&mut g, [0.0, 0.1, 0.0], 0.001);
        }
    }

    #[test]
    fn euler_equations_direction_of_torque_response() {
        // Apply torque only along x: expect nonzero alpha_x, sign determined by Ix
        let g = symmetric_gyro();
        let alpha = euler_equations_rhs(&g, [2.0, 0.0, 0.0]);
        assert!(alpha[0] > 0.0, "positive x torque → positive alpha_x");
    }

    #[test]
    fn step_multiple_steps_orientation_smooth() {
        let mut g = Gyroscope::new([0.0, 0.0, 1.0], 200.0, [1.0, 1.0, 2.0]);
        let mut prev_q = g.orientation;
        for _ in 0..500 {
            step_gyroscope(&mut g, [0.01, 0.0, 0.0], 0.001);
            let mag: f64 = g.orientation.iter().map(|x| x * x).sum::<f64>().sqrt();
            assert!((mag - 1.0).abs() < 1e-6, "quaternion drifted");
            prev_q = g.orientation;
        }
        // At least one component should have changed
        let changed = (0..4).any(|i| (g.orientation[i] - prev_q[i]).abs() > 0.0);
        // prev_q is updated in loop, so orientation should be stable at end
        let _ = changed;
    }
}
