//! AI-powered metadata enrichment for media assets.
//!
//! Provides rule-based and structural enrichment of asset metadata without
//! requiring a live inference server.  When the full `oximedia-neural` scene
//! classifier is available (feature-gated), results from the neural backend
//! are merged with the rule-based layer.
//!
//! # Architecture
//! ```text
//!  ┌────────────────────────────────┐
//!  │  MetadataEnricher              │
//!  │  ┌─────────────┐              │
//!  │  │ RuleEngine  │  filename /  │
//!  │  │             │  extension   │
//!  │  └─────────────┘  patterns    │
//!  │  ┌─────────────┐              │
//!  │  │ NeuralBackend│  (optional) │
//!  │  └─────────────┘              │
//!  └────────────────────────────────┘
//!         │ EnrichedMetadata
//!         ▼
//! ```
//!
//! # Example
//! ```rust
//! use oximedia_mam::ai_enrichment::{AiEnrichmentConfig, MetadataEnricher};
//!
//! let cfg = AiEnrichmentConfig::default();
//! let enricher = MetadataEnricher::new(cfg);
//! let result = enricher.enrich("holiday_video.mp4", b"");
//! assert!(!result.tags.is_empty());
//! ```

use std::collections::HashMap;

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

/// Configuration for the AI enrichment pipeline.
#[derive(Debug, Clone)]
pub struct AiEnrichmentConfig {
    /// Enable automatic tag generation.
    pub auto_tag: bool,
    /// Enable automatic short caption generation.
    pub auto_caption: bool,
    /// Enable automatic high-level category classification.
    pub auto_classify: bool,
    /// Minimum confidence threshold [0.0, 1.0] for a tag/category to be kept.
    pub confidence_threshold: f32,
    /// Maximum number of tags to retain.
    pub max_tags: usize,
}

impl Default for AiEnrichmentConfig {
    fn default() -> Self {
        Self {
            auto_tag: true,
            auto_caption: true,
            auto_classify: true,
            confidence_threshold: 0.3,
            max_tags: 20,
        }
    }
}

impl AiEnrichmentConfig {
    /// Create a fully enabled config with default thresholds.
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a config with all AI features disabled (pass-through mode).
    pub fn disabled() -> Self {
        Self {
            auto_tag: false,
            auto_caption: false,
            auto_classify: false,
            confidence_threshold: 1.0,
            max_tags: 0,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Output types
// ─────────────────────────────────────────────────────────────────────────────

/// Enriched metadata produced by the [`MetadataEnricher`].
#[derive(Debug, Clone, Default)]
pub struct EnrichedMetadata {
    /// Human-readable tags (keywords) discovered for the asset.
    pub tags: Vec<String>,
    /// Confidence scores aligned 1-to-1 with `tags`.
    pub confidence: Vec<f32>,
    /// Optional short auto-generated caption.
    pub auto_caption: Option<String>,
    /// Broad category labels (e.g., "sports", "nature", "documentary").
    pub categories: Vec<String>,
    /// Arbitrary key/value metadata pairs generated by the enrichment rules.
    pub extra: HashMap<String, String>,
}

impl EnrichedMetadata {
    /// Filter `tags` and `confidence` by the given minimum confidence value.
    pub fn filter_by_confidence(&mut self, min: f32) {
        let pairs: Vec<(String, f32)> = self
            .tags
            .drain(..)
            .zip(self.confidence.drain(..))
            .filter(|(_, c)| *c >= min)
            .collect();
        self.tags = pairs.iter().map(|(t, _)| t.clone()).collect();
        self.confidence = pairs.iter().map(|(_, c)| *c).collect();
    }

    /// Merge another `EnrichedMetadata` into this one, deduplicating tags.
    pub fn merge(&mut self, other: EnrichedMetadata) {
        // Merge tags + confidence (avoid duplicates).
        for (tag, conf) in other.tags.into_iter().zip(other.confidence.into_iter()) {
            if !self.tags.contains(&tag) {
                self.tags.push(tag);
                self.confidence.push(conf);
            }
        }
        // Merge categories.
        for cat in other.categories {
            if !self.categories.contains(&cat) {
                self.categories.push(cat);
            }
        }
        // Caption wins if we don't have one.
        if self.auto_caption.is_none() {
            self.auto_caption = other.auto_caption;
        }
        // Merge extra, existing keys win.
        for (k, v) in other.extra {
            self.extra.entry(k).or_insert(v);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Rule engine
// ─────────────────────────────────────────────────────────────────────────────

/// A single enrichment rule that matches on filename/extension patterns.
#[derive(Debug, Clone)]
pub struct EnrichmentRule {
    /// A substring that must appear in the lowercased filename (including extension)
    /// for this rule to fire.  Use `""` to always match.
    pub pattern: String,
    /// Tags to inject when the rule matches.
    pub tags: Vec<String>,
    /// Confidence assigned to injected tags.
    pub confidence: f32,
    /// Category to inject (optional).
    pub category: Option<String>,
    /// Extra metadata key/value pairs to inject.
    pub extra: HashMap<String, String>,
}

impl EnrichmentRule {
    /// Create a simple tag-injection rule.
    pub fn new(pattern: impl Into<String>, tags: Vec<String>, confidence: f32) -> Self {
        Self {
            pattern: pattern.into(),
            tags,
            confidence,
            category: None,
            extra: HashMap::new(),
        }
    }

    /// Check whether this rule matches the given lowercased filename.
    pub fn matches(&self, lower_name: &str) -> bool {
        self.pattern.is_empty() || lower_name.contains(self.pattern.as_str())
    }
}

/// Rule-based enrichment engine.
///
/// Applies a list of [`EnrichmentRule`]s in order against the lowercased
/// filename and accumulates tags, categories, and captions.
#[derive(Debug, Clone, Default)]
pub struct RuleEngine {
    rules: Vec<EnrichmentRule>,
}

impl RuleEngine {
    /// Create an engine with an empty rule set.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a rule to the engine.
    pub fn add_rule(&mut self, rule: EnrichmentRule) {
        self.rules.push(rule);
    }

    /// Apply all matching rules to `filename` and return the accumulated result.
    pub fn apply(&self, filename: &str) -> EnrichedMetadata {
        let lower = filename.to_lowercase();
        let mut result = EnrichedMetadata::default();

        for rule in &self.rules {
            if rule.matches(&lower) {
                for tag in &rule.tags {
                    if !result.tags.contains(tag) {
                        result.tags.push(tag.clone());
                        result.confidence.push(rule.confidence);
                    }
                }
                if let Some(ref cat) = rule.category {
                    if !result.categories.contains(cat) {
                        result.categories.push(cat.clone());
                    }
                }
                for (k, v) in &rule.extra {
                    result.extra.entry(k.clone()).or_insert_with(|| v.clone());
                }
            }
        }
        result
    }
}

/// Build the default rule set that covers common media filename patterns.
fn default_rule_engine() -> RuleEngine {
    let mut engine = RuleEngine::new();

    // ── Extension-based rules ──────────────────────────────────────────────
    let ext_rules: &[(&str, &[&str], f32, &str)] = &[
        (".mp4", &["video", "mp4"], 0.95, "video"),
        (".mov", &["video", "quicktime"], 0.95, "video"),
        (".mkv", &["video", "matroska"], 0.95, "video"),
        (".avi", &["video", "avi"], 0.90, "video"),
        (".webm", &["video", "webm"], 0.90, "video"),
        (".mp3", &["audio", "mp3"], 0.95, "audio"),
        (".flac", &["audio", "flac", "lossless"], 0.95, "audio"),
        (".wav", &["audio", "wav", "pcm"], 0.95, "audio"),
        (".ogg", &["audio", "ogg"], 0.90, "audio"),
        (".jpg", &["image", "jpeg"], 0.95, "image"),
        (".jpeg", &["image", "jpeg"], 0.95, "image"),
        (".png", &["image", "png"], 0.95, "image"),
        (".tiff", &["image", "tiff", "raw"], 0.90, "image"),
        (".dng", &["image", "raw", "dng"], 0.90, "image"),
        (".pdf", &["document", "pdf"], 0.95, "document"),
    ];

    for (ext, tags, conf, cat) in ext_rules {
        let mut rule =
            EnrichmentRule::new(*ext, tags.iter().map(|t| t.to_string()).collect(), *conf);
        rule.category = Some(cat.to_string());
        engine.add_rule(rule);
    }

    // ── Keyword-based subject rules ────────────────────────────────────────
    let kw_rules: &[(&str, &[&str], f32, &str)] = &[
        (
            "interview",
            &["interview", "talking-head"],
            0.80,
            "interview",
        ),
        (
            "tutorial",
            &["tutorial", "educational"],
            0.80,
            "educational",
        ),
        ("trailer", &["trailer", "promo"], 0.85, "promo"),
        ("timelapse", &["timelapse", "time-lapse"], 0.85, "timelapse"),
        ("broll", &["b-roll", "supplemental"], 0.75, "b-roll"),
        ("b_roll", &["b-roll", "supplemental"], 0.75, "b-roll"),
        ("highlight", &["highlight", "reel"], 0.80, "highlight"),
        ("behind", &["bts", "behind-the-scenes"], 0.80, "bts"),
        ("bts", &["bts", "behind-the-scenes"], 0.85, "bts"),
        ("livestream", &["live", "stream"], 0.80, "live"),
        (
            "screengrab",
            &["screen-recording"],
            0.80,
            "screen-recording",
        ),
        ("screencap", &["screen-recording"], 0.80, "screen-recording"),
        ("drone", &["aerial", "drone"], 0.85, "aerial"),
        ("aerial", &["aerial"], 0.85, "aerial"),
        ("macro", &["macro", "close-up"], 0.80, "macro"),
        ("slowmo", &["slow-motion"], 0.85, "slow-motion"),
        ("slo_mo", &["slow-motion"], 0.85, "slow-motion"),
        ("4k", &["4k", "uhd"], 0.80, "uhd"),
        ("uhd", &["uhd", "4k"], 0.80, "uhd"),
        ("hdr", &["hdr"], 0.80, "hdr"),
    ];

    for (kw, tags, conf, cat) in kw_rules {
        let mut rule =
            EnrichmentRule::new(*kw, tags.iter().map(|t| t.to_string()).collect(), *conf);
        rule.category = Some(cat.to_string());
        engine.add_rule(rule);
    }

    engine
}

// ─────────────────────────────────────────────────────────────────────────────
// Neural backend stub
// ─────────────────────────────────────────────────────────────────────────────

/// Result from the neural scene classifier.
///
/// In a production system this would be populated by calling into
/// `oximedia-neural`'s scene classification pipeline with the decoded
/// frame data.  Here we provide a pure-Rust placeholder that always returns
/// an empty result so the crate compiles without an ML runtime dependency.
#[derive(Debug, Clone, Default)]
pub struct NeuralClassifierResult {
    /// Scene class labels.
    pub labels: Vec<String>,
    /// Confidence scores, aligned with `labels`.
    pub scores: Vec<f32>,
}

/// Thin wrapper around the neural scene classifier.
///
/// Implement `classify_bytes` to connect to `oximedia-neural` when that
/// crate is available as a workspace dependency.
#[derive(Debug, Clone, Default)]
pub struct NeuralBackend;

impl NeuralBackend {
    /// Create a new backend.
    pub fn new() -> Self {
        Self
    }

    /// Classify a media asset from its raw bytes.
    ///
    /// The current implementation is a rule-based stub that inspects the
    /// first few bytes (magic numbers) and returns coarse labels.  When
    /// `oximedia-neural` is wired in, replace this body with an actual
    /// forward pass through the scene-classification model.
    pub fn classify_bytes(&self, filename: &str, data: &[u8]) -> NeuralClassifierResult {
        let mut labels = Vec::new();
        let mut scores = Vec::new();

        // Detect basic media type from magic bytes.
        let media_type = detect_media_type_from_magic(data);
        if let Some(mt) = media_type {
            labels.push(mt.to_string());
            scores.push(0.90);
        }

        // Supplement from filename extension as a fallback.
        let lower = filename.to_lowercase();
        if lower.ends_with(".mp4") || lower.ends_with(".mov") || lower.ends_with(".mkv") {
            if !labels.contains(&"video".to_string()) {
                labels.push("video".to_string());
                scores.push(0.85);
            }
        } else if lower.ends_with(".mp3") || lower.ends_with(".flac") || lower.ends_with(".wav") {
            if !labels.contains(&"audio".to_string()) {
                labels.push("audio".to_string());
                scores.push(0.85);
            }
        } else if lower.ends_with(".jpg") || lower.ends_with(".jpeg") || lower.ends_with(".png") {
            if !labels.contains(&"image".to_string()) {
                labels.push("image".to_string());
                scores.push(0.85);
            }
        }

        NeuralClassifierResult { labels, scores }
    }
}

/// Detect the broad media type from the first few magic bytes.
fn detect_media_type_from_magic(data: &[u8]) -> Option<&'static str> {
    if data.len() < 4 {
        return None;
    }
    match &data[..4] {
        // JPEG: FF D8 FF
        [0xFF, 0xD8, 0xFF, _] => Some("image"),
        // PNG: 89 50 4E 47
        [0x89, 0x50, 0x4E, 0x47] => Some("image"),
        // MP3 ID3
        [0x49, 0x44, 0x33, _] => Some("audio"),
        // RIFF (WAV, AVI)
        [0x52, 0x49, 0x46, 0x46] => {
            if data.len() >= 12 {
                match &data[8..12] {
                    [0x57, 0x41, 0x56, 0x45] => Some("audio"), // WAVE
                    [0x41, 0x56, 0x49, 0x20] => Some("video"), // AVI
                    _ => Some("audio"),
                }
            } else {
                Some("audio")
            }
        }
        // fLaC
        [0x66, 0x4C, 0x61, 0x43] => Some("audio"),
        // PDF
        [0x25, 0x50, 0x44, 0x46] => Some("document"),
        _ => None,
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Caption generator
// ─────────────────────────────────────────────────────────────────────────────

/// Generate a short, human-readable caption from enriched data.
fn generate_caption(filename: &str, tags: &[String], categories: &[String]) -> String {
    let stem = std::path::Path::new(filename)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(filename)
        .replace(['_', '-'], " ");

    if !categories.is_empty() && !tags.is_empty() {
        format!(
            "{} — {} ({})",
            stem,
            categories.join(", "),
            tags.iter().take(3).cloned().collect::<Vec<_>>().join(", ")
        )
    } else if !categories.is_empty() {
        format!("{} — {}", stem, categories.join(", "))
    } else if !tags.is_empty() {
        format!(
            "{} [{}]",
            stem,
            tags.iter().take(3).cloned().collect::<Vec<_>>().join(", ")
        )
    } else {
        stem
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// MetadataEnricher
// ─────────────────────────────────────────────────────────────────────────────

/// Orchestrates rule-based and neural enrichment for a media asset.
///
/// # Usage
/// ```rust
/// use oximedia_mam::ai_enrichment::{AiEnrichmentConfig, MetadataEnricher};
///
/// let enricher = MetadataEnricher::new(AiEnrichmentConfig::default());
/// let meta = enricher.enrich("interview_2024.mp4", b"");
/// assert!(meta.categories.contains(&"interview".to_string())
///      || meta.categories.contains(&"video".to_string()));
/// ```
#[derive(Debug, Clone)]
pub struct MetadataEnricher {
    config: AiEnrichmentConfig,
    rule_engine: RuleEngine,
    neural_backend: NeuralBackend,
}

impl MetadataEnricher {
    /// Create a new enricher with the given config and the built-in rule set.
    pub fn new(config: AiEnrichmentConfig) -> Self {
        Self {
            rule_engine: default_rule_engine(),
            neural_backend: NeuralBackend::new(),
            config,
        }
    }

    /// Create an enricher with a custom rule set.
    pub fn with_rules(config: AiEnrichmentConfig, rules: Vec<EnrichmentRule>) -> Self {
        let mut engine = RuleEngine::new();
        for r in rules {
            engine.add_rule(r);
        }
        Self {
            rule_engine: engine,
            neural_backend: NeuralBackend::new(),
            config,
        }
    }

    /// Enrich a media asset identified by `filename` with optional raw bytes
    /// for magic-number detection.
    ///
    /// Steps:
    /// 1. Rule-based enrichment from filename patterns.
    /// 2. Neural classification from raw bytes (if `auto_classify` is set).
    /// 3. Caption generation (if `auto_caption` is set).
    /// 4. Filtering by confidence threshold.
    /// 5. Tag count limiting.
    pub fn enrich(&self, filename: &str, data: &[u8]) -> EnrichedMetadata {
        let mut result = EnrichedMetadata::default();

        // 1. Rule-based tags + categories.
        if self.config.auto_tag || self.config.auto_classify {
            let rule_result = self.rule_engine.apply(filename);
            result.merge(rule_result);
        }

        // 2. Neural classification.
        if self.config.auto_classify {
            let neural = self.neural_backend.classify_bytes(filename, data);
            for (label, score) in neural.labels.into_iter().zip(neural.scores.into_iter()) {
                if !result.tags.contains(&label) {
                    result.tags.push(label.clone());
                    result.confidence.push(score);
                }
                if !result.categories.contains(&label) {
                    result.categories.push(label);
                }
            }
        }

        // 3. Caption.
        if self.config.auto_caption && result.auto_caption.is_none() {
            result.auto_caption =
                Some(generate_caption(filename, &result.tags, &result.categories));
        }

        // 4. Confidence filtering.
        result.filter_by_confidence(self.config.confidence_threshold);

        // 5. Tag limit.
        if result.tags.len() > self.config.max_tags {
            result.tags.truncate(self.config.max_tags);
            result.confidence.truncate(self.config.max_tags);
        }

        result
    }

    /// Enrich with explicit extra metadata key/value pairs (e.g., from sidecar files).
    pub fn enrich_with_extra(
        &self,
        filename: &str,
        data: &[u8],
        extra: HashMap<String, String>,
    ) -> EnrichedMetadata {
        let mut result = self.enrich(filename, data);
        for (k, v) in extra {
            result.extra.insert(k, v);
        }
        result
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn enricher() -> MetadataEnricher {
        MetadataEnricher::new(AiEnrichmentConfig::default())
    }

    // ── AiEnrichmentConfig ───────────────────────────────────────────────────

    #[test]
    fn test_config_default() {
        let cfg = AiEnrichmentConfig::default();
        assert!(cfg.auto_tag);
        assert!(cfg.auto_caption);
        assert!(cfg.auto_classify);
        assert!(cfg.max_tags > 0);
    }

    #[test]
    fn test_config_disabled() {
        let cfg = AiEnrichmentConfig::disabled();
        assert!(!cfg.auto_tag);
        assert!(!cfg.auto_caption);
        assert!(!cfg.auto_classify);
    }

    // ── EnrichedMetadata merge / filter ──────────────────────────────────────

    #[test]
    fn test_enriched_metadata_merge_no_duplicates() {
        let mut a = EnrichedMetadata::default();
        a.tags.push("video".to_string());
        a.confidence.push(0.9);

        let mut b = EnrichedMetadata::default();
        b.tags.push("video".to_string());
        b.confidence.push(0.8);
        b.tags.push("mp4".to_string());
        b.confidence.push(0.95);

        a.merge(b);
        assert_eq!(a.tags.iter().filter(|t| t.as_str() == "video").count(), 1);
        assert!(a.tags.contains(&"mp4".to_string()));
    }

    #[test]
    fn test_enriched_metadata_filter_by_confidence() {
        let mut m = EnrichedMetadata::default();
        m.tags = vec!["high".to_string(), "low".to_string()];
        m.confidence = vec![0.9, 0.1];
        m.filter_by_confidence(0.5);
        assert_eq!(m.tags, vec!["high".to_string()]);
        assert_eq!(m.confidence, vec![0.9]);
    }

    #[test]
    fn test_enriched_metadata_caption_merge_uses_existing() {
        let mut a = EnrichedMetadata {
            auto_caption: Some("existing".to_string()),
            ..Default::default()
        };
        let b = EnrichedMetadata {
            auto_caption: Some("new".to_string()),
            ..Default::default()
        };
        a.merge(b);
        assert_eq!(a.auto_caption.as_deref(), Some("existing"));
    }

    // ── RuleEngine ───────────────────────────────────────────────────────────

    #[test]
    fn test_rule_engine_extension_match() {
        let engine = default_rule_engine();
        let result = engine.apply("clip.mp4");
        assert!(result.tags.contains(&"video".to_string()));
        assert!(result.categories.contains(&"video".to_string()));
    }

    #[test]
    fn test_rule_engine_keyword_match() {
        let engine = default_rule_engine();
        let result = engine.apply("documentary_bts_2024.mp4");
        assert!(result.tags.contains(&"bts".to_string()));
    }

    #[test]
    fn test_rule_engine_no_duplicates() {
        let mut engine = RuleEngine::new();
        engine.add_rule(EnrichmentRule::new(".mp4", vec!["video".to_string()], 0.9));
        engine.add_rule(EnrichmentRule::new(".mp4", vec!["video".to_string()], 0.8));
        let result = engine.apply("test.mp4");
        assert_eq!(
            result.tags.iter().filter(|t| t.as_str() == "video").count(),
            1
        );
    }

    #[test]
    fn test_rule_engine_empty_pattern_always_matches() {
        let mut engine = RuleEngine::new();
        engine.add_rule(EnrichmentRule::new("", vec!["media".to_string()], 0.5));
        let result = engine.apply("anything.xyz");
        assert!(result.tags.contains(&"media".to_string()));
    }

    // ── NeuralBackend ────────────────────────────────────────────────────────

    #[test]
    fn test_neural_backend_jpeg_magic() {
        let backend = NeuralBackend::new();
        // FF D8 FF E0 (JFIF JPEG magic)
        let jpeg_magic = &[0xFF, 0xD8, 0xFF, 0xE0];
        let result = backend.classify_bytes("photo.jpg", jpeg_magic);
        assert!(result.labels.contains(&"image".to_string()));
    }

    #[test]
    fn test_neural_backend_png_magic() {
        let backend = NeuralBackend::new();
        let png_magic = &[0x89, 0x50, 0x4E, 0x47];
        let result = backend.classify_bytes("icon.png", png_magic);
        assert!(result.labels.contains(&"image".to_string()));
    }

    #[test]
    fn test_neural_backend_flac_magic() {
        let backend = NeuralBackend::new();
        let flac_magic = b"fLaC";
        let result = backend.classify_bytes("song.flac", flac_magic);
        assert!(result.labels.contains(&"audio".to_string()));
    }

    #[test]
    fn test_neural_backend_fallback_to_extension() {
        let backend = NeuralBackend::new();
        let result = backend.classify_bytes("video.mp4", b""); // empty bytes
        assert!(result.labels.contains(&"video".to_string()));
    }

    // ── MetadataEnricher ─────────────────────────────────────────────────────

    #[test]
    fn test_enrich_mp4_has_video_tag() {
        let meta = enricher().enrich("clip.mp4", b"");
        assert!(meta.tags.contains(&"video".to_string()) || meta.tags.contains(&"mp4".to_string()));
    }

    #[test]
    fn test_enrich_interview_has_category() {
        let meta = enricher().enrich("company_interview_2024.mp4", b"");
        assert!(
            meta.categories.contains(&"interview".to_string())
                || meta.tags.contains(&"interview".to_string()),
            "expected interview category or tag, got: {:?} / {:?}",
            meta.categories,
            meta.tags
        );
    }

    #[test]
    fn test_enrich_caption_generated() {
        let meta = enricher().enrich("holiday_drone_footage.mp4", b"");
        assert!(meta.auto_caption.is_some());
        let cap = meta.auto_caption.as_ref().expect("caption should be set");
        assert!(
            cap.contains("holiday")
                || cap.contains("drone")
                || cap.to_lowercase().contains("aerial")
        );
    }

    #[test]
    fn test_enrich_confidence_filter_applied() {
        let cfg = AiEnrichmentConfig {
            confidence_threshold: 0.99,
            ..Default::default()
        };
        let meta = MetadataEnricher::new(cfg).enrich("clip.mp4", b"");
        // All retained tags must be above threshold.
        for &c in &meta.confidence {
            assert!(c >= 0.99, "tag below threshold slipped through: {c}");
        }
    }

    #[test]
    fn test_enrich_tag_count_limit() {
        let cfg = AiEnrichmentConfig {
            max_tags: 2,
            confidence_threshold: 0.0,
            ..Default::default()
        };
        let meta = MetadataEnricher::new(cfg).enrich("bts_interview_drone_timelapse_4k.mp4", b"");
        assert!(meta.tags.len() <= 2);
        assert_eq!(meta.tags.len(), meta.confidence.len());
    }

    #[test]
    fn test_enrich_with_extra_metadata() {
        let mut extra = HashMap::new();
        extra.insert("director".to_string(), "Jane Doe".to_string());
        let meta = enricher().enrich_with_extra("film.mp4", b"", extra);
        assert_eq!(
            meta.extra.get("director").map(String::as_str),
            Some("Jane Doe")
        );
    }

    #[test]
    fn test_disabled_config_no_tags() {
        let cfg = AiEnrichmentConfig::disabled();
        let meta = MetadataEnricher::new(cfg).enrich("clip.mp4", b"");
        assert!(meta.tags.is_empty());
        assert!(meta.categories.is_empty());
        assert!(meta.auto_caption.is_none());
    }

    #[test]
    fn test_custom_rules_via_with_rules() {
        let rule = EnrichmentRule::new("custom", vec!["custom-tag".to_string()], 0.7);
        let enricher = MetadataEnricher::with_rules(AiEnrichmentConfig::default(), vec![rule]);
        let meta = enricher.enrich("custom_asset.mp4", b"");
        assert!(meta.tags.contains(&"custom-tag".to_string()));
    }
}
