//! Content Rights and Licensing Management for OxiMedia
//!
//! This crate provides comprehensive rights management capabilities including:
//! - Rights tracking and ownership management
//! - License management with various types (royalty-free, rights-managed, etc.)
//! - Expiration tracking and renewal management
//! - Geographic territory restrictions
//! - Usage tracking and reporting
//! - Clearance tracking (music, footage, talent)
//! - Royalty calculation and payment tracking
//! - Watermarking integration
//! - DRM metadata management
//! - Audit trail and compliance reporting
//!
//! ## Data Model
//!
//! ```text
//! RightsHolder
//!   └─ License (rights grant period + terms)
//!       ├─ Territory (list of allowed regions)
//!       └─ Usage (stream/download/broadcast limits)
//! ```
//!
//! A `RightsHolder` represents any entity (individual, label, studio, or PRO)
//! that owns or controls rights to a media asset.  Each `RightsHolder` may hold
//! one or more `License` records that specify the legal grant: the time window
//! during which the rights are valid, the agreed terms (royalty rates, exclusivity,
//! etc.), and the permitted territories and usage types.  `Territory` constrains
//! distribution to specific geographic regions (ISO 3166-1 alpha-2 codes or
//! aggregate zones).  `Usage` defines what the licensee may do — stream, download,
//! broadcast, or combinations thereof — and any volumetric limits.
//!
//! ## Rights Check Flow
//!
//! ```text
//! Asset request
//!      │
//!      ▼
//! Territory check ── DENIED ──►  403 Territory
//!      │ OK
//!      ▼
//! Expiry check ─────DENIED ──►  403 Expired
//!      │ OK
//!      ▼
//! Usage type check ─DENIED ──►  403 Usage
//!      │ OK
//!      ▼
//! Clearance check ──DENIED ──►  403 Clearance
//!      │ OK
//!      ▼
//!     200 OK
//! ```
//!
//! ## DRM Integration
//!
//! To link Widevine, PlayReady, or FairPlay protection to a rights record, store
//! the DRM content key identifier in the license record:
//!
//! ```text
//! License {
//!     content_key_id: Uuid,   // PSSH/KID from the DRM system
//!     ...
//! }
//! ```
//!
//! The `content_key_id` field holds the UUID that corresponds to the PSSH
//! (Protection System Specific Header) `KID` (Key ID) value generated by your
//! DRM server.  Cross-reference `oximedia-drm` for key lifecycle management:
//! key generation, rotation, and license server configuration for each DRM
//! scheme (Widevine CENC, PlayReady PIFF, FairPlay HLS).  When a rights record
//! is revoked or expired the associated `content_key_id` should be invalidated
//! in the DRM key management system to prevent further playback.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod audit;
pub mod automated_takedown;
pub mod batch_lookup;
pub mod clearance;
pub mod ddex;
pub mod in_memory_manager;
pub mod royalty_statement;

// Rights holder registry, usage reporting, and distribution rights
pub mod clearance_notifications;
pub mod clearance_workflow;
pub mod compliance;
pub mod compliance_report;
pub mod conflict;
pub mod conflict_resolution;
pub mod content_id;
pub mod contract;
#[cfg(not(target_arch = "wasm32"))]
pub mod database;
pub mod distribution_rights;
pub mod distribution_window;
pub mod drm;
pub mod embargo;
pub mod embargo_manager;
pub mod embargo_policy;
pub mod embargo_window;
pub mod expiration;
pub mod expiry_alert;
pub mod gantt_export;
pub mod license;
pub mod license_template;
pub mod licensing_model;
pub mod licensing_terms;
pub mod metadata_standards;
pub mod music_cue_sheet;
pub mod performance_rights;
pub mod platform_embargo;
pub mod pool_config;
pub mod query_cache;
pub mod registry;
pub mod revenue;
pub mod rights;
pub mod rights_api;
pub mod rights_audit;
pub mod rights_audit_trail;
pub mod rights_bundle;
pub mod rights_calendar;
pub mod rights_check;
pub mod rights_conflict;
pub mod rights_database;
pub mod rights_export;
pub mod rights_holder;
pub mod rights_import;
pub mod rights_manager_wasm;
pub mod rights_negotiation;
pub mod rights_renewal;
pub mod rights_search;
pub mod rights_timeline;
pub mod royalty;
pub mod royalty_calc;
pub mod royalty_engine;
pub mod royalty_schedule;
pub mod sub_licensing;
pub mod sync_licensing;
pub mod sync_rights;
pub mod syndication;
pub mod territory;
pub mod territory_hierarchy;
pub mod tiered_royalty;
pub mod usage;
pub mod usage_report;
pub mod usage_rights;
pub mod usage_tracking;
pub mod watermark;

pub use in_memory_manager::InMemoryRightsManager;

#[cfg(not(target_arch = "wasm32"))]
use chrono::Utc;
#[cfg(not(target_arch = "wasm32"))]
use std::{collections::HashMap, sync::Arc, time::Instant};
use thiserror::Error;
#[cfg(not(target_arch = "wasm32"))]
use tokio::sync::Mutex;

/// Result type for rights management operations
pub type Result<T> = std::result::Result<T, RightsError>;

/// Errors that can occur in rights management operations
#[derive(Error, Debug)]
pub enum RightsError {
    /// Database error
    #[cfg(not(target_arch = "wasm32"))]
    #[error("Database error: {0}")]
    Database(String),

    /// Rights not found
    #[error("Rights not found: {0}")]
    NotFound(String),

    /// Rights expired
    #[error("Rights expired: {0}")]
    Expired(String),

    /// Territory restriction violation
    #[error("Territory restriction violation: {0}")]
    TerritoryViolation(String),

    /// Usage restriction violation
    #[error("Usage restriction violation: {0}")]
    UsageViolation(String),

    /// License not valid
    #[error("License not valid: {0}")]
    InvalidLicense(String),

    /// Clearance not obtained
    #[error("Clearance not obtained: {0}")]
    ClearanceRequired(String),

    /// Royalty calculation error
    #[error("Royalty calculation error: {0}")]
    RoyaltyError(String),

    /// Watermark error
    #[error("Watermark error: {0}")]
    WatermarkError(String),

    /// DRM error
    #[error("DRM error: {0}")]
    DrmError(String),

    /// Compliance violation
    #[error("Compliance violation: {0}")]
    ComplianceViolation(String),

    /// Invalid operation
    #[error("Invalid operation: {0}")]
    InvalidOperation(String),

    /// Serialization error
    #[error("Serialization error: {0}")]
    Serialization(String),

    /// IO error
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

#[cfg(not(target_arch = "wasm32"))]
impl From<oxisql_core::OxiSqlError> for RightsError {
    fn from(e: oxisql_core::OxiSqlError) -> Self {
        Self::Database(e.to_string())
    }
}

// ── RightsManagerConfig ───────────────────────────────────────────────────────

/// Configuration for [`RightsManager`].
///
/// Controls the SQLite connection pool and the rights-check result cache.
#[cfg(not(target_arch = "wasm32"))]
#[derive(Debug, Clone)]
pub struct RightsManagerConfig {
    /// Maximum number of SQLite pool connections.  Defaults to `5`.
    pub pool_size: u32,
    /// Timeout in seconds when acquiring a pool connection.  Defaults to `5`.
    pub connect_timeout_secs: u64,
    /// Time-to-live in seconds for cached rights-check results.  Defaults to `60`.
    pub cache_ttl_secs: u64,
}

#[cfg(not(target_arch = "wasm32"))]
impl Default for RightsManagerConfig {
    fn default() -> Self {
        Self {
            pool_size: 5,
            connect_timeout_secs: 5,
            cache_ttl_secs: 60,
        }
    }
}

// ── RightsCheckCache ──────────────────────────────────────────────────────────

/// A lightweight in-process cache for `check_rights` results.
///
/// Cache key: `(asset_id, territory_or_none, at_date)`.
/// Each entry expires after `ttl_secs` seconds of wall-clock time.
#[cfg(not(target_arch = "wasm32"))]
struct RightsCheckCache {
    store: HashMap<(String, String, String), (bool, Instant)>,
    ttl_secs: u64,
}

#[cfg(not(target_arch = "wasm32"))]
impl RightsCheckCache {
    fn new(ttl_secs: u64) -> Self {
        Self {
            store: HashMap::new(),
            ttl_secs,
        }
    }

    /// Look up a cached result.  Returns `None` when no entry exists or the
    /// entry has expired (stale entries are removed on access).
    fn get(&mut self, asset_id: &str, territory: Option<&str>, at_date: &str) -> Option<bool> {
        let key = (
            asset_id.to_string(),
            territory.unwrap_or("*").to_string(),
            at_date.to_string(),
        );
        match self.store.get(&key) {
            Some((value, inserted_at)) if inserted_at.elapsed().as_secs() < self.ttl_secs => {
                Some(*value)
            }
            Some(_) => {
                // Stale — evict eagerly.
                self.store.remove(&key);
                None
            }
            None => None,
        }
    }

    /// Store a result.
    fn set(&mut self, asset_id: &str, territory: Option<&str>, at_date: &str, value: bool) {
        let key = (
            asset_id.to_string(),
            territory.unwrap_or("*").to_string(),
            at_date.to_string(),
        );
        self.store.insert(key, (value, Instant::now()));
    }

    /// Remove all entries for `asset_id` so that a revocation takes effect
    /// immediately without waiting for TTL expiry.
    fn invalidate(&mut self, asset_id: &str) {
        self.store.retain(|(a, _, _), _| a != asset_id);
    }
}

// ── RightsManager ─────────────────────────────────────────────────────────────

/// Main rights management system
#[cfg(not(target_arch = "wasm32"))]
pub struct RightsManager {
    db: database::RightsDatabase,
    config: RightsManagerConfig,
    cache: Arc<Mutex<RightsCheckCache>>,
}

#[cfg(not(target_arch = "wasm32"))]
impl RightsManager {
    /// Create a new rights manager with the specified database path.
    ///
    /// Uses [`RightsManagerConfig::default`] for pool and cache settings.
    pub async fn new(database_path: &str) -> Result<Self> {
        Self::new_with_config(database_path, RightsManagerConfig::default()).await
    }

    /// Create a new rights manager with explicit configuration.
    pub async fn new_with_config(database_path: &str, config: RightsManagerConfig) -> Result<Self> {
        let db = database::RightsDatabase::new_with_pool(
            database_path,
            config.pool_size,
            config.connect_timeout_secs,
        )
        .await?;
        let cache = Arc::new(Mutex::new(RightsCheckCache::new(config.cache_ttl_secs)));
        Ok(Self { db, config, cache })
    }

    /// Get reference to the database
    pub fn database(&self) -> &database::RightsDatabase {
        &self.db
    }

    /// Get mutable reference to the database
    pub fn database_mut(&mut self) -> &mut database::RightsDatabase {
        &mut self.db
    }

    /// Get the current configuration.
    pub fn config(&self) -> &RightsManagerConfig {
        &self.config
    }

    // ── High-level license API ────────────────────────────────────────────────

    /// Add a license grant record to the database.
    ///
    /// Inserts a row into `rights_grants`.  The `asset_id` must already exist
    /// in the `assets` table.
    ///
    /// # Parameters
    /// - `license_id` — globally unique identifier for this license.
    /// - `asset_id` — the asset being licensed.
    /// - `owner_id` — the rights owner granting the license.
    /// - `license_type` — e.g. `"royalty-free"`, `"rights-managed"`.
    /// - `start_date` — ISO 8601 / RFC 3339 start date string.
    /// - `end_date` — optional end date; `None` means perpetual.
    /// - `territory_json` — optional JSON array of territory codes.
    #[allow(clippy::too_many_arguments)]
    pub async fn add_license(
        &self,
        license_id: &str,
        asset_id: &str,
        owner_id: &str,
        license_type: &str,
        start_date: &str,
        end_date: Option<&str>,
        territory_json: Option<&str>,
    ) -> Result<()> {
        let now = Utc::now().to_rfc3339();
        self.db
            .pool()
            .execute(
                r"INSERT INTO rights_grants
              (id, asset_id, owner_id, license_type, start_date, end_date,
               is_exclusive, territory_json, created_at, updated_at)
              VALUES ($1, $2, $3, $4, $5, $6, 0, $7, $8, $9)",
                &[
                    &license_id,
                    &asset_id,
                    &owner_id,
                    &license_type,
                    &start_date,
                    &end_date,
                    &territory_json,
                    &now,
                    &now,
                ],
            )
            .await?;
        Ok(())
    }

    /// Revoke (delete) a license by its ID.
    ///
    /// Returns `Err(RightsError::NotFound)` if no row with that ID exists.
    ///
    /// Also invalidates any cache entries for the affected asset so that
    /// subsequent [`check_rights`](Self::check_rights) calls reflect the
    /// revocation immediately.
    pub async fn revoke_license(&self, license_id: &str) -> Result<()> {
        // Fetch the asset_id first so we can invalidate the cache after deletion.
        let asset_id_row = self
            .db
            .pool()
            .query_optional(
                "SELECT asset_id FROM rights_grants WHERE id = $1",
                &[&license_id],
            )
            .await?;

        let rows_affected = self
            .db
            .pool()
            .execute("DELETE FROM rights_grants WHERE id = $1", &[&license_id])
            .await?;
        if rows_affected == 0 {
            return Err(RightsError::NotFound(format!(
                "License not found: {license_id}"
            )));
        }

        // Invalidate cached results for this asset.
        if let Some(row) = asset_id_row {
            let asset_id: String = row.try_get("asset_id")?;
            let mut guard = self.cache.lock().await;
            guard.invalidate(&asset_id);
        }
        Ok(())
    }

    /// Check whether an active, unexpired license exists for `asset_id` in
    /// `territory` at `at_date` (ISO 8601 string).
    ///
    /// Results are cached for [`RightsManagerConfig::cache_ttl_secs`] seconds
    /// to reduce repeated database round-trips for hot assets.  The cache is
    /// invalidated automatically when `revoke_license` is called.
    ///
    /// Returns `true` if at least one matching license exists.
    pub async fn check_rights(
        &self,
        asset_id: &str,
        territory: Option<&str>,
        at_date: &str,
    ) -> Result<bool> {
        // Check cache first.
        {
            let mut guard = self.cache.lock().await;
            if let Some(cached) = guard.get(asset_id, territory, at_date) {
                return Ok(cached);
            }
        }

        // Cache miss — query the database.
        let territory_pattern = territory
            .map(|t| format!("%{t}%"))
            .unwrap_or_else(|| "%".to_string());
        let row = self
            .db
            .pool()
            .query_one(
                r"SELECT COUNT(*) AS cnt FROM rights_grants
              WHERE asset_id = $1
                AND start_date <= $2
                AND (end_date IS NULL OR end_date >= $3)
                AND (territory_json IS NULL OR territory_json LIKE $4)",
                &[&asset_id, &at_date, &at_date, &territory_pattern],
            )
            .await?;
        let count: i64 = row.try_get("cnt")?;
        let result = count > 0;

        // Store in cache.
        {
            let mut guard = self.cache.lock().await;
            guard.set(asset_id, territory, at_date, result);
        }
        Ok(result)
    }

    /// List all active licenses for `asset_id` valid at `at_date`.
    ///
    /// Returns a `Vec` of `(id, license_type, start_date, end_date)` tuples.
    pub async fn list_active_licenses(
        &self,
        asset_id: &str,
        at_date: &str,
    ) -> Result<Vec<(String, String, String, Option<String>)>> {
        let rows = self
            .db
            .pool()
            .query(
                r"SELECT id, license_type, start_date, end_date
              FROM rights_grants
              WHERE asset_id = $1
                AND start_date <= $2
                AND (end_date IS NULL OR end_date >= $3)",
                &[&asset_id, &at_date, &at_date],
            )
            .await?;
        rows.into_iter()
            .map(|r| {
                Ok((
                    r.try_get("id")?,
                    r.try_get("license_type")?,
                    r.try_get("start_date")?,
                    r.try_get("end_date")?,
                ))
            })
            .collect()
    }

    /// Batch rights check: for each `asset_id` in the slice, check whether
    /// a valid license exists using a single `WHERE asset_id IN (…)` query.
    ///
    /// Returns a `HashMap<asset_id, bool>` (true = at least one valid license).
    pub async fn check_rights_batch(
        &self,
        asset_ids: &[&str],
        territory: Option<&str>,
        at_date: &str,
    ) -> Result<std::collections::HashMap<String, bool>> {
        if asset_ids.is_empty() {
            return Ok(std::collections::HashMap::new());
        }

        // Build the IN clause placeholders ($1..$n) plus the trailing
        // date/territory parameters ($n+1..$n+3).
        let n = asset_ids.len();
        let placeholders: String = (1..=n)
            .map(|i| format!("${i}"))
            .collect::<Vec<_>>()
            .join(", ");
        let sql = format!(
            r"SELECT asset_id, COUNT(*) as cnt
              FROM rights_grants
              WHERE asset_id IN ({placeholders})
                AND start_date <= ${}
                AND (end_date IS NULL OR end_date >= ${})
                AND (territory_json IS NULL OR territory_json LIKE ${})
              GROUP BY asset_id",
            n + 1,
            n + 2,
            n + 3
        );

        let territory_pattern = territory
            .map(|t| format!("%{t}%"))
            .unwrap_or_else(|| "%".to_string());

        // Every value (ids, dates, territory pattern) is bound as a positional
        // parameter — the only dynamic SQL is the run of `$N` placeholders
        // whose count is driven by `asset_ids.len()`, never by string content
        // (a textbook-safe variable-arity `IN (...)` clause).
        let mut params: Vec<&dyn oxisql_core::ToSqlValue> = Vec::with_capacity(n + 3);
        for id in asset_ids {
            params.push(id);
        }
        params.push(&at_date);
        params.push(&at_date);
        params.push(&territory_pattern);

        let rows = self.db.pool().query(&sql, &params).await?;

        // Seed with false for all requested IDs, then flip to true if found.
        let mut result: std::collections::HashMap<String, bool> = asset_ids
            .iter()
            .map(|&id| (id.to_string(), false))
            .collect();
        for row in rows {
            let asset_id: String = row.try_get("asset_id")?;
            let count: i64 = row.try_get("cnt")?;
            if count > 0 {
                result.insert(asset_id, true);
            }
        }
        Ok(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_rights_manager_creation() {
        let temp_dir = tempfile::tempdir().expect("rights test operation should succeed");
        let db_path = temp_dir.path().join("rights.db");
        let manager = RightsManager::new(
            db_path
                .to_str()
                .expect("rights test operation should succeed"),
        )
        .await;
        assert!(manager.is_ok());
    }

    #[tokio::test]
    async fn test_rights_manager_config() {
        let temp_dir = tempfile::tempdir().expect("temp dir should succeed");
        let db_path = format!("sqlite://{}/test.db", temp_dir.path().display());
        let config = RightsManagerConfig {
            pool_size: 3,
            connect_timeout_secs: 10,
            cache_ttl_secs: 30,
        };
        let manager = RightsManager::new_with_config(&db_path, config.clone())
            .await
            .expect("new_with_config should succeed");
        assert_eq!(manager.config().pool_size, 3);
        assert_eq!(manager.config().cache_ttl_secs, 30);
    }

    /// Helper: create a fresh RightsManager in a temp dir.
    async fn make_manager() -> (RightsManager, tempfile::TempDir) {
        let temp_dir = tempfile::tempdir().expect("temp dir should succeed");
        let db_path = format!("sqlite://{}/test.db", temp_dir.path().display());
        let mgr = RightsManager::new(&db_path)
            .await
            .expect("RightsManager::new should succeed");
        (mgr, temp_dir)
    }

    /// Helper: insert a minimal asset row so foreign keys are satisfied.
    async fn insert_asset(mgr: &RightsManager, asset_id: &str) {
        let now = Utc::now().to_rfc3339();
        mgr.database()
            .pool()
            .execute(
                "INSERT INTO assets (id, name, asset_type, created_at, updated_at) VALUES ($1, $2, $3, $4, $5)",
                &[&asset_id, &asset_id, &"video", &now, &now],
            )
            .await
            .expect("insert asset should succeed");
    }

    /// Helper: insert a minimal owner row.
    async fn insert_owner(mgr: &RightsManager, owner_id: &str) {
        let now = Utc::now().to_rfc3339();
        mgr.database()
            .pool()
            .execute(
                "INSERT INTO rights_owners (id, name, created_at, updated_at) VALUES ($1, $2, $3, $4)",
                &[&owner_id, &"ACME Corp", &now, &now],
            )
            .await
            .expect("insert owner should succeed");
    }

    #[tokio::test]
    async fn test_add_and_revoke_license() {
        let (mgr, _dir) = make_manager().await;
        insert_asset(&mgr, "asset-1").await;
        insert_owner(&mgr, "owner-1").await;

        // Add license
        mgr.add_license(
            "lic-1",
            "asset-1",
            "owner-1",
            "royalty-free",
            "2020-01-01T00:00:00Z",
            Some("2030-01-01T00:00:00Z"),
            None,
        )
        .await
        .expect("add_license should succeed");

        // check_rights should be true
        let ok = mgr
            .check_rights("asset-1", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights should succeed");
        assert!(ok, "expected rights to be granted");

        // revoke_license
        mgr.revoke_license("lic-1")
            .await
            .expect("revoke_license should succeed");

        // check_rights should now be false
        let ok2 = mgr
            .check_rights("asset-1", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights should succeed");
        assert!(!ok2, "expected rights to be denied after revocation");
    }

    #[tokio::test]
    async fn test_revoke_nonexistent_returns_not_found() {
        let (mgr, _dir) = make_manager().await;
        let err = mgr.revoke_license("ghost").await;
        assert!(err.is_err());
        assert!(matches!(err.unwrap_err(), RightsError::NotFound(_)));
    }

    #[tokio::test]
    async fn test_list_active_licenses() {
        let (mgr, _dir) = make_manager().await;
        insert_asset(&mgr, "asset-2").await;
        insert_owner(&mgr, "owner-2").await;

        // Add two licenses
        mgr.add_license(
            "lic-a",
            "asset-2",
            "owner-2",
            "royalty-free",
            "2020-01-01T00:00:00Z",
            Some("2030-01-01T00:00:00Z"),
            None,
        )
        .await
        .expect("add lic-a");
        mgr.add_license(
            "lic-b",
            "asset-2",
            "owner-2",
            "rights-managed",
            "2020-01-01T00:00:00Z",
            Some("2030-01-01T00:00:00Z"),
            None,
        )
        .await
        .expect("add lic-b");

        let active = mgr
            .list_active_licenses("asset-2", "2025-01-01T00:00:00Z")
            .await
            .expect("list_active_licenses should succeed");
        assert_eq!(active.len(), 2, "expected 2 active licenses");
    }

    #[tokio::test]
    async fn test_pool_concurrent_access() {
        let (mgr, _dir) = make_manager().await;
        insert_asset(&mgr, "asset-3").await;
        insert_owner(&mgr, "owner-3").await;

        mgr.add_license(
            "lic-c",
            "asset-3",
            "owner-3",
            "royalty-free",
            "2020-01-01T00:00:00Z",
            None,
            None,
        )
        .await
        .expect("add_license should succeed");

        // 4 concurrent tasks all calling check_rights — should not deadlock.
        let pool = mgr.database().pool().clone();
        let handles: Vec<_> = (0..4)
            .map(|_| {
                let p = pool.clone();
                tokio::spawn(async move {
                    let row = p
                        .query_one(
                            "SELECT COUNT(*) AS cnt FROM rights_grants WHERE asset_id = $1",
                            &[&"asset-3"],
                        )
                        .await
                        .expect("concurrent query should succeed");
                    row.try_get::<i64>("cnt")
                        .expect("count column should decode")
                })
            })
            .collect();

        for handle in handles {
            let count = handle.await.expect("task should complete");
            assert_eq!(count, 1, "each task should see exactly 1 grant");
        }
    }

    #[tokio::test]
    async fn test_batch_lookup_correct_results() {
        let (mgr, _dir) = make_manager().await;
        insert_owner(&mgr, "owner-4").await;

        // Insert 5 assets and licenses
        for i in 1..=5u32 {
            let asset_id = format!("batch-asset-{i}");
            let lic_id = format!("batch-lic-{i}");
            insert_asset(&mgr, &asset_id).await;
            mgr.add_license(
                &lic_id,
                &asset_id,
                "owner-4",
                "royalty-free",
                "2020-01-01T00:00:00Z",
                None,
                None,
            )
            .await
            .expect("add_license should succeed");
        }

        let asset_ids: Vec<&str> = vec![
            "batch-asset-1",
            "batch-asset-2",
            "batch-asset-3",
            "batch-asset-4",
            "batch-asset-5",
        ];
        let results = mgr
            .check_rights_batch(&asset_ids, None, "2025-01-01T00:00:00Z")
            .await
            .expect("batch should succeed");

        assert_eq!(results.len(), 5);
        for id in &asset_ids {
            assert!(
                *results.get(*id).expect("id should be in results"),
                "asset {id} should be granted"
            );
        }
    }

    #[tokio::test]
    async fn test_batch_vs_individual_identical() {
        let (mgr, _dir) = make_manager().await;
        insert_owner(&mgr, "owner-5").await;

        for i in 1..=3u32 {
            let asset_id = format!("compare-asset-{i}");
            insert_asset(&mgr, &asset_id).await;
            mgr.add_license(
                &format!("compare-lic-{i}"),
                &asset_id,
                "owner-5",
                "royalty-free",
                "2020-01-01T00:00:00Z",
                None,
                None,
            )
            .await
            .expect("add_license");
        }

        let ids = [
            "compare-asset-1",
            "compare-asset-2",
            "compare-asset-3",
            "no-such",
        ];
        let batch = mgr
            .check_rights_batch(&ids, None, "2025-01-01T00:00:00Z")
            .await
            .expect("batch should succeed");

        for id in &ids {
            let individual = mgr
                .check_rights(id, None, "2025-01-01T00:00:00Z")
                .await
                .expect("individual check should succeed");
            let from_batch = *batch.get(*id).expect("id should be in batch results");
            assert_eq!(
                individual, from_batch,
                "batch and individual results should match for {id}"
            );
        }
    }

    #[tokio::test]
    async fn test_schema_indices_exist() {
        let (mgr, _dir) = make_manager().await;

        // Query for the two new performance indices on territory and end_date.
        let rows = mgr
            .database()
            .pool()
            .query(
                "SELECT name FROM sqlite_master WHERE type='index' AND (name LIKE 'idx_rights_grants_t%' OR name LIKE 'idx_rights_grants_e%')",
                &[],
            )
            .await
            .expect("sqlite_master query should succeed");

        let names: Vec<String> = rows
            .into_iter()
            .map(|r| r.try_get("name").expect("name column should decode"))
            .collect();
        assert!(
            names.iter().any(|n| n == "idx_rights_grants_territory"),
            "territory index should exist, got: {names:?}"
        );
        assert!(
            names.iter().any(|n| n == "idx_rights_grants_end_date"),
            "end_date index should exist, got: {names:?}"
        );
    }

    /// Verify that a second `check_rights` call for the same key does not
    /// create a second database row lookup — if it did, the count in
    /// `rights_grants` would still be 1, meaning the cache served the result.
    ///
    /// We verify cache behaviour indirectly: add a grant, check rights (true,
    /// stored in cache), then revoke the grant and immediately check again —
    /// because `revoke_license` invalidates the cache entry, the second check
    /// must hit the DB and return false.
    #[tokio::test]
    async fn test_rights_cache_hit_avoids_db_query() {
        let (mgr, _dir) = make_manager().await;
        insert_asset(&mgr, "cache-asset-1").await;
        insert_owner(&mgr, "cache-owner-1").await;

        mgr.add_license(
            "cache-lic-1",
            "cache-asset-1",
            "cache-owner-1",
            "royalty-free",
            "2020-01-01T00:00:00Z",
            None,
            None,
        )
        .await
        .expect("add_license");

        // First call: DB miss → stored in cache as `true`.
        let r1 = mgr
            .check_rights("cache-asset-1", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights 1");
        assert!(r1, "expected granted on first call");

        // Second call with same key: should be served from cache.
        let r2 = mgr
            .check_rights("cache-asset-1", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights 2");
        assert!(r2, "expected granted on second (cached) call");

        // Revoke invalidates the cache entry.
        mgr.revoke_license("cache-lic-1")
            .await
            .expect("revoke_license");

        // Third call: cache was invalidated, DB queried, returns false.
        let r3 = mgr
            .check_rights("cache-asset-1", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights after revoke");
        assert!(!r3, "expected denied after revocation (cache invalidated)");
    }

    /// Verify that after `cache_ttl_secs` elapses, `check_rights` re-queries
    /// the database.  We use TTL = 0 to force every call to bypass the cache,
    /// then revoke the license and confirm the next call returns `false`.
    #[tokio::test]
    async fn test_rights_cache_ttl_expiry() {
        let temp_dir = tempfile::tempdir().expect("temp dir should succeed");
        let db_path = format!("sqlite://{}/ttl_test.db", temp_dir.path().display());

        // TTL = 0 means caching is effectively disabled (every call is a miss).
        let config = RightsManagerConfig {
            pool_size: 2,
            connect_timeout_secs: 5,
            cache_ttl_secs: 0,
        };
        let mgr = RightsManager::new_with_config(&db_path, config)
            .await
            .expect("new_with_config");

        insert_asset(&mgr, "ttl-asset").await;
        insert_owner(&mgr, "ttl-owner").await;
        mgr.add_license(
            "ttl-lic",
            "ttl-asset",
            "ttl-owner",
            "royalty-free",
            "2020-01-01T00:00:00Z",
            None,
            None,
        )
        .await
        .expect("add_license");

        // First call: DB queried, returns true.
        let r1 = mgr
            .check_rights("ttl-asset", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights 1");
        assert!(r1, "expected granted");

        // Revoke license directly via pool (bypasses cache invalidation) —
        // with TTL=0 the next check_rights will always re-query the DB anyway.
        mgr.database()
            .pool()
            .execute("DELETE FROM rights_grants WHERE id = $1", &[&"ttl-lic"])
            .await
            .expect("direct delete");

        // Second call: with TTL=0 there is no caching, so DB is queried → false.
        let r2 = mgr
            .check_rights("ttl-asset", None, "2025-01-01T00:00:00Z")
            .await
            .expect("check_rights 2");
        assert!(!r2, "expected denied after TTL=0 re-query");
    }
}
