//! HLS and DASH manifest generation.
//!
//! Provides pure-Rust builders for HLS master playlists, HLS media playlists,
//! and DASH MPD documents.  All output is generated by string concatenation;
//! no external XML or template crates are used.

// ─── ManifestFormat ───────────────────────────────────────────────────────────

/// Identifies the output manifest format.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ManifestFormat {
    /// HLS version 3 (basic segmented HTTP streaming).
    HlsV3,
    /// HLS version 6 (adds EXT-X-MAP, EXT-X-INDEPENDENT-SEGMENTS, etc.).
    HlsV6,
    /// HLS version 7 (adds EXT-X-SESSION-DATA, etc.).
    HlsV7,
    /// MPEG-DASH Media Presentation Description.
    DashMpd,
}

impl ManifestFormat {
    /// Version integer to emit in `#EXT-X-VERSION` for HLS formats.
    pub fn hls_version(self) -> Option<u8> {
        match self {
            Self::HlsV3 => Some(3),
            Self::HlsV6 => Some(6),
            Self::HlsV7 => Some(7),
            Self::DashMpd => None,
        }
    }
}

// ─── StreamVariant ────────────────────────────────────────────────────────────

/// A single quality rendition described in a master playlist.
#[derive(Debug, Clone)]
pub struct StreamVariant {
    /// Target average bandwidth in bits per second.
    pub bandwidth: u64,
    /// Optional encoded resolution (width × height).
    pub resolution: Option<(u32, u32)>,
    /// Codec string, e.g. `"av01.0.04M.08"`.
    pub codecs: String,
    /// URI of the media playlist for this variant.
    pub uri: String,
    /// Optional average frame rate.
    pub frame_rate: Option<f32>,
}

// ─── EXT-X-DATERANGE ─────────────────────────────────────────────────────────

/// A `#EXT-X-DATERANGE` tag for in-stream event metadata (RFC 8216 §4.4.2.7).
///
/// Used in Low-Latency HLS to carry SCTE-35, ad markers, and other events
/// that are anchored to a wall-clock range.
#[derive(Debug, Clone)]
pub struct HlsDateRange {
    /// Unique identifier for this date-range (required).
    pub id: String,
    /// Class URI identifying the semantics of this range (optional).
    pub class: Option<String>,
    /// Start date-time as Unix timestamp in milliseconds (required).
    pub start_date_ms: i64,
    /// Optional end date-time in milliseconds (exclusive).
    pub end_date_ms: Option<i64>,
    /// Optional nominal duration in seconds.
    pub duration_secs: Option<f64>,
    /// Optional planned duration in seconds (before the actual end is known).
    pub planned_duration_secs: Option<f64>,
    /// Whether this range replaces (supersedes) a previously declared range
    /// with the same `class`.
    pub end_on_next: bool,
    /// Arbitrary key=value pairs for `X-` client-defined attributes.
    pub client_attributes: Vec<(String, String)>,
    /// Optional SCTE-35 command type byte, present when carrying SCTE-35.
    pub scte35_cmd: Option<Vec<u8>>,
}

impl HlsDateRange {
    /// Render this range as a `#EXT-X-DATERANGE:` line.
    pub fn to_tag_line(&self) -> String {
        let mut out = format!("#EXT-X-DATERANGE:ID=\"{}\"", self.id);
        if let Some(c) = &self.class {
            out.push_str(&format!(",CLASS=\"{}\"", c));
        }
        let start_secs = self.start_date_ms / 1000;
        let start_ms = self.start_date_ms.abs() % 1000;
        let (year, month, day) = days_to_ymd((start_secs.max(0) as u64) / 86400);
        let rem = (start_secs.max(0) as u64) % 86400;
        let hour = rem / 3600;
        let min = (rem % 3600) / 60;
        let sec = rem % 60;
        let iso =
            format!("{year:04}-{month:02}-{day:02}T{hour:02}:{min:02}:{sec:02}.{start_ms:03}Z");
        out.push_str(&format!(",START-DATE=\"{}\"", iso));
        if let Some(end_ms) = self.end_date_ms {
            let esecs = end_ms / 1000;
            let ems = end_ms.abs() % 1000;
            let (ey, em, ed) = days_to_ymd((esecs.max(0) as u64) / 86400);
            let er = (esecs.max(0) as u64) % 86400;
            let eh = er / 3600;
            let emin = (er % 3600) / 60;
            let es = er % 60;
            let eiso = format!("{ey:04}-{em:02}-{ed:02}T{eh:02}:{emin:02}:{es:02}.{ems:03}Z");
            out.push_str(&format!(",END-DATE=\"{}\"", eiso));
        }
        if let Some(dur) = self.duration_secs {
            out.push_str(&format!(",DURATION={:.3}", dur));
        }
        if let Some(pdur) = self.planned_duration_secs {
            out.push_str(&format!(",PLANNED-DURATION={:.3}", pdur));
        }
        if self.end_on_next {
            out.push_str(",END-ON-NEXT=YES");
        }
        if let Some(cmd) = &self.scte35_cmd {
            let hex: String = cmd.iter().map(|b| format!("{:02X}", b)).collect();
            out.push_str(&format!(",SCTE35-CMD=0x{}", hex));
        }
        for (k, v) in &self.client_attributes {
            out.push_str(&format!(",X-{}=\"{}\"", k, v));
        }
        out
    }
}

// ─── EXT-X-SKIP (LL-HLS playlist delta updates) ───────────────────────────────

/// `#EXT-X-SKIP` tag for LL-HLS playlist delta updates.
///
/// Indicates the number of media segments that were removed from the beginning
/// of the playlist in this delta update (RFC 8216bis §6.3.7).
#[derive(Debug, Clone)]
pub struct HlsSkip {
    /// Number of segments that are omitted from this delta playlist.
    pub skipped_segments: u64,
    /// Optional set of URIs for recently removed date-range IDs.
    pub recently_removed_dateranges: Vec<String>,
}

impl HlsSkip {
    /// Render this as a `#EXT-X-SKIP:` tag line.
    pub fn to_tag_line(&self) -> String {
        let mut out = format!("#EXT-X-SKIP:SKIPPED-SEGMENTS={}", self.skipped_segments);
        if !self.recently_removed_dateranges.is_empty() {
            out.push_str(",RECENTLY-REMOVED-DATERANGES=\"");
            out.push_str(&self.recently_removed_dateranges.join("\t"));
            out.push('"');
        }
        out
    }
}

// ─── HlsSegment ──────────────────────────────────────────────────────────────

/// A single entry in an HLS media playlist.
#[derive(Debug, Clone)]
pub struct HlsSegment {
    /// Nominal duration in seconds.
    pub duration: f64,
    /// URI of the segment file.
    pub uri: String,
    /// Optional byte-range `(offset, length)` within the URI.
    pub byte_range: Option<(u64, u64)>,
    /// Emit `#EXT-X-DISCONTINUITY` before this segment.
    pub discontinuity: bool,
    /// Optional `#EXT-X-PROGRAM-DATE-TIME` as Unix timestamp in milliseconds.
    pub program_date_time: Option<i64>,
    /// Optional `#EXT-X-DATERANGE` tag to emit before this segment.
    pub date_range: Option<HlsDateRange>,
}

// ─── HlsManifest ─────────────────────────────────────────────────────────────

/// Describes an HLS media playlist.
#[derive(Debug, Clone)]
pub struct HlsManifest {
    /// Maximum segment duration in seconds (for `#EXT-X-TARGETDURATION`).
    pub target_duration: u32,
    /// Sequence number of the first segment.
    pub media_sequence: u64,
    /// Ordered list of segments.
    pub segments: Vec<HlsSegment>,
    /// Emit `#EXT-X-ENDLIST` at the end of the playlist.
    pub is_endlist: bool,
    /// Emit `#EXT-X-ALLOW-CACHE` directive.
    pub allow_cache: bool,
    /// Optional `#EXT-X-SKIP` tag for LL-HLS delta playlist updates.
    pub skip: Option<HlsSkip>,
}

// ─── HLS builders ─────────────────────────────────────────────────────────────

/// Generate an HLS master playlist from a slice of [`StreamVariant`]s.
///
/// The playlist begins with the required `#EXTM3U` header, followed by one
/// `#EXT-X-STREAM-INF` tag per variant.
pub fn build_master_playlist(variants: &[StreamVariant]) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("#EXTM3U\n");
    out.push_str("# HLS Master Playlist\n\n");

    for v in variants {
        out.push_str("#EXT-X-STREAM-INF:BANDWIDTH=");
        out.push_str(&v.bandwidth.to_string());

        if let Some((w, h)) = v.resolution {
            out.push_str(",RESOLUTION=");
            out.push_str(&w.to_string());
            out.push('x');
            out.push_str(&h.to_string());
        }

        if !v.codecs.is_empty() {
            out.push_str(",CODECS=\"");
            out.push_str(&v.codecs);
            out.push('"');
        }

        if let Some(fps) = v.frame_rate {
            // Emit up to 3 decimal places, trimming trailing zeros
            let fps_str = format!("{fps:.3}");
            let fps_str = fps_str.trim_end_matches('0').trim_end_matches('.');
            out.push_str(",FRAME-RATE=");
            out.push_str(fps_str);
        }

        out.push('\n');
        out.push_str(&v.uri);
        out.push('\n');
    }

    out
}

/// Generate a full HLS media playlist from an [`HlsManifest`].
///
/// Supports LL-HLS extensions including `#EXT-X-SKIP` and `#EXT-X-DATERANGE`
/// for delta playlist updates and in-stream event markers.
pub fn build_media_playlist(manifest: &HlsManifest) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("#EXTM3U\n");
    // Use version 9 if LL-HLS skip is present, otherwise 3.
    let version = if manifest.skip.is_some() { 9u8 } else { 3 };
    out.push_str(&format!("#EXT-X-VERSION:{}\n", version));
    out.push_str("#EXT-X-TARGETDURATION:");
    out.push_str(&manifest.target_duration.to_string());
    out.push('\n');
    out.push_str("#EXT-X-MEDIA-SEQUENCE:");
    out.push_str(&manifest.media_sequence.to_string());
    out.push('\n');
    if manifest.allow_cache {
        out.push_str("#EXT-X-ALLOW-CACHE:YES\n");
    }
    // Emit EXT-X-SKIP immediately after the playlist header for delta updates.
    if let Some(skip) = &manifest.skip {
        out.push_str(&skip.to_tag_line());
        out.push('\n');
    }
    out.push('\n');

    for seg in &manifest.segments {
        if seg.discontinuity {
            out.push_str("#EXT-X-DISCONTINUITY\n");
        }
        // Emit EXT-X-DATERANGE before the segment it anchors to.
        if let Some(dr) = &seg.date_range {
            out.push_str(&dr.to_tag_line());
            out.push('\n');
        }
        if let Some(pdt_ms) = seg.program_date_time {
            // Emit as ISO 8601 UTC date-time (seconds-precision, simplified)
            let secs = pdt_ms / 1000;
            let millis = pdt_ms % 1000;
            out.push_str("#EXT-X-PROGRAM-DATE-TIME:");
            out.push_str(&format_unix_to_iso8601(secs, millis as u32));
            out.push('\n');
        }
        if let Some((offset, length)) = seg.byte_range {
            out.push_str("#EXT-X-BYTERANGE:");
            out.push_str(&length.to_string());
            out.push('@');
            out.push_str(&offset.to_string());
            out.push('\n');
        }
        // Duration: emit with 6 decimal places, e.g. `#EXTINF:6.000000,`
        out.push_str("#EXTINF:");
        out.push_str(&format!("{:.6}", seg.duration));
        out.push_str(",\n");
        out.push_str(&seg.uri);
        out.push('\n');
    }

    if manifest.is_endlist {
        out.push_str("#EXT-X-ENDLIST\n");
    }

    out
}

/// Format a Unix timestamp (seconds + sub-second milliseconds) as a simplified
/// ISO 8601 UTC string: `YYYY-MM-DDTHH:MM:SS.mmmZ`.
fn format_unix_to_iso8601(unix_secs: i64, millis: u32) -> String {
    // Use simple integer arithmetic; no external time crate required.
    // Handles dates from 1970-01-01 onwards (negative timestamps not required here).
    let secs = unix_secs.max(0) as u64;
    let total_days = secs / 86400;
    let rem_secs = secs % 86400;
    let hour = rem_secs / 3600;
    let min = (rem_secs % 3600) / 60;
    let sec = rem_secs % 60;

    // Gregorian calendar calculation
    let (year, month, day) = days_to_ymd(total_days);

    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{min:02}:{sec:02}.{millis:03}Z")
}

/// Convert days since Unix epoch to (year, month, day).
fn days_to_ymd(days: u64) -> (u64, u64, u64) {
    // Algorithm from Henry F. Fliegel and Thomas C. Van Flandern (1968)
    // adapted for unsigned arithmetic starting at 1970-01-01.
    let jd = days + 2_440_588; // Julian Day Number for 1970-01-01 = 2440588
    let l = jd + 68_569;
    let n = 4 * l / 146_097;
    let l = l - (146_097 * n + 3) / 4;
    let i = 4000 * (l + 1) / 1_461_001;
    let l = l - 1461 * i / 4 + 31;
    let j = 80 * l / 2447;
    let day = l - 2447 * j / 80;
    let l = j / 11;
    let month = j + 2 - 12 * l;
    let year = 100 * (n - 49) + i + l;
    (year, month, day)
}

// ─── DASH types ───────────────────────────────────────────────────────────────

/// Segment template for DASH segment addressing.
#[derive(Debug, Clone)]
pub struct SegmentTemplate {
    /// Media URL template, e.g. `"video_$RepresentationID$_$Number$.m4s"`.
    pub media: String,
    /// Initialization segment URL template.
    pub initialization: String,
    /// Timescale (ticks per second).
    pub timescale: u32,
    /// Segment duration in timescale units.
    pub duration: u32,
    /// Sequence number of the first segment.
    pub start_number: u32,
}

/// A single DASH representation (quality layer).
#[derive(Debug, Clone)]
pub struct DashRepresentation {
    /// Representation ID string.
    pub id: String,
    /// Bandwidth in bits per second.
    pub bandwidth: u64,
    /// Frame width in pixels.
    pub width: u32,
    /// Frame height in pixels.
    pub height: u32,
    /// Codec string, e.g. `"avc1.640028"`.
    pub codec: String,
    /// Base URL for segment files.
    pub base_url: String,
    /// Optional segment template.
    pub segment_template: Option<SegmentTemplate>,
}

/// Top-level DASH Media Presentation Description.
#[derive(Debug, Clone)]
pub struct DashMpd {
    /// Minimum buffer time in milliseconds.
    pub min_buffer_time_ms: u32,
    /// All representations included in the MPD.
    pub representations: Vec<DashRepresentation>,
}

// ─── DASH builder ─────────────────────────────────────────────────────────────

/// Generate a DASH MPD XML document from a [`DashMpd`] descriptor.
///
/// The output is a well-formed (but not schema-validated) MPD document.
/// All XML is built by string concatenation — no XML crate is used.
pub fn build_dash_mpd(mpd: &DashMpd) -> String {
    let mut out = String::with_capacity(2048);

    let min_buf_secs = mpd.min_buffer_time_ms / 1000;
    let min_buf_ms = mpd.min_buffer_time_ms % 1000;

    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\"\n");
    out.push_str("     xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
    out.push_str("     xsi:schemaLocation=\"urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd\"\n");
    out.push_str("     profiles=\"urn:mpeg:dash:profile:isoff-live:2011\"\n");
    out.push_str("     type=\"dynamic\"\n");
    out.push_str(&format!(
        "     minBufferTime=\"PT{min_buf_secs}.{min_buf_ms:03}S\"\n"
    ));
    out.push_str(">\n");
    out.push_str("  <Period>\n");
    out.push_str("    <AdaptationSet>\n");

    for rep in &mpd.representations {
        out.push_str("      <Representation\n");
        out.push_str(&format!("        id=\"{}\"\n", xml_escape(&rep.id)));
        out.push_str(&format!("        bandwidth=\"{}\"\n", rep.bandwidth));
        out.push_str(&format!("        width=\"{}\"\n", rep.width));
        out.push_str(&format!("        height=\"{}\"\n", rep.height));
        out.push_str(&format!("        codecs=\"{}\"\n", xml_escape(&rep.codec)));
        out.push_str("      >\n");

        if !rep.base_url.is_empty() {
            out.push_str(&format!(
                "        <BaseURL>{}</BaseURL>\n",
                xml_escape(&rep.base_url)
            ));
        }

        if let Some(st) = &rep.segment_template {
            out.push_str("        <SegmentTemplate\n");
            out.push_str(&format!("          timescale=\"{}\"\n", st.timescale));
            out.push_str(&format!("          duration=\"{}\"\n", st.duration));
            out.push_str(&format!("          startNumber=\"{}\"\n", st.start_number));
            out.push_str(&format!(
                "          initialization=\"{}\"\n",
                xml_escape(&st.initialization)
            ));
            out.push_str(&format!("          media=\"{}\"\n", xml_escape(&st.media)));
            out.push_str("        />\n");
        }

        out.push_str("      </Representation>\n");
    }

    out.push_str("    </AdaptationSet>\n");
    out.push_str("  </Period>\n");
    out.push_str("</MPD>\n");

    out
}

/// Escape the five predefined XML entities in a string.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            other => out.push(other),
        }
    }
    out
}

// ─── Async writers (feature = "async") ───────────────────────────────────────

#[cfg(feature = "async")]
mod async_io {
    use super::{
        build_dash_mpd, build_master_playlist, build_media_playlist, DashMpd, HlsManifest,
        StreamVariant,
    };
    use crate::StreamError;
    use tokio::io::{AsyncWrite, AsyncWriteExt};

    /// Async wrapper around [`build_master_playlist`] that streams the rendered
    /// playlist to an [`AsyncWrite`] sink.
    ///
    /// Equivalent to writing the result of [`build_master_playlist`] verbatim;
    /// useful when the segment pipeline drives a non-blocking I/O target.
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::IoError`] if the underlying writer fails.
    pub async fn write_master_playlist_async<W: AsyncWrite + Unpin>(
        variants: &[StreamVariant],
        w: &mut W,
    ) -> Result<(), StreamError> {
        let s = build_master_playlist(variants);
        w.write_all(s.as_bytes())
            .await
            .map_err(|e| StreamError::IoError(format!("master playlist write: {e}")))?;
        Ok(())
    }

    /// Async wrapper around [`build_media_playlist`].
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::IoError`] if the underlying writer fails.
    pub async fn write_media_playlist_async<W: AsyncWrite + Unpin>(
        manifest: &HlsManifest,
        w: &mut W,
    ) -> Result<(), StreamError> {
        let s = build_media_playlist(manifest);
        w.write_all(s.as_bytes())
            .await
            .map_err(|e| StreamError::IoError(format!("media playlist write: {e}")))?;
        Ok(())
    }

    /// Async wrapper around [`build_dash_mpd`].
    ///
    /// # Errors
    ///
    /// Returns [`StreamError::IoError`] if the underlying writer fails.
    pub async fn write_dash_mpd_async<W: AsyncWrite + Unpin>(
        mpd: &DashMpd,
        w: &mut W,
    ) -> Result<(), StreamError> {
        let s = build_dash_mpd(mpd);
        w.write_all(s.as_bytes())
            .await
            .map_err(|e| StreamError::IoError(format!("dash mpd write: {e}")))?;
        Ok(())
    }
}

#[cfg(feature = "async")]
pub use async_io::{write_dash_mpd_async, write_master_playlist_async, write_media_playlist_async};

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_variant(bw: u64, res: Option<(u32, u32)>) -> StreamVariant {
        StreamVariant {
            bandwidth: bw,
            resolution: res,
            codecs: "av01.0.04M.08".to_string(),
            uri: format!("stream_{bw}.m3u8"),
            frame_rate: Some(30.0),
        }
    }

    fn make_segment(duration: f64, n: u64) -> HlsSegment {
        HlsSegment {
            duration,
            uri: format!("seg{n:04}.ts"),
            byte_range: None,
            discontinuity: false,
            program_date_time: None,
            date_range: None,
        }
    }

    fn make_manifest_builder() -> HlsManifest {
        HlsManifest {
            target_duration: 6,
            media_sequence: 0,
            segments: (0..5).map(|i| make_segment(6.0, i)).collect(),
            is_endlist: false,
            allow_cache: false,
            skip: None,
        }
    }

    // ── ManifestFormat ────────────────────────────────────────────────────────

    #[test]
    fn test_manifest_format_hls_versions() {
        assert_eq!(ManifestFormat::HlsV3.hls_version(), Some(3));
        assert_eq!(ManifestFormat::HlsV6.hls_version(), Some(6));
        assert_eq!(ManifestFormat::HlsV7.hls_version(), Some(7));
        assert_eq!(ManifestFormat::DashMpd.hls_version(), None);
    }

    // ── build_master_playlist ─────────────────────────────────────────────────

    #[test]
    fn test_master_playlist_starts_with_extm3u() {
        let variants = vec![make_variant(3_000_000, Some((1280, 720)))];
        let output = build_master_playlist(&variants);
        assert!(output.starts_with("#EXTM3U\n"));
    }

    #[test]
    fn test_master_playlist_contains_bandwidth() {
        let variants = vec![make_variant(2_500_000, None)];
        let output = build_master_playlist(&variants);
        assert!(output.contains("BANDWIDTH=2500000"), "output={output}");
    }

    #[test]
    fn test_master_playlist_contains_resolution() {
        let variants = vec![make_variant(3_000_000, Some((1920, 1080)))];
        let output = build_master_playlist(&variants);
        assert!(output.contains("RESOLUTION=1920x1080"), "output={output}");
    }

    #[test]
    fn test_master_playlist_contains_codecs() {
        let variants = vec![make_variant(1_000_000, None)];
        let output = build_master_playlist(&variants);
        assert!(
            output.contains("CODECS=\"av01.0.04M.08\""),
            "output={output}"
        );
    }

    #[test]
    fn test_master_playlist_contains_frame_rate() {
        let variants = vec![make_variant(1_000_000, None)];
        let output = build_master_playlist(&variants);
        assert!(output.contains("FRAME-RATE=30"), "output={output}");
    }

    #[test]
    fn test_master_playlist_contains_uri() {
        let variants = vec![make_variant(500_000, None)];
        let output = build_master_playlist(&variants);
        assert!(output.contains("stream_500000.m3u8"), "output={output}");
    }

    #[test]
    fn test_master_playlist_multiple_variants() {
        let variants: Vec<StreamVariant> = [500_000u64, 1_500_000, 3_000_000]
            .iter()
            .map(|&bw| make_variant(bw, None))
            .collect();
        let output = build_master_playlist(&variants);
        assert_eq!(
            output.matches("#EXT-X-STREAM-INF").count(),
            3,
            "expected 3 STREAM-INF entries"
        );
    }

    #[test]
    fn test_master_playlist_empty_variants() {
        let output = build_master_playlist(&[]);
        assert!(output.starts_with("#EXTM3U"));
        assert!(!output.contains("STREAM-INF"));
    }

    // ── build_media_playlist ──────────────────────────────────────────────────

    #[test]
    fn test_media_playlist_starts_with_extm3u() {
        let manifest = make_manifest_builder();
        let output = build_media_playlist(&manifest);
        assert!(output.starts_with("#EXTM3U\n"));
    }

    #[test]
    fn test_media_playlist_contains_target_duration() {
        let manifest = make_manifest_builder();
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-TARGETDURATION:6"),
            "output={output}"
        );
    }

    #[test]
    fn test_media_playlist_contains_media_sequence() {
        let mut manifest = make_manifest_builder();
        manifest.media_sequence = 42;
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-MEDIA-SEQUENCE:42"),
            "output={output}"
        );
    }

    #[test]
    fn test_media_playlist_segment_extinf() {
        let manifest = make_manifest_builder();
        let output = build_media_playlist(&manifest);
        assert!(output.contains("#EXTINF:6.000000,"), "output={output}");
    }

    #[test]
    fn test_media_playlist_endlist_present_when_set() {
        let mut manifest = make_manifest_builder();
        manifest.is_endlist = true;
        let output = build_media_playlist(&manifest);
        assert!(output.contains("#EXT-X-ENDLIST"), "output={output}");
    }

    #[test]
    fn test_media_playlist_no_endlist_when_unset() {
        let manifest = make_manifest_builder();
        let output = build_media_playlist(&manifest);
        assert!(
            !output.contains("#EXT-X-ENDLIST"),
            "should not have ENDLIST"
        );
    }

    #[test]
    fn test_media_playlist_allow_cache() {
        let mut manifest = make_manifest_builder();
        manifest.allow_cache = true;
        let output = build_media_playlist(&manifest);
        assert!(output.contains("#EXT-X-ALLOW-CACHE:YES"), "output={output}");
    }

    #[test]
    fn test_media_playlist_byte_range() {
        let mut manifest = make_manifest_builder();
        manifest.segments[0].byte_range = Some((0, 12345));
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-BYTERANGE:12345@0"),
            "output={output}"
        );
    }

    #[test]
    fn test_media_playlist_discontinuity() {
        let mut manifest = make_manifest_builder();
        manifest.segments[2].discontinuity = true;
        let output = build_media_playlist(&manifest);
        assert!(output.contains("#EXT-X-DISCONTINUITY"), "output={output}");
    }

    #[test]
    fn test_media_playlist_program_date_time() {
        let mut manifest = make_manifest_builder();
        manifest.segments[0].program_date_time = Some(1_700_000_000_000i64); // ms
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-PROGRAM-DATE-TIME:"),
            "output={output}"
        );
    }

    // ── build_dash_mpd ────────────────────────────────────────────────────────

    fn make_dash_mpd() -> DashMpd {
        DashMpd {
            min_buffer_time_ms: 3000,
            representations: vec![DashRepresentation {
                id: "video-720p".to_string(),
                bandwidth: 3_000_000,
                width: 1280,
                height: 720,
                codec: "avc1.640028".to_string(),
                base_url: "https://cdn.example.com/".to_string(),
                segment_template: Some(SegmentTemplate {
                    media: "video_$Number$.m4s".to_string(),
                    initialization: "init.mp4".to_string(),
                    timescale: 90_000,
                    duration: 270_000,
                    start_number: 1,
                }),
            }],
        }
    }

    #[test]
    fn test_dash_mpd_starts_with_xml_declaration() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(
            output.starts_with("<?xml version=\"1.0\""),
            "output={output}"
        );
    }

    #[test]
    fn test_dash_mpd_contains_mpd_root_element() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("<MPD "), "output={output}");
        assert!(output.contains("</MPD>"), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_representation() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("<Representation"), "output={output}");
        assert!(output.contains("</Representation>"), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_bandwidth() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("bandwidth=\"3000000\""), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_resolution() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("width=\"1280\""), "output={output}");
        assert!(output.contains("height=\"720\""), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_codec() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("avc1.640028"), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_segment_template() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("<SegmentTemplate"), "output={output}");
        assert!(output.contains("timescale=\"90000\""), "output={output}");
    }

    #[test]
    fn test_dash_mpd_contains_base_url() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("<BaseURL>"), "output={output}");
    }

    #[test]
    fn test_dash_mpd_min_buffer_time() {
        let mpd = make_dash_mpd();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("minBufferTime="), "output={output}");
    }

    #[test]
    fn test_dash_mpd_xml_escape_in_codec() {
        let mut mpd = make_dash_mpd();
        mpd.representations[0].codec = "avc1 & vp09".to_string();
        let output = build_dash_mpd(&mpd);
        assert!(output.contains("avc1 &amp; vp09"), "output={output}");
    }

    #[test]
    fn test_dash_mpd_no_segment_template_when_none() {
        let mut mpd = make_dash_mpd();
        mpd.representations[0].segment_template = None;
        let output = build_dash_mpd(&mpd);
        assert!(!output.contains("<SegmentTemplate"), "output={output}");
    }

    // ── format_unix_to_iso8601 (internal) ────────────────────────────────────

    #[test]
    fn test_format_unix_epoch_is_1970() {
        let s = format_unix_to_iso8601(0, 0);
        assert!(s.starts_with("1970-01-01"), "got {s}");
    }

    #[test]
    fn test_xml_escape_ampersand() {
        assert_eq!(xml_escape("a&b"), "a&amp;b");
    }

    #[test]
    fn test_xml_escape_less_than() {
        assert_eq!(xml_escape("a<b"), "a&lt;b");
    }

    // ── EXT-X-DATERANGE tests ─────────────────────────────────────────────────

    #[test]
    fn test_daterange_tag_contains_id_and_start() {
        let dr = HlsDateRange {
            id: "splice-1".to_string(),
            class: None,
            start_date_ms: 1_700_000_000_000i64,
            end_date_ms: None,
            duration_secs: Some(30.0),
            planned_duration_secs: None,
            end_on_next: false,
            client_attributes: Vec::new(),
            scte35_cmd: None,
        };
        let line = dr.to_tag_line();
        assert!(
            line.contains("#EXT-X-DATERANGE:ID=\"splice-1\""),
            "line={line}"
        );
        assert!(line.contains("START-DATE="), "line={line}");
        assert!(line.contains("DURATION=30.000"), "line={line}");
    }

    #[test]
    fn test_daterange_tag_with_end_date() {
        let dr = HlsDateRange {
            id: "ad-break".to_string(),
            class: Some("com.example.ad".to_string()),
            start_date_ms: 1_000_000_000i64,
            end_date_ms: Some(1_000_030_000i64),
            duration_secs: None,
            planned_duration_secs: None,
            end_on_next: false,
            client_attributes: Vec::new(),
            scte35_cmd: None,
        };
        let line = dr.to_tag_line();
        assert!(line.contains("END-DATE="), "line={line}");
        assert!(line.contains("CLASS=\"com.example.ad\""), "line={line}");
    }

    #[test]
    fn test_daterange_tag_with_scte35_cmd() {
        let dr = HlsDateRange {
            id: "scte-ev1".to_string(),
            class: None,
            start_date_ms: 0,
            end_date_ms: None,
            duration_secs: None,
            planned_duration_secs: None,
            end_on_next: false,
            client_attributes: Vec::new(),
            scte35_cmd: Some(vec![0xFC, 0x30, 0x00]),
        };
        let line = dr.to_tag_line();
        assert!(line.contains("SCTE35-CMD=0xFC3000"), "line={line}");
    }

    #[test]
    fn test_daterange_tag_with_client_attrs() {
        let dr = HlsDateRange {
            id: "custom".to_string(),
            class: None,
            start_date_ms: 0,
            end_date_ms: None,
            duration_secs: None,
            planned_duration_secs: None,
            end_on_next: true,
            client_attributes: vec![("CUSTOM-VALUE".to_string(), "hello".to_string())],
            scte35_cmd: None,
        };
        let line = dr.to_tag_line();
        assert!(line.contains("END-ON-NEXT=YES"), "line={line}");
        assert!(line.contains("X-CUSTOM-VALUE=\"hello\""), "line={line}");
    }

    #[test]
    fn test_daterange_in_media_playlist() {
        let mut manifest = make_manifest_builder();
        manifest.segments[1].date_range = Some(HlsDateRange {
            id: "ad-1".to_string(),
            class: None,
            start_date_ms: 1_700_006_000_000i64,
            end_date_ms: None,
            duration_secs: Some(30.0),
            planned_duration_secs: None,
            end_on_next: false,
            client_attributes: Vec::new(),
            scte35_cmd: None,
        });
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-DATERANGE:ID=\"ad-1\""),
            "output={output}"
        );
    }

    // ── EXT-X-SKIP tests ──────────────────────────────────────────────────────

    #[test]
    fn test_ext_x_skip_tag_line() {
        let skip = HlsSkip {
            skipped_segments: 5,
            recently_removed_dateranges: Vec::new(),
        };
        let line = skip.to_tag_line();
        assert_eq!(line, "#EXT-X-SKIP:SKIPPED-SEGMENTS=5");
    }

    #[test]
    fn test_ext_x_skip_with_removed_dateranges() {
        let skip = HlsSkip {
            skipped_segments: 3,
            recently_removed_dateranges: vec!["range-1".to_string(), "range-2".to_string()],
        };
        let line = skip.to_tag_line();
        assert!(line.contains("RECENTLY-REMOVED-DATERANGES="), "line={line}");
        assert!(line.contains("range-1"), "line={line}");
    }

    #[test]
    fn test_media_playlist_with_skip_uses_version_9() {
        let manifest = HlsManifest {
            target_duration: 6,
            media_sequence: 5,
            segments: (5..8).map(|i| make_segment(6.0, i)).collect(),
            is_endlist: false,
            allow_cache: false,
            skip: Some(HlsSkip {
                skipped_segments: 5,
                recently_removed_dateranges: Vec::new(),
            }),
        };
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-VERSION:9"),
            "delta playlist should be version 9; output={output}"
        );
        assert!(
            output.contains("#EXT-X-SKIP:SKIPPED-SEGMENTS=5"),
            "output={output}"
        );
    }

    #[test]
    fn test_media_playlist_without_skip_uses_version_3() {
        let manifest = make_manifest_builder();
        let output = build_media_playlist(&manifest);
        assert!(
            output.contains("#EXT-X-VERSION:3"),
            "non-delta playlist should be version 3; output={output}"
        );
    }
}
