.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oxiarc-man 1  "oxiarc-man 0.4.2" 
.SH NAME
oxiarc\-man \- Generate man pages for all subcommands
.SH SYNOPSIS
\fBoxiarc\-man\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIOUT_DIR\fR] 
.SH DESCRIPTION
Generate man pages for all subcommands
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIOUT_DIR\fR]
Directory to write man pages into (default: ./man)
.SH VERSION
v0.4.2
