.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oxiarc-info 1  "oxiarc-info 0.4.2" 
.SH NAME
oxiarc\-info \- Show information about an archive, or a PNG/JPEG/TIFF image
.SH SYNOPSIS
\fBoxiarc\-info\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIARCHIVE\fR> 
.SH DESCRIPTION
Show information about an archive, or a PNG/JPEG/TIFF image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIARCHIVE\fR>
Archive or image file to inspect (use "\-" for stdin)
.SH VERSION
v0.4.2
