//! Core types and trait for the completion-API LLM abstraction.
//!
//! This module defines the provider-agnostic completion API used by
//! [`ShapeNlGenerator`](crate::shape_nl_generator::ShapeNlGenerator) and
//! [`ConstraintExplainer`](crate::explainer::ConstraintExplainer).
//!
//! The trait here is distinct from the older [`crate::llm::constraint_generator::LlmProvider`]
//! which uses a flat `LlmRequest` / `LlmResponse` envelope.  This newer API uses
//! the standard multi-turn chat format (system + user messages).

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// A single message in a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// The speaker role.
    pub role: Role,
    /// The message content.
    pub content: String,
}

/// Speaker role in a chat message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System / instruction-level context.
    System,
    /// User turn.
    User,
    /// Assistant / model turn.
    Assistant,
}

/// A request sent to the completion-API abstraction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// The model identifier to use (e.g. `"gpt-4o"`, `"claude-3-5-sonnet-…"`, `"local"`).
    pub model: String,
    /// Ordered list of messages forming the conversation.
    pub messages: Vec<Message>,
    /// Optional maximum number of tokens to generate.
    pub max_tokens: Option<u32>,
    /// Optional sampling temperature (0.0 = deterministic, 1.0 = creative).
    pub temperature: Option<f32>,
}

/// A response received from the completion-API abstraction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// The generated text content.
    pub content: String,
    /// The model that produced the response.
    pub model: String,
    /// Token usage statistics (if reported by the provider).
    pub usage: Option<TokenUsage>,
}

/// Token usage statistics for a completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens consumed by the prompt / messages.
    pub prompt_tokens: u32,
    /// Tokens generated by the model.
    pub completion_tokens: u32,
}

/// Advertised capabilities of a provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Capabilities {
    /// Whether the provider can handle tool/function calls.
    pub supports_tools: bool,
    /// Whether the provider can produce embeddings.
    pub supports_embeddings: bool,
    /// Whether the provider supports streaming responses.
    pub supports_streaming: bool,
    /// Maximum number of context tokens accepted.
    pub max_context_tokens: u32,
}

impl Default for Capabilities {
    fn default() -> Self {
        Self {
            supports_tools: false,
            supports_embeddings: true,
            supports_streaming: false,
            max_context_tokens: 4096,
        }
    }
}

/// Errors returned by a completion-API provider.
#[derive(Debug, thiserror::Error)]
pub enum LlmError {
    /// Provider is not reachable.
    #[error("provider unavailable: {0}")]
    Unavailable(String),

    /// Rate-limit exceeded; caller should retry after the indicated delay.
    #[error("rate limited — retry after {retry_after_secs}s")]
    RateLimited {
        /// Recommended back-off in seconds.
        retry_after_secs: u64,
    },

    /// The request context is larger than the model's context window.
    #[error("context too long: {tokens} tokens, max {max_tokens}")]
    ContextTooLong {
        /// Number of tokens in the request.
        tokens: u32,
        /// Provider maximum.
        max_tokens: u32,
    },

    /// A network-level error occurred (only meaningful for remote providers).
    #[error("network error: {0}")]
    Network(String),

    /// The API key or credentials were rejected.
    #[error("authentication failed")]
    AuthFailed,

    /// The requested model is not available on this provider.
    #[error("model not supported: {0}")]
    ModelNotSupported(String),

    /// The provider returned a response that could not be parsed.
    #[error("invalid response: {0}")]
    InvalidResponse(String),
}

/// Provider-agnostic trait for chat-completion and embedding APIs.
///
/// Implement this trait to plug in any LLM backend (OpenAI, Anthropic, local
/// GGUF inference, stubs, …).  Implementations must be `Send + Sync` so they
/// can be wrapped in `Arc` and shared across async tasks.
#[async_trait]
pub trait CompletionProvider: Send + Sync {
    /// Send a completion request and return the response.
    async fn complete(&self, request: &CompletionRequest) -> Result<CompletionResponse, LlmError>;

    /// Compute dense embeddings for a batch of texts.
    ///
    /// The returned outer `Vec` has the same length as `texts`; each inner
    /// `Vec<f32>` is the embedding vector for the corresponding text.
    async fn embed(&self, texts: &[String]) -> Result<Vec<Vec<f32>>, LlmError>;

    /// Return this provider's advertised capabilities.
    fn capabilities(&self) -> &Capabilities;

    /// Human-readable provider name (e.g. `"openai"`, `"anthropic"`, `"local"`).
    fn name(&self) -> &str;
}
