//! Parity tests: compare `aws_lc_provider()` vs `pure_provider()` (rustcrypto).
//!
//! These tests document — rather than enforce exact equality of — the supported
//! cipher suite and KX group sets between the two providers.  The only hard
//! assertions are that both providers expose the mandatory TLS 1.3 primitives.
//!
//! `rustls::CipherSuite` and `rustls::NamedGroup` are generated by
//! `enum_builder!` and only derive `PartialEq + Eq + Copy` (no `Hash`), so
//! comparison uses `Vec::contains` rather than `HashSet`.
//!
//! Run with:
//! ```bash
//! cargo test -p oxitls-adapter-aws-lc --features aws-lc -E 'test(parity)'
//! ```

#[cfg(feature = "aws-lc")]
mod parity_tests {
    use oxitls_adapter_aws_lc::aws_lc_provider;
    use oxitls_adapter_rustls_rustcrypto::pure_provider;

    // ── cipher suite parity ───────────────────────────────────────────────────

    /// Documents which cipher suites are exclusive to each provider.
    ///
    /// Hard assertion: both providers MUST expose the two mandatory TLS 1.3
    /// suites (`TLS13_AES_256_GCM_SHA384` and `TLS13_AES_128_GCM_SHA256`).
    #[test]
    fn cipher_suite_diffs_within_expected_whitelist() {
        let aws_provider = aws_lc_provider();
        let pure_provider = pure_provider();

        let aws_suites: Vec<rustls::CipherSuite> = aws_provider
            .cipher_suites
            .iter()
            .map(|s| s.suite())
            .collect();
        let pure_suites: Vec<rustls::CipherSuite> = pure_provider
            .cipher_suites
            .iter()
            .map(|s| s.suite())
            .collect();

        // Log differences for diagnostic purposes (visible with --nocapture).
        let only_in_aws: Vec<_> = aws_suites
            .iter()
            .filter(|s| !pure_suites.contains(s))
            .collect();
        let only_in_pure: Vec<_> = pure_suites
            .iter()
            .filter(|s| !aws_suites.contains(s))
            .collect();
        println!("Cipher suites only in aws-lc provider  : {only_in_aws:?}");
        println!("Cipher suites only in pure-rust provider: {only_in_pure:?}");

        // Both providers MUST support the mandatory TLS 1.3 suites.
        use rustls::CipherSuite;
        assert!(
            aws_suites.contains(&CipherSuite::TLS13_AES_256_GCM_SHA384),
            "aws-lc provider missing TLS13_AES_256_GCM_SHA384"
        );
        assert!(
            aws_suites.contains(&CipherSuite::TLS13_AES_128_GCM_SHA256),
            "aws-lc provider missing TLS13_AES_128_GCM_SHA256"
        );
        assert!(
            pure_suites.contains(&CipherSuite::TLS13_AES_256_GCM_SHA384),
            "pure provider missing TLS13_AES_256_GCM_SHA384"
        );
        assert!(
            pure_suites.contains(&CipherSuite::TLS13_AES_128_GCM_SHA256),
            "pure provider missing TLS13_AES_128_GCM_SHA256"
        );

        // Both providers should advertise at least one cipher suite.
        assert!(
            !aws_suites.is_empty(),
            "aws-lc provider has no cipher suites"
        );
        assert!(
            !pure_suites.is_empty(),
            "pure provider has no cipher suites"
        );
    }

    // ── KX group parity ───────────────────────────────────────────────────────

    /// Documents which KX groups are exclusive to each provider.
    ///
    /// Hard assertion: both providers MUST support X25519.
    #[test]
    fn kx_group_diffs_documented() {
        let aws_provider = aws_lc_provider();
        let pure_provider = pure_provider();

        let aws_groups: Vec<rustls::NamedGroup> =
            aws_provider.kx_groups.iter().map(|g| g.name()).collect();
        let pure_groups: Vec<rustls::NamedGroup> =
            pure_provider.kx_groups.iter().map(|g| g.name()).collect();

        let only_in_aws: Vec<_> = aws_groups
            .iter()
            .filter(|g| !pure_groups.contains(g))
            .collect();
        let only_in_pure: Vec<_> = pure_groups
            .iter()
            .filter(|g| !aws_groups.contains(g))
            .collect();
        println!("KX groups only in aws-lc provider  : {only_in_aws:?}");
        println!("KX groups only in pure-rust provider: {only_in_pure:?}");

        // Both providers MUST support X25519 as a baseline.
        assert!(
            aws_groups.contains(&rustls::NamedGroup::X25519),
            "aws-lc provider missing X25519 KX group"
        );
        assert!(
            pure_groups.contains(&rustls::NamedGroup::X25519),
            "pure provider missing X25519 KX group"
        );

        assert!(!aws_groups.is_empty(), "aws-lc provider has no KX groups");
        assert!(!pure_groups.is_empty(), "pure provider has no KX groups");
    }

    // ── provider construction sanity ──────────────────────────────────────────

    /// Verifies that calling `aws_lc_provider()` twice produces independent
    /// `Arc`s with equal cipher-suite counts (not the same pointer).
    #[test]
    fn provider_construction_independent() {
        let p1 = aws_lc_provider();
        let p2 = aws_lc_provider();
        // Different Arc allocations.
        assert!(!std::sync::Arc::ptr_eq(&p1, &p2));
        // Same cipher-suite count.
        assert_eq!(
            p1.cipher_suites.len(),
            p2.cipher_suites.len(),
            "cipher suite count should be stable across calls"
        );
        assert_eq!(
            p1.kx_groups.len(),
            p2.kx_groups.len(),
            "KX group count should be stable across calls"
        );
    }
}
