//! Threadgroup-tiled GEMM generators driven by a runtime parameter buffer.
//!
//! Child module of [`crate::msl`]; every item here is re-exported from there,
//! so the public paths are `oxicuda_metal::msl::gemm_msl_v2` and friends.
//!
//! The v1 GEMM kernels ([`crate::msl::gemm_msl`] and its batched/FP16 siblings)
//! are one-thread-per-output global-memory loops whose indexing hardcodes
//! `lda = k`, `ldb = n`, `ldc = n` and has no notion of a transpose, so a caller
//! passing a transposed or padded operand gets a silently wrong answer. The
//! kernels here take every shape, stride and transpose flag from a constant
//! buffer, stage `K` panels through threadgroup memory, and give each thread a
//! 2x2 register sub-tile.

// ─── GEMM v2 (runtime params + threadgroup tiling) ────────────────────────────

/// Element type of the A/B/C buffers for the v2 GEMM generators.
///
/// Accumulation is always performed in `float` regardless of the storage type —
/// the mixed-precision pattern that keeps a half-precision GEMM numerically
/// usable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum GemmDtype {
    /// 32-bit IEEE binary32 storage (`float` in MSL).
    #[default]
    F32,
    /// 16-bit IEEE binary16 storage (`half` in MSL), `float` accumulation.
    ///
    /// Host-side packing helpers live in [`crate::numeric::pack_f16`].
    F16,
}

impl GemmDtype {
    /// MSL scalar type used for the A/B/C buffers.
    pub fn msl_type(self) -> &'static str {
        match self {
            Self::F32 => "float",
            Self::F16 => "half",
        }
    }

    /// Suffix used in the generated kernel names (`f32` / `f16`).
    pub fn suffix(self) -> &'static str {
        match self {
            Self::F32 => "f32",
            Self::F16 => "f16",
        }
    }

    /// Size of one stored element, in bytes.
    pub fn size_bytes(self) -> usize {
        match self {
            Self::F32 => 4,
            Self::F16 => 2,
        }
    }
}

/// Output-tile height (rows of `C`) covered by one v2 GEMM threadgroup.
pub const GEMM_V2_TILE_M: usize = 32;
/// Output-tile width (columns of `C`) covered by one v2 GEMM threadgroup.
pub const GEMM_V2_TILE_N: usize = 32;
/// `K`-panel depth staged into threadgroup memory per iteration.
pub const GEMM_V2_TILE_K: usize = 16;
/// Threadgroup width the v2 GEMM kernels require (`threads.x`).
pub const GEMM_V2_THREADS_X: usize = 16;
/// Threadgroup height the v2 GEMM kernels require (`threads.y`).
pub const GEMM_V2_THREADS_Y: usize = 16;
/// Size in bytes of the `GemmParamsV2` constant buffer at `[[buffer(3)]]`.
pub const GEMM_PARAMS_V2_BYTES: usize = 40;
/// Size in bytes of the `BatchedGemmParamsV2` constant buffer at `[[buffer(3)]]`.
pub const BATCHED_GEMM_PARAMS_V2_BYTES: usize = 56;

/// Validate the threadgroup shape a dispatcher intends to use for
/// [`gemm_msl_v2`] / [`batched_gemm_msl_v2`].
///
/// The v2 GEMM kernels are **not** width-agnostic: the cooperative staging loop
/// strides by a hardcoded 256 threads and each thread owns a fixed `2×2`
/// sub-tile of the `32×32` output tile, addressed as
/// `tile_a[thread_y * 2 + i]` against a `32`-row staging array. Anything other
/// than `16×16` therefore either under-fills the staging tiles (fewer threads)
/// or indexes past them (more threads). Reject it here rather than letting a
/// generic "pick `max_total_threads_per_threadgroup()`" policy silently corrupt
/// the result.
///
/// The kernel additionally clamps its own tile indices as a memory-safety net,
/// so a mis-launched threadgroup produces wrong numbers rather than an
/// out-of-bounds threadgroup-memory access — but the numbers *are* wrong, which
/// is why this check exists.
pub fn validate_gemm_v2_dispatch(
    threads_x: usize,
    threads_y: usize,
) -> crate::error::MetalResult<()> {
    if threads_x != GEMM_V2_THREADS_X || threads_y != GEMM_V2_THREADS_Y {
        return Err(crate::error::MetalError::InvalidArgument(format!(
            "the v2 GEMM kernels require a {GEMM_V2_THREADS_X}x{GEMM_V2_THREADS_Y} threadgroup; \
             got {threads_x}x{threads_y}"
        )));
    }
    Ok(())
}

/// MSL function name generated by [`gemm_msl_v2`] for `dtype`.
pub fn gemm_v2_function_name(dtype: GemmDtype) -> &'static str {
    match dtype {
        GemmDtype::F32 => "gemm_v2_f32",
        GemmDtype::F16 => "gemm_v2_f16",
    }
}

/// MSL function name generated by [`batched_gemm_msl_v2`] for `dtype`.
pub fn batched_gemm_v2_function_name(dtype: GemmDtype) -> &'static str {
    match dtype {
        GemmDtype::F32 => "batched_gemm_v2_f32",
        GemmDtype::F16 => "batched_gemm_v2_f16",
    }
}

/// Threadgroup-tiled GEMM with a **runtime** parameter buffer.
///
/// `C := alpha * op(A) * op(B) + beta * C`, where `op(X)` is `X` or `Xᵀ`
/// selected per operand at dispatch time.
///
/// This is the replacement for [`gemm_msl`](super::gemm_msl), which is a one-thread-per-output
/// global-memory loop that bakes `lda = k`, `ldb = n`, `ldc = n` and no
/// transpose into the indexing — so it silently computes the wrong answer for a
/// transposed or padded operand.  Nothing about [`gemm_msl`](super::gemm_msl) changes; new
/// dispatchers should bind this kernel instead.
///
/// # Parameter buffer `[[buffer(3)]]` — exact byte layout
///
/// Total size 40 bytes ([`GEMM_PARAMS_V2_BYTES`]), alignment 4, no padding.
/// A `#[repr(C)]` Rust struct of eight `u32` followed by two `f32` matches it
/// exactly:
///
/// | offset | size | MSL            | meaning |
/// |-------:|-----:|----------------|---------|
/// | 0      | 4    | `uint  m`      | rows of `op(A)` and of `C` |
/// | 4      | 4    | `uint  n`      | columns of `op(B)` and of `C` |
/// | 8      | 4    | `uint  k`      | inner (contraction) dimension |
/// | 12     | 4    | `uint  lda`    | row stride of the **stored** `A`, in elements |
/// | 16     | 4    | `uint  ldb`    | row stride of the **stored** `B`, in elements |
/// | 20     | 4    | `uint  ldc`    | row stride of the stored `C`, in elements |
/// | 24     | 4    | `uint  trans_a`| `0` = `NoTrans`, non-zero = `Trans` |
/// | 28     | 4    | `uint  trans_b`| `0` = `NoTrans`, non-zero = `Trans` |
/// | 32     | 4    | `float alpha`  | |
/// | 36     | 4    | `float beta`   | `beta == 0` ⇒ `C` is never read |
///
/// # Addressing contract
///
/// All three matrices are **row-major**; a transpose flag selects which logical
/// index pair maps to the stored row/column, exactly mirroring the CPU oracle:
///
/// * `trans_a == 0`: `A` is stored `m × lda` (`lda >= k`), `A(r, i) = a[r*lda + i]`.
/// * `trans_a != 0`: `A` is stored `k × lda` (`lda >= m`), `A(r, i) = a[i*lda + r]`.
/// * `trans_b == 0`: `B` is stored `k × ldb` (`ldb >= n`), `B(i, c) = b[i*ldb + c]`.
/// * `trans_b != 0`: `B` is stored `n × ldb` (`ldb >= k`), `B(i, c) = b[c*ldb + i]`.
/// * `C` is always stored `m × ldc` (`ldc >= n`), `C(r, c) = c[r*ldc + c]`.
///
/// Passing `lda = k`, `ldb = n`, `ldc = n` with both transpose flags zero
/// reproduces [`gemm_msl`](super::gemm_msl)'s behaviour bit-for-bit up to FP association.
///
/// # Dispatch contract
///
/// * threads per threadgroup: **exactly** `MTLSize::new(16, 16, 1)`
///   ([`GEMM_V2_THREADS_X`] × [`GEMM_V2_THREADS_Y`] = 256 threads). This is a
///   hard precondition, not a tuning suggestion: the 256-thread staging stride
///   and the fixed `2×2` register sub-tile per thread are both baked into the
///   kernel. A narrower threadgroup leaves part of each staged panel
///   uninitialised; a wider one indexes past the `32`-row staging tile. Call
///   [`validate_gemm_v2_dispatch`] before encoding — in particular, do **not**
///   derive the width from `max_total_threads_per_threadgroup()` the way the
///   element-wise dispatchers may.
/// * threadgroups: `MTLSize::new(n.div_ceil(32), m.div_ceil(32), 1)`
///   ([`GEMM_V2_TILE_N`] / [`GEMM_V2_TILE_M`])
/// * threadgroup memory: **none to bind** — the `32×17` and `16×33` staging
///   tiles are statically declared inside the kernel, so
///   `set_threadgroup_memory_length` must *not* be called for slot 0.
///
/// # Implementation
///
/// Each threadgroup owns a `32 × 32` output tile; each of its 256 threads owns
/// a `2 × 2` register sub-tile, giving 4× arithmetic reuse per staged value.
/// The `K` dimension is walked in panels of 16, each panel cooperatively staged
/// into `threadgroup float tile_a[32][17]` / `tile_b[16][33]` (the `+1` padding
/// removes threadgroup-memory bank conflicts).  Ragged edges in `m`, `n` and
/// `k` are handled by zero-filling the staged tiles — zeros contribute nothing
/// to the dot product — and by guarding the stores, so **no** dimension needs to
/// be a multiple of the tile size and no out-of-bounds access is ever issued.
pub fn gemm_msl_v2(dtype: GemmDtype) -> String {
    build_gemm_v2(dtype, false)
}

/// Batched variant of [`gemm_msl_v2`]: `C_b := alpha * op(A_b) * op(B_b) + beta * C_b`.
///
/// # Parameter buffer `[[buffer(3)]]` — exact byte layout
///
/// The first 40 bytes are identical to [`gemm_msl_v2`]'s `GemmParamsV2`; four
/// `uint` fields follow, for a total of 56 bytes
/// ([`BATCHED_GEMM_PARAMS_V2_BYTES`]), alignment 4:
///
/// | offset | size | MSL                | meaning |
/// |-------:|-----:|--------------------|---------|
/// | 0..40  |      | *(as `GemmParamsV2`)* | |
/// | 40     | 4    | `uint batch_count` | number of matrices in the batch |
/// | 44     | 4    | `uint stride_a`    | element stride between `A_b` and `A_(b+1)` |
/// | 48     | 4    | `uint stride_b`    | element stride between `B_b` and `B_(b+1)` |
/// | 52     | 4    | `uint stride_c`    | element stride between `C_b` and `C_(b+1)` |
///
/// # Dispatch contract
///
/// As [`gemm_msl_v2`], but the grid gains a `z` axis:
/// `MTLSize::new(n.div_ceil(32), m.div_ceil(32), batch_count)`.  The batch index
/// is taken from `threadgroup_position_in_grid.z`, so it is uniform across the
/// threadgroup and the early-out for `z >= batch_count` cannot desynchronise the
/// threadgroup barriers.
pub fn batched_gemm_msl_v2(dtype: GemmDtype) -> String {
    build_gemm_v2(dtype, true)
}

/// Shared body generator for [`gemm_msl_v2`] / [`batched_gemm_msl_v2`].
fn build_gemm_v2(dtype: GemmDtype, batched: bool) -> String {
    let ty = dtype.msl_type();
    let (struct_name, kernel_name) = if batched {
        (
            "BatchedGemmParamsV2",
            batched_gemm_v2_function_name(dtype).to_string(),
        )
    } else {
        ("GemmParamsV2", gemm_v2_function_name(dtype).to_string())
    };
    let batch_fields = if batched {
        "    uint  batch_count;\n    uint  stride_a;\n    uint  stride_b;\n    uint  stride_c;\n"
    } else {
        ""
    };
    let batch_bases = if batched {
        "    if (tgid.z >= params.batch_count) return;\n    uint a_base = tgid.z * params.stride_a;\n    uint b_base = tgid.z * params.stride_b;\n    uint c_base = tgid.z * params.stride_c;\n"
    } else {
        "    uint a_base = 0u;\n    uint b_base = 0u;\n    uint c_base = 0u;\n"
    };

    format!(
        r#"
#include <metal_stdlib>
using namespace metal;

struct {struct_name} {{
    uint  m;
    uint  n;
    uint  k;
    uint  lda;
    uint  ldb;
    uint  ldc;
    uint  trans_a;
    uint  trans_b;
    float alpha;
    float beta;
{batch_fields}}};

// 32x32 output tile per threadgroup, 2x2 per thread, K panels of 16 staged in
// threadgroup memory. Ragged m/n/k edges are zero-filled on stage and guarded
// on store, so no dimension has to be a multiple of the tile size.
kernel void {kernel_name}(
    device const {ty}* a [[buffer(0)]],
    device const {ty}* b [[buffer(1)]],
    device {ty}*       c [[buffer(2)]],
    constant {struct_name}& params [[buffer(3)]],
    uint3 tgid [[threadgroup_position_in_grid]],
    uint3 ltid [[thread_position_in_threadgroup]],
    uint  lidx [[thread_index_in_threadgroup]]
) {{
    const uint BM = 32u;
    const uint BN = 32u;
    const uint BK = 16u;
    const uint TM = 2u;
    const uint TN = 2u;
    const uint THREADS = 256u;

    // `+1` padding on the minor axis removes threadgroup-memory bank conflicts.
    threadgroup float tile_a[32][17];
    threadgroup float tile_b[16][33];

{batch_bases}
    uint tile_row = tgid.y * BM;
    uint tile_col = tgid.x * BN;

    // The dispatch contract is exactly 16x16 threads (see validate_gemm_v2_dispatch).
    // Clamping here is a memory-safety net only: a mis-launched wider threadgroup
    // would otherwise index past tile_a's 32 rows / tile_b's 32 columns. The
    // clamp makes such a launch produce wrong numbers instead of reading out of
    // bounds; it is a no-op for a contract-conforming launch.
    uint ty = min(ltid.y, 15u);
    uint tx = min(ltid.x, 15u);

    float acc00 = 0.0f;
    float acc01 = 0.0f;
    float acc10 = 0.0f;
    float acc11 = 0.0f;

    for (uint kt = 0u; kt < params.k; kt += BK) {{
        // Stage the A panel (BM x BK), zero-filling past the edges.
        for (uint idx = lidx; idx < BM * BK; idx += THREADS) {{
            uint r  = idx / BK;
            uint cc = idx % BK;
            uint gr = tile_row + r;
            uint gk = kt + cc;
            float v = 0.0f;
            if (gr < params.m && gk < params.k) {{
                uint off = (params.trans_a != 0u) ? (gk * params.lda + gr)
                                                  : (gr * params.lda + gk);
                v = float(a[a_base + off]);
            }}
            tile_a[r][cc] = v;
        }}
        // Stage the B panel (BK x BN), zero-filling past the edges.
        for (uint idx = lidx; idx < BK * BN; idx += THREADS) {{
            uint r  = idx / BN;
            uint cc = idx % BN;
            uint gk = kt + r;
            uint gc = tile_col + cc;
            float v = 0.0f;
            if (gk < params.k && gc < params.n) {{
                uint off = (params.trans_b != 0u) ? (gc * params.ldb + gk)
                                                  : (gk * params.ldb + gc);
                v = float(b[b_base + off]);
            }}
            tile_b[r][cc] = v;
        }}
        threadgroup_barrier(mem_flags::mem_threadgroup);

        for (uint kk = 0u; kk < BK; ++kk) {{
            float a0 = tile_a[ty * TM + 0u][kk];
            float a1 = tile_a[ty * TM + 1u][kk];
            float b0 = tile_b[kk][tx * TN + 0u];
            float b1 = tile_b[kk][tx * TN + 1u];
            acc00 = fma(a0, b0, acc00);
            acc01 = fma(a0, b1, acc01);
            acc10 = fma(a1, b0, acc10);
            acc11 = fma(a1, b1, acc11);
        }}
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }}

    float acc[2][2];
    acc[0][0] = acc00;
    acc[0][1] = acc01;
    acc[1][0] = acc10;
    acc[1][1] = acc11;

    for (uint i = 0u; i < TM; ++i) {{
        uint row = tile_row + ty * TM + i;
        if (row >= params.m) {{ continue; }}
        for (uint j = 0u; j < TN; ++j) {{
            uint col = tile_col + tx * TN + j;
            if (col >= params.n) {{ continue; }}
            uint out_idx = c_base + row * params.ldc + col;
            // BLAS contract: beta==0 means C is not referenced at all, so a
            // fresh (possibly NaN/Inf) output buffer cannot poison the result.
            float prev = (params.beta == 0.0f) ? 0.0f : params.beta * float(c[out_idx]);
            c[out_idx] = {ty}(params.alpha * acc[i][j] + prev);
        }}
    }}
}}
"#
    )
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── GEMM v2 (string level) ────────────────────────────────────────────────

    #[test]
    fn gemm_v2_param_struct_matches_the_documented_byte_layout() {
        // Field order in the MSL struct IS the byte layout the dispatcher binds.
        let src = gemm_msl_v2(GemmDtype::F32);
        let order = [
            "uint  m;",
            "uint  n;",
            "uint  k;",
            "uint  lda;",
            "uint  ldb;",
            "uint  ldc;",
            "uint  trans_a;",
            "uint  trans_b;",
            "float alpha;",
            "float beta;",
        ];
        let mut cursor = 0usize;
        for field in order {
            let at = src[cursor..]
                .find(field)
                .unwrap_or_else(|| panic!("missing field {field}"))
                + cursor;
            cursor = at + field.len();
        }
        // 8 x u32 + 2 x f32 = 40 bytes, exactly what the doc table promises.
        assert_eq!(GEMM_PARAMS_V2_BYTES, std::mem::size_of::<[u32; 10]>());
        assert_eq!(
            BATCHED_GEMM_PARAMS_V2_BYTES,
            GEMM_PARAMS_V2_BYTES + std::mem::size_of::<[u32; 4]>()
        );
    }

    #[test]
    fn gemm_v2_is_threadgroup_tiled_and_honours_transpose_and_ld() {
        let src = gemm_msl_v2(GemmDtype::F32);
        assert!(src.contains("kernel void gemm_v2_f32"));
        assert!(src.contains("threadgroup float tile_a[32][17]"));
        assert!(src.contains("threadgroup float tile_b[16][33]"));
        assert!(src.contains("threadgroup_barrier(mem_flags::mem_threadgroup)"));
        // Transposed addressing, not the hardcoded row*k + i of v1.
        assert!(src.contains("(params.trans_a != 0u) ? (gk * params.lda + gr)"));
        assert!(src.contains("(params.trans_b != 0u) ? (gc * params.ldb + gk)"));
        assert!(src.contains("row * params.ldc + col"));
        // beta == 0 must not read C.
        assert!(src.contains("(params.beta == 0.0f) ? 0.0f"));
        // Register blocking: 2x2 accumulators.
        for acc in ["acc00", "acc01", "acc10", "acc11"] {
            assert!(src.contains(acc), "missing accumulator {acc}");
        }
        assert_eq!(gemm_v2_function_name(GemmDtype::F32), "gemm_v2_f32");
        assert_eq!(gemm_v2_function_name(GemmDtype::F16), "gemm_v2_f16");
        assert_eq!(GemmDtype::default(), GemmDtype::F32);
        assert_eq!(GemmDtype::F16.size_bytes(), 2);
        assert_eq!(GemmDtype::F32.size_bytes(), 4);
        assert_eq!(GemmDtype::F16.suffix(), "f16");
    }

    #[test]
    fn gemm_v2_dispatch_shape_is_a_hard_precondition() {
        assert!(validate_gemm_v2_dispatch(16, 16).is_ok());
        // The exact mistake a "use max_total_threads_per_threadgroup()" policy
        // would make: 32x32 = 1024 threads indexes past tile_a's 32 rows.
        for (x, y) in [
            (32usize, 32usize),
            (8, 8),
            (16, 8),
            (256, 1),
            (1, 1),
            (0, 0),
        ] {
            assert!(
                validate_gemm_v2_dispatch(x, y).is_err(),
                "{x}x{y} threadgroup accepted"
            );
        }
        // The kernel clamps its own tile indices as a memory-safety net.
        let src = gemm_msl_v2(GemmDtype::F32);
        assert!(src.contains("uint ty = min(ltid.y, 15u);"));
        assert!(src.contains("uint tx = min(ltid.x, 15u);"));
        assert!(
            !src.contains("tile_a[ltid.y"),
            "the staging tiles must be indexed through the clamped ids"
        );
    }

    #[test]
    fn gemm_v2_f16_stores_half_but_accumulates_in_float() {
        let src = gemm_msl_v2(GemmDtype::F16);
        assert!(src.contains("kernel void gemm_v2_f16"));
        assert!(src.contains("device const half* a"));
        assert!(src.contains("device half*       c"));
        // Staging tiles and accumulators stay float.
        assert!(src.contains("threadgroup float tile_a"));
        assert!(src.contains("float acc00 = 0.0f;"));
        assert!(src.contains("half(params.alpha * acc[i][j] + prev)"));
        assert_eq!(GemmDtype::F16.msl_type(), "half");
    }

    #[test]
    fn batched_gemm_v2_adds_the_four_batch_fields_after_beta() {
        let src = batched_gemm_msl_v2(GemmDtype::F32);
        assert!(src.contains("kernel void batched_gemm_v2_f32"));
        let beta = src.find("float beta;").expect("beta");
        for field in [
            "uint  batch_count;",
            "uint  stride_a;",
            "uint  stride_b;",
            "uint  stride_c;",
        ] {
            let at = src.find(field).unwrap_or_else(|| panic!("missing {field}"));
            assert!(at > beta, "{field} must follow beta in the struct");
        }
        assert!(src.contains("if (tgid.z >= params.batch_count) return;"));
        assert!(src.contains("uint a_base = tgid.z * params.stride_a;"));
        assert_eq!(
            batched_gemm_v2_function_name(GemmDtype::F16),
            "batched_gemm_v2_f16"
        );
        // The unbatched variant must not carry batch state.
        assert!(!gemm_msl_v2(GemmDtype::F32).contains("batch_count"));
    }

    // ── v2 GEMM numeric validation against a CPU oracle ───────────────────────

    /// Encode the documented 40-byte `GemmParamsV2` image as ten 32-bit words.
    #[cfg(target_os = "macos")]
    #[allow(clippy::too_many_arguments)]
    fn gemm_v2_params(
        m: u32,
        n: u32,
        k: u32,
        lda: u32,
        ldb: u32,
        ldc: u32,
        trans_a: bool,
        trans_b: bool,
        alpha: f32,
        beta: f32,
    ) -> [u32; 10] {
        [
            m,
            n,
            k,
            lda,
            ldb,
            ldc,
            u32::from(trans_a),
            u32::from(trans_b),
            alpha.to_bits(),
            beta.to_bits(),
        ]
    }

    /// Compile `src`, run `fn_name` over (a, b, c) and return C after the call.
    #[cfg(target_os = "macos")]
    fn run_gemm_v2(
        src: &str,
        fn_name: &str,
        a: &[f32],
        b: &[f32],
        c_init: &[f32],
        params: &[u32],
        groups: (u64, u64, u64),
    ) -> Option<Vec<f32>> {
        use metal::{CompileOptions, Device, MTLResourceOptions, MTLSize};
        let device = Device::system_default()?;
        let queue = device.new_command_queue();
        let lib = device
            .new_library_with_source(src, &CompileOptions::new())
            .ok()?;
        let func = lib.get_function(fn_name, None).ok()?;
        let pso = device
            .new_compute_pipeline_state_with_function(&func)
            .ok()?;
        let mk = |data: &[f32]| {
            device.new_buffer_with_data(
                data.as_ptr() as *const std::ffi::c_void,
                std::mem::size_of_val(data) as u64,
                MTLResourceOptions::StorageModeShared,
            )
        };
        let (buf_a, buf_b, buf_c) = (mk(a), mk(b), mk(c_init));
        let cb = queue.new_command_buffer();
        let enc = cb.new_compute_command_encoder();
        enc.set_compute_pipeline_state(&pso);
        enc.set_buffer(0, Some(&buf_a), 0);
        enc.set_buffer(1, Some(&buf_b), 0);
        enc.set_buffer(2, Some(&buf_c), 0);
        enc.set_bytes(
            3,
            std::mem::size_of_val(params) as u64,
            params.as_ptr() as *const std::ffi::c_void,
        );
        enc.dispatch_thread_groups(
            MTLSize::new(groups.0, groups.1, groups.2),
            MTLSize::new(GEMM_V2_THREADS_X as u64, GEMM_V2_THREADS_Y as u64, 1),
        );
        enc.end_encoding();
        cb.commit();
        cb.wait_until_completed();
        // SAFETY: shared-storage buffer, GPU work has completed, and the
        // allocation was sized from `c_init`.
        let out =
            unsafe { std::slice::from_raw_parts(buf_c.contents() as *const f32, c_init.len()) };
        Some(out.to_vec())
    }

    /// Deterministic pseudo-random values (no `rand` dependency).
    #[cfg(target_os = "macos")]
    fn lcg_fill(len: usize, seed: u32) -> Vec<f32> {
        let mut state = seed | 1;
        (0..len)
            .map(|_| {
                state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                ((state >> 8) as f32 / 8_388_608.0) - 1.0
            })
            .collect()
    }

    /// Reference GEMM honouring both transposes and all three leading
    /// dimensions, accumulated in `f64`.
    #[cfg(target_os = "macos")]
    #[allow(clippy::too_many_arguments)]
    fn gemm_v2_oracle(
        m: usize,
        n: usize,
        k: usize,
        lda: usize,
        ldb: usize,
        ldc: usize,
        trans_a: bool,
        trans_b: bool,
        alpha: f32,
        beta: f32,
        a: &[f32],
        b: &[f32],
        c: &[f32],
    ) -> Vec<f32> {
        let mut out = c.to_vec();
        for r in 0..m {
            for col in 0..n {
                let mut acc = 0.0f64;
                for i in 0..k {
                    let av = if trans_a {
                        a[i * lda + r]
                    } else {
                        a[r * lda + i]
                    };
                    let bv = if trans_b {
                        b[col * ldb + i]
                    } else {
                        b[i * ldb + col]
                    };
                    acc += f64::from(av) * f64::from(bv);
                }
                let prev = if beta == 0.0 {
                    0.0
                } else {
                    f64::from(beta) * f64::from(c[r * ldc + col])
                };
                out[r * ldc + col] = (f64::from(alpha) * acc + prev) as f32;
            }
        }
        out
    }

    /// The regression this whole kernel exists for: transposes and padded
    /// leading dimensions must be honoured, and ragged `m`/`n`/`k` must neither
    /// read nor write out of bounds.
    #[cfg(target_os = "macos")]
    #[test]
    fn gemm_v2_matches_cpu_oracle_for_every_transpose_and_padded_ld() {
        // Deliberately co-prime with the 32x32 tile and the 16-deep K panel.
        let (m, n, k) = (17usize, 13usize, 11usize);
        let (pad_a, pad_b, pad_c) = (3usize, 5usize, 2usize);
        let src = gemm_msl_v2(GemmDtype::F32);
        let groups = (
            (n as u64).div_ceil(GEMM_V2_TILE_N as u64),
            (m as u64).div_ceil(GEMM_V2_TILE_M as u64),
            1,
        );
        let ldc = n + pad_c;

        for trans_a in [false, true] {
            for trans_b in [false, true] {
                for (alpha, beta) in [(1.0f32, 0.0f32), (0.75, 0.25), (-1.5, 2.0)] {
                    let (a_rows, lda) = if trans_a {
                        (k, m + pad_a)
                    } else {
                        (m, k + pad_a)
                    };
                    let (b_rows, ldb) = if trans_b {
                        (n, k + pad_b)
                    } else {
                        (k, n + pad_b)
                    };
                    let a = lcg_fill(a_rows * lda, 7);
                    let b = lcg_fill(b_rows * ldb, 11);
                    let c = lcg_fill(m * ldc, 13);

                    let want = gemm_v2_oracle(
                        m, n, k, lda, ldb, ldc, trans_a, trans_b, alpha, beta, &a, &b, &c,
                    );
                    let params = gemm_v2_params(
                        m as u32, n as u32, k as u32, lda as u32, ldb as u32, ldc as u32, trans_a,
                        trans_b, alpha, beta,
                    );
                    let Some(got) = run_gemm_v2(&src, "gemm_v2_f32", &a, &b, &c, &params, groups)
                    else {
                        return; // no Metal device available
                    };

                    for r in 0..m {
                        for col in 0..n {
                            let idx = r * ldc + col;
                            let (g, w) = (got[idx], want[idx]);
                            assert!(
                                (g - w).abs() <= 1e-4 * w.abs().max(1.0),
                                "ta={trans_a} tb={trans_b} alpha={alpha} beta={beta} \
                                 at ({r},{col}): got {g} want {w}"
                            );
                        }
                        // The padding columns of C must be untouched.
                        for col in n..ldc {
                            let idx = r * ldc + col;
                            assert_eq!(
                                got[idx], c[idx],
                                "ldc padding at ({r},{col}) was overwritten"
                            );
                        }
                    }
                }
            }
        }
    }

    /// `beta == 0` must not read `C` at all, so a NaN-filled output buffer
    /// cannot poison the result.
    #[cfg(target_os = "macos")]
    #[test]
    fn gemm_v2_beta_zero_never_reads_c() {
        let (m, n, k) = (5usize, 6usize, 4usize);
        let a = lcg_fill(m * k, 3);
        let b = lcg_fill(k * n, 5);
        let c = vec![f32::NAN; m * n];
        let params = gemm_v2_params(
            m as u32, n as u32, k as u32, k as u32, n as u32, n as u32, false, false, 1.0, 0.0,
        );
        let Some(got) = run_gemm_v2(
            &gemm_msl_v2(GemmDtype::F32),
            "gemm_v2_f32",
            &a,
            &b,
            &c,
            &params,
            (1, 1, 1),
        ) else {
            return;
        };
        let want = gemm_v2_oracle(m, n, k, k, n, n, false, false, 1.0, 0.0, &a, &b, &c);
        for idx in 0..(m * n) {
            assert!(got[idx].is_finite(), "NaN leaked from C at {idx}");
            assert!((got[idx] - want[idx]).abs() <= 1e-5);
        }
    }

    /// Batched v2 GEMM: every batch element must use its own stride offsets.
    #[cfg(target_os = "macos")]
    #[test]
    fn batched_gemm_v2_matches_cpu_oracle() {
        let (m, n, k, batch) = (9usize, 7usize, 6usize, 3usize);
        let (sa, sb, sc) = (m * k, k * n, m * n);
        let a = lcg_fill(batch * sa, 17);
        let b = lcg_fill(batch * sb, 19);
        let c = lcg_fill(batch * sc, 23);
        let (alpha, beta) = (1.25f32, -0.5f32);

        let mut params = gemm_v2_params(
            m as u32, n as u32, k as u32, k as u32, n as u32, n as u32, false, false, alpha, beta,
        )
        .to_vec();
        params.extend_from_slice(&[batch as u32, sa as u32, sb as u32, sc as u32]);
        assert_eq!(
            std::mem::size_of_val(params.as_slice()),
            BATCHED_GEMM_PARAMS_V2_BYTES
        );

        let groups = (
            (n as u64).div_ceil(GEMM_V2_TILE_N as u64),
            (m as u64).div_ceil(GEMM_V2_TILE_M as u64),
            batch as u64,
        );
        let Some(got) = run_gemm_v2(
            &batched_gemm_msl_v2(GemmDtype::F32),
            "batched_gemm_v2_f32",
            &a,
            &b,
            &c,
            &params,
            groups,
        ) else {
            return;
        };

        for bi in 0..batch {
            let want = gemm_v2_oracle(
                m,
                n,
                k,
                k,
                n,
                n,
                false,
                false,
                alpha,
                beta,
                &a[bi * sa..],
                &b[bi * sb..],
                &c[bi * sc..(bi + 1) * sc],
            );
            for idx in 0..sc {
                let (g, w) = (got[bi * sc + idx], want[idx]);
                assert!(
                    (g - w).abs() <= 1e-4 * w.abs().max(1.0),
                    "batch {bi} idx {idx}: got {g} want {w}"
                );
            }
        }
    }

    /// End-to-end check that [`crate::numeric::pack_f16`] really feeds the
    /// `half` GEMM: pack on the host, run the FP16 kernel, unpack, compare.
    /// This is the host-side story `gemm_f16` previously lacked entirely.
    #[cfg(target_os = "macos")]
    #[test]
    fn gemm_v2_f16_round_trips_through_the_numeric_pack_helpers() {
        use crate::numeric::{pack_f16, unpack_f16};
        use metal::{CompileOptions, Device, MTLResourceOptions, MTLSize};

        let Some(device) = Device::system_default() else {
            return;
        };
        let queue = device.new_command_queue();
        let src = gemm_msl_v2(GemmDtype::F16);
        let Ok(lib) = device.new_library_with_source(&src, &CompileOptions::new()) else {
            return;
        };
        let Ok(func) = lib.get_function("gemm_v2_f16", None) else {
            return;
        };
        let Ok(pso) = device.new_compute_pipeline_state_with_function(&func) else {
            return;
        };

        let (m, n, k) = (10usize, 9usize, 7usize);
        // Quantise the inputs through binary16 first so the oracle sees exactly
        // the values the GPU will read.
        let a = unpack_f16(&pack_f16(&lcg_fill(m * k, 61)));
        let b = unpack_f16(&pack_f16(&lcg_fill(k * n, 67)));
        let (a16, b16) = (pack_f16(&a), pack_f16(&b));
        let c16 = vec![0u16; m * n];
        let (alpha, beta) = (1.0f32, 0.0f32);

        let mk = |data: &[u16]| {
            device.new_buffer_with_data(
                data.as_ptr() as *const std::ffi::c_void,
                std::mem::size_of_val(data) as u64,
                MTLResourceOptions::StorageModeShared,
            )
        };
        let (ba, bb, bc) = (mk(&a16), mk(&b16), mk(&c16));
        let params = gemm_v2_params(
            m as u32, n as u32, k as u32, k as u32, n as u32, n as u32, false, false, alpha, beta,
        );
        let cb = queue.new_command_buffer();
        let enc = cb.new_compute_command_encoder();
        enc.set_compute_pipeline_state(&pso);
        enc.set_buffer(0, Some(&ba), 0);
        enc.set_buffer(1, Some(&bb), 0);
        enc.set_buffer(2, Some(&bc), 0);
        enc.set_bytes(
            3,
            GEMM_PARAMS_V2_BYTES as u64,
            params.as_ptr() as *const std::ffi::c_void,
        );
        enc.dispatch_thread_groups(
            MTLSize::new(1, 1, 1),
            MTLSize::new(GEMM_V2_THREADS_X as u64, GEMM_V2_THREADS_Y as u64, 1),
        );
        enc.end_encoding();
        cb.commit();
        cb.wait_until_completed();
        // SAFETY: shared storage, GPU work complete, sized from `c16`.
        let raw = unsafe { std::slice::from_raw_parts(bc.contents() as *const u16, c16.len()) };
        let got = unpack_f16(raw);

        for r in 0..m {
            for col in 0..n {
                let mut acc = 0.0f64;
                for i in 0..k {
                    acc += f64::from(a[r * k + i]) * f64::from(b[i * n + col]);
                }
                let g = f64::from(got[r * n + col]);
                // binary16 output carries ~11 significant bits.
                assert!(
                    (g - acc).abs() <= 2e-3 * acc.abs().max(1.0),
                    "f16 gemm at ({r},{col}): got {g} want {acc}"
                );
            }
        }
    }
}
