// W1e: reading DEFLATE-compressed chunked datasets **written by h5py**.
//
// The writer's own tests prove that oxih5 can read back what oxih5 wrote, which
// is exactly the property a self-consistent mistake preserves.  These read a
// file produced by libhdf5 1.14.6 through h5py 3.15.1 — `fixtures/
// deflate_chunked.h5`, regenerated by `tests/gen_fixtures.py` — so the filter
// pipeline message, the chunk keys and the compressed streams all come from the
// reference implementation rather than from us.
//
// The fixture is written with `libver='earliest'`, which pins the same
// combination `FileWriter` emits: superblock v0, object header v1, layout v3, a
// version-1 filter pipeline and a B-tree v1 chunk index.

use std::path::PathBuf;

fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("deflate_chunked.h5")
}

/// One chunk covering the dataset — the shape `FileWriter::set_deflate` emits.
#[test]
fn w1e_read_h5py_deflate_single_chunk() {
    let file = oxih5::open(fixture()).expect("open deflate_chunked.h5");
    let ds = file.dataset("whole").expect("whole");
    assert_eq!(ds.shape, vec![4096usize]);

    let want: Vec<f64> = (0..4096).map(|i| f64::from(i % 17) * 0.25).collect();
    assert_eq!(
        ds.as_f64().expect("as_f64"),
        want,
        "a gzip chunk written by libhdf5 must inflate to the values it held"
    );
}

/// A 1-D dataset whose chunk size does not divide its extent.
///
/// The last chunk is stored full-size with fill in the overhang, so a reader
/// that trusted the chunk's element count over the dataspace would hand back
/// 9 values for a 7-element dataset.
#[test]
fn w1e_read_h5py_deflate_ragged_1d() {
    let file = oxih5::open(fixture()).expect("open");
    let ds = file.dataset("tiled").expect("tiled");
    assert_eq!(ds.shape, vec![7usize]);
    assert_eq!(
        ds.as_i32().expect("as_i32"),
        (0..7i32).collect::<Vec<_>>(),
        "three chunks of three over an extent of seven"
    );
}

/// A 2-D dataset ragged in **both** dimensions: 3 × 2 chunks of `[2, 2]` over
/// `[5, 3]`, so four of the six chunks hang over an edge.
///
/// This is the shape that catches a row-major/column-major mix-up in chunk
/// assembly: transposing the grid still yields fifteen values, just the wrong
/// fifteen.
#[test]
fn w1e_read_h5py_deflate_ragged_2d() {
    let file = oxih5::open(fixture()).expect("open");
    let ds = file.dataset("grid").expect("grid");
    assert_eq!(ds.shape, vec![5usize, 3]);
    assert_eq!(
        ds.as_i32().expect("as_i32"),
        (0..15i32).collect::<Vec<_>>(),
        "row-major over a 3 × 2 chunk grid"
    );
}

/// The highest compression level, and a pipeline with two filters in it.
///
/// `shuffled` is written `shuffle=True, compression='gzip'`, so the pipeline
/// holds shuffle then deflate and a reader has to invert them in the opposite
/// order.  Inverting them the other way round produces plausible-looking
/// garbage rather than an error.
#[test]
fn w1e_read_h5py_deflate_levels_and_filter_order() {
    let file = oxih5::open(fixture()).expect("open");

    let max_level = file.dataset("max_level").expect("max_level");
    assert_eq!(max_level.shape, vec![1024usize]);
    assert_eq!(
        max_level.as_u8().expect("as_u8"),
        (0..1024u32)
            .map(|i| (i % 256) as u8 % 7)
            .collect::<Vec<_>>(),
        "level 9 is the same codec as level 6"
    );

    let shuffled = file.dataset("shuffled").expect("shuffled");
    assert_eq!(shuffled.shape, vec![512usize]);
    assert_eq!(
        shuffled.as_f32().expect("as_f32"),
        (0..512).map(|i| i as f32).collect::<Vec<_>>(),
        "shuffle then deflate must be undone as inflate then unshuffle"
    );
}

/// Every dataset in the fixture is listed and readable in one pass.
#[test]
fn w1e_read_h5py_deflate_all_datasets_listed() {
    let file = oxih5::open(fixture()).expect("open");
    let mut names = file.dataset_names().expect("dataset_names");
    names.sort();
    assert_eq!(
        names,
        vec!["grid", "max_level", "shuffled", "tiled", "whole"]
            .into_iter()
            .map(String::from)
            .collect::<Vec<_>>()
    );
    for name in &names {
        let ds = file.dataset(name).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(!ds.shape.is_empty(), "{name} has a shape");
    }
}
