[package]
name = "oxiphysics-io"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "File I/O and serialization for the OxiPhysics engine"
readme = "README.md"
categories = ["science", "filesystem"]
keywords = ["physics", "io", "vtk", "hdf5", "serialization"]

[dependencies]
thiserror = { workspace = true }
oxiphysics-core = { workspace = true }
oxiphysics-articulated = { workspace = true }
oxiarc-zstd = { workspace = true }

[dev-dependencies]
oxiarc-zstd = { workspace = true }
