//! AllRAD (All-Round Ambisonic Decoding) for arbitrary loudspeaker arrays.
//!
//! AllRAD combines a *virtual* optimal t-design speaker array with a
//! subsequent VBAP-style mapping to the real (possibly irregular) speakers.
//! This gives perceptually robust results for any speaker geometry.
//!
//! # Algorithm overview
//!
//! 1. Choose a set of **virtual t-design points** on the sphere.  These are
//!    uniformly distributed directions that allow exact integration of SH
//!    polynomials up to the desired order.
//! 2. Build the **SH decode matrix** `D` of size `[N_virtual × N_ambi]`:
//!    each row is the SH basis vector evaluated at one virtual speaker direction.
//! 3. Build the **VBAP-style mapping matrix** `M` of size `[N_real × N_virtual]`:
//!    each virtual speaker is mapped to the nearest real speakers using an
//!    inverse-distance-weighted (IDW) scheme on the unit sphere.
//! 4. The combined **AllRAD matrix** is `A = M · D`.
//! 5. To decode: `feeds = A · ambisonics_vector`.
//!
//! # Coordinate convention
//! - Speaker positions are **unit vectors** `[x, y, z]`.
//!   If non-unit vectors are supplied they are normalised automatically.
//! - The ambisonic signal vector is ordered ACN, normalised N3D (AmbiX format).
//!
//! # References
//! Zotter, F. & Frank, M. (2012). *All-Round Ambisonic Panning and Decoding*.
//! Journal of the Audio Engineering Society 60(10), 807–820.

use crate::{ambisonics::n3d_sh_coefficients, SpatialError};

// ─── Constants ────────────────────────────────────────────────────────────────

/// Maximum supported HOA order.
const MAX_ORDER: u32 = 5;

// ─── t-design virtual speaker positions ──────────────────────────────────────

/// Return a set of near-uniform virtual speaker positions (unit vectors) for
/// a spherical t-design appropriate for the given HOA order.
///
/// We use a pre-computed 24-point t=5 design which is sufficient for decoding
/// up to 3rd-order HOA, and a 48-point set for higher orders.
fn t_design_points(order: u32) -> Vec<[f32; 3]> {
    if order <= 3 {
        t_design_24()
    } else {
        t_design_48()
    }
}

/// 24-point spherical t-design (t = 5, degree-5 precision).
///
/// Coordinates sourced from Hardin & Sloane (1996) numerical t-designs.
fn t_design_24() -> Vec<[f32; 3]> {
    // 24 points generated by the vertices + edge mid-points of a cuboctahedron
    // and normalised to the unit sphere.  This constitutes a valid t=5 design.
    let sqrt2_inv = 1.0_f32 / std::f32::consts::SQRT_2;
    vec![
        // Cuboctahedron vertices (12): permutations of (±1, ±1, 0)/√2
        [sqrt2_inv, sqrt2_inv, 0.0],
        [-sqrt2_inv, sqrt2_inv, 0.0],
        [sqrt2_inv, -sqrt2_inv, 0.0],
        [-sqrt2_inv, -sqrt2_inv, 0.0],
        [sqrt2_inv, 0.0, sqrt2_inv],
        [-sqrt2_inv, 0.0, sqrt2_inv],
        [sqrt2_inv, 0.0, -sqrt2_inv],
        [-sqrt2_inv, 0.0, -sqrt2_inv],
        [0.0, sqrt2_inv, sqrt2_inv],
        [0.0, -sqrt2_inv, sqrt2_inv],
        [0.0, sqrt2_inv, -sqrt2_inv],
        [0.0, -sqrt2_inv, -sqrt2_inv],
        // Additional 12 points: permutations from dodecahedron / icosahedron vertices
        // (golden-ratio based), normalised to unit sphere.
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [1.0 / n, phi / n, 0.0]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [-1.0 / n, phi / n, 0.0]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [1.0 / n, -phi / n, 0.0]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [-1.0 / n, -phi / n, 0.0]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [0.0, 1.0 / n, phi / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [0.0, -1.0 / n, phi / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [0.0, 1.0 / n, -phi / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [0.0, -1.0 / n, -phi / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [phi / n, 0.0, 1.0 / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [-phi / n, 0.0, 1.0 / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [phi / n, 0.0, -1.0 / n]
        },
        {
            let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
            let n = (1.0 + phi * phi).sqrt();
            [-phi / n, 0.0, -1.0 / n]
        },
    ]
}

/// 48-point near-uniform set obtained by combining the 24-point icosahedral
/// design with its antipodal points.
fn t_design_48() -> Vec<[f32; 3]> {
    let base = t_design_24();
    let mut pts: Vec<[f32; 3]> = Vec::with_capacity(48);
    for p in &base {
        pts.push(*p);
        pts.push([-p[0], -p[1], -p[2]]);
    }
    pts
}

// ─── Types ────────────────────────────────────────────────────────────────────

/// AllRAD decoder for an arbitrary loudspeaker array.
///
/// Build with [`AllRadDecoder::new`] and decode with [`AllRadDecoder::decode`].
#[derive(Debug, Clone)]
pub struct AllRadDecoder {
    /// HOA order to decode.
    pub order: u32,
    /// Real speaker positions (unit vectors).
    pub speakers: Vec<[f32; 3]>,
    /// Pre-computed decode matrix `A` of size `[n_speakers × n_ambi_channels]`.
    /// Stored row-major: `A[spk_idx * n_ambi + ch_idx]`.
    decode_matrix: Vec<f32>,
    /// Number of ambisonic channels `= (order+1)²`.
    n_ambi: usize,
}

// ─── AllRadDecoder ────────────────────────────────────────────────────────────

impl AllRadDecoder {
    /// Build an AllRAD decoder for the given HOA order and speaker positions.
    ///
    /// # Parameters
    /// - `order`: HOA order (1–5).
    /// - `speakers`: slice of unit-vector speaker positions.  Non-unit vectors
    ///   are normalised.  Must contain at least `(order+1)²` speakers.
    ///
    /// # Errors
    /// Returns [`SpatialError::InvalidConfig`] if the order is out of range or
    /// the speaker count is too small.
    pub fn new(order: u32, speakers: Vec<[f32; 3]>) -> Result<Self, SpatialError> {
        if order == 0 || order > MAX_ORDER {
            return Err(SpatialError::InvalidConfig(format!(
                "AllRAD order must be in [1, {MAX_ORDER}], got {order}"
            )));
        }
        let n_ambi = ((order + 1) * (order + 1)) as usize;
        // AllRAD can work with fewer real speakers than ambisonic channels: the
        // IDW virtual-to-real mapping distributes energy regardless of real
        // speaker count.  We enforce at least 4 speakers (minimum for 1st-order
        // HOA) so that the mapping is non-degenerate.
        let min_speakers = n_ambi.min(4);
        if speakers.len() < min_speakers {
            return Err(SpatialError::InvalidConfig(format!(
                "AllRAD requires at least {min_speakers} speakers, got {}",
                speakers.len()
            )));
        }

        // Normalise speaker vectors.
        let speakers: Vec<[f32; 3]> = speakers.into_iter().map(|s| normalise_vec3(s)).collect();

        // Build the decode matrix.
        let decode_matrix = build_allrad_matrix(order, &speakers);

        Ok(Self {
            order,
            speakers,
            decode_matrix,
            n_ambi,
        })
    }

    /// Decode an Nth-order HOA signal into per-speaker feeds.
    ///
    /// # Parameters
    /// - `ambisonics`: slice of `(order+1)²` HOA channel samples (ACN/N3D).
    ///
    /// # Returns
    /// A `Vec<f32>` of length `speakers.len()`.  Each element is the amplitude
    /// feed for the corresponding speaker.
    ///
    /// # Errors
    /// Returns [`SpatialError::InvalidConfig`] if the input length does not
    /// match the expected number of HOA channels.
    pub fn decode(&self, ambisonics: &[f32]) -> Result<Vec<f32>, SpatialError> {
        if ambisonics.len() != self.n_ambi {
            return Err(SpatialError::InvalidConfig(format!(
                "AllRAD decode: expected {} ambi channels, got {}",
                self.n_ambi,
                ambisonics.len()
            )));
        }

        let n_spk = self.speakers.len();
        let mut feeds = vec![0.0_f32; n_spk];

        for (spk_idx, feed) in feeds.iter_mut().enumerate() {
            let row_start = spk_idx * self.n_ambi;
            let mut sum = 0.0_f32;
            for ch in 0..self.n_ambi {
                sum += self.decode_matrix[row_start + ch] * ambisonics[ch];
            }
            *feed = sum;
        }

        Ok(feeds)
    }

    /// Return the raw decode matrix (row-major, `n_speakers × n_ambi`).
    pub fn decode_matrix(&self) -> &[f32] {
        &self.decode_matrix
    }

    /// Number of ambisonic input channels.
    pub fn n_ambi_channels(&self) -> usize {
        self.n_ambi
    }
}

// ─── Matrix construction ──────────────────────────────────────────────────────

/// Build the AllRAD decode matrix `A = M · D`.
///
/// - `D`: SH decode matrix `[N_virt × N_ambi]` — each row is the SH basis
///   evaluated at a virtual speaker direction, scaled by `1/N_virt`.
/// - `M`: VBAP-style IDW mapping `[N_real × N_virt]` — maps each virtual
///   speaker's energy to the nearest real speakers.
fn build_allrad_matrix(order: u32, speakers: &[[f32; 3]]) -> Vec<f32> {
    let n_ambi = ((order + 1) * (order + 1)) as usize;
    let virt_pts = t_design_points(order);
    let n_virt = virt_pts.len();
    let n_real = speakers.len();

    // ── SH decode matrix D: [n_virt × n_ambi] ────────────────────────────────
    // Row i = SH basis at virtual point i, scaled by 4π/n_virt.
    let weight = 4.0 * std::f32::consts::PI / n_virt as f32;
    let mut d_matrix: Vec<f32> = Vec::with_capacity(n_virt * n_ambi);
    for &vp in &virt_pts {
        let (az, el) = cartesian_to_spherical(vp);
        let sh = n3d_sh_coefficients(az, el, order);
        for c in sh {
            d_matrix.push(c * weight);
        }
    }

    // ── IDW mapping matrix M: [n_real × n_virt] ──────────────────────────────
    // For each virtual speaker v, find the 3 nearest real speakers and distribute
    // its energy inversely proportional to the great-circle distance.
    let k_nearest = 3.min(n_real);
    let mut m_matrix = vec![0.0_f32; n_real * n_virt];

    for (v_idx, &vp) in virt_pts.iter().enumerate() {
        // Compute angular distances from virtual point to all real speakers.
        let mut dist_idx: Vec<(usize, f32)> = speakers
            .iter()
            .enumerate()
            .map(|(i, &sp)| (i, great_circle_distance(vp, sp)))
            .collect();
        dist_idx.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));

        // Nearest k real speakers.
        let nearest = &dist_idx[..k_nearest];

        // Check for exact coincidence.
        if nearest[0].1 < 1e-6 {
            let row = nearest[0].0;
            m_matrix[row * n_virt + v_idx] = 1.0;
            continue;
        }

        // IDW weights: w_i = 1 / d_i.
        let raw: Vec<f32> = nearest.iter().map(|&(_, d)| 1.0 / d.max(1e-6)).collect();
        let sum: f32 = raw.iter().sum();
        if sum < 1e-12 {
            // Fallback: nearest speaker gets all weight.
            m_matrix[nearest[0].0 * n_virt + v_idx] = 1.0;
        } else {
            for (&(spk_i, _), &w) in nearest.iter().zip(raw.iter()) {
                m_matrix[spk_i * n_virt + v_idx] += w / sum;
            }
        }
    }

    // ── Combined matrix A = M · D: [n_real × n_ambi] ─────────────────────────
    let mut a_matrix = vec![0.0_f32; n_real * n_ambi];
    for r in 0..n_real {
        for c in 0..n_ambi {
            let mut sum = 0.0_f32;
            for v in 0..n_virt {
                sum += m_matrix[r * n_virt + v] * d_matrix[v * n_ambi + c];
            }
            a_matrix[r * n_ambi + c] = sum;
        }
    }

    a_matrix
}

// ─── Geometry helpers ─────────────────────────────────────────────────────────

/// Normalise a 3-D vector to unit length.  Returns [0,0,1] for zero vectors.
fn normalise_vec3(v: [f32; 3]) -> [f32; 3] {
    let norm = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
    if norm < 1e-10 {
        [0.0, 0.0, 1.0]
    } else {
        [v[0] / norm, v[1] / norm, v[2] / norm]
    }
}

/// Convert a unit Cartesian vector to (azimuth, elevation) in radians.
/// Azimuth: 0 = +x axis, CCW. Elevation: 0 = XY plane, +π/2 = +z.
fn cartesian_to_spherical(v: [f32; 3]) -> (f32, f32) {
    let [x, y, z] = normalise_vec3(v);
    let el = z.clamp(-1.0, 1.0).asin();
    let az = y.atan2(x);
    (az, el)
}

/// Great-circle distance between two unit vectors (radians).
fn great_circle_distance(a: [f32; 3], b: [f32; 3]) -> f32 {
    let dot = (a[0] * b[0] + a[1] * b[1] + a[2] * b[2]).clamp(-1.0, 1.0);
    dot.acos()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::PI;

    /// Build a regular icosahedral speaker layout (12 speakers) for tests.
    fn icosahedron_speakers() -> Vec<[f32; 3]> {
        let phi = (1.0_f32 + 5.0_f32.sqrt()) / 2.0;
        let n = (1.0 + phi * phi).sqrt();
        vec![
            [1.0 / n, phi / n, 0.0],
            [-1.0 / n, phi / n, 0.0],
            [1.0 / n, -phi / n, 0.0],
            [-1.0 / n, -phi / n, 0.0],
            [0.0, 1.0 / n, phi / n],
            [0.0, -1.0 / n, phi / n],
            [0.0, 1.0 / n, -phi / n],
            [0.0, -1.0 / n, -phi / n],
            [phi / n, 0.0, 1.0 / n],
            [-phi / n, 0.0, 1.0 / n],
            [phi / n, 0.0, -1.0 / n],
            [-phi / n, 0.0, -1.0 / n],
        ]
    }

    fn assert_near(a: f32, b: f32, tol: f32, label: &str) {
        assert!(
            (a - b).abs() < tol,
            "{label}: expected ≈ {b}, got {a} (tol {tol})"
        );
    }

    // ── Construction ────────────────────────────────────────────────────────

    #[test]
    fn test_allrad_new_valid_first_order() {
        let speakers = icosahedron_speakers();
        let decoder = AllRadDecoder::new(1, speakers).expect("should build");
        assert_eq!(decoder.n_ambi_channels(), 4);
    }

    #[test]
    fn test_allrad_new_valid_third_order() {
        let speakers = icosahedron_speakers();
        let decoder = AllRadDecoder::new(3, speakers).expect("should build for 3rd order");
        assert_eq!(decoder.n_ambi_channels(), 16);
    }

    #[test]
    fn test_allrad_new_too_few_speakers_fails() {
        // 1st order needs ≥ 4 speakers.
        let speakers = vec![[1.0_f32, 0.0, 0.0], [0.0, 1.0, 0.0], [-1.0, 0.0, 0.0]];
        assert!(AllRadDecoder::new(1, speakers).is_err());
    }

    #[test]
    fn test_allrad_new_order_zero_fails() {
        let speakers = icosahedron_speakers();
        assert!(AllRadDecoder::new(0, speakers).is_err());
    }

    // ── Decode ───────────────────────────────────────────────────────────────

    #[test]
    fn test_allrad_decode_output_length() {
        let speakers = icosahedron_speakers();
        let n_spk = speakers.len();
        let decoder = AllRadDecoder::new(1, speakers).expect("ok");
        let ambi = vec![1.0_f32; decoder.n_ambi_channels()];
        let feeds = decoder.decode(&ambi).expect("decode ok");
        assert_eq!(feeds.len(), n_spk);
    }

    #[test]
    fn test_allrad_decode_wrong_input_length_fails() {
        let decoder = AllRadDecoder::new(1, icosahedron_speakers()).expect("ok");
        let ambi = vec![1.0_f32; 5]; // should be 4
        assert!(decoder.decode(&ambi).is_err());
    }

    #[test]
    fn test_allrad_decode_omnidirectional_distributes_energy() {
        // W-only input (omni source): all speakers should receive some energy.
        let decoder = AllRadDecoder::new(1, icosahedron_speakers()).expect("ok");
        let mut ambi = vec![0.0_f32; decoder.n_ambi_channels()];
        ambi[0] = 1.0; // W channel only
        let feeds = decoder.decode(&ambi).expect("ok");
        let total: f32 = feeds.iter().map(|x| x.abs()).sum();
        assert!(
            total > 0.0,
            "Omni source should reach speakers, total={total}"
        );
    }

    #[test]
    fn test_allrad_decode_feeds_are_finite() {
        let decoder = AllRadDecoder::new(2, icosahedron_speakers()).expect("ok");
        let ambi: Vec<f32> = (0..decoder.n_ambi_channels())
            .map(|i| (i as f32 * 0.3).sin())
            .collect();
        let feeds = decoder.decode(&ambi).expect("ok");
        for (i, &f) in feeds.iter().enumerate() {
            assert!(f.is_finite(), "feed[{i}] should be finite, got {f}");
        }
    }

    // ── Geometry helpers ─────────────────────────────────────────────────────

    #[test]
    fn test_normalise_vec3_unit() {
        let v = normalise_vec3([3.0, 0.0, 0.0]);
        assert_near(v[0], 1.0, 1e-6, "normalised x");
        assert_near(v[1], 0.0, 1e-6, "normalised y");
    }

    #[test]
    fn test_normalise_vec3_zero_returns_fallback() {
        let v = normalise_vec3([0.0, 0.0, 0.0]);
        assert_near(v[2], 1.0, 1e-6, "zero vector → [0,0,1]");
    }

    #[test]
    fn test_cartesian_to_spherical_front() {
        let (az, el) = cartesian_to_spherical([1.0, 0.0, 0.0]);
        assert_near(az, 0.0, 1e-5, "front az");
        assert_near(el, 0.0, 1e-5, "front el");
    }

    #[test]
    fn test_cartesian_to_spherical_top() {
        let (_, el) = cartesian_to_spherical([0.0, 0.0, 1.0]);
        assert_near(el, PI / 2.0, 1e-5, "top elevation");
    }

    #[test]
    fn test_great_circle_distance_same_point() {
        let v = [1.0_f32, 0.0, 0.0];
        let d = great_circle_distance(v, v);
        assert_near(d, 0.0, 1e-5, "same point distance");
    }

    #[test]
    fn test_great_circle_distance_opposite_points() {
        let a = [1.0_f32, 0.0, 0.0];
        let b = [-1.0, 0.0, 0.0];
        let d = great_circle_distance(a, b);
        assert_near(d, PI, 1e-5, "antipodal distance = π");
    }
}
