//! Algebraic K-theory: K_0, K_1, and K_2 groups for rings and fields.
//!
//! This module implements the fundamental constructions of algebraic K-theory:
//!
//! - **K_0(R)**: The Grothendieck group of finitely generated projective R-modules.
//!   K_0(field) ≅ K_0(Z) ≅ Z.
//!
//! - **K_1(R)**: The abelianization GL(R)^ab of the stable general linear group.
//!   For commutative R, K_1(R) ≅ R× via the determinant.
//!
//! - **K_2(R)**: Milnor's K_2, generated by Steinberg symbols {a,b} subject to
//!   the Matsumoto relations. The Bass–Tate theorem and Hilbert's theorem 90
//!   connect K_2(F) to Brauer groups.
//!
//! ## References
//!
//! - Milnor, J. (1971). *Introduction to Algebraic K-theory*. Princeton UP.
//! - Bass, H. (1968). *Algebraic K-Theory*. W. A. Benjamin.
//! - Rosenberg, J. (1994). *Algebraic K-Theory and Its Applications*. Springer.

pub mod functions;
pub mod types;

pub use functions::*;
pub use types::*;
