//! Algebraic K-theory types: K_0, K_1, K_2 groups and supporting data structures.
//!
//! This module provides concrete representations of the K-groups of rings:
//! - K_0(R): the Grothendieck group of finitely generated projective modules
//! - K_1(R): the abelianization GL(R)^ab of the stable general linear group
//! - K_2(R): Milnor's K_2, generated by Steinberg symbols

use std::fmt;

/// Finitely generated projective module over a commutative ring R.
///
/// A projective module P satisfies: there exists Q such that P ⊕ Q ≅ Rⁿ.
/// The `rank` is the locally constant function dim_{R_p}(P_p) for prime p.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectiveModule {
    /// Rank of the projective module (number of generators in the free part).
    pub rank: usize,
    /// The base ring R over which this module is defined.
    pub base_ring: String,
    /// Generators of the module (by name or description).
    pub generators: Vec<String>,
}

impl ProjectiveModule {
    /// Construct a new projective module.
    pub fn new(rank: usize, base_ring: &str, generators: Vec<String>) -> Self {
        ProjectiveModule {
            rank,
            base_ring: base_ring.to_string(),
            generators,
        }
    }

    /// The free module R^n of rank n.
    pub fn free(n: usize, ring: &str) -> Self {
        let generators = (0..n).map(|i| format!("e_{i}")).collect();
        ProjectiveModule {
            rank: n,
            base_ring: ring.to_string(),
            generators,
        }
    }

    /// Direct sum of two projective modules (rank adds).
    pub fn direct_sum(&self, other: &ProjectiveModule) -> ProjectiveModule {
        let mut gens = self.generators.clone();
        gens.extend(other.generators.iter().cloned());
        ProjectiveModule {
            rank: self.rank + other.rank,
            base_ring: self.base_ring.clone(),
            generators: gens,
        }
    }
}

impl fmt::Display for ProjectiveModule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "ProjectiveModule(rank={}, ring={}, gens={:?})",
            self.rank, self.base_ring, self.generators
        )
    }
}

/// Stable isomorphism class of a projective module — element of K_0(R).
///
/// Two projective modules P, Q are stably isomorphic if P ⊕ Rⁿ ≅ Q ⊕ Rⁿ for some n.
/// K_0(R) = { \[P\] - \[Q\] : P, Q finitely generated projective } (Grothendieck group).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StableIsomorphismClass {
    /// The stable rank of this class (rank of a representative module).
    pub rank: usize,
    /// A unique identifier distinguishing non-isomorphic classes of the same rank.
    pub id: usize,
}

impl StableIsomorphismClass {
    /// Construct a stable isomorphism class.
    pub fn new(rank: usize, id: usize) -> Self {
        StableIsomorphismClass { rank, id }
    }

    /// The class of the free module R^n.
    pub fn free_class(n: usize) -> Self {
        StableIsomorphismClass { rank: n, id: 0 }
    }
}

impl fmt::Display for StableIsomorphismClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[P_{}(rank={})]", self.id, self.rank)
    }
}

/// The Grothendieck group K_0(R).
///
/// K_0(R) is generated by stable isomorphism classes \[P\] of f.g. projective modules,
/// with addition \[P\] + \[Q\] = \[P ⊕ Q\].
///
/// Key facts:
/// - K_0(field) ≅ Z (generated by \[k\])
/// - K_0(Z) ≅ Z (generated by \[Z\])
/// - K_0(Dedekind domain) ≅ Z ⊕ Cl(R) where Cl(R) is the class group
#[derive(Debug, Clone)]
pub struct K0Group {
    /// The stable isomorphism classes forming this K_0 group.
    pub classes: Vec<StableIsomorphismClass>,
    /// Addition table: `addition_table\[i\]\[j\]` = index of \[P_i\] + \[P_j\] in `classes`.
    pub addition_table: Vec<Vec<usize>>,
}

impl K0Group {
    /// Construct a K_0 group from its classes and addition table.
    pub fn new(classes: Vec<StableIsomorphismClass>, addition_table: Vec<Vec<usize>>) -> Self {
        K0Group {
            classes,
            addition_table,
        }
    }

    /// The rank homomorphism K_0(R) → Z sends \[P\] to rank(P).
    pub fn rank_of(&self, idx: usize) -> Option<usize> {
        self.classes.get(idx).map(|c| c.rank)
    }

    /// Number of generators (classes) in this K_0 group representation.
    pub fn num_classes(&self) -> usize {
        self.classes.len()
    }
}

impl fmt::Display for K0Group {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "K_0 with {} classes: [", self.classes.len())?;
        for (i, cls) in self.classes.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{cls}")?;
        }
        write!(f, "]")
    }
}

/// The multiplicative group of units R× used in computing K_1(R).
///
/// For a commutative ring R, K_1(R) = GL(R)^ab = R× (by Whitehead's theorem),
/// where R× denotes the group of invertible elements.
#[derive(Debug, Clone)]
pub struct UnitGroup {
    /// The units of the ring, represented by name.
    pub units: Vec<String>,
    /// Multiplication table: `multiplication_table\[i\]\[j\]` = index of units\[i\] * units\[j\].
    pub multiplication_table: Vec<Vec<usize>>,
}

impl UnitGroup {
    /// Construct a unit group.
    pub fn new(units: Vec<String>, multiplication_table: Vec<Vec<usize>>) -> Self {
        UnitGroup {
            units,
            multiplication_table,
        }
    }

    /// Number of units.
    pub fn order(&self) -> usize {
        self.units.len()
    }

    /// Return the name of unit at index i, if it exists.
    pub fn unit_name(&self, i: usize) -> Option<&str> {
        self.units.get(i).map(String::as_str)
    }

    /// Product of two units by index. Returns None if indices are out of bounds.
    pub fn multiply(&self, i: usize, j: usize) -> Option<usize> {
        self.multiplication_table
            .get(i)
            .and_then(|row| row.get(j))
            .copied()
    }
}

impl fmt::Display for UnitGroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "R× = {:?}", self.units)
    }
}

/// K_1(R) = GL(R)^ab — the first algebraic K-group of a ring R.
///
/// For a commutative ring R, K_1(R) ≅ R×.
/// For a general ring, K_1(R) is generated by invertible matrices modulo
/// elementary matrices (Whitehead's theorem: E(R) = \[GL(R), GL(R)\]).
///
/// The `relations` encode the defining relations in the presentation
/// K_1(R) = GL(R) / E(R), expressed as integer vectors (row relations in the
/// abelian group presentation).
#[derive(Debug, Clone)]
pub struct K1Group {
    /// The unit group R× generating K_1 (for commutative rings).
    pub units: UnitGroup,
    /// Relations in the abelian group presentation (each row is a relation vector).
    pub relations: Vec<Vec<i64>>,
}

impl K1Group {
    /// Construct a K_1 group.
    pub fn new(units: UnitGroup, relations: Vec<Vec<i64>>) -> Self {
        K1Group { units, relations }
    }

    /// Number of generators (= number of units).
    pub fn num_generators(&self) -> usize {
        self.units.order()
    }

    /// Number of defining relations.
    pub fn num_relations(&self) -> usize {
        self.relations.len()
    }
}

impl fmt::Display for K1Group {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "K_1 = {} with {} relations",
            self.units,
            self.relations.len()
        )
    }
}

/// A matrix with entries in a ring R, stored row-major.
///
/// Used in the definition of GL_n(R) and the computation of K_1 via
/// elementary matrix manipulations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatrixOverRing {
    /// Rows of the matrix (row-major storage).
    pub rows: Vec<Vec<i64>>,
    /// The ring over which entries are taken.
    pub ring: String,
}

impl MatrixOverRing {
    /// Construct a matrix from rows.
    pub fn new(rows: Vec<Vec<i64>>, ring: &str) -> Self {
        MatrixOverRing {
            rows,
            ring: ring.to_string(),
        }
    }

    /// The n×n identity matrix over `ring`.
    pub fn identity(n: usize, ring: &str) -> Self {
        let rows = (0..n)
            .map(|i| (0..n).map(|j| if i == j { 1 } else { 0 }).collect())
            .collect();
        MatrixOverRing {
            rows,
            ring: ring.to_string(),
        }
    }

    /// Number of rows.
    pub fn num_rows(&self) -> usize {
        self.rows.len()
    }

    /// Number of columns (0 if no rows).
    pub fn num_cols(&self) -> usize {
        self.rows.first().map(|r| r.len()).unwrap_or(0)
    }

    /// Entry at (i, j), returns None if out of bounds.
    pub fn entry(&self, i: usize, j: usize) -> Option<i64> {
        self.rows.get(i).and_then(|r| r.get(j)).copied()
    }
}

impl fmt::Display for MatrixOverRing {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Matrix({}x{} over {})",
            self.num_rows(),
            self.num_cols(),
            self.ring
        )
    }
}

/// Elementary matrix e_{ij}(λ): the identity matrix with λ added at position (i, j), i ≠ j.
///
/// These generate the elementary subgroup E(R) ⊂ GL(R), which equals \[GL(R), GL(R)\]
/// (Whitehead's theorem). The Steinberg relations are the defining relations among
/// elementary matrices.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ElementaryMatrix {
    /// Size n of the n×n matrix.
    pub size: usize,
    /// Row index i (0-based).
    pub i: usize,
    /// Column index j (0-based), must differ from i.
    pub j: usize,
    /// The scalar λ placed at position (i, j).
    pub scalar: i64,
}

impl ElementaryMatrix {
    /// Construct an elementary matrix e_{ij}(λ).
    pub fn new(size: usize, i: usize, j: usize, scalar: i64) -> Self {
        ElementaryMatrix { size, i, j, scalar }
    }

    /// Convert to a full MatrixOverRing.
    pub fn to_matrix(&self, ring: &str) -> MatrixOverRing {
        let mut rows: Vec<Vec<i64>> = (0..self.size)
            .map(|r| (0..self.size).map(|c| if r == c { 1 } else { 0 }).collect())
            .collect();
        if self.i < self.size && self.j < self.size && self.i != self.j {
            rows[self.i][self.j] = self.scalar;
        }
        MatrixOverRing::new(rows, ring)
    }

    /// An elementary matrix is valid when i ≠ j and both are within range.
    pub fn is_valid(&self) -> bool {
        self.i != self.j && self.i < self.size && self.j < self.size
    }
}

impl fmt::Display for ElementaryMatrix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "e_{{{}{}}}({})", self.i, self.j, self.scalar)
    }
}

/// Steinberg symbol {a, b} ∈ K_2(F) for a field (or ring) F.
///
/// For a field F, the Milnor K_2(F) is generated by symbols {a, b} for a, b ∈ F×,
/// subject to:
/// 1. Bilinearity: {ab, c} = {a, c}{b, c}
/// 2. Steinberg relation: {a, 1-a} = 1 for a ≠ 0, 1
///
/// This implies {a, -a} = 1 and {a, b}{b, a} = 1 (anti-symmetry).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MilnorK2Symbol {
    /// The first element a ∈ F×.
    pub a: String,
    /// The second element b ∈ F×.
    pub b: String,
}

impl MilnorK2Symbol {
    /// Construct the Steinberg symbol {a, b}.
    pub fn new(a: &str, b: &str) -> Self {
        MilnorK2Symbol {
            a: a.to_string(),
            b: b.to_string(),
        }
    }

    /// The trivial symbol {a, 1} = 1.
    pub fn is_trivially_one_right(&self) -> bool {
        self.b == "1"
    }

    /// The trivial symbol {1, b} = 1.
    pub fn is_trivially_one_left(&self) -> bool {
        self.a == "1"
    }
}

impl fmt::Display for MilnorK2Symbol {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{{}, {}}}", self.a, self.b)
    }
}

/// The second algebraic K-group K_2(R) (Milnor's K_2).
///
/// K_2(R) = ker(St(R) → GL(R)) where St(R) is the Steinberg group.
/// For a field F, K_2(F) is generated by symbols {a, b} with a, b ∈ F×
/// subject to the Steinberg (Matsumoto) relations.
#[derive(Debug, Clone)]
pub struct K2Group {
    /// The generators: Steinberg symbols {a, b}.
    pub symbols: Vec<MilnorK2Symbol>,
    /// Relations holding among the symbols (as human-readable strings).
    pub relations: Vec<String>,
}

impl K2Group {
    /// Construct a K_2 group from symbols and relations.
    pub fn new(symbols: Vec<MilnorK2Symbol>, relations: Vec<String>) -> Self {
        K2Group { symbols, relations }
    }

    /// Number of generators.
    pub fn num_symbols(&self) -> usize {
        self.symbols.len()
    }

    /// Number of relations.
    pub fn num_relations(&self) -> usize {
        self.relations.len()
    }

    /// Add a Steinberg symbol to this group.
    pub fn add_symbol(&mut self, sym: MilnorK2Symbol) {
        self.symbols.push(sym);
    }

    /// Add a relation.
    pub fn add_relation(&mut self, rel: &str) {
        self.relations.push(rel.to_string());
    }
}

impl fmt::Display for K2Group {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "K_2 with {} symbols and {} relations",
            self.symbols.len(),
            self.relations.len()
        )
    }
}
