//! Types for the `convert` tactic — exact with holes (subgoal generation).

use oxilean_kernel::Expr;

/// Configuration for the `convert` tactic.
#[derive(Debug, Clone)]
pub struct ConvertConfig {
    /// Maximum number of new subgoals that `convert` will generate.
    /// If the number of structural mismatches exceeds this limit, the tactic
    /// fails rather than generating a flood of goals.
    pub max_subgoals: usize,
    /// Maximum depth for the parallel tree walk when collecting mismatches.
    pub max_depth: usize,
}

impl Default for ConvertConfig {
    fn default() -> Self {
        Self {
            max_subgoals: 64,
            max_depth: 32,
        }
    }
}

/// The result of running `convert`.
#[derive(Debug, Clone)]
pub struct ConvertResult {
    /// The new subgoal expressions generated by mismatches.  Each entry is
    /// a pair `(expected_ty, provided_ty)` for which the user must supply
    /// a proof of `expected_ty = provided_ty`.
    pub new_goals: Vec<Expr>,
    /// The proof term constructed for the current goal (with metavariable
    /// holes for the mismatches).
    pub proof: Expr,
}
