[package]
name = "oximedia-metadata"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Comprehensive metadata standards support for OxiMedia (ID3v2, Vorbis, APE, iTunes, XMP, EXIF, IPTC, etc.)"
keywords = ["metadata", "id3", "multimedia", "media", "tags"]
categories = ["multimedia", "parser-implementations"]
readme = "README.md"

[lints]
workspace = true

[dependencies]
oximedia-core = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
quick-xml = { workspace = true }
encoding_rs = { workspace = true }
rayon = { workspace = true }
md-5 = { workspace = true }

[dev-dependencies]
oximedia-container = { workspace = true }
oximedia-io = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
