[package]
name = "oximedia-denoise"
description = "Video and audio denoising algorithms for media processing"
keywords = ["restoration", "denoising", "video", "multimedia", "quality"]
categories = ["multimedia::video"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
oximedia-core = { workspace = true }
oximedia-codec = { workspace = true, default-features = true }
oximedia-graph = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
