#!/usr/bin/env bash
# Generate a CHANGELOG entry from git log since the last version tag.
# Usage: ./scripts/generate_changelog.sh [--since <tag>] [--output <file>]
# Example: ./scripts/generate_changelog.sh --since v0.1.0 --output /tmp/changelog.md

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SINCE_TAG=""
OUTPUT_FILE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --since) SINCE_TAG="$2"; shift 2 ;;
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

cd "${WORKSPACE_ROOT}"

# Determine the range
if [[ -z "${SINCE_TAG}" ]]; then
    SINCE_TAG=$(git tag --sort=-creatordate | grep '^v' | head -1 2>/dev/null || echo "")
fi

RANGE="${SINCE_TAG:+${SINCE_TAG}..}HEAD"
CURRENT_VERSION=$(grep -m1 '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')

echo "Generating changelog for v${CURRENT_VERSION} (since ${SINCE_TAG:-beginning})..."

generate_section() {
    local pattern="$1"
    local title="$2"
    local commits
    commits=$(git log "${RANGE}" --oneline --no-merges --grep="${pattern}" 2>/dev/null || true)
    if [[ -n "${commits}" ]]; then
        echo "### ${title}"
        echo ""
        while IFS= read -r line; do
            local sha="${line%% *}"
            local msg="${line#* }"
            echo "- ${msg} (${sha})"
        done <<< "${commits}"
        echo ""
    fi
}

CONTENT="## [${CURRENT_VERSION}] - $(date +%Y-%m-%d)

$(generate_section "feat\|feature\|add\|implement" "Added")
$(generate_section "fix\|bug\|patch\|correct" "Fixed")
$(generate_section "perf\|optim\|speed\|faster\|improve" "Performance")
$(generate_section "refactor\|clean\|restructure\|reorganize" "Changed")
$(generate_section "deprecat\|remove\|drop\|delete" "Removed")
$(generate_section "doc\|docs\|comment\|readme" "Documentation")
$(generate_section "test\|spec\|bench" "Tests & Benchmarks")
$(generate_section "bump\|update\|upgrade\|dep\|version" "Dependencies")

---
*Generated by scripts/generate_changelog.sh*
"

if [[ -n "${OUTPUT_FILE}" ]]; then
    echo "${CONTENT}" > "${OUTPUT_FILE}"
    echo "Changelog written to ${OUTPUT_FILE}"
else
    echo "${CONTENT}"
fi
