[package]
name = "oxiphysics-md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Molecular dynamics simulation for the OxiPhysics engine"
readme = "README.md"
categories = ["science::computational-chemistry::molecular-simulation", "simulation"]
keywords = ["molecular-dynamics", "physics", "atomistic", "force-field", "simulation"]

[dependencies]
thiserror = { workspace = true }
oxiphysics-core = { workspace = true }
rand = { workspace = true }
oxifft = { workspace = true }
