[package]
name = "oxiproto-wkt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Well-Known Types interop for OxiProto"
readme = "README.md"
keywords = ["protobuf", "wkt", "timestamp", "duration"]
categories = ["encoding", "date-and-time"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
chrono = ["dep:chrono"]
time = ["dep:time"]
reflect = ["dep:oxiproto-reflect"]

[dependencies]
oxiproto-core.workspace = true
prost.workspace = true
prost-types.workspace = true

[dependencies.chrono]
workspace = true
optional = true

[dependencies.time]
workspace = true
optional = true

[dependencies.oxiproto-reflect]
workspace = true
optional = true

[dev-dependencies]
criterion.workspace = true
prost = { workspace = true, features = ["derive"] }
oxiproto-reflect.workspace = true

[[bench]]
name = "wkt"
harness = false
