//! # OxiPhoton
//!
//! Pure Rust Computational Photonics & Optical Simulation Framework.
//!
//! Provides FDTD, S-matrix, BPM, RCWA, and mode-solver engines for simulating
//! photonic devices, solar cells, fibers, and silicon photonic circuits.

pub mod biophotonics;
pub mod coherence;
pub mod detector;
pub mod error;
#[cfg(feature = "fdtd")]
pub mod fdtd;
pub mod geometry;
pub mod io;
pub mod material;
pub mod prelude;
#[cfg(feature = "smatrix")]
pub mod smatrix;
pub mod units;

pub mod adaptive_optics;
pub mod amplifiers;
pub mod beam_quality;
#[cfg(feature = "bpm")]
pub mod bpm;
pub mod comms;
#[cfg(feature = "siph-devices")]
pub mod devices;
pub mod diffractive;
pub mod entanglement;
#[cfg(feature = "fiber")]
pub mod fiber;
pub mod frequency_comb;
pub mod fso;
pub mod interconnect;
pub mod inverse;
pub mod laser;
pub mod mems;
pub mod metamaterials;
pub mod metasurface;
pub mod metrology;
pub mod microwave_photonics;
#[cfg(feature = "mode-solver")]
pub mod mode;
pub mod nanolaser;
pub mod nearfield;
pub mod nonlinear_crystal;
pub mod nonlinear_microscopy;
pub mod oct;
pub mod optical_cdma;
pub mod optical_computing;
pub mod optical_force;
pub mod optical_network;
pub mod optical_trapping;
pub mod photoacoustics;
pub mod photonic_antenna;
#[cfg(feature = "photonic-crystal")]
pub mod photonic_crystal;
pub mod photonic_dsp;
pub mod photonic_sensors;
pub mod pic_design;
pub mod pic_simulation;
pub mod plasmonics;
pub mod polarimetry;
pub mod quantum_optics;
pub mod quantum_photonics;
#[cfg(feature = "ray-optics")]
pub mod ray;
pub mod sdm;
pub mod single_photon;
#[cfg(feature = "solar-optics")]
pub mod solar;
pub mod structured_light;
pub mod temporal_photonics;
pub mod thin_film;
pub mod thz;
pub mod topological_photonics;
pub mod ultrafast;
pub mod xray;
