//! Integration test for `translate/main_loop.rs`'s virtual-table `ORDER BY` pushdown: a
//! `VirtualTable` scan's `xBestIndex` is now offered the query's real `ORDER BY` columns (instead
//! of an empty slice), and when it reports `order_by_consumed`, the core elides its own ORDER BY
//! sorter for that query instead of redundantly re-sorting rows the vtab already produced in
//! order.
//!
//! Sort elision is not observable from result rows alone (a real sorter running on already-sorted
//! input still produces the same correct output), so this test inspects the generated bytecode
//! via `EXPLAIN` (the same "internal plan-inspection" mechanism `lib.rs`'s own `explain_tests`
//! module already uses) and asserts on the presence/absence of the `SorterInsert` opcode.

use std::sync::Arc;

use limbo_core::{Connection, Database, MemoryIO, StepResult, Value as CoreValue, IO};
use limbo_ext::{
    ConstraintInfo, ConstraintUsage, ExtensionApi, IndexInfo, OrderByInfo, ResultCode, VTabCursor,
    VTabKind, VTabModule, VTabModuleDerive, VTable, Value,
};

fn new_conn() -> (Arc<dyn IO>, Arc<Connection>) {
    let io: Arc<dyn IO> = Arc::new(MemoryIO::new());
    let db = Database::open_file(io.clone(), ":memory:", false).expect("open :memory: database");
    let conn = db.connect().expect("connect to :memory: database");
    (io, conn)
}

fn exec(conn: &Arc<Connection>, sql: &str) {
    conn.execute(sql)
        .unwrap_or_else(|e| panic!("execute failed for {sql}: {e:?}"));
}

fn explain(conn: &Arc<Connection>, sql: &str) -> String {
    let stmt = conn
        .prepare(format!("EXPLAIN {sql}"))
        .unwrap_or_else(|e| panic!("prepare EXPLAIN {sql:?} failed: {e:?}"));
    stmt.explain()
}

fn run_query(io: &Arc<dyn IO>, conn: &Arc<Connection>, sql: &str) -> Vec<(i64, i64)> {
    let mut stmt = conn
        .query(sql)
        .unwrap_or_else(|e| panic!("prepare failed for {sql}: {e:?}"))
        .unwrap_or_else(|| panic!("no statement produced for {sql}"));
    let mut out = Vec::new();
    loop {
        match stmt
            .step()
            .unwrap_or_else(|e| panic!("step failed for {sql}: {e:?}"))
        {
            StepResult::Row => {
                let row = stmt.row().expect("row");
                let vals: Vec<i64> = row
                    .get_values()
                    .map(|v| match v {
                        CoreValue::Integer(i) => *i,
                        other => panic!("expected integer column, got {other:?}"),
                    })
                    .collect();
                out.push((vals[0], vals[1]));
            }
            StepResult::IO => io.run_once().unwrap(),
            StepResult::Done => break,
            other => panic!("unexpected step result for {sql}: {other:?}"),
        }
    }
    out
}

// -----------------------------------------------------------------------
// A tiny read-only virtual table: two columns `(id INTEGER, val INTEGER)`, three fixed rows,
// deliberately inserted in an order that is *not* already sorted by `val`. `best_index` reports
// `order_by_consumed = true` only for a request to pre-sort by `val` ascending (column index 1,
// `desc = false`); the cursor then actually returns rows in that order when `idx_num == 1`,
// keeping the test's *result* correct regardless of whether elision happens. Any other requested
// order (or none) is *not* claimed, and the cursor iterates in natural (insertion) order.
// -----------------------------------------------------------------------

#[derive(Debug, VTabModuleDerive)]
struct OrderedVtabModule;

impl VTabModule for OrderedVtabModule {
    type Table = OrderedTable;
    const VTAB_KIND: VTabKind = VTabKind::VirtualTable;
    const NAME: &'static str = "test_ordered";

    fn create(_args: &[Value]) -> Result<(String, Self::Table), ResultCode> {
        let schema = "CREATE TABLE test_ordered(id INTEGER, val INTEGER)".to_string();
        Ok((schema, OrderedTable))
    }
}

struct OrderedTable;

impl VTable for OrderedTable {
    type Cursor = OrderedCursor;
    type Error = &'static str;

    fn open(&self, _conn: Option<Arc<limbo_ext::Connection>>) -> Result<Self::Cursor, Self::Error> {
        Ok(OrderedCursor {
            // Insertion order is deliberately not `val`-sorted, so a query result that happens
            // to come out `val`-ascending proves *some* sort (core or vtab-side) really ran.
            rows: vec![(1, 30), (2, 10), (3, 20)],
            index: 0,
        })
    }

    fn best_index(_constraints: &[ConstraintInfo], order_by: &[OrderByInfo]) -> IndexInfo {
        let can_presort_by_val_asc = matches!(
            order_by,
            [OrderByInfo {
                column_index: 1,
                desc: false,
            }]
        );
        IndexInfo {
            idx_num: if can_presort_by_val_asc { 1 } else { 0 },
            // `VTabModuleDerive`'s generated `xFilter` glue only forwards `idx_num` to
            // `VTabCursor::filter` when `idx_str` is also non-null (it builds the `idx_info`
            // tuple from `CStr::from_ptr(idx_str)`, so a null `idx_str` yields `None` for the
            // *whole* tuple, silently dropping `idx_num` too). Carry a non-null placeholder
            // string whenever `idx_num` alone needs to reach `filter`, to work around that.
            idx_str: can_presort_by_val_asc.then(|| "val_asc".to_string()),
            order_by_consumed: can_presort_by_val_asc,
            estimated_cost: 1.0,
            estimated_rows: 3,
            constraint_usages: _constraints
                .iter()
                .map(|_| ConstraintUsage {
                    argv_index: None,
                    omit: false,
                })
                .collect(),
        }
    }
}

struct OrderedCursor {
    rows: Vec<(i64, i64)>,
    index: usize,
}

impl VTabCursor for OrderedCursor {
    type Error = &'static str;

    fn filter(&mut self, _args: &[Value], idx_info: Option<(&str, i32)>) -> ResultCode {
        let idx_num = idx_info.map(|(_, n)| n).unwrap_or(0);
        if idx_num == 1 {
            self.rows.sort_by_key(|(_, val)| *val);
        }
        self.index = 0;
        ResultCode::OK
    }

    fn rowid(&self) -> i64 {
        self.rows[self.index].0
    }

    fn column(&self, idx: u32) -> Result<Value, Self::Error> {
        let (id, val) = self.rows[self.index];
        match idx {
            0 => Ok(Value::from_integer(id)),
            1 => Ok(Value::from_integer(val)),
            _ => Ok(Value::null()),
        }
    }

    fn eof(&self) -> bool {
        self.index >= self.rows.len()
    }

    fn next(&mut self) -> ResultCode {
        self.index += 1;
        if self.index < self.rows.len() {
            ResultCode::OK
        } else {
            ResultCode::EOF
        }
    }
}

fn setup() -> (Arc<dyn IO>, Arc<Connection>) {
    let (io, conn) = new_conn();
    let ext_api: ExtensionApi = conn.build_limbo_ext();
    let rc = unsafe { OrderedVtabModule::register_OrderedVtabModule(&ext_api as *const _) };
    assert!(rc.is_ok(), "vtab module registration failed: {rc:?}");
    exec(&conn, "CREATE VIRTUAL TABLE ot USING test_ordered()");
    (io, conn)
}

#[test]
fn vtab_order_by_pushdown_elides_sort_and_returns_correct_order() {
    let (io, conn) = setup();
    let sql = "SELECT id, val FROM ot ORDER BY val";

    // The vtab claims it can pre-sort by `val` ascending, so the core's ORDER BY sorter should
    // never be populated for this query -- no `SorterInsert` in the generated bytecode.
    let bytecode = explain(&conn, sql);
    assert!(
        bytecode.contains("VFilter"),
        "expected the vtab scan (VFilter) to appear in the plan, got: {bytecode}"
    );
    assert!(
        !bytecode.contains("SorterInsert"),
        "ORDER BY sorter should have been elided (vtab reported order_by_consumed), \
         but SorterInsert is present in: {bytecode}"
    );

    // Regardless of elision, the actual output must be correctly ordered: rows are (id, val)
    // with val ascending, i.e. (2,10), (3,20), (1,30).
    let rows = run_query(&io, &conn, sql);
    assert_eq!(rows, vec![(2, 10), (3, 20), (1, 30)]);
}

#[test]
fn vtab_order_by_non_pushdown_column_still_uses_sorter() {
    let (io, conn) = setup();
    // `id` (column 0) is not a column the vtab claims to be able to pre-sort by (only `val`,
    // column 1, is), so `order_by_consumed` must be false and the core must still fall back to
    // its own sorter.
    let sql = "SELECT id, val FROM ot ORDER BY id";

    let bytecode = explain(&conn, sql);
    assert!(
        bytecode.contains("SorterInsert"),
        "core sorter must still run when the vtab does not claim this ordering, got: {bytecode}"
    );

    let rows = run_query(&io, &conn, sql);
    assert_eq!(rows, vec![(1, 30), (2, 10), (3, 20)]);
}

#[test]
fn vtab_order_by_desc_not_claimed_still_uses_sorter() {
    let (io, conn) = setup();
    // The vtab only claims ascending `val`; descending must not be (incorrectly) elided.
    let sql = "SELECT id, val FROM ot ORDER BY val DESC";

    let bytecode = explain(&conn, sql);
    assert!(
        bytecode.contains("SorterInsert"),
        "descending order was not claimed by the vtab, so the sorter must still run, got: {bytecode}"
    );

    let rows = run_query(&io, &conn, sql);
    assert_eq!(rows, vec![(1, 30), (3, 20), (2, 10)]);
}

#[test]
fn no_order_by_never_touches_the_sorter() {
    let (io, conn) = setup();
    let sql = "SELECT id, val FROM ot";
    let bytecode = explain(&conn, sql);
    assert!(
        !bytecode.contains("SorterInsert"),
        "a query with no ORDER BY at all should never involve a sorter, got: {bytecode}"
    );
    let rows = run_query(&io, &conn, sql);
    assert_eq!(rows, vec![(1, 30), (2, 10), (3, 20)]);
}
