//! OBJ mesh format export
//!
//! Provides export functionality for Wavefront OBJ format with materials (MTL).

use crate::error::{Error, Result};
use crate::mesh::Mesh;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

/// OBJ exporter
pub struct ObjExporter;

impl ObjExporter {
    /// Export mesh to OBJ file
    pub fn export<P: AsRef<Path>>(mesh: &Mesh, path: P) -> Result<()> {
        mesh.validate()?;

        let path = path.as_ref();
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);

        // Write header
        writeln!(writer, "# OBJ file generated by OxiGeo 3D")?;
        writeln!(writer, "# Vertices: {}", mesh.vertex_count())?;
        writeln!(writer, "# Triangles: {}", mesh.triangle_count())?;
        writeln!(writer)?;

        // Write material library reference if we have textures
        if mesh.material.texture.is_some() {
            let mtl_name = path.with_extension("mtl");
            writeln!(
                writer,
                "mtllib {}",
                mtl_name
                    .file_name()
                    .ok_or_else(|| Error::ObjExport("Invalid MTL filename".to_string()))?
                    .to_string_lossy()
            )?;
            writeln!(writer)?;

            // Write MTL file
            Self::write_mtl(mesh, &mtl_name)?;
        }

        // Use material
        writeln!(writer, "usemtl {}", mesh.material.name)?;
        writeln!(writer)?;

        // Write vertices
        writeln!(writer, "# Vertices")?;
        for vertex in &mesh.vertices {
            writeln!(
                writer,
                "v {} {} {}",
                vertex.position[0], vertex.position[1], vertex.position[2]
            )?;
        }
        writeln!(writer)?;

        // Write normals
        writeln!(writer, "# Normals")?;
        for vertex in &mesh.vertices {
            writeln!(
                writer,
                "vn {} {} {}",
                vertex.normal[0], vertex.normal[1], vertex.normal[2]
            )?;
        }
        writeln!(writer)?;

        // Write texture coordinates
        writeln!(writer, "# Texture coordinates")?;
        for vertex in &mesh.vertices {
            writeln!(
                writer,
                "vt {} {}",
                vertex.tex_coords[0], vertex.tex_coords[1]
            )?;
        }
        writeln!(writer)?;

        // Write faces
        writeln!(writer, "# Faces")?;
        for triangle in &mesh.triangles {
            // OBJ indices are 1-based
            let i0 = triangle.indices[0] + 1;
            let i1 = triangle.indices[1] + 1;
            let i2 = triangle.indices[2] + 1;

            // Format: f v/vt/vn v/vt/vn v/vt/vn
            writeln!(
                writer,
                "f {}/{}/{} {}/{}/{} {}/{}/{}",
                i0, i0, i0, i1, i1, i1, i2, i2, i2
            )?;
        }

        writer.flush()?;
        Ok(())
    }

    /// Write MTL (material) file
    fn write_mtl<P: AsRef<Path>>(mesh: &Mesh, path: P) -> Result<()> {
        let file = File::create(path)?;
        let mut writer = BufWriter::new(file);

        writeln!(writer, "# MTL file generated by OxiGeo 3D")?;
        writeln!(writer)?;

        writeln!(writer, "newmtl {}", mesh.material.name)?;

        // Ambient color
        let ambient = [
            mesh.material.base_color[0] * 0.2,
            mesh.material.base_color[1] * 0.2,
            mesh.material.base_color[2] * 0.2,
        ];
        writeln!(writer, "Ka {} {} {}", ambient[0], ambient[1], ambient[2])?;

        // Diffuse color
        writeln!(
            writer,
            "Kd {} {} {}",
            mesh.material.base_color[0], mesh.material.base_color[1], mesh.material.base_color[2]
        )?;

        // Specular color (based on metallic)
        let specular = mesh.material.metallic;
        writeln!(writer, "Ks {} {} {}", specular, specular, specular)?;

        // Specular exponent (based on roughness)
        let shininess = (1.0 - mesh.material.roughness) * 100.0;
        writeln!(writer, "Ns {}", shininess)?;

        // Transparency
        writeln!(writer, "d {}", mesh.material.base_color[3])?;

        // Illumination model (2 = highlight on)
        writeln!(writer, "illum 2")?;

        // Texture map
        if let Some(ref texture) = mesh.material.texture {
            writeln!(writer, "map_Kd {}", texture)?;
        }

        writer.flush()?;
        Ok(())
    }
}

/// Export mesh to OBJ file (convenience function)
pub fn export_obj<P: AsRef<Path>>(mesh: &Mesh, path: P) -> Result<()> {
    ObjExporter::export(mesh, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh::{Material, Vertex};
    use std::sync::atomic::{AtomicU64, Ordering};

    /// Per-test scratch fixture inside the system temp dir (house policy: no
    /// hardcoded absolute paths).
    ///
    /// The leaf name embeds the process id and a monotonic counter, so no two
    /// test binaries — nor two concurrent runs of this one — can ever land on
    /// the same file.  Dropping the guard removes the fixture, so a panicking
    /// test leaks nothing.
    struct TempPath(std::path::PathBuf);

    impl TempPath {
        fn new(name: &str) -> Self {
            static COUNTER: AtomicU64 = AtomicU64::new(0);
            let seq = COUNTER.fetch_add(1, Ordering::Relaxed);
            Self(
                std::env::temp_dir()
                    .join(format!("oxigeo_3d_obj_{}_{seq}_{name}", std::process::id())),
            )
        }
    }

    impl std::ops::Deref for TempPath {
        type Target = std::path::Path;

        fn deref(&self) -> &std::path::Path {
            &self.0
        }
    }

    impl AsRef<std::path::Path> for TempPath {
        fn as_ref(&self) -> &std::path::Path {
            &self.0
        }
    }

    impl Drop for TempPath {
        fn drop(&mut self) {
            let _ = std::fs::remove_file(&self.0);
        }
    }

    #[test]
    fn test_obj_export() {
        let mut mesh = Mesh::new();

        // Create a simple triangle
        mesh.add_vertex(Vertex::new([0.0, 0.0, 0.0]));
        mesh.add_vertex(Vertex::new([1.0, 0.0, 0.0]));
        mesh.add_vertex(Vertex::new([0.0, 1.0, 0.0]));
        mesh.add_triangle(0, 1, 2);

        mesh.calculate_normals();

        let output_path = TempPath::new("test_mesh.obj");

        let result = export_obj(&mesh, &output_path);
        assert!(result.is_ok());

        // Check file exists
        assert!(output_path.exists());
    }

    #[test]
    fn test_obj_export_with_material() {
        let mut mesh = Mesh::new();

        mesh.add_vertex(Vertex::new([0.0, 0.0, 0.0]));
        mesh.add_vertex(Vertex::new([1.0, 0.0, 0.0]));
        mesh.add_vertex(Vertex::new([0.0, 1.0, 0.0]));
        mesh.add_triangle(0, 1, 2);

        mesh.material = Material::new("terrain")
            .with_color(0.5, 0.5, 0.5, 1.0)
            .with_texture("texture.png");

        let output_path = TempPath::new("test_mesh_material.obj");

        let result = export_obj(&mesh, &output_path);
        assert!(result.is_ok());

        // Check both OBJ and MTL exist
        assert!(output_path.exists());
        let mtl_path = output_path.with_extension("mtl");
        assert!(mtl_path.exists());

        // Clean up (the .mtl sidecar is not covered by the TempPath guard)
        let _ = std::fs::remove_file(&mtl_path);
    }
}
