//! Real additively-homomorphic encryption: the Paillier cryptosystem.
//!
//! # What this is
//!
//! This is a from-scratch, pure-Rust implementation of Paillier (Public-Key
//! Cryptosystems Based on Composite Degree Residuosity Classes, EUROCRYPT '99)
//! on top of [`num_bigint`]. It replaces the previous
//! "homomorphic encryption" in this crate, which serialized the tensor with
//! `f32::to_ne_bytes` and XOR'd the bytes together — i.e. it stored plaintext
//! and called it a ciphertext.
//!
//! # What Paillier gives you, exactly
//!
//! Paillier is **additively** homomorphic and nothing more:
//!
//! - `E(m1) · E(m2) mod n²  =  E(m1 + m2 mod n)` — [`PaillierPublicKey::add`]
//! - `E(m)^k mod n²         =  E(k · m mod n)`   — [`PaillierPublicKey::multiply_by_plaintext`]
//!
//! There is **no** ciphertext × ciphertext multiplication: that requires a
//! fully-homomorphic scheme (BGV/BFV/CKKS/TFHE), which this crate does not
//! implement. Asking for it returns a structured
//! [`UnsupportedOperation`](trustformers_core::errors::ErrorKind::UnsupportedOperation)
//! error rather than a wrong answer.
//!
//! # Security notes
//!
//! - Encryption is randomized: `E(m) = g^m · r^n mod n²` with a fresh uniform
//!   `r ∈ Z*_n`. Encrypting the same message twice yields different ciphertexts.
//! - Key generation uses the simplified variant `g = n + 1`, `λ = lcm(p-1, q-1)`,
//!   `µ = (L(g^λ mod n²))⁻¹ mod n`, which is standard and constant-work.
//! - Primes are generated by rejection sampling with a Miller-Rabin test using
//!   40 rounds (error probability < 2⁻⁸⁰) plus small-prime trial division.
//! - This implementation is **not** side-channel hardened. `num-bigint`'s
//!   `modpow` is not constant-time. It is suitable for the aggregation use case
//!   here (a device encrypts its own gradient share); it is not suitable for a
//!   setting where an attacker can measure decryption timing on chosen
//!   ciphertexts. This limitation is documented rather than hidden.

use num_bigint::{BigRng010, BigUint};
use num_integer::Integer;
use num_traits::{One, Zero};
use rand_core::CryptoRng;
use std::fmt;
use trustformers_core::errors::{invalid_input, unsupported_operation, Result, TrustformersError};

/// Small primes used for trial division before the (expensive) Miller-Rabin
/// rounds. Cuts the vast majority of composite candidates immediately.
const SMALL_PRIMES: [u32; 54] = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
    101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193,
    197, 199, 211, 223, 227, 229, 233, 239, 241, 251,
];

/// Number of Miller-Rabin rounds. 40 rounds gives a composite-acceptance
/// probability below 2⁻⁸⁰ for random candidates.
const MILLER_RABIN_ROUNDS: usize = 40;

/// Structured error for the operations Paillier genuinely cannot perform.
///
/// Returned instead of silently computing something else.
pub fn unsupported_paillier_operation(operation: &str) -> TrustformersError {
    unsupported_operation(
        operation.to_string(),
        "Paillier (additively homomorphic only: ciphertext+ciphertext and \
         ciphertext*plaintext are supported; ciphertext*ciphertext requires a fully \
         homomorphic scheme, which trustformers-mobile does not implement)"
            .to_string(),
    )
}

/// A Paillier public (encryption) key.
#[derive(Clone, PartialEq, Eq)]
pub struct PaillierPublicKey {
    /// Modulus `n = p · q`.
    n: BigUint,
    /// `n²`, cached because every operation needs it.
    n_squared: BigUint,
}

impl fmt::Debug for PaillierPublicKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PaillierPublicKey")
            .field("modulus_bits", &self.n.bits())
            .finish()
    }
}

impl PaillierPublicKey {
    /// The modulus `n`. Messages must be in `[0, n)`.
    pub fn modulus(&self) -> &BigUint {
        &self.n
    }

    /// `n²`, the ciphertext modulus.
    pub fn modulus_squared(&self) -> &BigUint {
        &self.n_squared
    }

    /// Bit length of the modulus.
    pub fn bits(&self) -> u64 {
        self.n.bits()
    }

    /// Encrypt `message` with fresh randomness drawn from `rng`.
    ///
    /// `E(m) = (1 + n)^m · r^n mod n²`, which with `g = n + 1` simplifies the
    /// `g^m` term to `1 + m·n mod n²` (binomial theorem), saving a modexp.
    ///
    /// # Errors
    /// Returns an error if `message >= n`.
    pub fn encrypt_with_rng<R: CryptoRng>(
        &self,
        message: &BigUint,
        rng: &mut R,
    ) -> Result<PaillierCiphertext> {
        if message >= &self.n {
            return Err(invalid_input(format!(
                "Paillier plaintext must be < n; message has {} bits, n has {} bits",
                message.bits(),
                self.n.bits()
            )));
        }
        let r = self.sample_unit(rng);
        Ok(self.encrypt_with_randomness(message, &r))
    }

    /// Encrypt using the operating-system CSPRNG.
    ///
    /// # Errors
    /// Returns an error if `message >= n`.
    pub fn encrypt(&self, message: &BigUint) -> Result<PaillierCiphertext> {
        let mut rng = rand_core::UnwrapErr(getrandom::SysRng);
        self.encrypt_with_rng(message, &mut rng)
    }

    /// Encrypt with a caller-supplied randomizer. Exposed for tests that need
    /// to check the homomorphic identities with known randomness.
    fn encrypt_with_randomness(&self, message: &BigUint, r: &BigUint) -> PaillierCiphertext {
        // g^m mod n² with g = n+1 is (1 + m·n) mod n².
        let g_pow_m = (BigUint::one() + message * &self.n) % &self.n_squared;
        let r_pow_n = r.modpow(&self.n, &self.n_squared);
        PaillierCiphertext {
            value: (g_pow_m * r_pow_n) % &self.n_squared,
        }
    }

    /// Homomorphic addition: `E(m1) · E(m2) mod n² = E(m1 + m2 mod n)`.
    pub fn add(&self, a: &PaillierCiphertext, b: &PaillierCiphertext) -> PaillierCiphertext {
        PaillierCiphertext {
            value: (&a.value * &b.value) % &self.n_squared,
        }
    }

    /// Homomorphic scalar multiplication: `E(m)^k mod n² = E(k · m mod n)`.
    ///
    /// This is multiplication of a *ciphertext* by a *plaintext* scalar, which
    /// Paillier does support. See [`unsupported_paillier_operation`] for what
    /// it does not.
    pub fn multiply_by_plaintext(
        &self,
        ciphertext: &PaillierCiphertext,
        scalar: &BigUint,
    ) -> PaillierCiphertext {
        PaillierCiphertext {
            value: ciphertext.value.modpow(scalar, &self.n_squared),
        }
    }

    /// Add a plaintext constant to an encrypted value: `E(m) · g^k = E(m + k)`.
    pub fn add_plaintext(
        &self,
        ciphertext: &PaillierCiphertext,
        addend: &BigUint,
    ) -> PaillierCiphertext {
        let g_pow_k = (BigUint::one() + addend * &self.n) % &self.n_squared;
        PaillierCiphertext {
            value: (&ciphertext.value * g_pow_k) % &self.n_squared,
        }
    }

    /// Sample a uniform element of `Z*_n` (i.e. coprime to `n`).
    fn sample_unit<R: CryptoRng>(&self, rng: &mut R) -> BigUint {
        loop {
            let candidate = rng.random_biguint_below(&self.n);
            if !candidate.is_zero() && candidate.gcd(&self.n).is_one() {
                return candidate;
            }
        }
    }
}

/// A Paillier private (decryption) key. Holds `λ` and `µ`.
///
/// Debug-printing deliberately omits the secret scalars.
#[derive(Clone)]
pub struct PaillierPrivateKey {
    lambda: BigUint,
    mu: BigUint,
    public: PaillierPublicKey,
}

impl fmt::Debug for PaillierPrivateKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PaillierPrivateKey")
            .field("modulus_bits", &self.public.n.bits())
            .finish()
    }
}

impl PaillierPrivateKey {
    /// The matching public key.
    pub fn public_key(&self) -> &PaillierPublicKey {
        &self.public
    }

    /// Decrypt a ciphertext: `m = L(c^λ mod n²) · µ mod n` where `L(x) = (x-1)/n`.
    ///
    /// # Errors
    /// Returns an error if the ciphertext is not a residue mod `n²`.
    pub fn decrypt(&self, ciphertext: &PaillierCiphertext) -> Result<BigUint> {
        if ciphertext.value >= self.public.n_squared {
            return Err(invalid_input(
                "Paillier ciphertext is not reduced modulo n²".to_string(),
            ));
        }
        if ciphertext.value.is_zero() {
            return Err(invalid_input(
                "Paillier ciphertext must be non-zero".to_string(),
            ));
        }
        let c_pow_lambda = ciphertext.value.modpow(&self.lambda, &self.public.n_squared);
        let l = l_function(&c_pow_lambda, &self.public.n)?;
        Ok((l * &self.mu) % &self.public.n)
    }
}

/// A Paillier ciphertext: an element of `Z*_{n²}`.
#[derive(Clone, PartialEq, Eq)]
pub struct PaillierCiphertext {
    value: BigUint,
}

impl fmt::Debug for PaillierCiphertext {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PaillierCiphertext").field("bits", &self.value.bits()).finish()
    }
}

impl PaillierCiphertext {
    /// Big-endian byte serialization of the ciphertext integer.
    pub fn to_bytes_be(&self) -> Vec<u8> {
        self.value.to_bytes_be()
    }

    /// Reconstruct a ciphertext from its big-endian serialization.
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        Self {
            value: BigUint::from_bytes_be(bytes),
        }
    }

    /// The raw integer, for callers implementing further protocol layers.
    pub fn value(&self) -> &BigUint {
        &self.value
    }
}

/// A generated Paillier keypair.
#[derive(Clone, Debug)]
pub struct PaillierKeypair {
    /// The encryption key. Safe to publish.
    pub public: PaillierPublicKey,
    /// The decryption key. Must stay secret.
    pub private: PaillierPrivateKey,
}

impl PaillierKeypair {
    /// Borrow the public (encryption) key.
    pub fn public_key_ref(&self) -> &PaillierPublicKey {
        &self.public
    }

    /// Borrow the private (decryption) key.
    pub fn private_key_ref(&self) -> &PaillierPrivateKey {
        &self.private
    }
}

/// The `L` function from the Paillier paper: `L(x) = (x - 1) / n`.
fn l_function(x: &BigUint, n: &BigUint) -> Result<BigUint> {
    if x.is_zero() {
        return Err(invalid_input("Paillier L(0) is undefined".to_string()));
    }
    let numerator = x - BigUint::one();
    let (quotient, remainder) = numerator.div_rem(n);
    if !remainder.is_zero() {
        return Err(invalid_input(
            "Paillier L function applied to a non-residue (corrupt key or ciphertext)".to_string(),
        ));
    }
    Ok(quotient)
}

/// Generate a Paillier keypair with an `n` of `modulus_bits` bits.
///
/// `modulus_bits` must be at least 512 and even; 2048 or more is recommended
/// for real deployments. Each prime is `modulus_bits / 2` bits.
///
/// # Errors
/// Returns an error for an unusable `modulus_bits`, or if `µ` fails to invert
/// (which cannot happen for correctly generated primes but is checked rather
/// than assumed).
pub fn generate_keypair_with_rng<R: CryptoRng>(
    modulus_bits: u64,
    rng: &mut R,
) -> Result<PaillierKeypair> {
    if modulus_bits < 512 {
        return Err(invalid_input(format!(
            "Paillier modulus must be at least 512 bits for any security, got {modulus_bits}"
        )));
    }
    if !modulus_bits.is_multiple_of(2) {
        return Err(invalid_input(format!(
            "Paillier modulus bit length must be even, got {modulus_bits}"
        )));
    }
    let prime_bits = modulus_bits / 2;

    let p = generate_prime(prime_bits, rng);
    let q = loop {
        let candidate = generate_prime(prime_bits, rng);
        if candidate != p {
            break candidate;
        }
    };

    let n = &p * &q;
    let n_squared = &n * &n;

    // λ = lcm(p-1, q-1)
    let p_minus_1 = &p - BigUint::one();
    let q_minus_1 = &q - BigUint::one();
    let lambda = p_minus_1.lcm(&q_minus_1);

    let public = PaillierPublicKey {
        n: n.clone(),
        n_squared: n_squared.clone(),
    };

    // µ = (L(g^λ mod n²))⁻¹ mod n, with g = n + 1.
    let g = &n + BigUint::one();
    let g_pow_lambda = g.modpow(&lambda, &n_squared);
    let l = l_function(&g_pow_lambda, &n)?;
    let mu = l.modinv(&n).ok_or_else(|| {
        invalid_input("Paillier key generation failed: L(g^λ) is not invertible mod n".to_string())
    })?;

    Ok(PaillierKeypair {
        private: PaillierPrivateKey {
            lambda,
            mu,
            public: public.clone(),
        },
        public,
    })
}

/// Generate a Paillier keypair using the operating-system CSPRNG.
///
/// # Errors
/// See [`generate_keypair_with_rng`].
pub fn generate_keypair(modulus_bits: u64) -> Result<PaillierKeypair> {
    let mut rng = rand_core::UnwrapErr(getrandom::SysRng);
    generate_keypair_with_rng(modulus_bits, &mut rng)
}

/// Generate a probable prime of exactly `bits` bits with the top two bits set
/// (so that `p · q` reliably has `2 · bits` bits).
fn generate_prime<R: CryptoRng>(bits: u64, rng: &mut R) -> BigUint {
    loop {
        let mut candidate = rng.random_biguint(bits);
        // Force the top two bits and the low bit: odd, full-length, and the
        // product of two such primes has the expected bit length.
        candidate.set_bit(bits - 1, true);
        candidate.set_bit(bits - 2, true);
        candidate.set_bit(0, true);

        if is_probable_prime(&candidate, rng) {
            return candidate;
        }
    }
}

/// Miller-Rabin primality test with small-prime trial division.
fn is_probable_prime<R: CryptoRng>(n: &BigUint, rng: &mut R) -> bool {
    let two = BigUint::from(2u32);
    if n < &two {
        return false;
    }
    for &small in &SMALL_PRIMES {
        let small_big = BigUint::from(small);
        if n == &small_big {
            return true;
        }
        if (n % &small_big).is_zero() {
            return false;
        }
    }

    // n - 1 = d · 2^s with d odd.
    let n_minus_1 = n - BigUint::one();
    let mut d = n_minus_1.clone();
    let mut s = 0u64;
    while d.is_even() {
        d >>= 1;
        s += 1;
    }

    let n_minus_3 = n - BigUint::from(3u32);
    'witness: for _ in 0..MILLER_RABIN_ROUNDS {
        // a uniform in [2, n-2]
        let a = rng.random_biguint_below(&n_minus_3) + &two;
        let mut x = a.modpow(&d, n);
        if x.is_one() || x == n_minus_1 {
            continue;
        }
        for _ in 1..s {
            x = x.modpow(&two, n);
            if x == n_minus_1 {
                continue 'witness;
            }
        }
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::advanced_security::test_rng::TestRng;

    /// 512-bit modulus keeps the tests fast; production callers pick 2048+.
    const TEST_BITS: u64 = 512;

    fn test_keypair(seed: u8) -> PaillierKeypair {
        let mut rng = TestRng::seeded(seed);
        generate_keypair_with_rng(TEST_BITS, &mut rng).expect("keygen")
    }

    #[test]
    fn keygen_produces_a_modulus_of_the_requested_size() {
        let keypair = test_keypair(1);
        assert_eq!(keypair.public.bits(), TEST_BITS);
    }

    #[test]
    fn encrypt_decrypt_round_trip() {
        let keypair = test_keypair(2);
        let mut rng = TestRng::seeded(20);
        for message in [0u32, 1, 2, 42, 65535, 4_294_967_295] {
            let m = BigUint::from(message);
            let c = keypair.public.encrypt_with_rng(&m, &mut rng).expect("encrypt");
            let recovered = keypair.private.decrypt(&c).expect("decrypt");
            assert_eq!(recovered, m, "round trip failed for {message}");
        }
    }

    /// Regression for the old implementation, which stored
    /// `tensor.to_vec_f32()` as `f32::to_ne_bytes` and called it a ciphertext.
    #[test]
    fn ciphertext_does_not_contain_the_plaintext() {
        let keypair = test_keypair(3);
        let mut rng = TestRng::seeded(21);
        // A distinctive 8-byte plaintext.
        let plaintext_bytes: [u8; 8] = [0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE];
        let m = BigUint::from_bytes_be(&plaintext_bytes);
        let c = keypair.public.encrypt_with_rng(&m, &mut rng).expect("encrypt");
        let bytes = c.to_bytes_be();
        assert!(
            !bytes.windows(plaintext_bytes.len()).any(|w| w == plaintext_bytes),
            "ciphertext contains the plaintext verbatim"
        );
    }

    /// Encryption must be randomized: the same message twice gives different
    /// ciphertexts (semantic security). The old XOR "encryption" was
    /// deterministic.
    #[test]
    fn encryption_is_randomized() {
        let keypair = test_keypair(4);
        let mut rng = TestRng::seeded(22);
        let m = BigUint::from(12345u32);
        let c1 = keypair.public.encrypt_with_rng(&m, &mut rng).expect("encrypt");
        let c2 = keypair.public.encrypt_with_rng(&m, &mut rng).expect("encrypt");
        assert_ne!(c1, c2, "Paillier encryption must be randomized");
        assert_eq!(keypair.private.decrypt(&c1).expect("d1"), m);
        assert_eq!(keypair.private.decrypt(&c2).expect("d2"), m);
    }

    /// The defining homomorphic property: D(E(a) · E(b)) = a + b.
    #[test]
    fn homomorphic_addition_property() {
        let keypair = test_keypair(5);
        let mut rng = TestRng::seeded(23);
        for (a, b) in [
            (0u64, 0u64),
            (1, 1),
            (7, 35),
            (1_000_000, 2_345_678),
            (u32::MAX as u64, 1),
        ] {
            let big_a = BigUint::from(a);
            let big_b = BigUint::from(b);
            let ca = keypair.public.encrypt_with_rng(&big_a, &mut rng).expect("ea");
            let cb = keypair.public.encrypt_with_rng(&big_b, &mut rng).expect("eb");
            let sum = keypair.public.add(&ca, &cb);
            let decrypted = keypair.private.decrypt(&sum).expect("decrypt sum");
            assert_eq!(
                decrypted,
                big_a + big_b,
                "E({a}) * E({b}) should decrypt to {a}+{b}"
            );
        }
    }

    /// Summing many ciphertexts — the federated-aggregation use case.
    #[test]
    fn homomorphic_sum_of_many_ciphertexts() {
        let keypair = test_keypair(6);
        let mut rng = TestRng::seeded(24);
        let values: Vec<u64> = (1..=25).collect();
        let expected: u64 = values.iter().sum();

        let mut accumulator = keypair
            .public
            .encrypt_with_rng(&BigUint::zero(), &mut rng)
            .expect("encrypt zero");
        for v in &values {
            let c = keypair.public.encrypt_with_rng(&BigUint::from(*v), &mut rng).expect("enc");
            accumulator = keypair.public.add(&accumulator, &c);
        }
        assert_eq!(
            keypair.private.decrypt(&accumulator).expect("decrypt"),
            BigUint::from(expected)
        );
    }

    /// D(E(m)^k) = k · m.
    #[test]
    fn homomorphic_scalar_multiplication_property() {
        let keypair = test_keypair(7);
        let mut rng = TestRng::seeded(25);
        let m = BigUint::from(97u32);
        let k = BigUint::from(13u32);
        let c = keypair.public.encrypt_with_rng(&m, &mut rng).expect("enc");
        let scaled = keypair.public.multiply_by_plaintext(&c, &k);
        assert_eq!(
            keypair.private.decrypt(&scaled).expect("decrypt"),
            BigUint::from(97u32 * 13)
        );
    }

    /// D(E(m) · g^k) = m + k.
    #[test]
    fn homomorphic_plaintext_addition_property() {
        let keypair = test_keypair(8);
        let mut rng = TestRng::seeded(26);
        let m = BigUint::from(500u32);
        let k = BigUint::from(123u32);
        let c = keypair.public.encrypt_with_rng(&m, &mut rng).expect("enc");
        let shifted = keypair.public.add_plaintext(&c, &k);
        assert_eq!(
            keypair.private.decrypt(&shifted).expect("decrypt"),
            BigUint::from(623u32)
        );
    }

    /// A ciphertext produced under one key must not decrypt correctly under
    /// another. (Paillier decryption of a foreign ciphertext yields garbage
    /// rather than an error, so we assert on the value.)
    #[test]
    fn foreign_key_does_not_recover_the_plaintext() {
        let alice = test_keypair(9);
        let bob = test_keypair(10);
        let mut rng = TestRng::seeded(27);
        let m = BigUint::from(0xABCDEFu32);
        let c = alice.public.encrypt_with_rng(&m, &mut rng).expect("enc");

        // Bob's n² differs, so the ciphertext is out of range or decrypts to
        // something else; either way it must not be the plaintext.
        match bob.private.decrypt(&c) {
            Err(_) => {},
            Ok(value) => assert_ne!(value, m, "foreign key must not recover the plaintext"),
        }
    }

    #[test]
    fn rejects_plaintext_at_or_above_the_modulus() {
        let keypair = test_keypair(11);
        let mut rng = TestRng::seeded(28);
        let too_big = keypair.public.modulus().clone();
        assert!(keypair.public.encrypt_with_rng(&too_big, &mut rng).is_err());
    }

    #[test]
    fn rejects_ciphertext_out_of_range() {
        let keypair = test_keypair(12);
        let oversized = PaillierCiphertext {
            value: keypair.public.modulus_squared().clone(),
        };
        assert!(keypair.private.decrypt(&oversized).is_err());
        let zero = PaillierCiphertext {
            value: BigUint::zero(),
        };
        assert!(keypair.private.decrypt(&zero).is_err());
    }

    #[test]
    fn ciphertext_serialization_round_trip() {
        let keypair = test_keypair(13);
        let mut rng = TestRng::seeded(29);
        let m = BigUint::from(777u32);
        let c = keypair.public.encrypt_with_rng(&m, &mut rng).expect("enc");
        let restored = PaillierCiphertext::from_bytes_be(&c.to_bytes_be());
        assert_eq!(keypair.private.decrypt(&restored).expect("decrypt"), m);
    }

    #[test]
    fn keygen_rejects_short_or_odd_moduli() {
        let mut rng = TestRng::seeded(14);
        assert!(generate_keypair_with_rng(256, &mut rng).is_err());
        assert!(generate_keypair_with_rng(513, &mut rng).is_err());
    }

    #[test]
    fn miller_rabin_accepts_known_primes_and_rejects_composites() {
        let mut rng = TestRng::seeded(15);
        for p in [7u32, 97, 65537, 2_147_483_647] {
            assert!(
                is_probable_prime(&BigUint::from(p), &mut rng),
                "{p} is prime"
            );
        }
        for c in [9u32, 91, 1_000_000, 2_147_483_646] {
            assert!(
                !is_probable_prime(&BigUint::from(c), &mut rng),
                "{c} is composite"
            );
        }
        // A product of two 32-bit primes: passes trial division, must fail MR.
        let composite = BigUint::from(4_294_967_291u64) * BigUint::from(4_294_967_279u64);
        assert!(!is_probable_prime(&composite, &mut rng));
    }

    #[test]
    fn unsupported_operation_names_paillier_and_the_limitation() {
        let err = unsupported_paillier_operation("ciphertext * ciphertext");
        let text = format!("{err}{err:?}");
        assert!(text.contains("ciphertext * ciphertext"), "{text}");
        assert!(text.contains("Paillier"), "{text}");
    }
}
