//! Real zero-knowledge proofs: a Schnorr sigma protocol made non-interactive
//! with the Fiat-Shamir transform.
//!
//! # What was here before
//!
//! The previous "zk-SNARK" built `proof = model_hash || witness || proving_key[..32]`
//! — the secret witness was published verbatim, the exact opposite of zero
//! knowledge — and "verified" with `proof.data.len() > 32`, so any 33-byte blob
//! passed. Both properties are now tested against explicitly.
//!
//! # What this is
//!
//! A proof of knowledge of a discrete logarithm in a safe-prime group:
//!
//! - Public parameters: a safe prime `p = 2q + 1`, a generator `g` of the
//!   order-`q` subgroup of `Z*_p`.
//! - Statement: `y = g^x mod p`, published.
//! - Witness: `x ∈ Z_q`, kept secret.
//!
//! Protocol (Schnorr):
//!
//! 1. Prover picks a random nonce `k ∈ Z_q`, sends the commitment `t = g^k mod p`.
//! 2. Verifier sends a challenge `c`. Fiat-Shamir replaces this with
//!    `c = H(domain ‖ p ‖ g ‖ y ‖ t ‖ context) mod q`, using SHA-256.
//! 3. Prover sends `s = k + c·x mod q`.
//!
//! Verification checks `g^s ≡ t · y^c (mod p)`.
//!
//! # Properties
//!
//! - **Completeness**: an honest prover always verifies.
//! - **Soundness**: producing `(t, s)` satisfying the check without knowing `x`
//!   requires solving a discrete log; forging by guessing succeeds with
//!   probability `1/q`. In the random-oracle model Fiat-Shamir preserves this.
//! - **Zero knowledge**: `(t, c, s)` is simulatable — pick `c, s` at random and
//!   set `t = g^s · y^{-c}` — so the transcript reveals nothing about `x`. In
//!   particular the witness never appears in the proof bytes.
//! - The challenge binds the statement *and* a caller-supplied context string,
//!   so a proof for one statement/context cannot be replayed for another.
//!
//! # Limitations, stated plainly
//!
//! This is a sigma protocol, not a general-purpose SNARK: it proves knowledge
//! of a discrete log (and, via the context binding, that the prover authorized a
//! particular statement). It does **not** prove arbitrary circuit satisfiability.
//! `ZKProofSystem::ZkSNARKs`/`ZkSTARKs`/`Plonk`/`Bulletproofs` are therefore
//! reported as unsupported rather than faked. `num-bigint`'s `modpow` is not
//! constant-time; the prover's secret exponent is used in one modexp, so this
//! is not hardened against a local timing attacker.

use num_bigint::{BigRng010, BigUint};
use num_traits::{One, Zero};
use rand_core::CryptoRng;
use sha2::{Digest, Sha256};
use std::fmt;
use trustformers_core::errors::{invalid_input, unsupported_operation, Result, TrustformersError};

/// Domain separation tag for the Fiat-Shamir hash.
const CHALLENGE_DOMAIN: &[u8] = b"trustformers-mobile/schnorr-fiat-shamir/v1";

/// RFC 3526 MODP group 14 (2048-bit safe prime), hex, big-endian.
///
/// `p` is a safe prime: `(p - 1) / 2` is prime, so the subgroup generated by
/// `g = 2` has prime order `q = (p - 1) / 2` and the discrete-log problem in it
/// is believed hard at roughly the 112-bit security level.
const MODP_2048_HEX: &str = concat!(
    "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1",
    "29024E088A67CC74020BBEA63B139B22514A08798E3404DD",
    "EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245",
    "E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED",
    "EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3D",
    "C2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F",
    "83655D23DCA3AD961C62F356208552BB9ED529077096966D",
    "670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B",
    "E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9",
    "DE2BCBF6955817183995497CEA956AE515D2261898FA0510",
    "15728E5A8AACAA68FFFFFFFFFFFFFFFF",
);

/// Structured error for a proof system this crate does not implement.
pub fn unsupported_proof_system(system: &str) -> TrustformersError {
    unsupported_operation(
        format!("zero-knowledge proof system {system}"),
        "trustformers-mobile (only a Schnorr sigma protocol with Fiat-Shamir over a \
         2048-bit safe-prime group is implemented; general-purpose circuit SNARKs/STARKs \
         are not)"
            .to_string(),
    )
}

/// Public parameters of the discrete-log group.
#[derive(Clone, PartialEq, Eq)]
pub struct SchnorrGroup {
    /// Safe prime modulus `p`.
    p: BigUint,
    /// Prime order `q = (p - 1) / 2` of the subgroup generated by `g`.
    q: BigUint,
    /// Generator of the order-`q` subgroup.
    g: BigUint,
}

impl fmt::Debug for SchnorrGroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("SchnorrGroup")
            .field("modulus_bits", &self.p.bits())
            .field("order_bits", &self.q.bits())
            .finish()
    }
}

impl Default for SchnorrGroup {
    fn default() -> Self {
        Self::modp_2048()
    }
}

impl SchnorrGroup {
    /// The RFC 3526 2048-bit MODP group with `g = 4` (a square, hence a
    /// generator of the order-`q` subgroup rather than of all of `Z*_p`).
    ///
    /// # Panics
    /// Never: the embedded constant is a valid hexadecimal literal, and the
    /// fallback below is only reachable if that constant were edited to an
    /// invalid value, which the `modp_2048_constant_parses` test rules out.
    pub fn modp_2048() -> Self {
        let p = BigUint::parse_bytes(MODP_2048_HEX.as_bytes(), 16).unwrap_or_else(BigUint::zero);
        let q = (&p - BigUint::one()) >> 1;
        // g = 2^2 = 4 lies in the order-q subgroup (every square does), and is
        // not 1, so it generates the whole subgroup (q is prime).
        Self {
            p,
            q,
            g: BigUint::from(4u32),
        }
    }

    /// The prime modulus.
    pub fn modulus(&self) -> &BigUint {
        &self.p
    }

    /// The subgroup order.
    pub fn order(&self) -> &BigUint {
        &self.q
    }

    /// The subgroup generator.
    pub fn generator(&self) -> &BigUint {
        &self.g
    }

    /// Sample a uniform witness `x ∈ [1, q)`.
    pub fn sample_witness<R: CryptoRng>(&self, rng: &mut R) -> BigUint {
        loop {
            let candidate = rng.random_biguint_below(&self.q);
            if !candidate.is_zero() {
                return candidate;
            }
        }
    }

    /// Compute the public statement `y = g^x mod p` for a witness `x`.
    pub fn public_value(&self, witness: &BigUint) -> BigUint {
        self.g.modpow(witness, &self.p)
    }
}

/// A Schnorr keypair: a secret witness and its public value.
#[derive(Clone)]
pub struct SchnorrKeypair {
    group: SchnorrGroup,
    witness: BigUint,
    public_value: BigUint,
}

impl fmt::Debug for SchnorrKeypair {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // The witness is secret and is deliberately not printed.
        f.debug_struct("SchnorrKeypair")
            .field("group", &self.group)
            .field("public_value_bits", &self.public_value.bits())
            .finish()
    }
}

impl SchnorrKeypair {
    /// Generate a keypair in `group` from the supplied CSPRNG.
    pub fn generate_with_rng<R: CryptoRng>(group: SchnorrGroup, rng: &mut R) -> Self {
        let witness = group.sample_witness(rng);
        let public_value = group.public_value(&witness);
        Self {
            group,
            witness,
            public_value,
        }
    }

    /// Generate a keypair in the default 2048-bit group using the OS CSPRNG.
    pub fn generate() -> Self {
        let mut rng = rand_core::UnwrapErr(getrandom::SysRng);
        Self::generate_with_rng(SchnorrGroup::default(), &mut rng)
    }

    /// The public verification data derived from this keypair.
    pub fn verifier(&self) -> SchnorrVerifier {
        SchnorrVerifier {
            group: self.group.clone(),
            public_value: self.public_value.clone(),
        }
    }

    /// The public value `y = g^x mod p`.
    pub fn public_value(&self) -> &BigUint {
        &self.public_value
    }

    /// Produce a non-interactive proof of knowledge of the witness, bound to
    /// `context` (for example a model hash, so the proof cannot be replayed for
    /// a different model).
    pub fn prove_with_rng<R: CryptoRng>(&self, context: &[u8], rng: &mut R) -> SchnorrProof {
        // Nonce k must be fresh and secret; reusing it across two proofs leaks x.
        let k = self.group.sample_witness(rng);
        let commitment = self.group.g.modpow(&k, &self.group.p);
        let challenge =
            fiat_shamir_challenge(&self.group, &self.public_value, &commitment, context);
        // s = k + c·x mod q
        let response = (k + challenge * &self.witness) % &self.group.q;
        SchnorrProof {
            commitment,
            response,
        }
    }

    /// Produce a proof using the OS CSPRNG.
    pub fn prove(&self, context: &[u8]) -> SchnorrProof {
        let mut rng = rand_core::UnwrapErr(getrandom::SysRng);
        self.prove_with_rng(context, &mut rng)
    }
}

/// The public half needed to check a [`SchnorrProof`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SchnorrVerifier {
    group: SchnorrGroup,
    public_value: BigUint,
}

impl SchnorrVerifier {
    /// Construct a verifier from a group and a published `y`.
    ///
    /// # Errors
    /// Returns an error if `y` is not a valid element of the order-`q` subgroup.
    pub fn new(group: SchnorrGroup, public_value: BigUint) -> Result<Self> {
        if public_value.is_zero() || public_value >= group.p {
            return Err(invalid_input(
                "Schnorr public value is out of range for the group modulus".to_string(),
            ));
        }
        // Subgroup membership: y^q must be 1 mod p.
        if public_value.modpow(&group.q, &group.p) != BigUint::one() {
            return Err(invalid_input(
                "Schnorr public value is not in the prime-order subgroup".to_string(),
            ));
        }
        Ok(Self {
            group,
            public_value,
        })
    }

    /// The published `y`.
    pub fn public_value(&self) -> &BigUint {
        &self.public_value
    }

    /// Check `g^s ≡ t · y^c (mod p)` where `c` is recomputed by the verifier.
    ///
    /// Returns `false` — never `true` — for a malformed or forged proof.
    pub fn verify(&self, proof: &SchnorrProof, context: &[u8]) -> bool {
        // Range checks first: an out-of-range commitment or response is a
        // forgery attempt, not a valid transcript.
        if proof.commitment.is_zero() || proof.commitment >= self.group.p {
            return false;
        }
        if proof.response >= self.group.q {
            return false;
        }
        // The commitment must live in the prime-order subgroup, otherwise a
        // small-subgroup element could be used to sidestep the check.
        if proof.commitment.modpow(&self.group.q, &self.group.p) != BigUint::one() {
            return false;
        }

        let challenge =
            fiat_shamir_challenge(&self.group, &self.public_value, &proof.commitment, context);
        let lhs = self.group.g.modpow(&proof.response, &self.group.p);
        let rhs = (&proof.commitment * self.public_value.modpow(&challenge, &self.group.p))
            % &self.group.p;
        lhs == rhs
    }
}

/// A non-interactive Schnorr proof: the commitment `t` and the response `s`.
///
/// The challenge is not stored: the verifier recomputes it from the statement,
/// which is what binds the proof to that statement.
#[derive(Clone, PartialEq, Eq)]
pub struct SchnorrProof {
    commitment: BigUint,
    response: BigUint,
}

impl fmt::Debug for SchnorrProof {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("SchnorrProof")
            .field("commitment_bits", &self.commitment.bits())
            .field("response_bits", &self.response.bits())
            .finish()
    }
}

impl SchnorrProof {
    /// Serialize as `len(t) as u32 BE || t || len(s) as u32 BE || s`.
    pub fn to_bytes(&self) -> Vec<u8> {
        let t = self.commitment.to_bytes_be();
        let s = self.response.to_bytes_be();
        let mut out = Vec::with_capacity(8 + t.len() + s.len());
        let t_len = u32::try_from(t.len()).unwrap_or(u32::MAX);
        let s_len = u32::try_from(s.len()).unwrap_or(u32::MAX);
        out.extend_from_slice(&t_len.to_be_bytes());
        out.extend_from_slice(&t);
        out.extend_from_slice(&s_len.to_be_bytes());
        out.extend_from_slice(&s);
        out
    }

    /// Parse the encoding produced by [`SchnorrProof::to_bytes`].
    ///
    /// # Errors
    /// Returns an error for a truncated or inconsistent encoding.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        fn read_field<'a>(input: &'a [u8], what: &str) -> Result<(BigUint, &'a [u8])> {
            if input.len() < 4 {
                return Err(invalid_input(format!(
                    "Schnorr proof truncated while reading the {what} length"
                )));
            }
            let (len_bytes, rest) = input.split_at(4);
            let mut len_array = [0u8; 4];
            len_array.copy_from_slice(len_bytes);
            let len = u32::from_be_bytes(len_array) as usize;
            if rest.len() < len {
                return Err(invalid_input(format!(
                    "Schnorr proof truncated while reading the {what} value"
                )));
            }
            let (value, tail) = rest.split_at(len);
            Ok((BigUint::from_bytes_be(value), tail))
        }

        let (commitment, rest) = read_field(bytes, "commitment")?;
        let (response, tail) = read_field(rest, "response")?;
        if !tail.is_empty() {
            return Err(invalid_input(
                "Schnorr proof has trailing bytes after the response".to_string(),
            ));
        }
        Ok(Self {
            commitment,
            response,
        })
    }
}

/// `c = H(domain ‖ p ‖ g ‖ y ‖ t ‖ context) mod q`.
///
/// Every field is length-prefixed so that concatenation is unambiguous — without
/// this, two different statements could hash to the same challenge.
fn fiat_shamir_challenge(
    group: &SchnorrGroup,
    public_value: &BigUint,
    commitment: &BigUint,
    context: &[u8],
) -> BigUint {
    let mut hasher = Sha256::new();
    hasher.update(CHALLENGE_DOMAIN);
    for field in [
        group.p.to_bytes_be(),
        group.g.to_bytes_be(),
        public_value.to_bytes_be(),
        commitment.to_bytes_be(),
        context.to_vec(),
    ] {
        let len = u64::try_from(field.len()).unwrap_or(u64::MAX);
        hasher.update(len.to_be_bytes());
        hasher.update(&field);
    }
    BigUint::from_bytes_be(&hasher.finalize()) % &group.q
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::advanced_security::test_rng::TestRng;

    fn keypair(seed: u8) -> SchnorrKeypair {
        let mut rng = TestRng::seeded(seed);
        SchnorrKeypair::generate_with_rng(SchnorrGroup::default(), &mut rng)
    }

    #[test]
    fn modp_2048_constant_parses_and_is_a_safe_prime_shape() {
        let group = SchnorrGroup::modp_2048();
        assert_eq!(
            group.modulus().bits(),
            2048,
            "MODP-2048 constant failed to parse"
        );
        assert_eq!(group.order().bits(), 2047);
        // g must be in the prime-order subgroup: g^q == 1.
        assert_eq!(
            group.generator().modpow(group.order(), group.modulus()),
            BigUint::one()
        );
        // g must not be the identity.
        assert_ne!(group.generator(), &BigUint::one());
    }

    #[test]
    fn honest_proof_verifies() {
        let kp = keypair(1);
        let mut rng = TestRng::seeded(101);
        let proof = kp.prove_with_rng(b"model-hash-abc", &mut rng);
        assert!(kp.verifier().verify(&proof, b"model-hash-abc"));
    }

    /// Regression for the old `generate_snark_proof`, which appended the
    /// witness in the clear. The proof bytes must not contain the witness.
    #[test]
    fn proof_does_not_contain_the_witness() {
        let kp = keypair(2);
        let mut rng = TestRng::seeded(102);
        let proof = kp.prove_with_rng(b"ctx", &mut rng);
        let bytes = proof.to_bytes();
        let witness_bytes = kp.witness.to_bytes_be();
        assert!(
            witness_bytes.len() > 16,
            "witness should be large enough for this test"
        );
        assert!(
            !bytes.windows(witness_bytes.len()).any(|w| w == witness_bytes.as_slice()),
            "proof leaks the witness verbatim"
        );
    }

    /// Regression for the old verifier `proof.data.len() > 32`, which accepted
    /// any sufficiently long blob.
    #[test]
    fn arbitrary_bytes_do_not_verify() {
        let kp = keypair(3);
        let verifier = kp.verifier();
        for filler in [0x00u8, 0x01, 0xAA, 0xFF] {
            let blob = vec![filler; 512];
            match SchnorrProof::from_bytes(&blob) {
                // Most blobs do not even parse.
                Err(_) => {},
                // Any that do must still fail the algebraic check.
                Ok(parsed) => assert!(
                    !verifier.verify(&parsed, b"ctx"),
                    "a {filler:#04x}-filled blob must not verify"
                ),
            }
        }

        // Explicitly build a well-formed-but-wrong proof of the length the old
        // verifier would have accepted.
        let forged = SchnorrProof {
            commitment: BigUint::from(12345u32),
            response: BigUint::from(67890u32),
        };
        assert!(!verifier.verify(&forged, b"ctx"));
    }

    #[test]
    fn proof_is_bound_to_its_context() {
        let kp = keypair(4);
        let mut rng = TestRng::seeded(104);
        let proof = kp.prove_with_rng(b"context-a", &mut rng);
        assert!(kp.verifier().verify(&proof, b"context-a"));
        assert!(
            !kp.verifier().verify(&proof, b"context-b"),
            "a proof must not verify under a different context"
        );
    }

    #[test]
    fn proof_does_not_verify_against_a_different_public_value() {
        let alice = keypair(5);
        let mallory = keypair(6);
        let mut rng = TestRng::seeded(105);
        let proof = alice.prove_with_rng(b"ctx", &mut rng);
        assert!(
            !mallory.verifier().verify(&proof, b"ctx"),
            "a proof must not verify against a foreign statement"
        );
    }

    #[test]
    fn tampering_with_the_response_breaks_verification() {
        let kp = keypair(7);
        let mut rng = TestRng::seeded(107);
        let mut proof = kp.prove_with_rng(b"ctx", &mut rng);
        proof.response += BigUint::one();
        assert!(!kp.verifier().verify(&proof, b"ctx"));
    }

    #[test]
    fn tampering_with_the_commitment_breaks_verification() {
        let kp = keypair(8);
        let mut rng = TestRng::seeded(108);
        let mut proof = kp.prove_with_rng(b"ctx", &mut rng);
        proof.commitment = (&proof.commitment * BigUint::from(4u32)) % kp.group.modulus();
        assert!(!kp.verifier().verify(&proof, b"ctx"));
    }

    #[test]
    fn out_of_range_values_are_rejected() {
        let kp = keypair(9);
        let verifier = kp.verifier();
        let zero_commitment = SchnorrProof {
            commitment: BigUint::zero(),
            response: BigUint::one(),
        };
        assert!(!verifier.verify(&zero_commitment, b"ctx"));

        let oversized_response = SchnorrProof {
            commitment: kp.group.generator().clone(),
            response: kp.group.order().clone(),
        };
        assert!(!verifier.verify(&oversized_response, b"ctx"));

        let oversized_commitment = SchnorrProof {
            commitment: kp.group.modulus().clone(),
            response: BigUint::one(),
        };
        assert!(!verifier.verify(&oversized_commitment, b"ctx"));
    }

    /// A non-subgroup commitment (an element of order 2q, e.g. p-1 combined
    /// with a generator) must not be accepted.
    #[test]
    fn non_subgroup_commitment_is_rejected() {
        let kp = keypair(10);
        let verifier = kp.verifier();
        // p - 1 has order 2, which is not q.
        let non_subgroup = kp.group.modulus() - BigUint::one();
        let proof = SchnorrProof {
            commitment: non_subgroup,
            response: BigUint::one(),
        };
        assert!(!verifier.verify(&proof, b"ctx"));
    }

    #[test]
    fn proof_serialization_round_trip() {
        let kp = keypair(11);
        let mut rng = TestRng::seeded(111);
        let proof = kp.prove_with_rng(b"ctx", &mut rng);
        let restored = SchnorrProof::from_bytes(&proof.to_bytes()).expect("parse");
        assert_eq!(restored, proof);
        assert!(kp.verifier().verify(&restored, b"ctx"));
    }

    #[test]
    fn truncated_serialization_is_rejected() {
        let kp = keypair(12);
        let mut rng = TestRng::seeded(112);
        let bytes = kp.prove_with_rng(b"ctx", &mut rng).to_bytes();
        assert!(SchnorrProof::from_bytes(&bytes[..bytes.len() - 1]).is_err());
        assert!(SchnorrProof::from_bytes(&bytes[..2]).is_err());
        let mut extended = bytes.clone();
        extended.push(0);
        assert!(SchnorrProof::from_bytes(&extended).is_err());
    }

    /// Two proofs of the same statement use fresh nonces, so their commitments
    /// differ (nonce reuse would leak the witness).
    #[test]
    fn proofs_use_fresh_nonces() {
        let kp = keypair(13);
        let mut rng = TestRng::seeded(113);
        let p1 = kp.prove_with_rng(b"ctx", &mut rng);
        let p2 = kp.prove_with_rng(b"ctx", &mut rng);
        assert_ne!(
            p1.commitment, p2.commitment,
            "nonce must be fresh per proof"
        );
        assert!(kp.verifier().verify(&p1, b"ctx"));
        assert!(kp.verifier().verify(&p2, b"ctx"));
    }

    #[test]
    fn verifier_rejects_a_public_value_outside_the_subgroup() {
        let group = SchnorrGroup::default();
        // p - 1 has order 2.
        let bad = group.modulus() - BigUint::one();
        assert!(SchnorrVerifier::new(group.clone(), bad).is_err());
        assert!(SchnorrVerifier::new(group.clone(), BigUint::zero()).is_err());
        assert!(SchnorrVerifier::new(group.clone(), group.modulus().clone()).is_err());
    }

    #[test]
    fn unsupported_proof_system_error_is_structured() {
        let err = unsupported_proof_system("Groth16");
        let text = format!("{err}{err:?}");
        assert!(text.contains("Groth16"), "{text}");
        assert!(text.contains("Schnorr"), "{text}");
    }
}
