//! Pure-Rust AES-128-CTR and AES-256-CTR encryption backed by the `aes` crate.
//!
//! The [`aes`] crate automatically selects AES-NI hardware acceleration at
//! runtime on x86/x86_64 processors that support it (via `cpuid` detection),
//! falling back to a fully constant-time software implementation otherwise.
//! No feature flags or compile-time configuration are needed — the runtime
//! dispatch is entirely transparent to the caller.
//!
//! # Hardware AES-NI Detection
//!
//! On x86/x86_64, `aes 0.8+` uses `std::arch` and `is_x86_feature_detected!`
//! internally to select the AES-NI path at first use.  The `hardware-aes`
//! feature flag in this crate documents this capability; enabling it does not
//! add any extra dependencies because the `aes` crate already performs the
//! dispatch unconditionally.
//!
//! # CTR Mode Construction
//!
//! The counter block is 128 bits wide: the upper 64 bits are the nonce
//! (passed by the caller), and the lower 64 bits are a big-endian block
//! counter starting at `counter_start` and incrementing by one per block.

use aes::cipher::{BlockCipherDecrypt, BlockCipherEncrypt, KeyInit};
use aes::{Aes128, Aes256};

// ---------------------------------------------------------------------------
// CTR mode state
// ---------------------------------------------------------------------------

/// Counter state for AES-CTR mode: 64-bit nonce + 64-bit counter = 128-bit counter block.
#[derive(Debug, Clone)]
pub struct CtrState {
    /// 64-bit nonce (high 8 bytes of the 128-bit counter block).
    pub nonce: [u8; 8],
    /// 64-bit counter (low 8 bytes of the 128-bit counter block).
    pub counter: u64,
}

impl CtrState {
    /// Create a new CTR state with the given nonce and counter starting at 0.
    pub fn new(nonce: [u8; 8]) -> Self {
        Self { nonce, counter: 0 }
    }

    /// Produce the next 16-byte counter block: nonce (8 bytes) || counter (8 bytes, big-endian).
    /// Increments the internal counter after returning the current block.
    pub fn next_block(&mut self) -> [u8; 16] {
        let mut block = [0u8; 16];
        block[0..8].copy_from_slice(&self.nonce);
        block[8..16].copy_from_slice(&self.counter.to_be_bytes());
        self.counter = self.counter.wrapping_add(1);
        block
    }
}

// ---------------------------------------------------------------------------
// Internal cipher enum
// ---------------------------------------------------------------------------

/// Unified wrapper around AES-128 and AES-256 ciphers.
#[derive(Clone)]
enum AesCipher {
    Aes128(Aes128),
    Aes256(Aes256),
}

impl AesCipher {
    /// Encrypt a single 16-byte block in-place.
    fn encrypt_block_inplace(&self, block: &mut [u8; 16]) {
        match self {
            AesCipher::Aes128(c) => {
                let mut b = aes::Block::from(*block);
                c.encrypt_block(&mut b);
                block.copy_from_slice(b.as_slice());
            }
            AesCipher::Aes256(c) => {
                let mut b = aes::Block::from(*block);
                c.encrypt_block(&mut b);
                block.copy_from_slice(b.as_slice());
            }
        }
    }
}

impl std::fmt::Debug for AesCipher {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AesCipher::Aes128(_) => write!(f, "AesCipher::Aes128"),
            AesCipher::Aes256(_) => write!(f, "AesCipher::Aes256"),
        }
    }
}

// ---------------------------------------------------------------------------
// AesCtr structure
// ---------------------------------------------------------------------------

/// AES-CTR cipher for 128-bit or 256-bit keys.
///
/// Backed by the [`aes`] crate which transparently uses AES-NI hardware
/// acceleration when available.
#[derive(Debug, Clone)]
pub struct AesCtr {
    /// Key size in bits: 128 or 256.
    pub key_size_bits: usize,
    cipher: AesCipher,
}

impl AesCtr {
    /// Create a new AES-128-CTR cipher from a 16-byte key.
    pub fn new_128(key: &[u8; 16]) -> Self {
        let cipher =
            Aes128::new_from_slice(key).expect("AES-128 key is exactly 16 bytes; infallible");
        Self {
            key_size_bits: 128,
            cipher: AesCipher::Aes128(cipher),
        }
    }

    /// Create a new AES-256-CTR cipher from a 32-byte key.
    pub fn new_256(key: &[u8; 32]) -> Self {
        let cipher =
            Aes256::new_from_slice(key).expect("AES-256 key is exactly 32 bytes; infallible");
        Self {
            key_size_bits: 256,
            cipher: AesCipher::Aes256(cipher),
        }
    }

    /// Encrypt `data` in CTR mode.
    ///
    /// The keystream is generated by encrypting `nonce || counter` blocks,
    /// where `counter` starts at `counter_start` and increments by 1 per 16-byte block.
    pub fn encrypt(&self, data: &[u8], nonce: &[u8; 8], counter_start: u64) -> Vec<u8> {
        self.apply_keystream(data, nonce, counter_start)
    }

    /// Decrypt `data` in CTR mode (identical to encryption — CTR is symmetric).
    pub fn decrypt(&self, data: &[u8], nonce: &[u8; 8], counter_start: u64) -> Vec<u8> {
        self.apply_keystream(data, nonce, counter_start)
    }

    /// Core CTR keystream XOR operation.
    fn apply_keystream(&self, data: &[u8], nonce: &[u8; 8], counter_start: u64) -> Vec<u8> {
        let mut output = Vec::with_capacity(data.len());
        let mut counter = counter_start;
        let mut offset = 0;

        while offset < data.len() {
            // Build counter block: nonce (8 bytes) || counter (8 bytes big-endian)
            let mut block = [0u8; 16];
            block[0..8].copy_from_slice(nonce);
            block[8..16].copy_from_slice(&counter.to_be_bytes());

            // Encrypt counter block to produce keystream block
            self.cipher.encrypt_block_inplace(&mut block);

            // XOR keystream with plaintext/ciphertext
            let chunk_len = (data.len() - offset).min(16);
            for i in 0..chunk_len {
                output.push(data[offset + i] ^ block[i]);
            }

            offset += chunk_len;
            counter = counter.wrapping_add(1);
        }

        output
    }
}

// ---------------------------------------------------------------------------
// Public block-level helpers (used by aes_cbc.rs)
// ---------------------------------------------------------------------------

/// Encrypt a single 16-byte AES-128 block.
///
/// This is a thin adapter that lets `aes_cbc.rs` share the same
/// AES-NI-accelerated code path without duplicating cipher construction.
pub(crate) fn encrypt_block_128(cipher: &Aes128, plaintext: &[u8; 16]) -> [u8; 16] {
    let mut block = aes::Block::from(*plaintext);
    cipher.encrypt_block(&mut block);
    let mut out = [0u8; 16];
    out.copy_from_slice(block.as_slice());
    out
}

/// Decrypt a single 16-byte AES-128 block.
pub(crate) fn decrypt_block_128(cipher: &aes::Aes128Dec, plaintext: &[u8; 16]) -> [u8; 16] {
    let mut block = aes::Block::from(*plaintext);
    cipher.decrypt_block(&mut block);
    let mut out = [0u8; 16];
    out.copy_from_slice(block.as_slice());
    out
}

/// Encrypt a single 16-byte AES-256 block.
pub(crate) fn encrypt_block_256(cipher: &Aes256, plaintext: &[u8; 16]) -> [u8; 16] {
    let mut block = aes::Block::from(*plaintext);
    cipher.encrypt_block(&mut block);
    let mut out = [0u8; 16];
    out.copy_from_slice(block.as_slice());
    out
}

/// Decrypt a single 16-byte AES-256 block.
pub(crate) fn decrypt_block_256(cipher: &aes::Aes256Dec, plaintext: &[u8; 16]) -> [u8; 16] {
    let mut block = aes::Block::from(*plaintext);
    cipher.decrypt_block(&mut block);
    let mut out = [0u8; 16];
    out.copy_from_slice(block.as_slice());
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // NIST FIPS 197 Appendix B test vector (AES-128 ECB)
    // Key:        2b 7e 15 16 28 ae d2 a6 ab f7 15 88 09 cf 4f 3c
    // Plaintext:  32 43 f6 a8 88 5a 30 8d 31 31 98 a2 e0 37 07 34
    // Ciphertext: 39 25 84 1d 02 dc 09 fb dc 11 85 97 19 6a 0b 32
    // -----------------------------------------------------------------------

    #[test]
    fn test_aes128_nist_fips197_appendix_b() {
        use aes::cipher::KeyInit;
        let key: [u8; 16] = [
            0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf,
            0x4f, 0x3c,
        ];
        let plaintext: [u8; 16] = [
            0x32, 0x43, 0xf6, 0xa8, 0x88, 0x5a, 0x30, 0x8d, 0x31, 0x31, 0x98, 0xa2, 0xe0, 0x37,
            0x07, 0x34,
        ];
        let expected: [u8; 16] = [
            0x39, 0x25, 0x84, 0x1d, 0x02, 0xdc, 0x09, 0xfb, 0xdc, 0x11, 0x85, 0x97, 0x19, 0x6a,
            0x0b, 0x32,
        ];
        let cipher =
            Aes128::new_from_slice(&key).expect("16-byte key is valid for AES-128; infallible");
        let ciphertext = encrypt_block_128(&cipher, &plaintext);
        assert_eq!(
            ciphertext, expected,
            "NIST FIPS 197 Appendix B test vector failed"
        );
    }

    // NIST AES-256 test vector (ECB mode, from FIPS 197 Appendix B / NIST AESAVS)
    // Key:        00 01 02 03 .. 1e 1f
    // Plaintext:  00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff
    // Ciphertext: 8e a2 b7 ca 51 67 45 bf ea fc 49 90 4b 49 60 89
    #[test]
    fn test_aes256_nist_vector() {
        use aes::cipher::KeyInit;
        let key: [u8; 32] = [
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
            0x1c, 0x1d, 0x1e, 0x1f,
        ];
        let plaintext: [u8; 16] = [
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
            0xee, 0xff,
        ];
        let expected: [u8; 16] = [
            0x8e, 0xa2, 0xb7, 0xca, 0x51, 0x67, 0x45, 0xbf, 0xea, 0xfc, 0x49, 0x90, 0x4b, 0x49,
            0x60, 0x89,
        ];
        let cipher =
            Aes256::new_from_slice(&key).expect("32-byte key is valid for AES-256; infallible");
        let ciphertext = encrypt_block_256(&cipher, &plaintext);
        assert_eq!(ciphertext, expected, "AES-256 NIST vector failed");
    }

    #[test]
    fn test_ctr128_roundtrip() {
        let key = [0x42u8; 16];
        let nonce = [0x01u8; 8];
        let plaintext = b"Hello, AES-128-CTR mode!";

        let cipher = AesCtr::new_128(&key);
        let ciphertext = cipher.encrypt(plaintext, &nonce, 0);
        let decrypted = cipher.decrypt(&ciphertext, &nonce, 0);

        assert_eq!(decrypted, plaintext.to_vec());
    }

    #[test]
    fn test_ctr256_roundtrip() {
        let key = [0xabu8; 32];
        let nonce = [0x00u8; 8];
        let plaintext = b"AES-256-CTR encryption and decryption round-trip test";

        let cipher = AesCtr::new_256(&key);
        let ciphertext = cipher.encrypt(plaintext, &nonce, 0);
        let decrypted = cipher.decrypt(&ciphertext, &nonce, 0);

        assert_eq!(decrypted, plaintext.to_vec());
    }

    #[test]
    fn test_ctr_empty_input() {
        let key = [0x00u8; 16];
        let nonce = [0x00u8; 8];
        let cipher = AesCtr::new_128(&key);
        let result = cipher.encrypt(&[], &nonce, 0);
        assert!(result.is_empty());
    }

    #[test]
    fn test_ctr_partial_block() {
        // Less than 16 bytes — must still work correctly
        let key = [0x11u8; 16];
        let nonce = [0x22u8; 8];
        let plaintext = b"short";

        let cipher = AesCtr::new_128(&key);
        let ciphertext = cipher.encrypt(plaintext, &nonce, 0);
        let decrypted = cipher.decrypt(&ciphertext, &nonce, 0);

        assert_eq!(ciphertext.len(), plaintext.len());
        assert_eq!(decrypted, plaintext.to_vec());
    }

    #[test]
    fn test_ctr_large_data() {
        let key = [0x5au8; 16];
        let nonce = [0x3cu8; 8];
        let plaintext: Vec<u8> = (0u8..=255u8).cycle().take(65536).collect();

        let cipher = AesCtr::new_128(&key);
        let ciphertext = cipher.encrypt(&plaintext, &nonce, 0);
        let decrypted = cipher.decrypt(&ciphertext, &nonce, 0);

        assert_eq!(ciphertext.len(), plaintext.len());
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_ctr_different_nonces_produce_different_output() {
        let key = [0x77u8; 16];
        let nonce1 = [0x00u8; 8];
        let nonce2 = [0x01u8; 8];
        let plaintext = b"same plaintext for nonce comparison";

        let cipher = AesCtr::new_128(&key);
        let ct1 = cipher.encrypt(plaintext, &nonce1, 0);
        let ct2 = cipher.encrypt(plaintext, &nonce2, 0);

        assert_ne!(ct1, ct2);
    }

    #[test]
    fn test_ctr_different_counter_start_produces_different_output() {
        let key = [0x88u8; 16];
        let nonce = [0x00u8; 8];
        let plaintext = b"counter offset test";

        let cipher = AesCtr::new_128(&key);
        let ct1 = cipher.encrypt(plaintext, &nonce, 0);
        let ct2 = cipher.encrypt(plaintext, &nonce, 1);

        assert_ne!(ct1, ct2);
    }

    #[test]
    fn test_ctr_state_new() {
        let nonce = [0x01u8, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
        let state = CtrState::new(nonce);
        assert_eq!(state.nonce, nonce);
        assert_eq!(state.counter, 0);
    }

    #[test]
    fn test_ctr_state_next_block_increments_counter() {
        let nonce = [0xffu8; 8];
        let mut state = CtrState::new(nonce);

        let block0 = state.next_block();
        assert_eq!(&block0[0..8], &nonce);
        assert_eq!(&block0[8..16], &0u64.to_be_bytes());
        assert_eq!(state.counter, 1);

        let block1 = state.next_block();
        assert_eq!(&block1[8..16], &1u64.to_be_bytes());
        assert_eq!(state.counter, 2);
    }

    #[test]
    fn test_ctr_counter_wraps_around() {
        let key = [0xaau8; 16];
        let nonce = [0x00u8; 8];
        let plaintext = b"wrap test";

        let cipher = AesCtr::new_128(&key);
        // Counter near overflow
        let ct = cipher.encrypt(plaintext, &nonce, u64::MAX);
        let pt = cipher.decrypt(&ct, &nonce, u64::MAX);
        assert_eq!(pt, plaintext.to_vec());
    }

    #[test]
    fn test_encrypt_decrypt_symmetry_256() {
        let key = [0xdeu8; 32];
        let nonce = [0xadu8; 8];
        let original = b"test symmetry for AES-256-CTR mode encryption";

        let cipher = AesCtr::new_256(&key);
        let encrypted = cipher.encrypt(original, &nonce, 42);
        let decrypted = cipher.decrypt(&encrypted, &nonce, 42);

        assert_eq!(decrypted, original.to_vec());
        // Encrypted should differ from plaintext
        assert_ne!(encrypted, original.to_vec());
    }

    /// Verifies that the AES-NI path (if present) and the software path both
    /// produce the same output.  Since the `aes` crate dispatches transparently,
    /// we just confirm a stable encrypt→decrypt identity using both key sizes.
    #[test]
    fn test_aes_ctr_hardware_path_matches_software() {
        let key128 = [0xC0u8; 16];
        let key256 = [0xFFu8; 32];
        let nonce = [0xAAu8; 8];
        let data: Vec<u8> = (0..256).map(|i| i as u8).collect();

        let c128 = AesCtr::new_128(&key128);
        let encrypted = c128.encrypt(&data, &nonce, 0);
        let decrypted = c128.decrypt(&encrypted, &nonce, 0);
        assert_eq!(decrypted, data, "AES-128-CTR identity failed");

        let c256 = AesCtr::new_256(&key256);
        let encrypted = c256.encrypt(&data, &nonce, 0);
        let decrypted = c256.decrypt(&encrypted, &nonce, 0);
        assert_eq!(decrypted, data, "AES-256-CTR identity failed");
    }
}
