//! [`DebiasedRanker`] — **unbiased learning to rank from biased implicit
//! feedback** (Joachims, Swaminathan & Schnabel, 2017, "Unbiased Learning-to-Rank
//! with Biased Feedback").
//!
//! # The construction
//!
//! From a click log, a *naive* pairwise learner reads off one preference per
//! `(clicked, not-clicked)` pair in a session and minimises the usual pairwise
//! logistic (`RankNet`) loss. That learner converges — enthusiastically — to the
//! **logging policy's own bias**, because a document at rank 0 wins those pairs
//! far more often than an equally good document at rank 9, purely by being
//! looked at more.
//!
//! The fix is a single, decisive multiplication. A pair generated by a click on
//! document `d⁺`, logged at rank `r`, is *itself* only observable with
//! probability `γ_r`. So weight it by `1 / γ_r`:
//!
//! ```text
//! L(w) = ( Σ_sessions Σ_{d⁺ clicked} Σ_{d⁻ not clicked}  (1/γ_{r(d⁺)}) ·
//!            ln(1 + exp(−(w·x_{d⁺} − w·x_{d⁻}))) )  /  Σ (1/γ_{r(d⁺)})
//!        + (λ/2)·‖w‖²
//! ```
//!
//! Under the examination hypothesis, `E[click at rank r] = γ_r · α_d`, so
//! `E[click / γ_r] = α_d` — the `γ_r` in the numerator (the probability of
//! *seeing* the pair) and the `1/γ_r` in the weight cancel **exactly**, and the
//! expected loss is the loss the learner would have paid on the *unbiased*
//! preferences it never got to see. The empirical risk minimiser of the weighted
//! loss is therefore consistent for the true ranking, from data that is
//! systematically lying to it.
//!
//! # Why the loss is exactly minimised, not approximately
//!
//! The score is linear (`s = w · x`), the pairwise logistic loss is convex in
//! the score difference, and the difference is linear in `w`; adding an `L2`
//! penalty makes the objective **strictly** convex. Full-batch gradient descent
//! with a sensibly small step therefore decreases the loss monotonically and
//! converges to the unique optimum. The tests assert the monotone decrease
//! directly. The `L2` term is not decoration: with one-hot features and a
//! document that never loses a pair, the unregularised optimum is at infinity.
//!
//! # Pair aggregation
//!
//! Because the score depends on the document alone, two pairs over the same
//! `(d⁺, d⁻)` differ only in their weight. The fitter therefore **aggregates**
//! them into one pair carrying the summed weight before the first gradient step.
//! This is exact — not an approximation — and it turns an `O(sessions × k²)`
//! inner loop into an `O(distinct pairs)` one.
//!
//! # How to get the *naive* learner for comparison
//!
//! Fit against [`PropensityEstimates::uniform`]. Every weight becomes `1`, the
//! correction disappears, and you have the biased baseline — which is exactly how
//! the module's tests show that it is the debiasing, and nothing else, that
//! recovers the true order.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use super::counterfactual::{ClickRankingPolicy, PropensityEstimates};
use super::types::{ClickLog, ClickModelError, ClickModelResult};

// ── DebiasedRankerConfig ─────────────────────────────────────────────────────

/// Hyper-parameters of [`DebiasedRanker`]'s gradient-descent fit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DebiasedRankerConfig {
    /// Full-batch gradient-descent step size. Default `0.5`.
    pub learning_rate: f64,
    /// Maximum number of full-batch epochs. Default `500`.
    pub epochs: usize,
    /// `L2` penalty coefficient `λ`. Keeps the optimum finite even when a
    /// document never loses a pair. Default `1e-3`.
    pub l2_regularization: f64,
    /// Stop early once the loss improves by less than this in an epoch. Default
    /// `1e-9`.
    pub tolerance: f64,
}

impl Default for DebiasedRankerConfig {
    fn default() -> Self {
        Self {
            learning_rate: 0.5,
            epochs: 500,
            l2_regularization: 1e-3,
            tolerance: 1e-9,
        }
    }
}

impl DebiasedRankerConfig {
    /// The documented defaults.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Override the learning rate.
    #[must_use]
    pub fn with_learning_rate(mut self, value: f64) -> Self {
        self.learning_rate = value;
        self
    }

    /// Override the epoch cap.
    #[must_use]
    pub fn with_epochs(mut self, value: usize) -> Self {
        self.epochs = value;
        self
    }

    /// Override the `L2` penalty.
    #[must_use]
    pub fn with_l2_regularization(mut self, value: f64) -> Self {
        self.l2_regularization = value;
        self
    }

    /// Override the early-stopping tolerance.
    #[must_use]
    pub fn with_tolerance(mut self, value: f64) -> Self {
        self.tolerance = value;
        self
    }

    /// Check the hyper-parameters are usable.
    ///
    /// # Errors
    ///
    /// [`ClickModelError::InvalidConfig`] for a non-finite or non-positive
    /// learning rate, a zero epoch budget, or a negative / non-finite `L2`
    /// coefficient or tolerance.
    pub fn validate(&self) -> ClickModelResult<()> {
        let invalid = |reason: &str| ClickModelError::InvalidConfig {
            reason: reason.to_owned(),
        };
        if !self.learning_rate.is_finite() || self.learning_rate <= 0.0 {
            return Err(invalid("learning_rate must be finite and positive"));
        }
        if self.epochs == 0 {
            return Err(invalid("epochs must be at least 1"));
        }
        if !self.l2_regularization.is_finite() || self.l2_regularization < 0.0 {
            return Err(invalid("l2_regularization must be finite and non-negative"));
        }
        if !self.tolerance.is_finite() || self.tolerance < 0.0 {
            return Err(invalid("tolerance must be finite and non-negative"));
        }
        Ok(())
    }
}

// ── DebiasedRankerFit ────────────────────────────────────────────────────────

/// What a [`DebiasedRanker::fit`] run did.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DebiasedRankerFit {
    /// Epochs actually run.
    pub epochs: usize,
    /// Whether the run stopped on the tolerance rather than the epoch cap.
    pub converged: bool,
    /// The loss before the first step, then after each epoch. Convex objective +
    /// full-batch descent ⇒ this is monotone non-increasing.
    pub loss_history: Vec<f64>,
    /// The loss of the returned weights.
    pub final_loss: f64,
    /// How many *distinct* `(clicked, unclicked)` document pairs the log yielded
    /// after aggregation.
    pub distinct_pair_count: usize,
    /// The total inverse-propensity weight across all pairs, before aggregation.
    pub total_pair_weight: f64,
}

impl DebiasedRankerFit {
    /// Whether the loss trace never *increased* by more than `epsilon`.
    #[must_use]
    pub fn is_monotone(&self, epsilon: f64) -> bool {
        self.loss_history
            .windows(2)
            .all(|pair| pair[1] <= pair[0] + epsilon)
    }
}

// ── DebiasedRanker ───────────────────────────────────────────────────────────

/// A linear scorer fitted by minimising an **inverse-propensity-weighted**
/// pairwise loss over a click log — i.e. learning to rank from clicks that are
/// systematically biased by position, and coming out unbiased anyway.
///
/// ```
/// # #[cfg(feature = "click-model")]
/// # {
/// use oxirag::click_model::{
///     ClickLogSimulator, ClickRankingPolicy, ClickSimulationModel, DebiasedRanker,
///     DebiasedRankerConfig, PropensityEstimates, naive_click_through_rates,
/// };
///
/// // A rigged log: 90% of traffic sees "mediocre" first and "excellent" last,
/// // so the top slot's examination advantage flows entirely to the wrong
/// // document. The remaining 10% is randomised — which is the *only* reason the
/// // propensities are estimable at all (see the module docs on identifiability).
/// let docs = vec!["mediocre".to_owned(), "filler".to_owned(), "excellent".to_owned()];
/// let mut rankings = Vec::new();
/// for index in 0..6_000 {
///     rankings.push(match index % 20 {
///         18 => vec!["excellent".to_owned(), "mediocre".to_owned(), "filler".to_owned()],
///         19 => vec!["filler".to_owned(), "excellent".to_owned(), "mediocre".to_owned()],
///         _ => docs.clone(),
///     });
/// }
/// let log = ClickLogSimulator::new(docs)
///     .with_attractiveness(vec![0.3, 0.15, 0.9])
///     .with_examination(vec![1.0, 0.4, 0.1])
///     .with_seed(99)
///     .simulate_rankings(ClickSimulationModel::PositionBased, &rankings)
///     .expect("valid simulation");
///
/// // The naive click-through rate is fooled, exactly as advertised.
/// let ctr = naive_click_through_rates(&log);
/// assert!(ctr["mediocre"] > ctr["excellent"]);
///
/// // So is a naive PAIRWISE learner — `uniform` propensities are precisely the
/// // "assume no position bias" assumption.
/// let mut naive = DebiasedRanker::new(DebiasedRankerConfig::default());
/// naive
///     .fit_tabular(&log, &PropensityEstimates::uniform(3))
///     .expect("fit succeeds");
/// assert!(naive.score("q0", "mediocre") > naive.score("q0", "excellent"));
///
/// // Now weight each preference by the inverse propensity of the rank its click
/// // was observed at — here, the true examination curve.
/// let propensities = PropensityEstimates::new(vec![1.0, 0.4, 0.1], 0.01).expect("valid");
/// let mut debiased = DebiasedRanker::new(DebiasedRankerConfig::default());
/// let fit = debiased.fit_tabular(&log, &propensities).expect("fit succeeds");
/// assert!(fit.is_monotone(1e-9)); // convex loss, full-batch descent
///
/// // ...and the true order comes back out of the very same biased clicks.
/// assert!(debiased.score("q0", "excellent") > debiased.score("q0", "mediocre"));
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct DebiasedRanker {
    config: DebiasedRankerConfig,
    /// Document → feature vector. Owned, so the fitted ranker is a standalone
    /// [`ClickRankingPolicy`].
    features: HashMap<String, Vec<f64>>,
    weights: Vec<f64>,
    feature_dim: usize,
    fitted: bool,
}

/// The per-document feature matrix a fit runs on, plus the reverse index from
/// document id to its row.
type FeatureMatrix<'a> = (Vec<Vec<f64>>, HashMap<&'a str, usize>);

/// What one full gradient-descent run produced.
#[derive(Debug, Clone)]
struct DebiasedDescent {
    weights: Vec<f64>,
    epochs: usize,
    converged: bool,
    final_loss: f64,
    loss_history: Vec<f64>,
}

/// One aggregated preference: "document `positive` should out-rank document
/// `negative`", carrying the summed inverse-propensity weight of every logged
/// pair that said so.
#[derive(Debug, Clone, Copy)]
struct WeightedPair {
    positive: usize,
    negative: usize,
    weight: f64,
}

impl DebiasedRanker {
    /// A fresh, unfitted ranker.
    #[must_use]
    pub fn new(config: DebiasedRankerConfig) -> Self {
        Self {
            config,
            features: HashMap::new(),
            weights: Vec::new(),
            feature_dim: 0,
            fitted: false,
        }
    }

    /// The hyper-parameters this ranker fits with.
    #[must_use]
    pub fn config(&self) -> &DebiasedRankerConfig {
        &self.config
    }

    /// The fitted weight vector.
    #[must_use]
    pub fn weights(&self) -> &[f64] {
        &self.weights
    }

    /// The feature dimensionality established at fit time.
    #[must_use]
    pub fn feature_dim(&self) -> usize {
        self.feature_dim
    }

    /// Whether the ranker has been fitted.
    #[must_use]
    pub fn is_fitted(&self) -> bool {
        self.fitted
    }

    /// The learned score of a document, `w · x_d`. Unknown documents score `0`
    /// (they have no features, hence no evidence, hence no opinion).
    #[must_use]
    pub fn score_doc(&self, doc_id: &str) -> f64 {
        self.features.get(doc_id).map_or(0.0, |features| {
            features
                .iter()
                .zip(self.weights.iter())
                .map(|(feature, weight)| feature * weight)
                .sum()
        })
    }

    /// The learned scores of every document the ranker knows about.
    #[must_use]
    pub fn score_map(&self) -> HashMap<String, f64> {
        self.features
            .keys()
            .map(|doc_id| (doc_id.clone(), self.score_doc(doc_id)))
            .collect()
    }

    /// Rank a candidate list by learned score, best first. Ties break on the
    /// input order, so the result is deterministic.
    #[must_use]
    pub fn rank(&self, doc_ids: &[String]) -> Vec<String> {
        let mut ranked: Vec<(usize, &String)> = doc_ids.iter().enumerate().collect();
        ranked.sort_by(|&(left_index, left), &(right_index, right)| {
            self.score_doc(right)
                .total_cmp(&self.score_doc(left))
                .then_with(|| left_index.cmp(&right_index))
        });
        ranked
            .into_iter()
            .map(|(_, doc_id)| doc_id.clone())
            .collect()
    }

    /// Fit on **one-hot document-identity features**: one free score per
    /// document, with no generalisation between them.
    ///
    /// This is the purest possible test of the debiasing itself — the model has
    /// no features to hide behind, so whatever ordering it produces came from the
    /// propensity weighting and nothing else. It is also the right choice when
    /// the document set is small and fixed.
    ///
    /// # Errors
    ///
    /// [`ClickModelError::EmptyLog`], [`ClickModelError::InvalidConfig`], or
    /// [`ClickModelError::NoPreferencePairs`] — see [`DebiasedRanker::fit`].
    pub fn fit_tabular(
        &mut self,
        log: &ClickLog,
        propensities: &PropensityEstimates,
    ) -> ClickModelResult<DebiasedRankerFit> {
        let doc_ids = log.doc_ids();
        let dimension = doc_ids.len();
        let features: HashMap<String, Vec<f64>> = doc_ids
            .iter()
            .enumerate()
            .map(|(index, doc_id)| {
                let mut one_hot = vec![0.0_f64; dimension];
                one_hot[index] = 1.0;
                (doc_id.clone(), one_hot)
            })
            .collect();
        self.fit(log, propensities, &features)
    }

    /// Fit on caller-supplied per-document feature vectors.
    ///
    /// Every document in `log` must have a feature vector, and every vector must
    /// have the same non-zero dimension.
    ///
    /// # Errors
    ///
    /// - [`ClickModelError::EmptyLog`] for a log with no sessions.
    /// - [`ClickModelError::InvalidConfig`] if the hyper-parameters are unusable.
    /// - [`ClickModelError::UnknownDocument`] if `features` omits a document the
    ///   log contains.
    /// - [`ClickModelError::FeatureDimensionMismatch`] for a ragged or empty
    ///   feature vector.
    /// - [`ClickModelError::NoPreferencePairs`] if the log contains no session
    ///   with both a clicked and an unclicked document — there is then no
    ///   preference signal of any kind to learn from, and returning an untrained
    ///   zero vector would be a silent lie.
    pub fn fit(
        &mut self,
        log: &ClickLog,
        propensities: &PropensityEstimates,
        features: &HashMap<String, Vec<f64>>,
    ) -> ClickModelResult<DebiasedRankerFit> {
        self.config.validate()?;
        if log.is_empty() {
            return Err(ClickModelError::EmptyLog);
        }

        let doc_ids = log.doc_ids();
        let (matrix, doc_index) = Self::build_feature_matrix(&doc_ids, features)?;
        let feature_dim = matrix.first().map_or(0, Vec::len);
        let (pairs, total_pair_weight) = Self::build_weighted_pairs(log, propensities, &doc_index)?;
        let weight_sum: f64 = pairs.iter().map(|pair| pair.weight).sum();

        let descent = self.descend(&pairs, &matrix, weight_sum, feature_dim);

        self.features = doc_ids.iter().cloned().zip(matrix).collect();
        self.weights = descent.weights;
        self.feature_dim = feature_dim;
        self.fitted = true;

        let (epochs, converged, previous, history) = (
            descent.epochs,
            descent.converged,
            descent.final_loss,
            descent.loss_history,
        );

        Ok(DebiasedRankerFit {
            epochs,
            converged,
            final_loss: previous,
            loss_history: history,
            distinct_pair_count: pairs.len(),
            total_pair_weight,
        })
    }

    /// Lay the per-document feature vectors out as a matrix, indexed in the log's
    /// sorted document order so that every gradient accumulation happens in the
    /// same floating-point order on every run.
    fn build_feature_matrix<'a>(
        doc_ids: &'a [String],
        features: &HashMap<String, Vec<f64>>,
    ) -> ClickModelResult<FeatureMatrix<'a>> {
        let mut feature_dim = 0_usize;
        let mut matrix: Vec<Vec<f64>> = Vec::with_capacity(doc_ids.len());
        let mut doc_index: HashMap<&str, usize> = HashMap::with_capacity(doc_ids.len());

        for (index, doc_id) in doc_ids.iter().enumerate() {
            let vector = features
                .get(doc_id)
                .ok_or_else(|| ClickModelError::UnknownDocument {
                    doc_id: doc_id.clone(),
                })?;
            if index == 0 {
                feature_dim = vector.len();
                if feature_dim == 0 {
                    return Err(ClickModelError::FeatureDimensionMismatch {
                        doc_id: doc_id.clone(),
                        expected: 1,
                        actual: 0,
                    });
                }
            } else if vector.len() != feature_dim {
                return Err(ClickModelError::FeatureDimensionMismatch {
                    doc_id: doc_id.clone(),
                    expected: feature_dim,
                    actual: vector.len(),
                });
            }
            doc_index.insert(doc_id.as_str(), index);
            matrix.push(vector.clone());
        }
        Ok((matrix, doc_index))
    }

    /// Read every `(clicked, unclicked)` preference out of the log, weight each
    /// one by the **inverse propensity of the rank its click was observed at**,
    /// and aggregate duplicates.
    ///
    /// That weight is the crux of the whole module: a preference revealed by a
    /// click at rank `r` is itself only observable with probability `γ_r`, so
    /// dividing by `γ_r` exactly undoes the logging policy's choice of what we
    /// were allowed to see.
    fn build_weighted_pairs(
        log: &ClickLog,
        propensities: &PropensityEstimates,
        doc_index: &HashMap<&str, usize>,
    ) -> ClickModelResult<(Vec<WeightedPair>, f64)> {
        let mut aggregated: HashMap<(usize, usize), f64> = HashMap::new();
        let mut total_pair_weight = 0.0_f64;

        for session in log.sessions() {
            let clicked: Vec<usize> = (0..session.len())
                .filter(|&rank| session.clicks[rank])
                .collect();
            if clicked.is_empty() {
                continue;
            }
            let unclicked: Vec<usize> = (0..session.len())
                .filter(|&rank| !session.clicks[rank])
                .collect();
            if unclicked.is_empty() {
                continue;
            }
            for &positive_rank in &clicked {
                let weight = propensities.importance_weight(positive_rank);
                let Some(&positive) = doc_index.get(session.ranked_doc_ids[positive_rank].as_str())
                else {
                    continue;
                };
                for &negative_rank in &unclicked {
                    let Some(&negative) =
                        doc_index.get(session.ranked_doc_ids[negative_rank].as_str())
                    else {
                        continue;
                    };
                    *aggregated.entry((positive, negative)).or_insert(0.0) += weight;
                    total_pair_weight += weight;
                }
            }
        }

        if aggregated.is_empty() {
            return Err(ClickModelError::NoPreferencePairs);
        }

        // Sorted, so gradient accumulation is deterministic down to the last bit.
        let mut pairs: Vec<WeightedPair> = aggregated
            .into_iter()
            .map(|((positive, negative), weight)| WeightedPair {
                positive,
                negative,
                weight,
            })
            .collect();
        pairs.sort_by(|left, right| {
            left.positive
                .cmp(&right.positive)
                .then_with(|| left.negative.cmp(&right.negative))
        });
        Ok((pairs, total_pair_weight))
    }

    /// Full-batch gradient descent on the strictly convex, `L2`-regularised,
    /// weighted pairwise logistic loss.
    fn descend(
        &self,
        pairs: &[WeightedPair],
        matrix: &[Vec<f64>],
        weight_sum: f64,
        feature_dim: usize,
    ) -> DebiasedDescent {
        let l2 = self.config.l2_regularization;
        let mut weights = vec![0.0_f64; feature_dim];
        let mut previous = Self::loss(&weights, pairs, matrix, weight_sum, l2);
        let mut loss_history = vec![previous];
        let mut epochs = 0_usize;
        let mut converged = false;

        for _ in 0..self.config.epochs {
            let gradient = Self::gradient(&weights, pairs, matrix, weight_sum, l2);
            for (weight, component) in weights.iter_mut().zip(gradient.iter()) {
                *weight -= self.config.learning_rate * component;
            }
            epochs += 1;

            let current = Self::loss(&weights, pairs, matrix, weight_sum, l2);
            loss_history.push(current);
            let improvement = previous - current;
            previous = current;
            if improvement.abs() < self.config.tolerance {
                converged = true;
                break;
            }
        }

        DebiasedDescent {
            weights,
            epochs,
            converged,
            final_loss: previous,
            loss_history,
        }
    }

    /// `s = w · x` for one row of the feature matrix.
    fn score_row(weights: &[f64], row: &[f64]) -> f64 {
        weights
            .iter()
            .zip(row.iter())
            .map(|(weight, feature)| weight * feature)
            .sum()
    }

    /// The weight-normalised pairwise logistic loss plus the `L2` penalty.
    ///
    /// `ln(1 + exp(−Δ))` is evaluated as `ln1p(exp(−|Δ|)) + max(0, −Δ)`, which is
    /// the numerically stable form: no `exp` of a large positive number, ever.
    fn loss(
        weights: &[f64],
        pairs: &[WeightedPair],
        matrix: &[Vec<f64>],
        weight_sum: f64,
        l2: f64,
    ) -> f64 {
        let mut total = 0.0_f64;
        for pair in pairs {
            let margin = Self::score_row(weights, &matrix[pair.positive])
                - Self::score_row(weights, &matrix[pair.negative]);
            let stable = (-margin.abs()).exp().ln_1p() + (-margin).max(0.0);
            total += pair.weight * stable;
        }
        let penalty = 0.5 * l2 * weights.iter().map(|weight| weight * weight).sum::<f64>();
        if weight_sum > 0.0 {
            total / weight_sum + penalty
        } else {
            penalty
        }
    }

    /// `∇L`. The derivative of `ln(1 + e^{−Δ})` with respect to `Δ` is
    /// `−σ(−Δ)`, and `∂Δ/∂w = x⁺ − x⁻`.
    fn gradient(
        weights: &[f64],
        pairs: &[WeightedPair],
        matrix: &[Vec<f64>],
        weight_sum: f64,
        l2: f64,
    ) -> Vec<f64> {
        let dimension = weights.len();
        let mut gradient = vec![0.0_f64; dimension];
        for pair in pairs {
            let positive = &matrix[pair.positive];
            let negative = &matrix[pair.negative];
            let margin = Self::score_row(weights, positive) - Self::score_row(weights, negative);
            // σ(−Δ) = 1 / (1 + e^{Δ}), computed stably for either sign of Δ.
            let sigmoid_negative = if margin >= 0.0 {
                let exponential = (-margin).exp();
                exponential / (1.0 + exponential)
            } else {
                1.0 / (1.0 + margin.exp())
            };
            let scale = -pair.weight * sigmoid_negative;
            for index in 0..dimension {
                gradient[index] += scale * (positive[index] - negative[index]);
            }
        }
        if weight_sum > 0.0 {
            for component in &mut gradient {
                *component /= weight_sum;
            }
        }
        for (component, weight) in gradient.iter_mut().zip(weights.iter()) {
            *component += l2 * weight;
        }
        gradient
    }
}

impl ClickRankingPolicy for DebiasedRanker {
    /// The learned score. Features are per-document, so the score is
    /// query-independent; `query_id` is accepted to satisfy the trait and to
    /// leave the door open for query-conditioned features.
    fn score(&self, _query_id: &str, doc_id: &str) -> f64 {
        self.score_doc(doc_id)
    }
}
