//! `click_model` — click models fitted by Expectation-Maximisation, and
//! **counterfactual (propensity-weighted) learning to rank** built on top of
//! them.
//!
//! Every click your users make is a lie. Not a malicious one — a *positional*
//! one. A document at rank 1 is seen by almost everybody; a document at rank 9
//! is seen by almost nobody. Raw click-through rate cannot tell the difference
//! between "this document is good" and "this document was standing in a
//! well-lit place", so a ranker trained on raw clicks converges to whatever the
//! ranker that produced the log already believed. That feedback loop is one of
//! the most expensive failure modes in production retrieval, and it is what this
//! module exists to break.
//!
//! The cure has two halves, and this module implements both:
//!
//! 1. **Model the bias.** Fit a generative model of *how clicks arise* — a click
//!    model — whose latent structure separates `examination` (a property of the
//!    rank) from `attractiveness` (a property of the document). Three models are
//!    provided, all fitted by EM: [`PositionBasedModel`], [`CascadeClickModel`]
//!    and [`DbnClickModel`].
//! 2. **Divide it out.** The fitted examination probability at rank `r` *is* the
//!    **propensity** `γ_r`: the probability an item there was even given a chance
//!    to be clicked. Weighting each observed click by `1/γ_r` recovers an
//!    unbiased estimate of relevance from systematically biased data — the
//!    Horvitz–Thompson trick. That gives off-policy evaluation
//!    ([`IpsEstimator`], [`SnipsEstimator`], [`DoublyRobustEstimator`]) and
//!    unbiased training ([`DebiasedRanker`]).
//!
//! # How this differs from `learning_to_rank`
//!
//! [`crate::learning_to_rank`] is this module's **supervised, offline**
//! counterpart, and the contrast is the whole point:
//!
//! | | [`learning_to_rank`](crate::learning_to_rank) | `click_model` (this module) |
//! |---|---|---|
//! | **Supervision** | explicit, human-assigned preference labels (`LtrTrainingPair::preferred`) | *implicit*, machine-collected clicks — no labels anywhere |
//! | **Is the data biased?** | no — a labeller reads both documents | **yes, systematically** — the logging policy decided what got seen |
//! | **Latent variables** | none | examination, attractiveness, satisfaction — none of them observed |
//! | **How it is fitted** | gradient descent on a labelled pairwise loss | Expectation-Maximisation over latent examination |
//! | **What it corrects for** | nothing; it trusts its labels | position bias, by inverse-propensity weighting |
//! | **What it can answer** | "which of these two documents did the annotator prefer?" | "how would a ranking I have *never deployed* have performed?" |
//!
//! `learning_to_rank` has no notion of examination probability, propensity, or
//! bias, and it cannot have one: its labels are already unbiased by construction.
//! This module never sees a label at all. Hand it a click log — the exhaust of a
//! system already running — and it recovers what the labels *would have said*.
//! The two are complements, not competitors: use `learning_to_rank` when you can
//! afford annotators, and `click_model` when you cannot.
//!
//! # The three click models
//!
//! | Model | Examination is… | Latent | Fitted by |
//! |---|---|---|---|
//! | [`PositionBasedModel`] | an independent coin flip per rank, `γ_r` | `E`, `A` | genuine EM (Bayes E-step, posterior-mean M-step) |
//! | [`CascadeClickModel`] | *deterministic*: everything down to the first click | — | closed-form MLE (the examined set is observed, so EM finishes in one step) |
//! | [`DbnClickModel`] | a Markov chain: click → maybe satisfied → leave; else persist with `γ` | `S`, and the tail below the last click | EM with a forward/backward recursion |
//!
//! Each model's own module documentation ([`pbm`], [`cascade`], [`dbn`]) derives
//! its E-step and M-step in full. They are not summaries — they are the
//! derivations the code was written from, and they are worth reading before
//! trusting any number this module produces.
//!
//! # The correctness invariant: EM goes uphill, always
//!
//! Expectation-Maximisation guarantees that the observed-data log-likelihood is
//! **monotone non-decreasing** at every iteration. That is not a hope; it is a
//! theorem, and it makes an unusually sharp test: *if the log-likelihood ever
//! goes down, the E-step or the M-step is wrong.* Every fit returns its complete
//! log-likelihood trace ([`ClickModelFit::log_likelihood_history`]), every model
//! is tested against [`ClickModelFit::is_monotone`], and the tests recover known
//! ground-truth parameters from synthetic logs generated by
//! [`ClickLogSimulator`] — because a click model that fits a real log
//! beautifully and estimates the wrong `γ` looks exactly like one that works.
//!
//! # Identifiability, stated up front
//!
//! The PBM likelihood depends on `γ_r` and `α_d` **only through their product**.
//! Scale all examinations up by `c`, all attractivenesses down by `c`, and no
//! amount of data can tell the difference. The model is therefore identified
//! only up to one global scale, which is pinned by anchoring `γ₀ = 1` (the top
//! result is always examined) — see
//! [`ClickModelConfig::anchor_top_examination`].
//!
//! The deeper consequence is operational, and it is the single most important
//! practical fact in this module: **a logging policy that always shows the same
//! document at the same rank cannot identify propensities at all.** There is no
//! information in such a log about which of "seen rarely" and "not very good"
//! explains a low click rate. Real unbiased-LTR deployments solve this by
//! injecting a slice of randomised or swapped traffic, and
//! [`ClickLogSimulator::simulate_rankings`] exists to model exactly that.
//! [`PositionBasedModel::identifiability`] reports, per rank and per document,
//! which parameters your log actually determined — rather than quietly handing
//! back a number that came from the initialisation.
//!
//! # Quick start: the bias, and its cure
//!
//! ```
//! # #[cfg(feature = "click-model")]
//! # {
//! use oxirag::click_model::{
//!     ClickLogSimulator, ClickModel, ClickModelConfig, ClickRankingPolicy,
//!     ClickSimulationModel, DebiasedRanker, DebiasedRankerConfig, PositionBasedModel,
//!     PropensityEstimates, naive_click_through_rates,
//! };
//!
//! // Ground truth: "excellent" is three times as attractive as "mediocre".
//! // But the production ranker shows "mediocre" first and buries "excellent",
//! // and only 10% of traffic gets a randomised ordering.
//! let docs = vec!["mediocre".to_owned(), "filler".to_owned(), "excellent".to_owned()];
//! let mut rankings = Vec::new();
//! for index in 0..6_000 {
//!     rankings.push(match index % 20 {
//!         18 => vec!["excellent".to_owned(), "mediocre".to_owned(), "filler".to_owned()],
//!         19 => vec!["filler".to_owned(), "excellent".to_owned(), "mediocre".to_owned()],
//!         _ => docs.clone(),
//!     });
//! }
//! let log = ClickLogSimulator::new(docs)
//!     .with_attractiveness(vec![0.3, 0.15, 0.9])   // mediocre, filler, excellent
//!     .with_examination(vec![1.0, 0.4, 0.1])       // a steep examination curve
//!     .with_seed(2_024)
//!     .simulate_rankings(ClickSimulationModel::PositionBased, &rankings)
//!     .expect("valid simulation");
//!
//! // 1. The naive view is fooled — decisively.
//! let ctr = naive_click_through_rates(&log);
//! assert!(ctr["mediocre"] > ctr["excellent"]);
//!
//! // 2. Fit a PBM: it recovers the examination curve from the randomised slice.
//! let mut pbm = PositionBasedModel::new(ClickModelConfig::default().with_max_iterations(300));
//! pbm.fit(&log).expect("fit succeeds");
//! assert!(pbm.identifiability().expect("fitted").fully_identified);
//! assert!((pbm.examination_curve()[2] - 0.1).abs() < 0.03);
//!
//! // 3. Debias with those propensities, and the true order comes back.
//! let propensities = PropensityEstimates::from_click_model(&pbm, 0.01).expect("usable");
//! let mut ranker = DebiasedRanker::new(DebiasedRankerConfig::default());
//! ranker.fit_tabular(&log, &propensities).expect("fit succeeds");
//! assert!(ranker.score("q0", "excellent") > ranker.score("q0", "mediocre"));
//! # }
//! ```
//!
//! # What is *not* here
//!
//! No neural click model, no query-conditioned attractiveness (`α` is keyed by
//! document, not by `(query, document)`), and no online interventional
//! randomisation policy. The estimators evaluate policies over the documents a
//! session actually logged; they do not extrapolate to documents the logging
//! policy never showed, because nothing in a click log licenses that.

pub mod cascade;
pub mod counterfactual;
pub mod dbn;
pub mod debias;
pub mod pbm;
pub mod synthetic;
pub mod types;

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests;
#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests_counterfactual;

pub use cascade::{CascadeClickModel, cascade_examined_depth};
pub use counterfactual::{
    ClickRankingPolicy, ClickRewardModel, CounterfactualEstimate, CounterfactualEstimator,
    CounterfactualStrategy, DoublyRobustEstimator, IpsEstimator, PropensityEstimates,
    SnipsEstimator, TableClickPolicy, naive_click_through_rates, policy_positions,
};
pub use dbn::DbnClickModel;
pub use debias::{DebiasedRanker, DebiasedRankerConfig, DebiasedRankerFit};
pub use pbm::{PbmIdentifiability, PositionBasedModel};
pub use synthetic::{ClickLogSimulator, ClickSimulationModel, ClickSplitMix64};
pub use types::{
    ClickImpression, ClickLog, ClickModel, ClickModelConfig, ClickModelError, ClickModelFit,
    ClickModelResult, ClickSession, position_gain,
};
