//! Integration tests: generate Rust server/client stubs from a `.proto` file
//! via `ServiceCodegen`, write them to a temp dir with a synthesized
//! `Cargo.toml`, and run `cargo check` to assert the generated code compiles.
//!
//! These tests are marked `#[ignore]` by default because they spawn a child
//! `cargo check` process which is slow for CI.  Run them explicitly with:
//!
//! ```text
//! cargo test -p oxirpc-build --test compile_link -- --ignored
//! ```

use oxirpc_build::codegen::ServiceCodegen;
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

// ---------------------------------------------------------------------------
// Constants / helper: proto fixture path
// ---------------------------------------------------------------------------

/// Absolute path to the greeter.proto fixture file.
fn greeter_proto_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("greeter.proto")
}

/// Absolute path to the fixtures directory (acts as the proto include dir).
fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

// ---------------------------------------------------------------------------
// Workspace root helpers
// ---------------------------------------------------------------------------

/// Returns the absolute path to the oxirpc workspace root.
///
/// `CARGO_MANIFEST_DIR` for this crate is `.../crates/oxirpc-build`, so
/// walking two parents gives `.../` (the workspace root).
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates dir exists")
        .parent()
        .expect("workspace root exists")
        .to_path_buf()
}

fn oxirpc_core_path() -> PathBuf {
    workspace_root().join("crates").join("oxirpc-core")
}

// ---------------------------------------------------------------------------
// Temp-dir helpers
// ---------------------------------------------------------------------------

/// Create a unique temp subdirectory for a test run.
fn make_temp_dir(tag: &str) -> PathBuf {
    let base = std::env::temp_dir().join(format!(
        "oxirpc_compile_link_{}_{}_{}",
        std::process::id(),
        tag,
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0),
    ));
    fs::create_dir_all(&base).expect("create temp dir");
    base
}

/// Remove a temp directory, ignoring errors (best-effort cleanup).
fn cleanup(dir: &Path) {
    let _ = fs::remove_dir_all(dir);
}

// ---------------------------------------------------------------------------
// Code synthesis helpers
// ---------------------------------------------------------------------------

/// Parse greeter.proto and generate Rust service stub code with the given
/// `ServiceCodegen` configuration.  Returns the generated source string.
fn generate_greeter_code(codegen: &ServiceCodegen) -> String {
    let proto = greeter_proto_path();
    let inc = fixtures_dir();

    let fds = protox::compile([&proto], [&inc]).expect("protox compile greeter.proto");
    assert_eq!(fds.file.len(), 1, "expected exactly one file descriptor");
    codegen.generate(&fds.file[0])
}

/// Build the `lib.rs` content for the synthesized crate.
///
/// The generated service stubs reference `super::HelloRequest` /
/// `super::HelloReply`.  Because `ServiceCodegen` does not generate prost
/// message types (only service stubs), we provide them as hand-written prost
/// structs inside the wrapper module — they live one level above the generated
/// `greeter_server` / `greeter_client` inner modules, so `super::` resolves
/// correctly.
fn make_lib_rs(service_code: &str) -> String {
    format!(
        r#"// Auto-generated by oxirpc compile_link integration test.
#![allow(dead_code, unused_variables, unused_imports, clippy::all)]

/// Wrapper module containing prost message types and generated service stubs.
pub mod greeter_generated {{
    // Message types that the service stubs reference via `super::`.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct HelloRequest {{
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
    }}

    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct HelloReply {{
        #[prost(string, tag = "1")]
        pub message: ::prost::alloc::string::String,
    }}

    // Generated service stubs (references super::HelloRequest / super::HelloReply).
{service_code}
}}
"#,
    )
}

// ---------------------------------------------------------------------------
// cargo check runner
// ---------------------------------------------------------------------------

/// Write a minimal Rust crate to `temp_dir`, run `cargo check` on it,
/// and assert it succeeds.  Cleans up the directory on success; leaves it
/// for debugging on failure.
fn run_cargo_check(temp_dir: &Path, service_code: &str) {
    let lib_rs = make_lib_rs(service_code);
    let src_dir = temp_dir.join("src");
    fs::create_dir_all(&src_dir).expect("create src dir");
    fs::write(src_dir.join("lib.rs"), &lib_rs).expect("write lib.rs");

    // NOTE: `[target-dir] path = ...` is not a valid TOML key in standard
    // Cargo.toml — use CARGO_TARGET_DIR env var instead to isolate the target.
    let cargo_target_dir = temp_dir.join("target");

    let cargo_toml = format!(
        r#"[workspace]

[package]
name = "oxirpc-codegen-verify"
version = "0.0.0"
edition = "2021"

[dependencies]
oxirpc-core = {{ path = "{core}" }}
tonic        = {{ version = "0.14", default-features = false, features = ["transport", "codegen", "server", "channel"] }}
tonic-prost  = {{ version = "0.14" }}
prost        = {{ version = "0.14" }}
http         = {{ version = "1" }}
bytes        = {{ version = "1" }}
async-trait  = {{ version = "0.1" }}
tokio        = {{ version = "1", features = ["full"] }}
"#,
        core = oxirpc_core_path().display(),
    );
    fs::write(temp_dir.join("Cargo.toml"), &cargo_toml).expect("write Cargo.toml");

    let output = Command::new(env!("CARGO"))
        .arg("check")
        .arg("--quiet")
        .current_dir(temp_dir)
        .env("CARGO_TARGET_DIR", &cargo_target_dir)
        // Ensure the child cargo does not inherit the parent's workspace lock.
        .env_remove("CARGO_HOME")
        .output()
        .expect("failed to spawn cargo check");

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "cargo check failed in {}:\n\nstdout:\n{}\n\nstderr:\n{}\n\nlib.rs:\n{}",
            temp_dir.display(),
            stdout,
            stderr,
            lib_rs,
        );
    }

    cleanup(temp_dir);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Full (server + client) stub generation compiles successfully.
#[test]
#[ignore]
fn test_generated_code_compiles() {
    let codegen = ServiceCodegen::new();
    let code = generate_greeter_code(&codegen);

    let temp_dir = make_temp_dir("full");
    run_cargo_check(&temp_dir, &code);
}

/// Server-only generation (no client stubs) compiles successfully.
#[test]
#[ignore]
fn test_generated_code_with_server_only() {
    let codegen = ServiceCodegen {
        emit_client: false,
        emit_server: true,
        ..ServiceCodegen::new()
    };
    let code = generate_greeter_code(&codegen);

    let temp_dir = make_temp_dir("server_only");
    run_cargo_check(&temp_dir, &code);
}

/// Client-only generation (no server stubs) compiles successfully.
#[test]
#[ignore]
fn test_generated_code_with_client_only() {
    let codegen = ServiceCodegen {
        emit_client: true,
        emit_server: false,
        ..ServiceCodegen::new()
    };
    let code = generate_greeter_code(&codegen);

    let temp_dir = make_temp_dir("client_only");
    run_cargo_check(&temp_dir, &code);
}

/// Verify that `Builder::compile()` with the native backend writes a
/// `.services.rs` file whose content compiles under `cargo check`.
///
/// This test exercises the full `Builder` → `ServiceCodegen` pipeline,
/// confirming that `Builder::compile()` correctly routes through the native
/// path (no `legacy-tonic-codegen` feature required).
#[test]
#[ignore]
fn compile_link_via_native_codegen() {
    let proto = greeter_proto_path();
    let inc = fixtures_dir();

    // Write the service stubs via Builder::compile() (native path).
    let out_dir = make_temp_dir("native_codegen_builder");
    let build_result = oxirpc_build::Builder::new()
        .build_client(true)
        .build_server(true)
        .out_dir(&out_dir)
        .compile(&[&proto], &[&inc]);

    assert!(
        build_result.is_ok(),
        "Builder::compile() (native path) must succeed; got: {:?}",
        build_result.err()
    );

    // Read the generated service stubs file.
    let services_file = out_dir.join("greeter.services.rs");
    assert!(
        services_file.exists(),
        "expected greeter.services.rs in {out_dir:?}"
    );
    let service_code = fs::read_to_string(&services_file).expect("read greeter.services.rs");

    // Sanity: both server and client modules present.
    assert!(
        service_code.contains("pub mod greeter_server"),
        "native codegen must emit greeter_server"
    );
    assert!(
        service_code.contains("pub mod greeter_client"),
        "native codegen must emit greeter_client"
    );

    // Run cargo check on the generated code.
    run_cargo_check(&out_dir, &service_code);
}
