//! Integration test: `ServiceCodegen`-generated stubs compose with
//! `NativeHealthService` inside a `NativeServiceRegistry`.
//!
//! Follows the `compile_link.rs` pattern:
//! 1. Write a minimal `.proto` to a temp dir.
//! 2. Run `oxirpc_build::Builder::compile()` to generate stubs into the same
//!    temp dir.
//! 3. Synthesise a minimal Cargo project that:
//!    - hand-writes the prost message types (codegen emits stubs only),
//!    - provides a trivial `impl` of the generated service trait,
//!    - constructs a `NativeServiceRegistry` and registers both the generated
//!      service wrapper **and** `NativeHealthService`.
//! 4. Runs `cargo check` on the synthesised project and asserts exit code 0.
//!
//! The test is `#[ignore]` because it spawns a child `cargo check` process.
//! Run explicitly with:
//! ```text
//! cargo test -p oxirpc-build --test health_integration -- --ignored
//! ```

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

// ─────────────────────────────────────────────────────────────────────────────
// Workspace root helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Returns the absolute path to the oxirpc workspace root.
///
/// `CARGO_MANIFEST_DIR` for this crate is `.../crates/oxirpc-build`, so
/// walking two parents gives `.../` (the workspace root).
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates dir exists")
        .parent()
        .expect("workspace root exists")
        .to_path_buf()
}

fn oxirpc_core_path() -> PathBuf {
    workspace_root().join("crates").join("oxirpc-core")
}

fn oxirpc_health_path() -> PathBuf {
    workspace_root().join("crates").join("oxirpc-health")
}

fn oxirpc_server_path() -> PathBuf {
    workspace_root().join("crates").join("oxirpc-server")
}

// ─────────────────────────────────────────────────────────────────────────────
// Temp-dir helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Create a unique temp subdirectory for a test run.
fn make_temp_dir(tag: &str) -> PathBuf {
    let base = std::env::temp_dir().join(format!(
        "oxirpc_health_integ_{}_{}_{}",
        std::process::id(),
        tag,
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0),
    ));
    fs::create_dir_all(&base).expect("create temp dir");
    base
}

/// Remove a temp directory, ignoring errors (best-effort cleanup).
fn cleanup(dir: &Path) {
    let _ = fs::remove_dir_all(dir);
}

// ─────────────────────────────────────────────────────────────────────────────
// Proto content
// ─────────────────────────────────────────────────────────────────────────────

/// Minimal `.proto` with a single unary service — enough to exercise the
/// `ServiceCodegen` path while keeping the required trait `impl` trivial.
const HEALTH_INTEG_PROTO: &str = r#"syntax = "proto3";
package healthinteg;

message PingRequest  { string msg = 1; }
message PingResponse { string msg = 1; }

service PingService {
  rpc Ping(PingRequest) returns (PingResponse);
}
"#;

// ─────────────────────────────────────────────────────────────────────────────
// Synthesised crate source
// ─────────────────────────────────────────────────────────────────────────────

/// Build the `main.rs` for the synthesised verification crate.
///
/// The generated service stubs reference `super::PingRequest` / `super::PingResponse`
/// via `type_path = "super"` (the default).  We hand-write those prost message
/// types at the `healthinteg_generated` module level so `super::` resolves
/// correctly.
///
/// The test then constructs a `NativeServiceRegistry<tonic::body::Body>` and
/// registers both the generated `PingServiceServer<ImplPing>` and
/// `NativeHealthService` — proving they compose.
fn make_main_rs(service_code: &str) -> String {
    format!(
        r#"// Auto-generated by oxirpc health_integration test.
#![allow(dead_code, unused_variables, unused_imports, clippy::all)]

pub mod healthinteg_generated {{
    // ── Prost message types (service stubs reference these via `super::`) ──
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PingRequest {{
        #[prost(string, tag = "1")]
        pub msg: ::prost::alloc::string::String,
    }}

    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PingResponse {{
        #[prost(string, tag = "1")]
        pub msg: ::prost::alloc::string::String,
    }}

    // ── Generated service stubs (server + client) ──
{service_code}

    // ── Trivial service implementation ──
    //
    // A zero-dependency impl so we can construct a PingServiceServer<ImplPing>
    // and pass it to NativeServiceRegistry::add_service.  The body is never
    // called; we only need it to type-check.
    pub struct ImplPing;

    #[tonic::async_trait]
    impl ping_service_server::PingService for ImplPing {{
        async fn ping(
            &self,
            _req: oxirpc_core::Request<PingRequest>,
        ) -> std::result::Result<oxirpc_core::Response<PingResponse>, oxirpc_core::Status> {{
            Ok(oxirpc_core::Response::new(PingResponse {{ msg: "pong".into() }}))
        }}
    }}
}}

fn main() {{
    use healthinteg_generated::{{ping_service_server::PingServiceServer, ImplPing}};
    use oxirpc_health::NativeHealthService;
    use oxirpc_server::native_registry::NativeServiceRegistry;

    // Both services are registered in a single NativeServiceRegistry — proving
    // that ServiceCodegen-generated stubs compose with NativeHealthService.
    let registry: NativeServiceRegistry<tonic::body::Body> = NativeServiceRegistry::new()
        .add_service(PingServiceServer::new(ImplPing))
        .add_service(NativeHealthService::default());

    // Verify both names are present (compile-time composition proof).
    let names: Vec<_> = registry.names().collect();
    assert!(
        names.contains(&"healthinteg.PingService"),
        "PingService not registered"
    );
    assert!(
        names.contains(&"grpc.health.v1.Health"),
        "NativeHealthService not registered"
    );
}}
"#,
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// cargo check runner
// ─────────────────────────────────────────────────────────────────────────────

/// Write a minimal Rust crate to `temp_dir`, run `cargo check` on it,
/// and assert it succeeds.  Cleans up the directory on success; leaves it
/// for debugging on failure.
fn run_cargo_check(temp_dir: &Path, service_code: &str) {
    let main_rs = make_main_rs(service_code);
    let src_dir = temp_dir.join("src");
    fs::create_dir_all(&src_dir).expect("create src dir");
    fs::write(src_dir.join("main.rs"), &main_rs).expect("write main.rs");

    let cargo_target_dir = temp_dir.join("target");

    let cargo_toml = format!(
        r#"[workspace]

[package]
name    = "oxirpc-health-integ-verify"
version = "0.0.0"
edition = "2021"

[dependencies]
oxirpc-core   = {{ path = "{core}" }}
oxirpc-health = {{ path = "{health}" }}
oxirpc-server = {{ path = "{server}", features = ["native"] }}
tonic         = {{ version = "0.14", default-features = false, features = ["transport", "codegen", "server", "channel"] }}
tonic-prost   = {{ version = "0.14" }}
prost         = {{ version = "0.14" }}
http          = {{ version = "1" }}
bytes         = {{ version = "1" }}
async-trait   = {{ version = "0.1" }}
tokio         = {{ version = "1", features = ["full"] }}
"#,
        core = oxirpc_core_path().display(),
        health = oxirpc_health_path().display(),
        server = oxirpc_server_path().display(),
    );
    fs::write(temp_dir.join("Cargo.toml"), &cargo_toml).expect("write Cargo.toml");

    let output = Command::new(env!("CARGO"))
        .arg("check")
        .arg("--quiet")
        .current_dir(temp_dir)
        .env("CARGO_TARGET_DIR", &cargo_target_dir)
        // Ensure the child cargo does not inherit the parent workspace lock.
        .env_remove("CARGO_HOME")
        .output()
        .expect("failed to spawn cargo check");

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "cargo check failed in {}:\n\nstdout:\n{}\n\nstderr:\n{}\n\nmain.rs:\n{}",
            temp_dir.display(),
            stdout,
            stderr,
            main_rs,
        );
    }

    cleanup(temp_dir);
}

// ─────────────────────────────────────────────────────────────────────────────
// Test
// ─────────────────────────────────────────────────────────────────────────────

/// Prove that a `ServiceCodegen`-generated server stub composes with
/// `NativeHealthService` inside a `NativeServiceRegistry`.
///
/// Uses the `compile_link.rs` pattern:
/// 1. Write a tiny proto to temp dir.
/// 2. Builder::compile() → generate `.services.rs` stubs.
/// 3. Synthesise a crate that registers both services in a registry.
/// 4. Run `cargo check`; assert exit code 0.
#[test]
#[ignore]
fn generated_service_composes_with_health_registry() {
    // 1. Create a temp dir and write the proto.
    let temp_dir = make_temp_dir("health_compose");
    let proto_file = temp_dir.join("healthinteg.proto");
    fs::write(&proto_file, HEALTH_INTEG_PROTO).expect("write proto file");

    // 2. Compile the proto via Builder — generates stubs into temp_dir.
    let build_result = oxirpc_build::Builder::new()
        .build_client(true)
        .build_server(true)
        .out_dir(&temp_dir)
        .compile(&[&proto_file], &[&temp_dir]);

    assert!(
        build_result.is_ok(),
        "Builder::compile() must succeed; got: {:?}",
        build_result.err()
    );

    // 3. Read the generated service stubs.
    let services_file = temp_dir.join("healthinteg.services.rs");
    assert!(
        services_file.exists(),
        "expected healthinteg.services.rs in {temp_dir:?}"
    );
    let service_code = fs::read_to_string(&services_file).expect("read healthinteg.services.rs");

    // Sanity: both server and client modules are present.
    assert!(
        service_code.contains("pub mod ping_service_server"),
        "native codegen must emit ping_service_server"
    );
    assert!(
        service_code.contains("pub mod ping_service_client"),
        "native codegen must emit ping_service_client"
    );

    // 4. Run cargo check on the synthesised crate.
    run_cargo_check(&temp_dir, &service_code);
}
