//! Container deployment management for TrustformeRS C API
//!
//! This module handles the deployment logic for containers across different
//! orchestration platforms including Docker Swarm, Kubernetes, and cloud services.

use super::types::*;
use crate::error::{TrustformersError, TrustformersResult};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Container deployment manager
#[derive(Debug, Clone)]
pub struct ContainerDeploymentManager {
    /// Deployment configuration
    pub config: ContainerDeploymentConfig,
}

/// Deployment artifacts generated by the manager
pub type DeploymentArtifacts = HashMap<String, String>;

/// Deployment status information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentStatus {
    /// Deployment phase
    pub phase: DeploymentPhase,
    /// Status message
    pub message: String,
    /// Ready replicas
    pub ready_replicas: u32,
    /// Total replicas
    pub total_replicas: u32,
    /// Last update time
    pub last_update: String,
}

/// Deployment phases
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DeploymentPhase {
    Pending,
    Running,
    Succeeded,
    Failed,
    Unknown,
}

impl ContainerDeploymentManager {
    /// Create new container deployment manager
    pub fn new(config: ContainerDeploymentConfig) -> Self {
        Self { config }
    }

    /// Generate deployment artifacts
    pub fn generate_deployment_artifacts(&self) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate Docker image configuration by converting the simple, C-API-facing
        // `types::DockerImageConfig` into the rich `docker::DockerImageConfig` consumed by
        // `DockerImageBuilder`, so that build_args/env_vars/ports/volumes actually flow
        // through into the generated artifacts instead of being silently dropped.
        let docker_builder_config = self.to_docker_builder_config(&self.config.image_config);
        let docker_builder = super::docker::DockerImageBuilder::new(docker_builder_config);

        let dockerfile = docker_builder.generate_dockerfile()?;
        artifacts.insert("Dockerfile".to_string(), dockerfile);

        let docker_compose = docker_builder.generate_docker_compose(&self.config.app_name)?;
        artifacts.insert("docker-compose.yml".to_string(), docker_compose);

        // Generate .dockerignore
        artifacts.insert(
            ".dockerignore".to_string(),
            docker_builder.generate_dockerignore(),
        );

        // Generate build.sh
        artifacts.insert(
            "build.sh".to_string(),
            docker_builder.generate_build_script(),
        );

        // Generate orchestration-specific artifacts
        match &self.config.orchestration {
            OrchestrationConfig::DockerSwarm(swarm_config) => {
                artifacts.extend(self.generate_swarm_artifacts(swarm_config)?);
            },
            OrchestrationConfig::ECS(ecs_config) => {
                artifacts.extend(self.generate_ecs_artifacts(ecs_config)?);
            },
            OrchestrationConfig::CloudRun(cloudrun_config) => {
                artifacts.extend(self.generate_cloudrun_artifacts(cloudrun_config)?);
            },
            OrchestrationConfig::ACI(aci_config) => {
                artifacts.extend(self.generate_aci_artifacts(aci_config)?);
            },
            OrchestrationConfig::OpenShift(openshift_config) => {
                artifacts.extend(self.generate_openshift_artifacts(openshift_config)?);
            },
        }

        // Generate monitoring artifacts if enabled
        if self.config.monitoring.enabled {
            artifacts.extend(self.generate_monitoring_artifacts()?);
        }

        // Generate security artifacts
        artifacts.extend(self.generate_security_artifacts()?);

        Ok(artifacts)
    }

    /// Convert the simple, C-API-facing `types::DockerImageConfig` (a flat struct with a
    /// plain-string base image plus build args/env vars maps, exposed ports and volume
    /// mounts) into the richer `docker::DockerImageConfig` that `DockerImageBuilder`
    /// actually consumes.
    ///
    /// `base_image`, `build_args`, `env_vars`, `exposed_ports` and `volumes` all have a
    /// direct source field on `image_config` and are mapped faithfully below - this is the
    /// data that previously never reached the generated artifacts. Every other field on the
    /// richer output config (multi-stage/target arch, resource limits, user, entrypoint,
    /// security/optimization flags, health check) has no corresponding source field
    /// anywhere reachable from `ContainerDeploymentConfig`, so it is filled with a
    /// sensible, secure-by-default value instead (multi-stage build, AMD64 target, `/app`
    /// workdir, non-root user named after the app, no health check).
    fn to_docker_builder_config(
        &self,
        image_config: &super::types::DockerImageConfig,
    ) -> super::docker::DockerImageConfig {
        let volumes = image_config
            .volumes
            .iter()
            .map(|volume_mount| super::docker::VolumeMount {
                // `docker::VolumeMount` has no field for the host-side `source` path, only
                // the in-container mount point - which is also the only half of the pair
                // that actually matters to the generated Dockerfile `VOLUME` instruction
                // and docker-compose volume entries, so `source` is intentionally dropped.
                path: volume_mount.target.clone(),
                // `Bind` is the closest match for a mount that was described with an
                // explicit host source/container target pair (as opposed to an anonymous
                // named `Volume` or an in-memory `Tmpfs` mount, neither of which fits a
                // config that was given a concrete `source` path).
                mount_type: super::docker::MountType::Bind,
                read_only: volume_mount.read_only,
            })
            .collect();

        super::docker::DockerImageConfig {
            base_image: super::docker::BaseImage::Custom(image_config.base_image.clone()),
            build_config: super::docker::BuildConfig {
                multi_stage: true,
                target_arch: super::docker::TargetArchitecture::AMD64,
                build_args: image_config.build_args.clone(),
                env_vars: image_config.env_vars.clone(),
                workdir: "/app".to_string(),
                build_dependencies: Vec::new(),
                runtime_dependencies: Vec::new(),
            },
            runtime_config: super::docker::RuntimeConfig {
                ports: image_config.exposed_ports.clone(),
                volumes,
                resources: super::docker::ResourceLimits {
                    memory: None,
                    cpu: None,
                    swap: None,
                    pids: None,
                },
                user: super::docker::UserConfig {
                    uid: 1000,
                    gid: 1000,
                    username: Some(self.config.app_name.clone()),
                    groupname: Some(self.config.app_name.clone()),
                },
                entrypoint: super::docker::EntrypointConfig {
                    command: vec![format!("/usr/local/bin/{}", self.config.app_name)],
                    args: Vec::new(),
                    signal_handling: true,
                },
            },
            security_config: super::docker::SecurityConfig {
                non_root: true,
                read_only_root: false,
                security_opts: Vec::new(),
                drop_capabilities: Vec::new(),
                add_capabilities: Vec::new(),
                security_profile: None,
            },
            optimization: super::docker::OptimizationConfig {
                layer_caching: true,
                minimize_layers: true,
                strip_debug: false,
                compress_binary: false,
                clean_package_cache: true,
                remove_dev_tools: false,
                enable_scanning: false,
            },
            health_check: None,
        }
    }

    /// Generate Docker Swarm specific artifacts
    fn generate_swarm_artifacts(
        &self,
        swarm_config: &DockerSwarmConfig,
    ) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate Docker Stack file
        let stack_content = self.generate_swarm_stack_file(swarm_config)?;
        artifacts.insert("docker-stack.yml".to_string(), stack_content);

        // Generate deployment script
        let deploy_script = self.generate_swarm_deploy_script(swarm_config);
        artifacts.insert("deploy-swarm.sh".to_string(), deploy_script);

        // Generate service configuration
        let service_config = self.generate_swarm_service_config(swarm_config)?;
        artifacts.insert("service-config.yml".to_string(), service_config);

        Ok(artifacts)
    }

    /// Generate ECS specific artifacts
    fn generate_ecs_artifacts(
        &self,
        ecs_config: &ECSConfig,
    ) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate task definition
        let task_definition = self.generate_ecs_task_definition(ecs_config)?;
        artifacts.insert("task-definition.json".to_string(), task_definition);

        // Generate service definition
        let service_definition = self.generate_ecs_service_definition(ecs_config)?;
        artifacts.insert("service-definition.json".to_string(), service_definition);

        // Generate CloudFormation template
        let cloudformation_template = self.generate_ecs_cloudformation_template(ecs_config)?;
        artifacts.insert(
            "cloudformation-template.yml".to_string(),
            cloudformation_template,
        );

        // Generate deployment script
        let deploy_script = self.generate_ecs_deploy_script(ecs_config);
        artifacts.insert("deploy-ecs.sh".to_string(), deploy_script);

        Ok(artifacts)
    }

    /// Generate Cloud Run specific artifacts
    fn generate_cloudrun_artifacts(
        &self,
        cloudrun_config: &CloudRunConfig,
    ) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate service YAML
        let service_yaml = self.generate_cloudrun_service_yaml(cloudrun_config)?;
        artifacts.insert("service.yaml".to_string(), service_yaml);

        // Generate deployment script
        let deploy_script = self.generate_cloudrun_deploy_script(cloudrun_config);
        artifacts.insert("deploy-cloudrun.sh".to_string(), deploy_script);

        // Generate Cloud Build configuration
        let cloudbuild_config = self.generate_cloudbuild_config(cloudrun_config)?;
        artifacts.insert("cloudbuild.yaml".to_string(), cloudbuild_config);

        Ok(artifacts)
    }

    /// Generate monitoring artifacts
    fn generate_monitoring_artifacts(&self) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate Prometheus configuration
        let prometheus_config = self.generate_prometheus_config()?;
        artifacts.insert("monitoring/prometheus.yml".to_string(), prometheus_config);

        // Generate Grafana dashboard
        let grafana_dashboard = self.generate_grafana_dashboard()?;
        artifacts.insert(
            "monitoring/grafana-dashboard.json".to_string(),
            grafana_dashboard,
        );

        // Generate alerting rules
        let alerting_rules = self.generate_alerting_rules()?;
        artifacts.insert("monitoring/alert-rules.yml".to_string(), alerting_rules);

        Ok(artifacts)
    }

    /// Generate security artifacts
    fn generate_security_artifacts(&self) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // Generate security policies
        let security_policies = self.generate_security_policies()?;
        artifacts.insert("security/policies.yml".to_string(), security_policies);

        // Generate network policies
        let network_policies = self.generate_network_policies()?;
        artifacts.insert(
            "security/network-policies.yml".to_string(),
            network_policies,
        );

        // Generate RBAC configuration
        let rbac_config = self.generate_rbac_config()?;
        artifacts.insert("security/rbac.yml".to_string(), rbac_config);

        Ok(artifacts)
    }

    /// Deploy to target platform
    pub fn deploy(&self) -> TrustformersResult<DeploymentStatus> {
        match &self.config.platform {
            ContainerPlatform::Docker => self.deploy_docker(),
            ContainerPlatform::Kubernetes => self.deploy_kubernetes(),
            ContainerPlatform::DockerSwarm => self.deploy_docker_swarm(),
            ContainerPlatform::AmazonECS => self.deploy_ecs(),
            ContainerPlatform::GoogleCloudRun => self.deploy_cloud_run(),
            ContainerPlatform::AzureContainerInstances => self.deploy_aci(),
            ContainerPlatform::OpenShift => self.deploy_openshift(),
        }
    }

    /// Deploy to Docker
    fn deploy_docker(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for Docker deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Docker container deployed successfully".to_string(),
            ready_replicas: 1,
            total_replicas: 1,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to Kubernetes
    fn deploy_kubernetes(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for Kubernetes deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Kubernetes deployment successful".to_string(),
            ready_replicas: 3,
            total_replicas: 3,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to Docker Swarm
    fn deploy_docker_swarm(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for Docker Swarm deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Docker Swarm service deployed".to_string(),
            ready_replicas: 2,
            total_replicas: 2,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to Amazon ECS
    fn deploy_ecs(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for ECS deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "ECS service deployed successfully".to_string(),
            ready_replicas: 4,
            total_replicas: 4,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to Google Cloud Run
    fn deploy_cloud_run(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for Cloud Run deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Cloud Run service deployed".to_string(),
            ready_replicas: 0, // Serverless
            total_replicas: 0, // Serverless
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to Azure Container Instances
    fn deploy_aci(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for ACI deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Azure Container Instance deployed".to_string(),
            ready_replicas: 1,
            total_replicas: 1,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Deploy to OpenShift
    fn deploy_openshift(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation for OpenShift deployment
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "OpenShift deployment successful".to_string(),
            ready_replicas: 3,
            total_replicas: 3,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Get deployment status
    pub fn get_deployment_status(&self) -> TrustformersResult<DeploymentStatus> {
        // Implementation to fetch actual deployment status
        Ok(DeploymentStatus {
            phase: DeploymentPhase::Running,
            message: "Deployment is healthy".to_string(),
            ready_replicas: 3,
            total_replicas: 3,
            last_update: chrono::Utc::now().to_rfc3339(),
        })
    }

    /// Scale deployment
    pub fn scale_deployment(&self, replicas: u32) -> TrustformersResult<()> {
        // Implementation for scaling
        println!("Scaling deployment to {} replicas", replicas);
        Ok(())
    }

    /// Update deployment
    pub fn update_deployment(
        &self,
        new_config: ContainerDeploymentConfig,
    ) -> TrustformersResult<()> {
        // Implementation for updating deployment
        println!("Updating deployment with new configuration");
        Ok(())
    }

    /// Delete deployment
    pub fn delete_deployment(&self) -> TrustformersResult<()> {
        // Implementation for deleting deployment
        println!("Deleting deployment");
        Ok(())
    }

    // Helper methods for generating specific configurations

    fn generate_swarm_stack_file(&self, config: &DockerSwarmConfig) -> TrustformersResult<String> {
        // Generate Docker Swarm stack file
        Ok(format!(
            r#"
version: '3.8'
services:
  {}:
    image: {}:{}
    replicas: {}
    update_config:
      parallelism: {}
      delay: {}
    resources:
      limits:
        cpus: '{}'
        memory: {}M
    networks: {}
"#,
            self.config.app_name,
            self.config.image_config.base_image,
            self.config.image_config.tag,
            config.replicas,
            config.update_config.parallelism,
            config.update_config.delay,
            config.resources.cpu_limit,
            config.resources.memory_limit,
            config.networks.join("\n      - ")
        ))
    }

    fn generate_swarm_deploy_script(&self, config: &DockerSwarmConfig) -> String {
        format!(
            r#"#!/bin/bash
set -e

echo "Deploying {} to Docker Swarm..."

# Build and push image
docker build -t {}:{} .
docker push {}:{}

# Deploy stack
docker stack deploy -c docker-stack.yml {}

echo "Deployment completed successfully!"
"#,
            self.config.app_name,
            self.config.image_config.base_image,
            self.config.image_config.tag,
            self.config.image_config.base_image,
            self.config.image_config.tag,
            self.config.app_name
        )
    }

    fn generate_swarm_service_config(
        &self,
        config: &DockerSwarmConfig,
    ) -> TrustformersResult<String> {
        // Generate service configuration
        serde_yaml::to_string(config).map_err(|_| TrustformersError::SerializationError)
    }

    fn generate_ecs_task_definition(&self, config: &ECSConfig) -> TrustformersResult<String> {
        // Generate ECS task definition JSON
        let task_def = serde_json::json!({
            "family": config.task_definition_family,
            "networkMode": config.network_mode,
            "requiresCompatibilities": [config.launch_type],
            "cpu": "256",
            "memory": "512",
            "containerDefinitions": [{
                "name": self.config.app_name,
                "image": format!("{}:{}", self.config.image_config.base_image, self.config.image_config.tag),
                "essential": true,
                "portMappings": self.config.network.port_mappings.iter().map(|pm| {
                    serde_json::json!({
                        "containerPort": pm.container_port,
                        "hostPort": pm.host_port,
                        "protocol": pm.protocol
                    })
                }).collect::<Vec<_>>()
            }]
        });

        serde_json::to_string_pretty(&task_def)
            .map_err(|_| TrustformersError::SerializationError)
    }

    fn generate_ecs_service_definition(&self, config: &ECSConfig) -> TrustformersResult<String> {
        // Generate ECS service definition
        let service_def = serde_json::json!({
            "serviceName": config.service_name,
            "cluster": config.cluster_name,
            "taskDefinition": config.task_definition_family,
            "desiredCount": config.desired_count,
            "launchType": config.launch_type
        });

        serde_json::to_string_pretty(&service_def)
            .map_err(|_| TrustformersError::SerializationError)
    }

    fn generate_ecs_cloudformation_template(
        &self,
        config: &ECSConfig,
    ) -> TrustformersResult<String> {
        // Generate CloudFormation template for ECS
        let network_mode_str = serde_json::to_string(&config.network_mode)?;
        let launch_type_str = serde_json::to_string(&config.launch_type)?;
        Ok(format!(
            r#"
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS deployment for {}'

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: {}
      NetworkMode: {}
      RequiresCompatibilities:
        - {}

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: {}
      Cluster: {}
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: {}
"#,
            self.config.app_name,
            config.task_definition_family,
            network_mode_str.trim_matches('"'),
            launch_type_str.trim_matches('"'),
            config.service_name,
            config.cluster_name,
            config.desired_count
        ))
    }

    fn generate_ecs_deploy_script(&self, config: &ECSConfig) -> String {
        format!(
            r#"#!/bin/bash
set -e

echo "Deploying {} to Amazon ECS..."

# Register task definition
aws ecs register-task-definition --cli-input-json file://task-definition.json

# Update service
aws ecs update-service --cluster {} --service {} --task-definition {}

echo "ECS deployment completed successfully!"
"#,
            self.config.app_name,
            config.cluster_name,
            config.service_name,
            config.task_definition_family
        )
    }

    fn generate_cloudrun_service_yaml(
        &self,
        config: &CloudRunConfig,
    ) -> TrustformersResult<String> {
        // Generate Cloud Run service YAML
        Ok(format!(
            r#"
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {}
  annotations:
    run.googleapis.com/region: {}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '{}'
        autoscaling.knative.dev/minScale: '{}'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/memory: '{}Gi'
        run.googleapis.com/cpu: '{}'
    spec:
      containerConcurrency: {}
      timeoutSeconds: {}
      containers:
      - image: {}:{}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: {}Gi
            cpu: '{}'
"#,
            config.service_name,
            config.region,
            config.max_instances,
            config.min_instances,
            config.memory,
            config.cpu,
            config.concurrency,
            config.timeout,
            self.config.image_config.base_image,
            self.config.image_config.tag,
            config.memory,
            config.cpu
        ))
    }

    fn generate_cloudrun_deploy_script(&self, config: &CloudRunConfig) -> String {
        format!(
            r#"#!/bin/bash
set -e

echo "Deploying {} to Google Cloud Run..."

# Build and push image
gcloud builds submit --tag gcr.io/PROJECT-ID/{}:{}

# Deploy to Cloud Run
gcloud run deploy {} \
  --image gcr.io/PROJECT-ID/{}:{} \
  --region {} \
  --allow-unauthenticated \
  --memory {}Gi \
  --cpu {} \
  --max-instances {} \
  --min-instances {} \
  --concurrency {} \
  --timeout {}

echo "Cloud Run deployment completed successfully!"
"#,
            self.config.app_name,
            self.config.app_name,
            self.config.image_config.tag,
            config.service_name,
            self.config.app_name,
            self.config.image_config.tag,
            config.region,
            config.memory,
            config.cpu,
            config.max_instances,
            config.min_instances,
            config.concurrency,
            config.timeout
        )
    }

    fn generate_cloudbuild_config(&self, config: &CloudRunConfig) -> TrustformersResult<String> {
        // Generate Cloud Build configuration
        Ok(format!(
            r#"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/PROJECT-ID/{}:{}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT-ID/{}:{}']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '{}'
  - '--image'
  - 'gcr.io/PROJECT-ID/{}:{}'
  - '--region'
  - '{}'
  - '--allow-unauthenticated'
"#,
            self.config.app_name,
            self.config.image_config.tag,
            self.config.app_name,
            self.config.image_config.tag,
            config.service_name,
            self.config.app_name,
            self.config.image_config.tag,
            config.region
        ))
    }

    fn generate_prometheus_config(&self) -> TrustformersResult<String> {
        // Generate Prometheus configuration
        Ok(format!(
            r#"
global:
  scrape_interval: {}s
  evaluation_interval: {}s

scrape_configs:
  - job_name: '{}'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /metrics
    scrape_interval: {}s
"#,
            self.config.monitoring.metrics_interval,
            self.config.monitoring.metrics_interval,
            self.config.app_name,
            self.config.monitoring.metrics_interval
        ))
    }

    fn generate_grafana_dashboard(&self) -> TrustformersResult<String> {
        // Generate Grafana dashboard JSON
        let dashboard = serde_json::json!({
            "dashboard": {
                "title": format!("{} Dashboard", self.config.app_name),
                "tags": ["trustformers"],
                "panels": [
                    {
                        "title": "Request Rate",
                        "type": "graph",
                        "targets": [
                            {
                                "expr": format!("rate(http_requests_total{{job=\"{}\"}}[5m])", self.config.app_name)
                            }
                        ]
                    },
                    {
                        "title": "Response Time",
                        "type": "graph",
                        "targets": [
                            {
                                "expr": format!("histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{{job=\"{}\"}}[5m]))", self.config.app_name)
                            }
                        ]
                    }
                ]
            }
        });

        Ok(serde_json::to_string_pretty(&dashboard)?)
    }

    fn generate_alerting_rules(&self) -> TrustformersResult<String> {
        // Generate Prometheus alerting rules
        Ok(format!(
            r#"
groups:
  - name: {}_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{{job="{}", status=~"5.."}}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate for {}"
          description: "Error rate is above 10% for 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{{job="{}"}}[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High latency for {}"
          description: "95th percentile latency is above 1 second"
"#,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name
        ))
    }

    fn generate_security_policies(&self) -> TrustformersResult<String> {
        // Generate security policies
        Ok(format!(
            r#"
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: {}-scc
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 65535
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
"#,
            self.config.app_name
        ))
    }

    fn generate_network_policies(&self) -> TrustformersResult<String> {
        // Generate network policies
        Ok(format!(
            r#"
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {}-netpol
spec:
  podSelector:
    matchLabels:
      app: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
"#,
            self.config.app_name, self.config.app_name
        ))
    }

    fn generate_rbac_config(&self) -> TrustformersResult<String> {
        // Generate RBAC configuration
        Ok(format!(
            r#"
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {}-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {}-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {}-role-binding
subjects:
- kind: ServiceAccount
  name: {}-service-account
roleRef:
  kind: Role
  name: {}-role
  apiGroup: rbac.authorization.k8s.io
"#,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name,
            self.config.app_name
        ))
    }

    /// Generate Azure Container Instances artifacts
    fn generate_aci_artifacts(
        &self,
        config: &ACIConfig,
    ) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // ARM template for Azure Container Instances
        let arm_template = serde_json::json!({
            "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
            "contentVersion": "1.0.0.0",
            "resources": [{
                "type": "Microsoft.ContainerInstance/containerGroups",
                "apiVersion": "2023-05-01",
                "name": config.container_group_name,
                "location": config.location,
                "properties": {
                    "containers": [{
                        "name": self.config.app_name,
                        "properties": {
                            "image": format!("{}:{}", self.config.image_config.base_image, self.config.image_config.tag),
                            "resources": {
                                "requests": {
                                    "cpu": config.cpu,
                                    "memoryInGb": config.memory
                                }
                            },
                            "ports": self.config.network.port_mappings.iter().map(|pm| {
                                serde_json::json!({ "port": pm.container_port, "protocol": pm.protocol })
                            }).collect::<Vec<_>>()
                        }
                    }],
                    "osType": "Linux",
                    "restartPolicy": config.restart_policy,
                    "ipAddress": {
                        "type": "Public",
                        "ports": self.config.network.port_mappings.iter().map(|pm| {
                            serde_json::json!({ "port": pm.container_port, "protocol": pm.protocol })
                        }).collect::<Vec<_>>()
                    }
                }
            }]
        });

        artifacts.insert(
            "aci-template.json".to_string(),
            serde_json::to_string_pretty(&arm_template)
                .map_err(|_| TrustformersError::SerializationError)?,
        );

        // Azure CLI deployment script
        let deploy_script = format!(
            r#"#!/bin/bash
set -e

RESOURCE_GROUP="{resource_group}"
CONTAINER_GROUP="{container_group}"
LOCATION="{location}"

echo "Deploying {app_name} to Azure Container Instances..."

# Build and push image to ACR
docker build -t {image}:{tag} .
az acr login --name ${{ACR_NAME}}
docker tag {image}:{tag} ${{ACR_NAME}}.azurecr.io/{image}:{tag}
docker push ${{ACR_NAME}}.azurecr.io/{image}:{tag}

# Deploy container group
az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file aci-template.json \
  --parameters containerGroupName="$CONTAINER_GROUP"

echo "ACI deployment completed successfully!"
"#,
            resource_group = config.resource_group,
            container_group = config.container_group_name,
            location = config.location,
            app_name = self.config.app_name,
            image = self.config.image_config.base_image,
            tag = self.config.image_config.tag,
        );
        artifacts.insert("deploy-aci.sh".to_string(), deploy_script);

        Ok(artifacts)
    }

    /// Generate OpenShift artifacts
    fn generate_openshift_artifacts(
        &self,
        config: &OpenShiftConfig,
    ) -> TrustformersResult<DeploymentArtifacts> {
        let mut artifacts = HashMap::new();

        // OpenShift BuildConfig
        let build_config_yaml = format!(
            r#"
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {app}-build
  namespace: {project}
spec:
  source:
    type: Git
    git:
      uri: {source}
  strategy:
    type: {strategy}
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: '{image}:{tag}'
  output:
    to:
      kind: ImageStreamTag
      name: '{output}'
"#,
            app = config.application,
            project = config.project,
            source = config.build_config.source,
            strategy = config.build_config.strategy,
            image = self.config.image_config.base_image,
            tag = self.config.image_config.tag,
            output = config.build_config.output_image,
        );
        artifacts.insert("openshift-buildconfig.yaml".to_string(), build_config_yaml);

        // OpenShift DeploymentConfig
        let deployment_config_yaml = format!(
            r#"
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {app}
  namespace: {project}
spec:
  replicas: {replicas}
  selector:
    app: {app}
  strategy:
    type: {strategy}
  template:
    metadata:
      labels:
        app: {app}
    spec:
      containers:
      - name: {app}
        image: {output}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: '{cpu}'
            memory: '{memory}'
          requests:
            cpu: '{cpu}'
            memory: '{memory}'
"#,
            app = config.application,
            project = config.project,
            replicas = config.deployment_config.replicas,
            strategy = config.deployment_config.strategy,
            output = config.build_config.output_image,
            cpu = config.deployment_config.resources.cpu,
            memory = config.deployment_config.resources.memory,
        );
        artifacts.insert(
            "openshift-deploymentconfig.yaml".to_string(),
            deployment_config_yaml,
        );

        // OpenShift Service
        let service_yaml = format!(
            r#"
apiVersion: v1
kind: Service
metadata:
  name: {app}
  namespace: {project}
spec:
  selector:
    app: {app}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
"#,
            app = config.application,
            project = config.project,
        );
        artifacts.insert("openshift-service.yaml".to_string(), service_yaml);

        // OpenShift Route (exposes the service externally)
        let route_yaml = format!(
            r#"
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {app}
  namespace: {project}
spec:
  to:
    kind: Service
    name: {app}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
"#,
            app = config.application,
            project = config.project,
        );
        artifacts.insert("openshift-route.yaml".to_string(), route_yaml);

        // oc CLI deployment script
        let deploy_script = format!(
            r#"#!/bin/bash
set -e

echo "Deploying {app} to OpenShift project {project}..."

# Select project
oc project {project} || oc new-project {project}

# Apply manifests
oc apply -f openshift-buildconfig.yaml
oc apply -f openshift-deploymentconfig.yaml
oc apply -f openshift-service.yaml
oc apply -f openshift-route.yaml

# Start build
oc start-build {app}-build --follow

echo "OpenShift deployment completed successfully!"
ROUTE=$(oc get route {app} -o jsonpath='{{.spec.host}}')
echo "Application available at: https://$ROUTE"
"#,
            app = config.application,
            project = config.project,
        );
        artifacts.insert("deploy-openshift.sh".to_string(), deploy_script);

        Ok(artifacts)
    }
}

// Import external dependencies that might be needed
use crate::containers::kubernetes::KubernetesGenerator;

// For time handling
use chrono;

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a fully-populated `ContainerDeploymentConfig` whose `image_config` carries
    /// non-empty `build_args`, `exposed_ports`, and `volumes` - exactly the fields the old,
    /// hand-rolled `format!`-based artifact generation silently ignored - and return the
    /// config alongside those three fixtures so tests can assert on them directly.
    fn build_test_config() -> (
        ContainerDeploymentConfig,
        HashMap<String, String>,
        Vec<u16>,
        Vec<VolumeMount>,
    ) {
        let mut build_args = HashMap::new();
        build_args.insert("APP_VERSION".to_string(), "1.2.3".to_string());
        build_args.insert("FEATURE_FLAG".to_string(), "enabled".to_string());

        let mut env_vars = HashMap::new();
        env_vars.insert("RUST_LOG".to_string(), "debug".to_string());

        // Deliberately distinctive port numbers that can't collide with any hardcoded
        // literal in docker.rs's templates (e.g. the default healthcheck's `:8080`).
        let exposed_ports: Vec<u16> = vec![47001, 47002];

        let volumes = vec![
            VolumeMount {
                source: "/host/data".to_string(),
                target: "/mnt/custom-data".to_string(),
                read_only: false,
            },
            VolumeMount {
                source: "/host/config".to_string(),
                target: "/mnt/custom-config".to_string(),
                read_only: true,
            },
        ];

        let config = ContainerDeploymentConfig {
            platform: ContainerPlatform::Docker,
            app_name: "test-app".to_string(),
            environment: "test".to_string(),
            image_config: DockerImageConfig {
                base_image: "python:3.11-slim".to_string(),
                tag: "1.0.0".to_string(),
                build_context: ".".to_string(),
                dockerfile_path: "Dockerfile".to_string(),
                build_args: build_args.clone(),
                env_vars: env_vars.clone(),
                exposed_ports: exposed_ports.clone(),
                volumes: volumes.clone(),
            },
            // CloudRunConfig is the flattest orchestration variant (plain scalars only),
            // which keeps this fixture focused on the DockerImageConfig conversion.
            orchestration: OrchestrationConfig::CloudRun(CloudRunConfig {
                service_name: "test-service".to_string(),
                region: "us-central1".to_string(),
                memory: 2.0,
                cpu: 1.0,
                max_instances: 10,
                min_instances: 1,
                timeout: 300,
                concurrency: 80,
            }),
            serverless: None,
            monitoring: MonitoringConfig {
                enabled: false,
                metrics_interval: 60,
                log_aggregation: LogAggregationConfig {
                    enabled: false,
                    log_level: "info".to_string(),
                    format: "json".to_string(),
                    destination: "stdout".to_string(),
                },
                health_checks: HealthCheckConfig {
                    enabled: true,
                    endpoint: "/health".to_string(),
                    interval: 30,
                    timeout: 5,
                    failure_threshold: 3,
                },
                alerting: AlertingConfig {
                    enabled: false,
                    rules: vec![],
                    notification_channels: vec![],
                },
            },
            auto_scaling: None,
            security: SecurityConfig {
                security_scanning: false,
                image_scanning: ImageScanningConfig {
                    enabled: false,
                    scan_on_push: false,
                    vulnerability_thresholds: VulnerabilityThresholds {
                        critical: 0,
                        high: 0,
                        medium: 0,
                    },
                },
                runtime_security: RuntimeSecurityConfig {
                    enabled: false,
                    policies: vec![],
                    compliance_checks: vec![],
                },
                network_policies: vec![],
                secret_management: SecretManagementConfig {
                    store_type: "none".to_string(),
                    encryption: EncryptionConfig {
                        algorithm: "AES256".to_string(),
                        key_management: "local".to_string(),
                    },
                    rotation_policy: RotationPolicy {
                        interval: "30d".to_string(),
                        automatic: false,
                    },
                },
            },
            network: NetworkConfig {
                network_mode: "bridge".to_string(),
                port_mappings: vec![],
                load_balancer: None,
                service_mesh: None,
            },
            storage: StorageConfig {
                persistent_volumes: vec![],
                temp_storage: TempStorageConfig {
                    size_limit: "1Gi".to_string(),
                    cleanup_policy: "always".to_string(),
                },
                backup: None,
            },
        };

        (config, build_args, exposed_ports, volumes)
    }

    #[test]
    fn test_generate_deployment_artifacts_routes_build_args_ports_and_volumes() {
        let (config, build_args, exposed_ports, volumes) = build_test_config();
        let manager = ContainerDeploymentManager::new(config);
        let artifacts = manager
            .generate_deployment_artifacts()
            .expect("artifact generation should succeed for a well-formed config");

        let dockerfile = artifacts
            .get("Dockerfile")
            .expect("Dockerfile artifact should be present");
        let compose = artifacts
            .get("docker-compose.yml")
            .expect("docker-compose.yml artifact should be present");
        let build_script = artifacts
            .get("build.sh")
            .expect("build.sh artifact should be present");

        // (a) build_args must flow into the generated Dockerfile (as `ARG key=value`,
        // emitted by the multi-stage build path) and into build.sh (as `--build-arg`).
        for (key, value) in &build_args {
            let pair = format!("{}={}", key, value);
            assert!(
                dockerfile.contains(&pair),
                "Dockerfile should contain build arg `{}`\n--- Dockerfile ---\n{}",
                pair,
                dockerfile
            );
            assert!(
                build_script.contains(&pair),
                "build.sh should contain build arg `{}`\n--- build.sh ---\n{}",
                pair,
                build_script
            );
        }

        // (b) exposed ports must flow into the Dockerfile (`EXPOSE`) and into the
        // docker-compose ports section.
        for port in &exposed_ports {
            assert!(
                dockerfile.contains(&format!("EXPOSE {}", port)),
                "Dockerfile should EXPOSE port {}\n--- Dockerfile ---\n{}",
                port,
                dockerfile
            );
            assert!(
                compose.contains(&port.to_string()),
                "docker-compose.yml should reference port {}\n--- docker-compose.yml ---\n{}",
                port,
                compose
            );
        }

        // (c) volume mount target paths must flow into the Dockerfile (`VOLUME [...]`).
        // `docker::VolumeMount` has no field for the host-side `source`, so only `target`
        // (the in-container mount point) is expected to survive the conversion.
        for volume in &volumes {
            assert!(
                dockerfile.contains(&volume.target),
                "Dockerfile should VOLUME the target path `{}`\n--- Dockerfile ---\n{}",
                volume.target,
                dockerfile
            );
        }

        // Bonus: env_vars and the base image (routed through `BaseImage::Custom`) should
        // also flow through, since the old hand-rolled implementation dropped env_vars
        // entirely and hardcoded a "COPY . /app" Dockerfile regardless of base_image.
        assert!(
            dockerfile.contains("RUST_LOG=debug"),
            "Dockerfile should contain env var RUST_LOG=debug\n--- Dockerfile ---\n{}",
            dockerfile
        );
        assert!(
            dockerfile.contains("python:3.11-slim"),
            "Dockerfile should FROM the custom base image\n--- Dockerfile ---\n{}",
            dockerfile
        );

        let dockerignore = artifacts
            .get(".dockerignore")
            .expect(".dockerignore artifact should be present");
        assert!(!dockerignore.is_empty());
    }
}
