[package]
name = "oxiphysics-materials"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Material properties and material library for the OxiPhysics engine"
readme = "README.md"
categories = ["science::materials", "simulation"]
keywords = ["materials", "physics", "constitutive", "plasticity", "simulation"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
oxifft = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
