//! Convergence tests for the Gauss-Seidel dimension tree.
//!
//! The claim these tests defend is precise and falsifiable:
//!
//! > Running a CP-ALS sweep on the dimension tree ([`super::dimtree`]) computes the
//! > **same sweep operator** as the classical per-mode loop
//! > `for mode in 0..N { mttkrp(X, A, mode); solve; write A[mode] }`.
//! > It is not a Jacobi relaxation of it.
//!
//! So we test:
//!
//! 1. `dimtree_sweep_matches_naive_gauss_seidel_operator` — the sweep operator
//!    itself, re-synchronised each sweep so no test can pass by accident of the
//!    iteration washing out a discrepancy.
//! 2. `dimtree_trajectory_matches_naive_gauss_seidel` — the *free-running* fit
//!    trajectory, iterate for iterate, across orders 2–5, exact-low-rank and noisy
//!    tensors.
//! 3. `fit_from_last_mttkrp_matches_recomputed_fit` — the sweep's last leaf really
//!    does supply `<X, [[A]]>` for the post-sweep factors.
//! 4. `jacobi_is_a_different_algorithm` / `gauss_seidel_needs_no_more_sweeps_than_jacobi`
//!    — Jacobi is not the same iteration, and it is not free.
//!
//! All tensors and initial factors are generated by an inline splitmix64, so every
//! comparison is exactly reproducible and no two runs of the same test disagree.

use super::dimtree::AlsDimTree;
use super::helpers::{
    compute_fit, compute_fit_from_mttkrp, compute_gram_hadamard, compute_norm_squared,
    solve_least_squares,
};
use super::types::{CpError, InitStrategy, UpdateScheme};
use crate::cp::{cp_als, cp_als_with_scheme};
use scirs2_core::ndarray_ext::{Array, Array2, IxDyn};
use tenrso_core::DenseND;
use tenrso_kernels::mttkrp;

// ─── Deterministic data generation ──────────────────────────────────────────

/// splitmix64 — a deterministic, well-distributed generator so that every
/// assertion below is exactly reproducible run to run.
struct SplitMix(u64);

impl SplitMix {
    fn new(seed: u64) -> Self {
        SplitMix(seed)
    }

    /// Uniform in `[0, 1)`.
    fn next_unit(&mut self) -> f64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        ((z >> 11) as f64) / ((1u64 << 53) as f64)
    }

    /// Roughly standard-normal, via a 12-uniform sum (Irwin-Hall).
    fn next_normal(&mut self) -> f64 {
        (0..12).map(|_| self.next_unit()).sum::<f64>() - 6.0
    }
}

/// Dense tensor with i.i.d. uniform entries in `[0, 1)`.
fn random_tensor(shape: &[usize], seed: u64) -> DenseND<f64> {
    let mut rng = SplitMix::new(seed);
    let numel: usize = shape.iter().product();
    let data: Vec<f64> = (0..numel).map(|_| rng.next_unit()).collect();
    let array = Array::from_shape_vec(IxDyn(shape), data).expect("shape matches data length");
    DenseND::from_array(array)
}

/// A tensor that is *exactly* rank-`rank`, optionally perturbed by Gaussian noise.
///
/// Exact low-rank tensors are the case where ALS is expected to drive the fit to
/// 1.0; the noisy variant is the case where it must plateau at the noise floor.
fn low_rank_tensor(shape: &[usize], rank: usize, noise: f64, seed: u64) -> DenseND<f64> {
    let mut rng = SplitMix::new(seed);
    let factors: Vec<Array2<f64>> = shape
        .iter()
        .map(|&dim| Array2::from_shape_fn((dim, rank), |_| rng.next_unit()))
        .collect();

    let numel: usize = shape.iter().product();
    let mut data = vec![0.0f64; numel];
    for (flat, value) in data.iter_mut().enumerate() {
        // Decode the row-major multi-index of `flat`.
        let mut rem = flat;
        let mut index = vec![0usize; shape.len()];
        for axis in (0..shape.len()).rev() {
            index[axis] = rem % shape[axis];
            rem /= shape[axis];
        }
        let mut acc = 0.0;
        for r in 0..rank {
            let mut term = 1.0;
            for (axis, factor) in factors.iter().enumerate() {
                term *= factor[[index[axis], r]];
            }
            acc += term;
        }
        *value = acc + noise * rng.next_normal();
    }

    let array = Array::from_shape_vec(IxDyn(shape), data).expect("shape matches data length");
    DenseND::from_array(array)
}

/// An exactly rank-`rank` tensor built from **sign-varying** factors.
///
/// [`low_rank_tensor`]'s all-positive factors are strongly collinear (every
/// component correlates with every other), which is a fine stress test for
/// *equivalence* but a poor one for *convergence quality*: ALS legitimately stalls
/// short of a perfect fit. Where a test asserts a fit threshold, it uses this
/// well-conditioned, identifiable variant instead.
fn low_rank_tensor_signed(shape: &[usize], rank: usize, noise: f64, seed: u64) -> DenseND<f64> {
    let mut rng = SplitMix::new(seed);
    let factors: Vec<Array2<f64>> = shape
        .iter()
        .map(|&dim| Array2::from_shape_fn((dim, rank), |_| 2.0 * rng.next_unit() - 1.0))
        .collect();

    let numel: usize = shape.iter().product();
    let mut data = vec![0.0f64; numel];
    for (flat, value) in data.iter_mut().enumerate() {
        let mut rem = flat;
        let mut index = vec![0usize; shape.len()];
        for axis in (0..shape.len()).rev() {
            index[axis] = rem % shape[axis];
            rem /= shape[axis];
        }
        let mut acc = 0.0;
        for r in 0..rank {
            let mut term = 1.0;
            for (axis, factor) in factors.iter().enumerate() {
                term *= factor[[index[axis], r]];
            }
            acc += term;
        }
        *value = acc + noise * rng.next_normal();
    }

    let array = Array::from_shape_vec(IxDyn(shape), data).expect("shape matches data length");
    DenseND::from_array(array)
}

/// Deterministic initial factors, shared by every scheme under comparison so that
/// any trajectory difference is attributable to the algorithm and nothing else.
fn initial_factors(shape: &[usize], rank: usize, seed: u64) -> Vec<Array2<f64>> {
    let mut rng = SplitMix::new(seed);
    shape
        .iter()
        .map(|&dim| Array2::from_shape_fn((dim, rank), |_| rng.next_unit()))
        .collect()
}

// ─── Reference implementation: the pre-dimension-tree sweep, verbatim ───────

/// The classical per-mode Gauss-Seidel sweep, exactly as `cp_als` performed it
/// before the dimension tree landed: one flat `mttkrp` per mode, against the
/// factor state *including* the modes this sweep already rewrote.
///
/// Returns the mode-`(N-1)` MTTKRP, so the caller can cross-check the fit shortcut.
fn naive_gauss_seidel_sweep(
    tensor: &DenseND<f64>,
    factors: &mut Vec<Array2<f64>>,
) -> Result<Array2<f64>, CpError> {
    let n_modes = factors.len();
    let mut last = Array2::<f64>::zeros((0, 0));

    for mode in 0..n_modes {
        let factor_views: Vec<_> = factors.iter().map(|f| f.view()).collect();
        let mttkrp_result = mttkrp(&tensor.view(), &factor_views, mode)
            .map_err(|e| CpError::ShapeMismatch(e.to_string()))?;

        let gram = compute_gram_hadamard(factors, mode);
        factors[mode] = solve_least_squares(&mttkrp_result, &gram)?;

        if mode + 1 == n_modes {
            last = mttkrp_result;
        }
    }

    Ok(last)
}

/// One sweep on the dimension tree, with the identical per-mode update rule.
fn tree_gauss_seidel_sweep(
    tree: &AlsDimTree,
    tensor: &DenseND<f64>,
    factors: &mut Vec<Array2<f64>>,
) -> Result<Array2<f64>, CpError> {
    let mut update = |mode: usize,
                      mttkrp_result: &Array2<f64>,
                      factors: &mut Vec<Array2<f64>>|
     -> Result<(), CpError> {
        let gram = compute_gram_hadamard(factors, mode);
        factors[mode] = solve_least_squares(mttkrp_result, &gram)?;
        Ok(())
    };
    tree.gauss_seidel_sweep(&tensor.view(), factors, &mut update)
}

/// Largest absolute discrepancy between two factor sets.
fn max_factor_diff(left: &[Array2<f64>], right: &[Array2<f64>]) -> f64 {
    assert_eq!(left.len(), right.len(), "factor counts differ");
    let mut worst = 0.0f64;
    for (a, b) in left.iter().zip(right.iter()) {
        assert_eq!(a.shape(), b.shape(), "factor shapes differ");
        for (&x, &y) in a.iter().zip(b.iter()) {
            worst = worst.max((x - y).abs());
        }
    }
    worst
}

/// Scale of a factor set, so the comparison above can be read as a *relative* error.
fn factor_scale(factors: &[Array2<f64>]) -> f64 {
    factors
        .iter()
        .flat_map(|f| f.iter())
        .fold(0.0f64, |acc, &v| acc.max(v.abs()))
        .max(1.0)
}

/// The tensor shapes / ranks every equivalence test sweeps over: orders 2–5,
/// balanced and lopsided, ranks below and at the smallest mode size.
const CASES: &[(&[usize], usize)] = &[
    (&[6, 5], 3),
    (&[7, 6, 5], 3),
    (&[8, 8, 8], 5),
    (&[4, 9, 3, 6], 3),
    (&[10, 3, 4, 5], 3),
    (&[3, 4, 3, 5, 4], 2),
];

// ─── 1. The sweep operator ──────────────────────────────────────────────────

/// The dimension tree must compute *the same sweep operator* as the naive loop.
///
/// Both sweeps are fed the identical input factor set every iteration (the naive
/// result is the one carried forward), so a discrepancy cannot be hidden by the
/// iteration converging anyway: each of the `sweeps` comparisons is an independent
/// probe of the operator, taken at a different point of the ALS trajectory.
#[test]
fn dimtree_sweep_matches_naive_gauss_seidel_operator() {
    for (case, &(shape, rank)) in CASES.iter().enumerate() {
        let tensor = random_tensor(shape, 0xA11CE ^ case as u64);
        let tree = AlsDimTree::new(shape).expect("tree builds for order >= 2");
        let mut factors = initial_factors(shape, rank, 0xBEEF ^ case as u64);

        for sweep in 0..8 {
            let mut naive = factors.clone();
            let mut tree_side = factors.clone();

            let naive_last = naive_gauss_seidel_sweep(&tensor, &mut naive).expect("naive sweep");
            let tree_last =
                tree_gauss_seidel_sweep(&tree, &tensor, &mut tree_side).expect("tree sweep");

            let scale = factor_scale(&naive);
            let diff = max_factor_diff(&naive, &tree_side);
            assert!(
                diff <= 1e-9 * scale,
                "shape {shape:?} rank {rank} sweep {sweep}: dimension-tree sweep is not the \
                 Gauss-Seidel sweep operator (max factor diff {diff:.3e}, scale {scale:.3e})"
            );

            // The last leaf must also be the mode-(N-1) MTTKRP the naive loop took.
            assert_eq!(naive_last.shape(), tree_last.shape());
            let mut mttkrp_diff = 0.0f64;
            let mut mttkrp_scale = 1.0f64;
            for (&x, &y) in naive_last.iter().zip(tree_last.iter()) {
                mttkrp_diff = mttkrp_diff.max((x - y).abs());
                mttkrp_scale = mttkrp_scale.max(x.abs());
            }
            assert!(
                mttkrp_diff <= 1e-9 * mttkrp_scale,
                "shape {shape:?} sweep {sweep}: last-mode MTTKRP differs by {mttkrp_diff:.3e}"
            );

            factors = naive;
        }
    }
}

// ─── 2. The free-running trajectory ─────────────────────────────────────────

/// Fit trajectory, iterate for iterate, of the naive Gauss-Seidel loop versus the
/// dimension-tree Gauss-Seidel loop — run *independently*, not re-synchronised.
///
/// Both an exactly-low-rank tensor (fit must climb to ~1) and a noisy one (fit must
/// plateau) are covered, because those exercise very different conditioning of the
/// Gram matrices along the way.
#[test]
fn dimtree_trajectory_matches_naive_gauss_seidel() {
    let scenarios: &[(&[usize], usize, f64, u64)] = &[
        // shape, rank, noise, seed
        (&[7, 6, 5], 3, 0.0, 11),
        (&[8, 8, 8], 4, 0.0, 12),
        (&[8, 8, 8], 4, 0.05, 13),
        (&[4, 9, 3, 6], 3, 0.0, 14),
        (&[4, 9, 3, 6], 3, 0.02, 15),
        (&[3, 4, 3, 5, 4], 2, 0.01, 16),
        (&[6, 5], 3, 0.03, 17),
    ];

    for &(shape, rank, noise, seed) in scenarios {
        let tensor = low_rank_tensor(shape, rank, noise, seed);
        let norm_sq = compute_norm_squared(&tensor);
        let tree = AlsDimTree::new(shape).expect("tree builds");
        let start = initial_factors(shape, rank, seed ^ 0x5EED);

        let sweeps = 20;

        let mut naive_factors = start.clone();
        let mut naive_fits = Vec::with_capacity(sweeps);
        for _ in 0..sweeps {
            naive_gauss_seidel_sweep(&tensor, &mut naive_factors).expect("naive sweep");
            naive_fits.push(compute_fit(&tensor, &naive_factors, norm_sq).expect("fit"));
        }

        let mut tree_factors = start.clone();
        let mut tree_fits = Vec::with_capacity(sweeps);
        for _ in 0..sweeps {
            tree_gauss_seidel_sweep(&tree, &tensor, &mut tree_factors).expect("tree sweep");
            tree_fits.push(compute_fit(&tensor, &tree_factors, norm_sq).expect("fit"));
        }

        for (iter, (&a, &b)) in naive_fits.iter().zip(tree_fits.iter()).enumerate() {
            assert!(
                (a - b).abs() <= 1e-8,
                "shape {shape:?} rank {rank} noise {noise}: fit trajectories diverge at sweep \
                 {iter} (naive {a:.12}, dimtree {b:.12}); the dimension tree changed the \
                 algorithm, not just the arithmetic"
            );
        }

        // ...and the final iterates themselves, not just their fits.
        let scale = factor_scale(&naive_factors);
        let diff = max_factor_diff(&naive_factors, &tree_factors);
        assert!(
            diff <= 1e-6 * scale,
            "shape {shape:?} rank {rank} noise {noise}: final factors diverge \
             (max diff {diff:.3e}, scale {scale:.3e})"
        );
    }
}

/// The public `cp_als` entry point is Gauss-Seidel, and `cp_als_with_scheme` with
/// `GaussSeidel` is literally the same code path.
#[test]
fn cp_als_default_is_gauss_seidel() {
    let tensor = low_rank_tensor_signed(&[9, 8, 7], 3, 0.0, 21);

    let default = cp_als(&tensor, 3, 30, 1e-8, InitStrategy::Svd, None).expect("cp_als");
    let explicit = cp_als_with_scheme(
        &tensor,
        3,
        30,
        1e-8,
        InitStrategy::Svd,
        UpdateScheme::GaussSeidel,
        None,
    )
    .expect("cp_als_with_scheme");

    // SVD init is deterministic, so these two runs must agree exactly.
    assert_eq!(default.iters, explicit.iters);
    assert!(
        (default.fit - explicit.fit).abs() < 1e-12,
        "cp_als ({}) and cp_als_with_scheme(GaussSeidel) ({}) disagree",
        default.fit,
        explicit.fit
    );

    // An exactly rank-3 tensor must be recovered essentially perfectly.
    assert!(
        default.fit > 0.99,
        "Gauss-Seidel CP-ALS failed to fit an exact rank-3 tensor (fit {})",
        default.fit
    );
}

// ─── 3. The free fit ────────────────────────────────────────────────────────

/// The sweep's last leaf is the mode-`(N-1)` MTTKRP against the *final* factors
/// `0..N-2`, so `<X, [[A]]> = sum(M_{N-1} * A_{N-1})` and the fit needs no extra
/// tensor pass. Cross-check it against the fit computed the long way (a freshly
/// recomputed mode-0 MTTKRP over the post-sweep factors).
#[test]
fn fit_from_last_mttkrp_matches_recomputed_fit() {
    for (case, &(shape, rank)) in CASES.iter().enumerate() {
        let tensor = low_rank_tensor(shape, rank, 0.02, 31 + case as u64);
        let norm_sq = compute_norm_squared(&tensor);
        let tree = AlsDimTree::new(shape).expect("tree builds");
        let mut factors = initial_factors(shape, rank, 41 + case as u64);
        let n_modes = shape.len();

        for sweep in 0..10 {
            let last = tree_gauss_seidel_sweep(&tree, &tensor, &mut factors).expect("tree sweep");

            let cheap = compute_fit_from_mttkrp(&factors, &last, n_modes - 1, norm_sq);
            let reference = compute_fit(&tensor, &factors, norm_sq).expect("fit");

            assert!(
                (cheap - reference).abs() <= 1e-10,
                "shape {shape:?} sweep {sweep}: fit from the sweep's last MTTKRP ({cheap:.14}) \
                 does not match the recomputed fit ({reference:.14})"
            );
        }
    }
}

// ─── 4. Jacobi is a different algorithm ─────────────────────────────────────

/// The **naked** simultaneous update — solve every mode against the frozen factor
/// set and install all `N` results, i.e. exactly what dropping an all-modes MTTKRP
/// kernel into an ALS loop gives you — **diverges**.
///
/// The scale subspace is the culprit: in the rank-1 case with `A_k = α_k a_k` and
/// `p = Π α_k`, the exact per-mode solve gives `α_k' = α_k / p`, hence `p' = p^{1-N}`,
/// whose linearization about the correct fixed point `p = 1` amplifies the error by
/// `N-1` per sweep and flips its sign.
///
/// This test is the empirical counterpart of that derivation, and it is the reason
/// `UpdateScheme::Jacobi` ships with column normalization and an optimal weight
/// refit rather than as the textbook one-liner. **If this test ever starts passing
/// trivially because the naked iteration converged, the reference implementation
/// below has drifted and the stabilization rationale must be re-checked.**
#[test]
fn naked_simultaneous_updates_diverge() {
    /// The one-liner: all modes solved against the frozen set, all installed.
    fn naked_jacobi_sweep(
        tensor: &DenseND<f64>,
        factors: &[Array2<f64>],
    ) -> Result<Vec<Array2<f64>>, CpError> {
        let n_modes = factors.len();
        let factor_views: Vec<_> = factors.iter().map(|f| f.view()).collect();
        let tree = tenrso_kernels::DimTree::new(tensor.shape())
            .map_err(|e| CpError::ShapeMismatch(e.to_string()))?;
        let mttkrps = tree
            .mttkrp_all(&tensor.view(), &factor_views)
            .map_err(|e| CpError::ShapeMismatch(e.to_string()))?;

        let mut updated = Vec::with_capacity(n_modes);
        for (mode, mttkrp_result) in mttkrps.iter().enumerate() {
            let gram = compute_gram_hadamard(factors, mode);
            updated.push(solve_least_squares(mttkrp_result, &gram)?);
        }
        Ok(updated)
    }

    for &(shape, rank) in &[(&[8usize, 8, 8][..], 3usize), (&[6, 5, 4, 5][..], 3)] {
        let tensor = low_rank_tensor_signed(shape, rank, 0.0, 101);
        let norm_sq = compute_norm_squared(&tensor);
        let tree = AlsDimTree::new(shape).expect("tree builds");

        // Same starting point for both, deliberately a *good* one.
        let start = initial_factors(shape, rank, 102);

        let mut naked = start.clone();
        let mut naked_best = 0.0f64;
        for _ in 0..12 {
            naked = naked_jacobi_sweep(&tensor, &naked).expect("naked sweep");
            let fit = compute_fit(&tensor, &naked, norm_sq).expect("fit");
            naked_best = naked_best.max(fit);
        }

        // The control. Gauss-Seidel is given plenty of sweeps: the point of this test
        // is the *divergence* of the naked iteration, so the control must be an
        // unambiguous success, not a race.
        let mut gauss = start.clone();
        let mut gauss_fit = 0.0f64;
        for _ in 0..60 {
            tree_gauss_seidel_sweep(&tree, &tensor, &mut gauss).expect("tree sweep");
            gauss_fit = compute_fit(&tensor, &gauss, norm_sq).expect("fit");
        }

        assert!(
            gauss_fit > 0.95,
            "shape {shape:?}: Gauss-Seidel should recover an exact rank-{rank} tensor \
             (fit {gauss_fit:.6})"
        );
        assert!(
            naked_best < 0.5,
            "shape {shape:?}: the naked simultaneous iteration reached fit {naked_best:.6}, but \
             it is supposed to diverge (scale error amplified by N-1 = {} per sweep). Either the \
             derivation is wrong or the reference sweep no longer implements it.",
            shape.len() - 1
        );
    }
}

/// A Jacobi sweep is *not* the Gauss-Seidel sweep. If this test ever starts failing
/// because the two agree, something has silently collapsed one into the other.
#[test]
fn jacobi_is_a_different_algorithm() {
    let shape: &[usize] = &[8, 8, 8];
    let rank = 4;
    let tensor = low_rank_tensor_signed(shape, rank, 0.0, 51);

    let gauss = cp_als_with_scheme(
        &tensor,
        rank,
        1,
        1e-12,
        InitStrategy::Svd,
        UpdateScheme::GaussSeidel,
        None,
    )
    .expect("gauss-seidel");
    let jacobi = cp_als_with_scheme(
        &tensor,
        rank,
        1,
        1e-12,
        InitStrategy::Svd,
        UpdateScheme::Jacobi,
        None,
    )
    .expect("jacobi");

    // Same deterministic (SVD) init, one sweep: the iterates must genuinely differ.
    let diff = max_factor_diff(&gauss.factors, &jacobi.factors);
    assert!(
        diff > 1e-6,
        "after one sweep from the same initialization, Jacobi and Gauss-Seidel produced the \
         same iterate (max diff {diff:.3e}) — one of the two schemes is not doing what it says"
    );
}

/// The **stabilized** Jacobi converges — it is a legitimate algorithm once the scale
/// subspace is solved rather than iterated — and Gauss-Seidel never needs *more*
/// sweeps than it to hit the same fit.
///
/// This is the honest accounting the `UpdateScheme` docs promise: the per-sweep cost
/// of the two schemes is the same `2·nnz·R` on the dimension tree (Jacobi in fact
/// pays one extra `nnz·R` MTTKRP for its fit), so if Gauss-Seidel also needs no more
/// sweeps, there is no regime in which Jacobi wins on time-to-target-fit in-process.
#[test]
fn gauss_seidel_needs_no_more_sweeps_than_jacobi() {
    let scenarios: &[(&[usize], usize, f64, u64, f64)] = &[
        // shape, rank, noise, seed, target fit
        (&[8, 8, 8], 3, 0.0, 61, 0.99),
        (&[7, 6, 5], 3, 0.0, 62, 0.99),
        (&[6, 7, 8], 4, 0.02, 63, 0.90),
        (&[4, 9, 3, 6], 3, 0.0, 64, 0.95),
        (&[3, 4, 3, 5, 4], 2, 0.0, 65, 0.95),
    ];

    for &(shape, rank, noise, seed, target) in scenarios {
        let tensor = low_rank_tensor_signed(shape, rank, noise, seed);

        // `tol = 0` is not allowed (it must be in [0, 1)), so use a tolerance far
        // below any plausible fit change and let `max_iters` do the stopping.
        let max_iters = 60;
        let gauss = cp_als_with_scheme(
            &tensor,
            rank,
            max_iters,
            1e-14,
            InitStrategy::Svd,
            UpdateScheme::GaussSeidel,
            None,
        )
        .expect("gauss-seidel");
        let jacobi = cp_als_with_scheme(
            &tensor,
            rank,
            max_iters,
            1e-14,
            InitStrategy::Svd,
            UpdateScheme::Jacobi,
            None,
        )
        .expect("jacobi");

        let sweeps_to_target = |cp: &crate::cp::CpDecomp<f64>| -> Option<usize> {
            cp.convergence
                .as_ref()
                .and_then(|c| c.fit_history.iter().position(|&f| f >= target))
                .map(|i| i + 1)
        };

        let gauss_sweeps = sweeps_to_target(&gauss);
        let jacobi_sweeps = sweeps_to_target(&jacobi);

        assert!(
            gauss_sweeps.is_some(),
            "shape {shape:?} rank {rank} noise {noise}: Gauss-Seidel never reached fit {target} \
             in {max_iters} sweeps (final {:.6})",
            gauss.fit
        );

        // Jacobi converges too, just possibly needing more sweeps.
        assert!(
            jacobi.fit > 0.0,
            "shape {shape:?}: Jacobi failed to make any progress (final fit {:.6})",
            jacobi.fit
        );

        if let (Some(g), Some(j)) = (gauss_sweeps, jacobi_sweeps) {
            assert!(
                g <= j,
                "shape {shape:?} rank {rank} noise {noise}: Gauss-Seidel needed MORE sweeps \
                 ({g}) than Jacobi ({j}) to reach fit {target} — the premise of making \
                 GaussSeidel the default is wrong and the docs must be corrected"
            );
        }
    }
}

// ─── Structural / edge cases ────────────────────────────────────────────────

/// The tree is order-`N` only for `N >= 2`; CP of an order-1 tensor is meaningless
/// and must be rejected rather than silently mishandled.
#[test]
fn dimtree_rejects_order_one() {
    let err = AlsDimTree::new(&[7]).expect_err("order-1 must be rejected");
    assert!(
        matches!(err, CpError::ShapeMismatch(_)),
        "expected a shape error, got {err:?}"
    );
}

/// The tree is shape-checked: reusing it against a differently shaped tensor is an
/// error, never a silently wrong contraction.
#[test]
fn dimtree_rejects_shape_mismatch() {
    let tree = AlsDimTree::new(&[4, 5, 6]).expect("tree builds");
    let tensor = random_tensor(&[4, 5, 7], 71);
    let mut factors = initial_factors(&[4, 5, 7], 2, 72);
    let err = tree_gauss_seidel_sweep(&tree, &tensor, &mut factors)
        .expect_err("shape mismatch must be rejected");
    assert!(matches!(err, CpError::ShapeMismatch(_)));
}

/// Matrices (order 2) are the tree's degenerate case — the root's two children are
/// both leaves — and must still be exact Gauss-Seidel.
#[test]
fn dimtree_handles_order_two() {
    let shape: &[usize] = &[9, 7];
    let tensor = random_tensor(shape, 81);
    let tree = AlsDimTree::new(shape).expect("tree builds");
    let mut naive = initial_factors(shape, 4, 82);
    let mut tree_side = naive.clone();

    for sweep in 0..5 {
        naive_gauss_seidel_sweep(&tensor, &mut naive).expect("naive sweep");
        tree_gauss_seidel_sweep(&tree, &tensor, &mut tree_side).expect("tree sweep");

        let diff = max_factor_diff(&naive, &tree_side);
        let scale = factor_scale(&naive);
        assert!(
            diff <= 1e-8 * scale,
            "order-2 sweep {sweep}: diff {diff:.3e} (scale {scale:.3e})"
        );
    }
}

/// Constrained CP-ALS runs on the same tree, and its projections must be visible to
/// the *later* modes of the same sweep (that is what makes it Gauss-Seidel).
/// Non-negativity is the easiest constraint to check end to end.
#[test]
fn constrained_cp_als_on_the_tree_stays_gauss_seidel() {
    use super::types::CpConstraints;
    use crate::cp::cp_als_constrained;

    let tensor = low_rank_tensor(&[8, 7, 6], 3, 0.0, 91);
    let cp = cp_als_constrained(
        &tensor,
        3,
        40,
        1e-8,
        InitStrategy::Nnsvd,
        CpConstraints::nonnegative(),
        None,
    )
    .expect("constrained cp_als");

    for (mode, factor) in cp.factors.iter().enumerate() {
        for &value in factor.iter() {
            assert!(
                value >= 0.0,
                "mode {mode} factor has a negative entry ({value}) — the projection did not \
                 survive the tree traversal"
            );
        }
    }

    // A non-negative exact-rank-3 tensor built from non-negative factors is
    // recoverable, so the fit must be high; a Jacobi-style stale-partner sweep would
    // visibly degrade this.
    assert!(
        cp.fit > 0.9,
        "non-negative CP-ALS on the dimension tree fit only {:.4}",
        cp.fit
    );
}
