//! Planck radiation law.
//!
//! Target law: `B(lambda, T) = (2 h c^2 / lambda^5) / (exp(h c / (lambda k T)) - 1)`.
//! In dimensionless units with `u = h c / (lambda k T)` this collapses to the single-variable
//! spectral curve `B(u) = u^5 / (exp(u) - 1)`, which is what this demo fits. Sampling
//! `u in [0.5, 8]` avoids the `u -> 0` singularity, brackets the Wien peak (`u ~ 5`), and keeps
//! the radiance well-scaled (order 1-30).
//!
//! Data source: synthetic (generated by `phop_examples::planck_dataset`).
//! Time budget (design §4.1): 60 s.
//!
//! Exact recovery of the Planck form is NOT expected from today's engine; the demo shows the
//! discoverer fitting the curve and is allowed to only approximate it.

use phop_core::Config;
use phop_examples::{planck_dataset, report};

fn main() {
    let ds = planck_dataset();
    // 60 s budget: a deeper search than the trivial laws, but still CPU-friendly.
    let cfg = Config::default().max_depth(4).max_epochs(800).top_k(5);
    report(
        "Planck radiation (normalized)",
        "B(u) = u^5 / (exp(u) - 1)   [u = h c / (lambda k T)]",
        &ds,
        cfg,
    );
}
