/**
 * AmateRS TypeScript SDK
 *
 * This SDK provides TypeScript bindings for AmateRS, a Fully Homomorphic
 * Encrypted Database. It allows you to store and query encrypted data
 * without ever exposing the plaintext to the server.
 *
 * @example
 * ```typescript
 * import { AmateRSClient, Key, CipherBlob } from '@amaters/sdk';
 *
 * // Connect to server
 * const client = await AmateRSClient.connect('http://localhost:50051');
 *
 * // Set a value
 * await client.set('users', Key.fromString('user:123'), CipherBlob.fromBytes(data));
 *
 * // Get a value
 * const value = await client.get('users', Key.fromString('user:123'));
 * ```
 *
 * @packageDocumentation
 */

// Re-export WASM bindings (will be generated by wasm-pack)
// In a real build, these would come from the pkg/ directory

/**
 * Error codes for AmateRS operations
 */
export enum ErrorCode {
  /** Connection error */
  Connection = 1,
  /** Timeout error */
  Timeout = 2,
  /** Invalid argument error */
  InvalidArgument = 3,
  /** Not found error */
  NotFound = 4,
  /** Operation failed error */
  OperationFailed = 5,
  /** Serialization error */
  Serialization = 6,
  /** FHE operation error */
  FheError = 7,
  /** Configuration error */
  Configuration = 8,
  /** Internal error */
  Internal = 9,
  /** Unknown error */
  Unknown = 10,
}

/**
 * AmateRS error type
 */
export interface AmateRSError {
  /** Error code */
  readonly code: ErrorCode;
  /** Error message */
  readonly message: string;
  /** Optional cause */
  readonly cause?: string;
  /** Whether the error is retryable */
  readonly retryable: boolean;
  /** Error code as string */
  codeString(): string;
  /** Convert to JSON */
  toJSON(): string;
}

/**
 * Database key type
 *
 * Keys are immutable byte sequences used to identify data.
 */
export interface Key {
  /** Get the key as bytes */
  toBytes(): Uint8Array;
  /** Get the key as string (lossy conversion) */
  toString(): string;
  /** Key length in bytes */
  readonly length: number;
  /** Check if key is empty */
  isEmpty(): boolean;
  /** Check equality with another key */
  equals(other: Key): boolean;
  /** Compare with another key (-1, 0, 1) */
  compareTo(other: Key): number;
}

/**
 * Key factory functions
 */
export interface KeyConstructor {
  /** Create a key from string */
  fromString(s: string): Key;
  /** Create a key from bytes */
  fromBytes(data: Uint8Array): Key;
  /** Maximum key size (64KB) */
  readonly maxSize: number;
}

/**
 * Encrypted data blob
 *
 * Represents encrypted ciphertext data.
 */
export interface CipherBlob {
  /** Get the ciphertext as bytes */
  toBytes(): Uint8Array;
  /** Ciphertext length in bytes */
  readonly length: number;
  /** Check if blob is empty */
  isEmpty(): boolean;
  /** Verify integrity using checksum */
  verifyIntegrity(): boolean;
  /** Check equality with another blob */
  equals(other: CipherBlob): boolean;
}

/**
 * CipherBlob factory functions
 */
export interface CipherBlobConstructor {
  /** Create a cipher blob from bytes */
  fromBytes(data: Uint8Array): CipherBlob;
  /** Maximum blob size (1GB) */
  readonly maxSize: number;
}

/**
 * Column reference for query building
 */
export interface ColumnRef {
  /** Column name */
  readonly name: string;
}

/**
 * Client configuration options
 */
export interface ClientConfig {
  /** Server address */
  serverAddr: string;
  /** Connection timeout in milliseconds */
  readonly connectTimeoutMs: number;
  /** Request timeout in milliseconds */
  readonly requestTimeoutMs: number;
  /** Maximum connections in pool */
  readonly maxConnections: number;
  /** Maximum retry attempts */
  readonly maxRetries: number;
  /** Initial retry backoff in milliseconds */
  readonly initialBackoffMs: number;

  /** Set connection timeout */
  withConnectTimeout(timeoutMs: number): ClientConfig;
  /** Set request timeout */
  withRequestTimeout(timeoutMs: number): ClientConfig;
  /** Set max connections */
  withMaxConnections(max: number): ClientConfig;
  /** Set max retries */
  withMaxRetries(max: number): ClientConfig;
  /** Set initial backoff */
  withInitialBackoff(backoffMs: number): ClientConfig;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * ClientConfig factory
 */
export interface ClientConfigConstructor {
  new (serverAddr: string): ClientConfig;
  /** Create from plain object */
  fromObject(obj: Record<string, unknown>): ClientConfig;
}

/**
 * Connection pool statistics
 */
export interface PoolStats {
  /** Total connections in pool */
  readonly totalConnections: number;
  /** Idle connections */
  readonly idleConnections: number;
  /** Active connections */
  readonly activeConnections: number;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * Key-value pair for query results
 */
export interface KeyValuePair {
  /** The key */
  readonly key: Key;
  /** The value */
  readonly value: CipherBlob;
}

/**
 * Query result type
 */
export interface QueryResult {
  /** Check if this is a single value result */
  isSingle(): boolean;
  /** Check if this is a multi-value result */
  isMulti(): boolean;
  /** Check if this is a success result */
  isSuccess(): boolean;
  /** Get the single value (if applicable) */
  readonly value: CipherBlob | null;
  /** Get item count (for multi-value results) */
  readonly itemCount: number;
  /** Get affected rows (for success results) */
  readonly affectedRows: number;
  /** Get item at index */
  getItem(index: number): KeyValuePair | null;
  /** Get all items as array */
  getItems(): KeyValuePair[];
}

/**
 * Predicate type for filtering
 */
export enum PredicateType {
  Eq = 'Eq',
  Gt = 'Gt',
  Lt = 'Lt',
  Gte = 'Gte',
  Lte = 'Lte',
  And = 'And',
  Or = 'Or',
  Not = 'Not',
}

/**
 * Predicate for query filtering
 */
export interface Predicate {
  /** Predicate type */
  readonly predicateType: PredicateType;
  /** Column (if applicable) */
  readonly column?: ColumnRef;
  /** Value (if applicable) */
  readonly value?: CipherBlob;
}

/**
 * Predicate factory functions
 */
export interface PredicateConstructor {
  /** Create equality predicate */
  eq(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create greater than predicate */
  gt(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create less than predicate */
  lt(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create greater than or equal predicate */
  gte(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create less than or equal predicate */
  lte(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create AND predicate */
  and(left: Predicate, right: Predicate): Predicate;
  /** Create OR predicate */
  or(left: Predicate, right: Predicate): Predicate;
  /** Create NOT predicate */
  not(predicate: Predicate): Predicate;
}

/**
 * Update operation type
 */
export enum UpdateType {
  Set = 'Set',
  Add = 'Add',
  Mul = 'Mul',
}

/**
 * Update operation
 */
export interface UpdateOp {
  /** Update type */
  readonly updateType: UpdateType;
  /** Column */
  readonly column: ColumnRef;
  /** Value */
  readonly value: CipherBlob;
}

/**
 * UpdateOp factory functions
 */
export interface UpdateOpConstructor {
  /** Create set update */
  set(column: ColumnRef, value: CipherBlob): UpdateOp;
  /** Create add update (FHE addition) */
  add(column: ColumnRef, value: CipherBlob): UpdateOp;
  /** Create multiply update (FHE multiplication) */
  mul(column: ColumnRef, value: CipherBlob): UpdateOp;
}

/**
 * Query type
 */
export enum QueryType {
  Get = 'get',
  Set = 'set',
  Delete = 'delete',
  Filter = 'filter',
  Update = 'update',
  Range = 'range',
}

/**
 * Query object
 */
export interface Query {
  /** Query type */
  readonly queryType: QueryType;
  /** Collection name */
  readonly collection: string;
  /** Key (if applicable) */
  readonly key?: Key;
  /** Value (if applicable) */
  readonly value?: CipherBlob;
  /** Predicate (if applicable) */
  readonly predicate?: Predicate;
  /** Start key (for range queries) */
  readonly startKey?: Key;
  /** End key (for range queries) */
  readonly endKey?: Key;
  /** Update count */
  readonly updateCount: number;
  /** Get update at index */
  getUpdate(index: number): UpdateOp | null;
}

/**
 * Query builder
 */
export interface QueryBuilder {
  /** Build a Get query */
  get(key: Key): Query;
  /** Build a Set query */
  set(key: Key, value: CipherBlob): Query;
  /** Build a Delete query */
  delete(key: Key): Query;
  /** Build a Filter query */
  filter(predicate: Predicate): Query;
  /** Build a Range query */
  range(start: Key, end: Key): Query;
  /** Start building a where clause */
  whereClause(): PredicateBuilder;
}

/**
 * QueryBuilder factory
 */
export interface QueryBuilderConstructor {
  new (collection: string): QueryBuilder;
}

/**
 * Predicate builder for fluent API
 */
export interface PredicateBuilder {
  /** Create equality filter */
  eq(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create greater than filter */
  gt(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create less than filter */
  lt(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create greater than or equal filter */
  gte(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create less than or equal filter */
  lte(column: ColumnRef, value: CipherBlob): FilterBuilder;
}

/**
 * Filter builder for fluent API
 */
export interface FilterBuilder {
  /** Add AND condition */
  and(other: Predicate): FilterBuilder;
  /** Add OR condition */
  or(other: Predicate): FilterBuilder;
  /** Negate the current predicate */
  not(): FilterBuilder;
  /** Build the filter query */
  build(): Query;
  /** Build an update query */
  update(updates: UpdateOp[]): Query;
  /** Get current predicate */
  readonly predicate: Predicate;
}

/**
 * Batch operation
 */
export interface BatchOperation {
  /** Operation type ('set', 'delete', 'get') */
  readonly type: string;
  /** Collection name */
  readonly collection: string;
  /** Key */
  readonly key: Key;
  /** Value (for set operations) */
  readonly value?: CipherBlob;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * BatchOperation factory functions
 */
export interface BatchOperationConstructor {
  /** Create a set operation */
  set(collection: string, key: Key, value: CipherBlob): BatchOperation;
  /** Create a delete operation */
  delete(collection: string, key: Key): BatchOperation;
  /** Create a get operation */
  get(collection: string, key: Key): BatchOperation;
}

/**
 * AmateRS Client interface
 */
export interface AmateRSClient {
  /** Whether the client is connected */
  readonly isConnected: boolean;
  /** Current configuration */
  readonly config: ClientConfig;
  /** Connection pool statistics */
  readonly poolStats: PoolStats;

  /**
   * Set a key-value pair
   * @param collection Collection name
   * @param key Key to set
   * @param value Value to store
   */
  set(collection: string, key: Key, value: CipherBlob): Promise<void>;

  /**
   * Get a value by key
   * @param collection Collection name
   * @param key Key to retrieve
   * @returns The value or null if not found
   */
  get(collection: string, key: Key): Promise<CipherBlob | null>;

  /**
   * Delete a key
   * @param collection Collection name
   * @param key Key to delete
   */
  delete(collection: string, key: Key): Promise<void>;

  /**
   * Check if a key exists
   * @param collection Collection name
   * @param key Key to check
   * @returns True if key exists
   */
  contains(collection: string, key: Key): Promise<boolean>;

  /**
   * Execute a range query
   * @param collection Collection name
   * @param start Start key (inclusive)
   * @param end End key (exclusive)
   * @returns Array of key-value pairs
   */
  range(collection: string, start: Key, end: Key): Promise<KeyValuePair[]>;

  /**
   * Execute a batch of operations
   * @param operations Array of batch operations
   * @returns Array of results
   */
  batch(operations: BatchOperation[]): Promise<unknown[]>;

  /**
   * Execute a query
   * @param query Query to execute
   * @returns Query result
   */
  executeQuery(query: Query): Promise<QueryResult>;

  /**
   * Perform a health check
   * @returns True if server is healthy
   */
  healthCheck(): Promise<boolean>;

  /**
   * Close all connections
   */
  close(): void;

  /**
   * Reconnect to the server
   */
  reconnect(): Promise<void>;
}

/**
 * AmateRSClient factory
 */
export interface AmateRSClientConstructor {
  /**
   * Connect to an AmateRS server
   * @param addr Server address
   * @returns Connected client
   */
  connect(addr: string): Promise<AmateRSClient>;

  /**
   * Connect with custom configuration
   * @param config Client configuration
   * @returns Connected client
   */
  connectWithConfig(config: ClientConfig): Promise<AmateRSClient>;
}

/**
 * Helper function to create a column reference
 * @param name Column name
 * @returns Column reference
 */
export function col(name: string): ColumnRef {
  return { name };
}

// Module-level initialization state.
// `_initialized` becomes `true` once `init()` has completed.
// `_initPromise` caches the in-flight promise so concurrent callers share it.
let _initialized = false;
let _initPromise: Promise<void> | null = null;

/**
 * Initialize the WASM module. Idempotent — safe to call multiple times.
 * Concurrent calls while init is in-flight share the same promise; only one
 * actual initialization occurs.
 *
 * @example
 * ```typescript
 * await init();
 * console.log(isInitialized()); // true
 * ```
 */
export async function init(): Promise<void> {
  if (_initialized) return;
  if (_initPromise !== null) return _initPromise;
  _initPromise = (async () => {
    // In a real wasm-pack build, the generated glue code calls the Rust
    // `#[wasm_bindgen(start)]` function automatically when the WASM module is
    // loaded. Here we mark initialized so that JS-level state is consistent
    // with the Rust-level WASM_INITIALIZED flag set by that function.
    _initialized = true;
  })();
  return _initPromise;
}

/**
 * Helper function to create a query builder.
 *
 * Auto-initializes the WASM module if not yet done. After initialization
 * this delegates to the WASM-generated QueryBuilder.
 *
 * @param collection Collection name
 * @returns Query builder
 */
export function query(collection: string): QueryBuilder {
  if (!_initialized) {
    throw new Error(
      'WASM module not initialized. Await init() before calling query().',
    );
  }
  // In the real wasm-pack build, this delegates to the generated WASM binding.
  // The type below satisfies the interface; actual values come from the WASM module.
  throw new Error(
    `query('${collection}'): WASM QueryBuilder is only available in the compiled WASM bundle (run wasm-pack build).`,
  );
}

/**
 * Execute a query against an AmateRS server via the WASM export.
 *
 * Auto-initializes the WASM module if not yet done. Returns an empty array
 * until the full HTTP transport is wired in the wasm-pack bundle.
 *
 * @param serverUrl  Server URL (e.g. "http://localhost:50051")
 * @param collection Collection name
 * @param queryJson  JSON-encoded query object
 * @returns Promise resolving to the query result array
 */
export async function executeQuery(
  serverUrl: string,
  collection: string,
  queryJson: string,
): Promise<unknown[]> {
  if (!_initialized) {
    await init();
  }
  // In the wasm-pack compiled bundle, `wasm_query` is exported as `query`
  // via `#[wasm_bindgen(js_name = query)]` in Rust. In non-WASM contexts
  // (e.g. unit tests of this TS file) we return an empty array.
  // When the WASM bundle is available, replace the body with:
  //   const { query: wasmQuery } = await import('../pkg/amaters_sdk_typescript');
  //   return wasmQuery(serverUrl, collection, queryJson);
  void serverUrl;
  void collection;
  void queryJson;
  return [];
}

/**
 * Internal: lightweight in-TS implementation of the public `Key` interface.
 * Used by `streamQuery` to wrap callback-delivered strings in a value that
 * satisfies the SDK's existing `KeyValuePair` shape without importing the
 * WASM-generated `Key` constructor (which is unavailable until the wasm-pack
 * bundle is loaded).
 *
 * The full WASM `Key` type carries richer behavior (length checks, equality
 * helpers, byte-accurate comparison). Streamed chunks are short-lived view
 * values; this implementation provides the same surface but does not attempt
 * binary compatibility with the WASM `Key`.
 */
function makeKeyFromString(s: string): Key {
  const bytes = new TextEncoder().encode(s);
  const key: Key = {
    toBytes: () => bytes.slice(),
    toString: () => s,
    length: bytes.length,
    isEmpty: () => bytes.length === 0,
    equals: (other: Key) => {
      const a = bytes;
      const b = other.toBytes();
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) {
        if (a[i] !== b[i]) return false;
      }
      return true;
    },
    compareTo: (other: Key) => {
      const a = bytes;
      const b = other.toBytes();
      const len = Math.min(a.length, b.length);
      for (let i = 0; i < len; i++) {
        const av = a[i] ?? 0;
        const bv = b[i] ?? 0;
        if (av < bv) return -1;
        if (av > bv) return 1;
      }
      if (a.length < b.length) return -1;
      if (a.length > b.length) return 1;
      return 0;
    },
  };
  return key;
}

/**
 * Internal: lightweight in-TS implementation of the public `CipherBlob`
 * interface, parallel to `makeKeyFromString`. Used to wrap callback-delivered
 * value strings into the public `KeyValuePair.value` shape.
 *
 * `verifyIntegrity()` returns `true` for streamed chunks because the WASM
 * side has not yet round-tripped a checksum for the synthesized payload;
 * once the real streaming RPC lands this is replaced by the WASM-built
 * `CipherBlob` carried over from the server response.
 */
function makeCipherBlobFromString(s: string): CipherBlob {
  const bytes = new TextEncoder().encode(s);
  const blob: CipherBlob = {
    toBytes: () => bytes.slice(),
    length: bytes.length,
    isEmpty: () => bytes.length === 0,
    verifyIntegrity: () => true,
    equals: (other: CipherBlob) => {
      const a = bytes;
      const b = other.toBytes();
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) {
        if (a[i] !== b[i]) return false;
      }
      return true;
    },
  };
  return blob;
}

/**
 * Producer signature for {@link createStreamIterator}.
 *
 * The `start` callback is invoked exactly once when the iterator's first
 * `next()` is awaited (or sooner — implementations may choose to start
 * eagerly). The producer must invoke exactly one of `onDone` or `onError`
 * for the stream to terminate cleanly. `onChunk` may be called any number
 * of times before termination.
 *
 * Implementations should treat consumer cancellation (signaled via the
 * iterator's `return()`) as best-effort: the iterator stops yielding
 * additional chunks immediately, but in-flight producers may still invoke
 * the callbacks; those invocations are dropped on the floor.
 */
export type StreamProducer<T> = (
  onChunk: (value: T) => void,
  onDone: () => void,
  onError: (message: string) => void,
) => void;

/**
 * Generic queue + Promise-pull async iterator factory.
 *
 * Wraps a callback-driven producer (`start`) into an
 * `AsyncIterableIterator<T>`, so consumers can use `for await...of`.
 * Handles three cases:
 *
 *  1. **Backpressure**: if the consumer pulls before the next chunk arrives,
 *     `next()` registers a waiter; when the producer next emits, the waiter
 *     resolves. If chunks arrive before the consumer pulls, they queue up.
 *  2. **Completion**: when the producer calls `onDone`, every pending and
 *     subsequent `next()` resolves with `{ value: undefined, done: true }`.
 *  3. **Error**: when the producer calls `onError(msg)`, every pending and
 *     subsequent `next()` rejects with `Error(msg)`. Subsequent `next()`
 *     calls after the first rejection resolve to `done: true` (never
 *     re-throw).
 *  4. **Cancellation**: the iterator's `return()` method flips an internal
 *     `aborted` flag, drains queued chunks/waiters with `done: true`, and
 *     ignores further producer callbacks.
 *
 * This is exported so the test suite can drive the state machine with a
 * fake producer instead of going through the WASM bridge. Library
 * consumers should normally use {@link streamQuery} which wraps this
 * factory with the WASM-backed producer.
 *
 * @param start Producer callback. Invoked synchronously inside this function.
 * @returns A fresh async iterator each call.
 */
export function createStreamIterator<T>(
  start: StreamProducer<T>,
): AsyncIterableIterator<T> {
  const queue: T[] = [];
  // Each waiter is paired with its rejecter so we can fan errors to
  // pending pulls. `resolve` for normal/done events; `reject` for errors.
  const waiters: Array<{
    resolve: (v: IteratorResult<T>) => void;
    reject: (e: Error) => void;
  }> = [];
  let done = false;
  let aborted = false;
  let errorMsg: string | null = null;

  const drainWaitersDone = (): void => {
    while (waiters.length > 0) {
      const w = waiters.shift();
      if (w !== undefined) {
        w.resolve({ value: undefined, done: true });
      }
    }
  };

  const drainWaitersError = (msg: string): void => {
    while (waiters.length > 0) {
      const w = waiters.shift();
      if (w !== undefined) {
        w.reject(new Error(msg));
      }
    }
  };

  const onChunk = (value: T): void => {
    if (aborted || done) return;
    if (waiters.length > 0) {
      const w = waiters.shift();
      if (w !== undefined) {
        w.resolve({ value, done: false });
        return;
      }
    }
    queue.push(value);
  };

  const onDone = (): void => {
    if (aborted || done) return;
    done = true;
    drainWaitersDone();
  };

  const onError = (message: string): void => {
    if (aborted || done) return;
    done = true;
    errorMsg = message;
    drainWaitersError(message);
  };

  // Kick off the producer. Synchronous invocation is fine — producers that
  // do real I/O return immediately and feed callbacks asynchronously.
  start(onChunk, onDone, onError);

  const iterator: AsyncIterableIterator<T> = {
    next(): Promise<IteratorResult<T>> {
      if (aborted) {
        return Promise.resolve({ value: undefined, done: true });
      }
      if (queue.length > 0) {
        const value = queue.shift() as T;
        return Promise.resolve({ value, done: false });
      }
      if (done) {
        if (errorMsg !== null) {
          // Surface the error exactly once. After the first reject, switch
          // to done so the consumer's loop terminates cleanly.
          const msg = errorMsg;
          errorMsg = null;
          return Promise.reject(new Error(msg));
        }
        return Promise.resolve({ value: undefined, done: true });
      }
      return new Promise<IteratorResult<T>>((resolve, reject) => {
        waiters.push({ resolve, reject });
      });
    },
    return(): Promise<IteratorResult<T>> {
      aborted = true;
      // Drop any queued values so the consumer doesn't accidentally see
      // post-cancellation chunks if they pull again.
      queue.length = 0;
      drainWaitersDone();
      return Promise.resolve({ value: undefined, done: true });
    },
    [Symbol.asyncIterator](): AsyncIterableIterator<T> {
      return this;
    },
  };
  return iterator;
}

/**
 * Stream a query against an AmateRS server, returning an
 * `AsyncIterableIterator<KeyValuePair>` that consumers iterate with
 * `for await...of`.
 *
 * Auto-initializes the WASM module if not yet done. Cancellation is
 * supported via the iterator's `return()` method (called automatically
 * when a `for await...of` loop is broken out of); the underlying WASM
 * stream is signalled to stop on the next pull.
 *
 * @example
 * ```typescript
 * for await (const kv of streamQuery('http://localhost:50051', 'users', queryObj)) {
 *   console.log(kv.key.toString(), kv.value.length);
 * }
 * ```
 *
 * ## Stub limitation
 * Until the real server-streaming RPC is wired, the producer emits exactly
 * three synthetic chunks (`k1/v1`, `k2/v2`, `k3/v3`) on each invocation.
 * The shape of the iterator and the cancellation/error semantics are real;
 * only the data is synthetic.
 *
 * @param serverUrl  Server URL (e.g. `"http://localhost:50051"`).
 * @param collection Collection name.
 * @param query      Query object to stream.
 * @returns          An async iterator yielding `KeyValuePair` values.
 */
export function streamQuery(
  serverUrl: string,
  collection: string,
  query: Query,
): AsyncIterableIterator<KeyValuePair> {
  const queryJson = JSON.stringify(query);
  return createStreamIterator<KeyValuePair>((onChunk, onDone, onError) => {
    // Auto-await init() before invoking the WASM bridge. The producer
    // function is sync but we drive an async IIFE in the background so
    // the iterator is usable immediately. Errors during init or the
    // WASM call are reported through `onError`.
    void (async () => {
      try {
        if (!_initialized) {
          await init();
        }
        await invokeWasmStreamQuery(
          serverUrl,
          collection,
          queryJson,
          onChunk,
          onDone,
          onError,
        );
      } catch (err) {
        onError(err instanceof Error ? err.message : String(err));
      }
    })();
  });
}

/**
 * Internal seam: dispatches to the wasm-pack-generated `streamQuery` export.
 *
 * In native (non-WASM) contexts the WASM module is not loaded; this
 * implementation falls back to a deterministic stub matching the Rust-side
 * `wasm_stream_query` producer so the TS test suite can exercise the
 * iterator without a wasm-pack build. Once the wasm-pack bundle is loaded,
 * replace the body with:
 *
 * ```ts
 * const { streamQuery: wasmStream } = await import('../pkg/amaters_sdk_typescript');
 * await wasmStream(serverUrl, collection, queryJson, onChunk, onDoneRaw, onErrorRaw);
 * ```
 *
 * The translation layer here adapts the WASM-side `(string, string)` chunk
 * signature into `KeyValuePair`.
 */
async function invokeWasmStreamQuery(
  serverUrl: string,
  collection: string,
  queryJson: string,
  onChunk: (kv: KeyValuePair) => void,
  onDone: () => void,
  onError: (msg: string) => void,
): Promise<void> {
  // Mirror the Rust-side validation so the stub error path matches the
  // behavior consumers will observe under wasm-pack.
  if (serverUrl.trim() === '') {
    onError('server_url must not be empty');
    return;
  }
  if (collection.trim() === '') {
    onError('collection must not be empty');
    return;
  }
  try {
    JSON.parse(queryJson);
  } catch (err) {
    onError(
      `invalid query_json: ${err instanceof Error ? err.message : String(err)}`,
    );
    return;
  }

  // Deterministic stub producer (matches the Rust side). Emits 3 chunks via
  // microtask scheduling so consumers see real backpressure between chunks.
  for (const [k, v] of [
    ['k1', 'v1'],
    ['k2', 'v2'],
    ['k3', 'v3'],
  ] as const) {
    await Promise.resolve();
    onChunk({
      key: makeKeyFromString(k),
      value: makeCipherBlobFromString(v),
    });
  }
  onDone();
}

/**
 * Get the SDK version.
 * @returns SDK version string
 */
export function getVersion(): string {
  return '0.2.1';
}

/**
 * Check if the WASM SDK has been initialized.
 *
 * Returns `false` until `init()` has been awaited. This was previously always
 * `true` (a bug); it now correctly tracks initialization state.
 *
 * @returns `true` if `init()` has completed, `false` otherwise
 */
export function isInitialized(): boolean {
  return _initialized;
}

export { WebSocketTransport } from './ws_transport';
export type { WsTransportConfig, MessageHandler, ErrorHandler } from './ws_transport';

// Default export with all types and functions
export default {
  ErrorCode,
  PredicateType,
  UpdateType,
  QueryType,
  col,
  init,
  query,
  executeQuery,
  streamQuery,
  createStreamIterator,
  getVersion,
  isInitialized,
};
