//! Permanent robustness gates for the ZIP / XZ / 7z readers (Wave 3).
//!
//! Every test here is hermetic (crafted byte vectors or embedded fixtures;
//! no external tools) and pins a specific hardening fix:
//!
//! * ZIP-02 — a crafted DOS date with month/day = 0 must not panic.
//! * XZ-01  — a block header declaring a huge compressed size must `Err`
//!   instead of aborting the process on allocation.
//! * XZ-02  — filter properties overrunning the block header must `Err`
//!   instead of indexing out of bounds.
//! * XZ-03  — a corrupted block header must be rejected by its CRC32
//!   before any parsed field is trusted.
//! * SEVENZ-01 — unbounded complex-coder stream counts must `Err` instead
//!   of a capacity-overflow panic / TiB reservation.
//! * SEVENZ-02 — an unbounded SubStreamsInfo `kCrc` aggregate must `Err`
//!   instead of reserving hundreds of MiB from a ~200-byte header.
//! * Multi-chunk XZ — a real `xz -6` stream whose block spans several
//!   LZMA2 chunks must decode byte-exactly at the archive level
//!   (embedded fixture generated by XZ Utils).

use oxiarc_archive::sevenz::SevenZReader;
use oxiarc_archive::xz;
use oxiarc_archive::zip::{ZipReader, ZipWriter};
use oxiarc_core::Crc32;
use std::io::Cursor;

// =========================================================================
// ZIP-02: month-0 / day-0 DOS date must not panic
// =========================================================================

/// Locate `sig` in `haystack` and return the offset after it.
fn find_sig(haystack: &[u8], sig: &[u8]) -> usize {
    haystack
        .windows(sig.len())
        .position(|w| w == sig)
        .expect("signature not found in crafted archive")
}

#[test]
fn zip_month_zero_dos_date_does_not_panic() {
    // Build a normal one-file archive, then zero out the DOS time/date
    // words in both the local and the central-directory headers — the
    // shape produced by the fuzzer that previously panicked with
    // "attempt to subtract with overflow" in read_central_dir_entry.
    let mut bytes = Vec::new();
    {
        let mut writer = ZipWriter::new(&mut bytes);
        writer
            .add_file("clock.txt", b"time flies like an arrow")
            .expect("add_file");
        writer.finish().expect("finish");
    }

    // Local file header: mtime at +10, mdate at +12 from the signature.
    let local = find_sig(&bytes, &[0x50, 0x4B, 0x03, 0x04]);
    for b in &mut bytes[local + 10..local + 14] {
        *b = 0;
    }
    // Central directory header: mtime at +12, mdate at +14.
    let central = find_sig(&bytes, &[0x50, 0x4B, 0x01, 0x02]);
    for b in &mut bytes[central + 12..central + 16] {
        *b = 0;
    }

    // Opening must not panic, the timestamp must be usable, and the
    // payload (whose CRC is untouched) must still extract byte-exactly.
    let mut reader = ZipReader::new(Cursor::new(&bytes)).expect("open crafted zip");
    let entry = reader.entries()[0].clone();
    let modified = entry.modified.expect("modified timestamp present");
    assert!(modified >= std::time::UNIX_EPOCH);
    let data = reader.extract(&entry).expect("extract");
    assert_eq!(data, b"time flies like an arrow");
}

// =========================================================================
// XZ crafted-header gates
// =========================================================================

/// XZ stream header for CRC32 check type.
fn xz_stream_header() -> Vec<u8> {
    let mut out = vec![0xFD, 0x37, 0x7A, 0x58, 0x5A, 0x00];
    let flags = [0x00, 0x01]; // check type: CRC32
    out.extend_from_slice(&flags);
    out.extend_from_slice(&Crc32::compute(&flags).to_le_bytes());
    out
}

/// Assemble a block header from its body: size byte + body + padding +
/// valid CRC32, exactly as the xz spec lays it out.
fn xz_block_header(body: &[u8]) -> Vec<u8> {
    let header_size_byte = ((body.len() + 4) / 4) as u8;
    let total = (header_size_byte as usize + 1) * 4;
    let padding = total - 1 - body.len() - 4;

    let mut padded = body.to_vec();
    padded.resize(body.len() + padding, 0x00);

    let mut crc_input = Vec::with_capacity(1 + padded.len());
    crc_input.push(header_size_byte);
    crc_input.extend_from_slice(&padded);
    let crc = Crc32::compute(&crc_input);

    let mut out = Vec::with_capacity(total);
    out.push(header_size_byte);
    out.extend_from_slice(&padded);
    out.extend_from_slice(&crc.to_le_bytes());
    out
}

/// Encode an xz-style multibyte integer.
fn xz_varint(mut value: u64) -> Vec<u8> {
    let mut out = Vec::new();
    loop {
        let byte = (value & 0x7F) as u8;
        value >>= 7;
        if value == 0 {
            out.push(byte);
            break;
        }
        out.push(byte | 0x80);
    }
    out
}

#[test]
fn xz_huge_declared_compressed_size_errors_without_abort() {
    // XZ-01: block header declares compressed_size = 2^60. The old code
    // did `vec![0u8; compressed_size]` and aborted the process with an
    // allocation failure; it must now return Err.
    let mut body = vec![0x40]; // flags: 1 filter, has compressed size
    body.extend_from_slice(&xz_varint(1u64 << 60));
    body.extend_from_slice(&[0x21, 0x01, 0x00]); // LZMA2 filter, 1 prop byte

    let mut stream = xz_stream_header();
    stream.extend_from_slice(&xz_block_header(&body));

    let result = xz::decompress(&mut Cursor::new(&stream));
    assert!(result.is_err(), "huge declared size must be rejected");
}

#[test]
fn xz_filter_props_overrunning_header_errors_without_panic() {
    // XZ-02: the LZMA2 filter declares 127 property bytes but the header
    // body ends long before that. The old code indexed `header[offset]`
    // unchecked; it must now return Err.
    let body = vec![0x00, 0x21, 0x7F]; // flags: 1 filter; LZMA2; props = 127
    let mut stream = xz_stream_header();
    stream.extend_from_slice(&xz_block_header(&body));

    let result = xz::decompress(&mut Cursor::new(&stream));
    assert!(result.is_err(), "overrunning filter props must be rejected");
}

#[test]
fn xz_truncated_props_varint_errors_without_panic() {
    // XZ-02 (varint shape): the props-size varint has its continuation
    // bit set on the final body byte, so parsing runs off the end.
    let body = vec![0x00, 0x21, 0x80]; // flags: 1 filter; LZMA2; truncated varint
    let mut stream = xz_stream_header();
    stream.extend_from_slice(&xz_block_header(&body));

    let result = xz::decompress(&mut Cursor::new(&stream));
    assert!(result.is_err(), "truncated props varint must be rejected");
}

#[test]
fn xz_block_header_bitflip_rejected_by_crc() {
    // XZ-03: any bit flip inside the block header (here: the filter-id
    // byte) must be caught by the now-validated header CRC32.
    let original = b"xz block header CRC must be validated".to_vec();
    let mut compressed = xz::compress(&original, 6).expect("compress");

    // Stream header is 12 bytes; byte 12 is the block-header size byte,
    // byte 13 the first body byte. Flip a body byte without fixing the CRC.
    compressed[14] ^= 0x10;

    let result = xz::decompress(&mut Cursor::new(&compressed));
    assert!(
        result.is_err(),
        "corrupted block header must be rejected before use"
    );
}

// =========================================================================
// Multi-chunk XZ (real `xz -6` output) at the archive level
// =========================================================================

/// The fixture was produced by XZ Utils (`xz -6`) from 128 KiB of
/// deterministic data: 2048 alternating 64-byte blocks — even blocks from
/// the xorshift64 stream below, odd blocks a fixed text pattern. Its single
/// block spans two LZMA2 chunks (61 KiB + 6 KiB compressed), the second
/// with control byte 0x80 (no state/dictionary reset), which requires the
/// decoder's persistent uncompressed position to resolve back-references.
const MULTICHUNK_XZ: &[u8] = include_bytes!("data/xz_multichunk_xz6.xz");

fn xorshift_stream(seed: u64, len: usize) -> Vec<u8> {
    let mut state = seed | 1;
    let mut out = Vec::with_capacity(len + 8);
    while out.len() < len {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        out.extend_from_slice(&state.to_le_bytes());
    }
    out.truncate(len);
    out
}

fn multichunk_plaintext() -> Vec<u8> {
    let pattern: Vec<u8> = b"OxiArc multi-chunk XZ interop fixture block. "
        .iter()
        .cycle()
        .take(64)
        .copied()
        .collect();
    let prng = xorshift_stream(0x0A2C_57F3_11D4_B689, 64 * 1024);
    let mut data = Vec::with_capacity(128 * 1024);
    let mut prng_off = 0;
    for i in 0..2048 {
        if i % 2 == 0 {
            data.extend_from_slice(&prng[prng_off..prng_off + 64]);
            prng_off += 64;
        } else {
            data.extend_from_slice(&pattern);
        }
    }
    data
}

#[test]
fn xz_real_cli_multichunk_block_decodes_byte_exact() {
    let expected = multichunk_plaintext();
    assert_eq!(expected.len(), 128 * 1024);

    let decoded = xz::decompress(&mut Cursor::new(MULTICHUNK_XZ))
        .expect("decode real xz -6 multi-chunk stream");
    assert_eq!(decoded.len(), expected.len(), "decoded length mismatch");
    assert_eq!(decoded, expected, "decoded bytes mismatch");
}

// =========================================================================
// 7z crafted-header gates
// =========================================================================

const SEVENZ_MAGIC: [u8; 6] = [0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C];

/// Wrap raw next-header bytes in a valid 32-byte 7z signature header
/// (correct start-header and next-header CRC32s) so parsing reaches the
/// header body under test.
fn sevenz_archive(header: &[u8]) -> Vec<u8> {
    let mut sig = vec![0u8; 32];
    sig[0..6].copy_from_slice(&SEVENZ_MAGIC);
    sig[6] = 0; // major version
    sig[7] = 4; // minor version
    sig[12..20].copy_from_slice(&0u64.to_le_bytes()); // next header offset
    sig[20..28].copy_from_slice(&(header.len() as u64).to_le_bytes());
    sig[28..32].copy_from_slice(&Crc32::compute(header).to_le_bytes());
    let start_crc = Crc32::compute(&sig[12..32]);
    sig[8..12].copy_from_slice(&start_crc.to_le_bytes());
    sig.extend_from_slice(header);
    sig
}

/// Encode a value in the full 8-extra-byte form of a 7z variable-length
/// number (always valid, independent of magnitude).
fn sevenz_number_full(value: u64) -> Vec<u8> {
    let mut out = vec![0xFF];
    out.extend_from_slice(&value.to_le_bytes());
    out
}

#[test]
fn sevenz_unbounded_complex_coder_stream_counts_error() {
    // SEVENZ-01: a complex coder declaring 2^40 input/output streams.
    // The old code fed `total_out_streams - 1` straight into
    // `Vec::with_capacity` (capacity-overflow panic / TiB reservation).
    let mut header = vec![
        0x01, // kHeader
        0x04, // kMainStreamsInfo
        0x06, // kPackInfo
        0x00, // pack pos = 0
        0x01, // 1 pack stream
        0x09, 0x01, // kSize: [1]
        0x00, // kEnd (PackInfo)
        0x07, // kUnpackInfo
        0x0B, // kFolder
        0x01, // 1 folder
        0x00, // not external
        0x01, // 1 coder
        0x11, // codec-id size 1 | complex (0x10)
        0x00, // codec id: Copy
    ];
    header.extend_from_slice(&sevenz_number_full(1u64 << 40)); // num in streams
    header.extend_from_slice(&sevenz_number_full(1u64 << 40)); // num out streams

    let result = SevenZReader::new(Cursor::new(sevenz_archive(&header)));
    assert!(
        result.is_err(),
        "unbounded coder stream counts must be rejected"
    );
}

#[test]
fn sevenz_moderate_but_implausible_stream_counts_error() {
    // SEVENZ-01 (second shape): counts that pass the generic 16M bound
    // but exceed any real folder layout (reference limit: 64 streams).
    let mut header = vec![
        0x01, 0x04, // kHeader, kMainStreamsInfo
        0x06, 0x00, 0x01, 0x09, 0x01, 0x00, // kPackInfo {pos 0, 1 stream, size [1]}
        0x07, 0x0B, 0x01, 0x00, // kUnpackInfo, kFolder, 1 folder, internal
        0x01, 0x11, 0x00, // 1 coder, complex copy coder
    ];
    header.extend_from_slice(&sevenz_number_full(100_000)); // in streams
    header.extend_from_slice(&sevenz_number_full(100_000)); // out streams

    let result = SevenZReader::new(Cursor::new(sevenz_archive(&header)));
    assert!(
        result.is_err(),
        "implausible folder stream counts must be rejected"
    );
}

#[test]
fn sevenz_unbounded_substream_crc_aggregate_errors() {
    // SEVENZ-02: one folder claiming 16M substreams, then a kCrc block
    // with AllAreDefined = 1 and no digest bytes. The old code
    // materialized `vec![true; 16M]` (and 256 MiB for 16 such folders)
    // without consuming a single input byte; it must now Err because
    // 16M digests could never fit in the remaining header bytes.
    let mut header = vec![
        0x01, 0x04, // kHeader, kMainStreamsInfo
        0x06, 0x00, 0x01, 0x09, 0x40, 0x00, // kPackInfo {pos 0, 1 stream, size [64]}
        0x07, // kUnpackInfo
        0x0B, 0x01, 0x00, // kFolder, 1 folder, internal
        0x01, 0x01, 0x00, // 1 coder: simple Copy
        0x0C, 0x40, // kCodersUnpackSize: [64]
        0x00, // kEnd (UnpackInfo)
        0x08, // kSubStreamsInfo
        0x0D, // kNumUnpackStream
    ];
    header.extend_from_slice(&sevenz_number_full(16 * 1024 * 1024)); // 16M substreams
    header.push(0x0A); // kCrc
    header.push(0x01); // AllAreDefined = 1, no digest bytes follow

    let result = SevenZReader::new(Cursor::new(sevenz_archive(&header)));
    assert!(
        result.is_err(),
        "unbounded substream CRC aggregate must be rejected"
    );
}

#[test]
fn sevenz_multi_folder_substream_sum_overflow_errors() {
    // SEVENZ-02 (aggregate-across-folders shape): 16 folders x 16M
    // substreams each — every per-folder count is individually within the
    // 16M bound, but the 256M aggregate must be rejected.
    let mut header = vec![
        0x01, 0x04, // kHeader, kMainStreamsInfo
        0x06, 0x00, 0x10, // kPackInfo: pos 0, 16 pack streams
        0x09, // kSize
    ];
    header.extend_from_slice(&[0x01; 16]); // 16 pack sizes of 1
    header.push(0x00); // kEnd (PackInfo)
    header.extend_from_slice(&[0x07, 0x0B, 0x10, 0x00]); // kUnpackInfo, kFolder, 16, internal
    for _ in 0..16 {
        header.extend_from_slice(&[0x01, 0x01, 0x00]); // simple Copy coder
    }
    header.push(0x0C); // kCodersUnpackSize
    header.extend_from_slice(&[0x40; 16]); // 16 unpack sizes of 64
    header.push(0x00); // kEnd (UnpackInfo)
    header.extend_from_slice(&[0x08, 0x0D]); // kSubStreamsInfo, kNumUnpackStream
    for _ in 0..16 {
        header.extend_from_slice(&sevenz_number_full(16 * 1024 * 1024));
    }
    header.push(0x0A); // kCrc
    header.push(0x01); // AllAreDefined

    let result = SevenZReader::new(Cursor::new(sevenz_archive(&header)));
    assert!(result.is_err(), "256M substream aggregate must be rejected");
}

#[test]
fn sevenz_valid_fixture_still_opens_after_hardening() {
    // Guard against over-tightening: the embedded bsdtar fixture (real
    // multi-entry archive with SubStreamsInfo CRCs) must still parse and
    // extract after the new bounds.
    let bytes: &[u8] = include_bytes!("data/sevenz_bsdtar_copy.7z");
    let mut reader = SevenZReader::new(Cursor::new(bytes)).expect("open fixture");
    let entries = reader.sevenz_entries().to_vec();
    assert_eq!(entries.len(), 5);
    let alpha = entries
        .iter()
        .position(|e| e.name == "alpha.txt")
        .expect("alpha.txt present");
    let data = reader.extract(alpha).expect("extract alpha.txt");
    assert_eq!(data, b"Hello, 7z world!\n");
}
