//! Real RDF store loading and query execution for scenario workload runs.
//!
//! Converts the synthetic validation datasets' CURIE-prefixed strings (see
//! `crate::datasets`) into genuine `oxirs_core` RDF terms and bulk-loads them
//! into an in-memory `RdfStore`, then executes each dataset's real SPARQL
//! query templates through the full `oxirs-arq` parser and algebra executor
//! -- the same engine `oxirs-fuseki` uses in production -- instead of
//! approximating latency/throughput with a `tokio::time::sleep()`.

use crate::datasets::{Dataset, Triple as DatasetTriple};
use anyhow::{anyhow, Result};
use oxirs_arq::executor::{QueryExecutor, StoreRefDataset};
use oxirs_core::model::{Literal, NamedNode, Object, Quad, Triple};
use oxirs_core::rdf_store::Store as StoreTrait;
use oxirs_core::RdfStore;

/// CURIE prefix -> base IRI table covering every prefix produced by the
/// synthetic dataset generators (`crate::datasets`) and referenced by their
/// matching SPARQL query templates.
const PREFIX_TABLE: &[(&str, &str)] = &[
    ("dbo", "http://dbpedia.org/ontology/"),
    ("dbr", "http://dbpedia.org/resource/"),
    ("wd", "http://www.wikidata.org/entity/"),
    ("wdt", "http://www.wikidata.org/prop/direct/"),
    ("bio", "http://biomedical.org/entity/"),
    ("bioprop", "http://biomedical.org/property/"),
    ("synth", "http://synthetic.org/entity/"),
    ("synthprop", "http://synthetic.org/property/"),
    ("xsd", "http://www.w3.org/2001/XMLSchema#"),
];

/// Expand a `prefix:local` CURIE into a full IRI string using
/// [`PREFIX_TABLE`]. Returns `None` for unrecognized prefixes (never
/// fabricates an IRI for a prefix it doesn't know).
fn expand_curie(raw: &str) -> Option<String> {
    let (prefix, local) = raw.split_once(':')?;
    let base = PREFIX_TABLE
        .iter()
        .find(|(p, _)| *p == prefix)
        .map(|(_, base)| *base)?;
    Some(format!("{base}{local}"))
}

/// Parse a CURIE-prefixed subject/predicate string into a real `NamedNode`.
pub fn parse_named_node_term(raw: &str) -> Result<NamedNode> {
    let expanded =
        expand_curie(raw).ok_or_else(|| anyhow!("unrecognized CURIE prefix in term '{raw}'"))?;
    NamedNode::new(expanded).map_err(|e| anyhow!("invalid IRI expanded from '{raw}': {e}"))
}

/// Parse a triple-object string, which is either another CURIE-prefixed
/// entity reference or an RDF literal (`"value"^^xsd:type`, `"value"@lang`,
/// or a plain quoted string), as generated by `crate::datasets`.
pub fn parse_object_term(raw: &str) -> Result<Object> {
    if let Some(rest) = raw.strip_prefix('"') {
        let close_idx = rest
            .find('"')
            .ok_or_else(|| anyhow!("malformed literal (missing closing quote): '{raw}'"))?;
        let value = &rest[..close_idx];
        let suffix = &rest[close_idx + 1..];

        if let Some(lang) = suffix.strip_prefix('@') {
            let literal = Literal::new_language_tagged_literal(value, lang)
                .map_err(|e| anyhow!("invalid language tag in literal '{raw}': {e}"))?;
            return Ok(Object::Literal(literal));
        }

        if let Some(datatype_curie) = suffix.strip_prefix("^^") {
            let datatype_iri = expand_curie(datatype_curie)
                .ok_or_else(|| anyhow!("unrecognized datatype prefix in literal '{raw}'"))?;
            let datatype = NamedNode::new(datatype_iri)
                .map_err(|e| anyhow!("invalid datatype IRI in literal '{raw}': {e}"))?;
            return Ok(Object::Literal(Literal::new_typed_literal(value, datatype)));
        }

        return Ok(Object::Literal(Literal::new(value)));
    }

    if let Some(expanded) = expand_curie(raw) {
        return NamedNode::new(expanded)
            .map(Object::NamedNode)
            .map_err(|e| anyhow!("invalid IRI expanded from object '{raw}': {e}"));
    }

    // Unknown shape (neither a quoted literal nor a recognized CURIE):
    // preserve the raw text verbatim as a plain literal rather than
    // guessing at or silently dropping the value.
    Ok(Object::Literal(Literal::new(raw)))
}

/// Convert one synthetic dataset triple into a real `oxirs_core::model::Triple`.
fn convert_triple(triple: &DatasetTriple) -> Result<Triple> {
    let subject = parse_named_node_term(&triple.subject)?;
    let predicate = parse_named_node_term(&triple.predicate)?;
    let object = parse_object_term(&triple.object)?;
    Ok(Triple::new(subject, predicate, object))
}

/// Bulk-load every triple from the given datasets into a fresh in-memory
/// `RdfStore`, so scenario queries execute against real, queryable data.
pub fn load_datasets_into_store(datasets: &[&Dataset]) -> Result<RdfStore> {
    let store = RdfStore::new().map_err(|e| anyhow!("failed to create RDF store: {e}"))?;

    let mut quads = Vec::new();
    for dataset in datasets {
        for triple in &dataset.triples {
            quads.push(Quad::from_triple(convert_triple(triple)?));
        }
    }

    if quads.is_empty() {
        return Err(anyhow!(
            "no triples available to load into the scenario store"
        ));
    }

    store
        .bulk_insert_quads(quads)
        .map_err(|e| anyhow!("failed to bulk-load triples into the RDF store: {e}"))?;

    Ok(store)
}

/// Execute a real SPARQL query against the loaded store using the full
/// oxirs-arq parser and algebra executor -- the same engine oxirs-fuseki
/// dispatches production HTTP queries to -- and return the number of
/// solution rows actually produced.
///
/// A malformed or unsupported query surfaces as a real `Err` (fail-loud);
/// it is never silently treated as zero results.
pub fn execute_query(sparql: &str, store: &RdfStore) -> Result<usize> {
    let query =
        oxirs_arq::query::parse_query(sparql).map_err(|e| anyhow!("SPARQL parse error: {e}"))?;

    let store_ref: &dyn StoreTrait = store;
    let dataset = StoreRefDataset::new(store_ref);
    let mut executor = QueryExecutor::new();
    let (solution, _stats) = executor
        .execute(&query.where_clause, &dataset)
        .map_err(|e| anyhow!("SPARQL execution error: {e}"))?;

    Ok(solution.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::datasets::{
        DatasetComplexity, DatasetConfig, DatasetDomain, DatasetFormat, DatasetSize,
        DatasetStatistics, QueryTemplate,
    };

    fn tiny_dataset() -> Dataset {
        Dataset {
            config: DatasetConfig {
                name: "regression_tiny".to_string(),
                size: DatasetSize::Small,
                format: DatasetFormat::NTriples,
                complexity: DatasetComplexity::Simple,
                include_embeddings: false,
                embedding_dimensions: 0,
                domain: DatasetDomain::General,
            },
            triples: vec![
                DatasetTriple {
                    subject: "dbr:Person_1".to_string(),
                    predicate: "dbo:birthPlace".to_string(),
                    object: "dbr:Place_1".to_string(),
                },
                DatasetTriple {
                    subject: "dbr:Person_1".to_string(),
                    predicate: "dbo:label".to_string(),
                    object: "\"Alice\"@en".to_string(),
                },
                DatasetTriple {
                    subject: "dbr:Person_1".to_string(),
                    predicate: "dbo:populationTotal".to_string(),
                    object: "\"42\"^^xsd:int".to_string(),
                },
            ],
            embeddings: None,
            query_templates: vec![QueryTemplate {
                name: "regression_lookup".to_string(),
                sparql: r#"
                    PREFIX dbo: <http://dbpedia.org/ontology/>
                    PREFIX dbr: <http://dbpedia.org/resource/>
                    SELECT ?p ?o WHERE { dbr:Person_1 ?p ?o }
                "#
                .to_string(),
                complexity: DatasetComplexity::Simple,
                expected_result_count: Some(3),
                estimated_execution_time_ms: Some(5),
            }],
            statistics: DatasetStatistics {
                triple_count: 3,
                unique_subjects: 1,
                unique_predicates: 3,
                unique_objects: 3,
                avg_subject_degree: 3.0,
                avg_predicate_frequency: 1.0,
                graph_density: 0.0,
            },
        }
    }

    #[test]
    fn regression_expand_curie_known_prefix() {
        assert_eq!(
            expand_curie("dbr:Person_1").as_deref(),
            Some("http://dbpedia.org/resource/Person_1")
        );
    }

    #[test]
    fn regression_expand_curie_unknown_prefix_returns_none() {
        assert_eq!(expand_curie("nope:Foo"), None);
    }

    #[test]
    fn regression_parse_object_term_entity_reference() {
        let object = parse_object_term("dbr:Place_1").expect("valid CURIE");
        match object {
            Object::NamedNode(n) => {
                assert_eq!(n.as_str(), "http://dbpedia.org/resource/Place_1")
            }
            other => panic!("expected NamedNode, got {other:?}"),
        }
    }

    #[test]
    fn regression_parse_object_term_typed_literal() {
        let object = parse_object_term("\"42\"^^xsd:int").expect("valid typed literal");
        match object {
            Object::Literal(l) => {
                assert_eq!(l.value(), "42");
                assert_eq!(
                    l.datatype().as_str(),
                    "http://www.w3.org/2001/XMLSchema#int"
                );
            }
            other => panic!("expected Literal, got {other:?}"),
        }
    }

    #[test]
    fn regression_parse_object_term_language_tagged_literal() {
        let object = parse_object_term("\"Alice\"@en").expect("valid language-tagged literal");
        match object {
            Object::Literal(l) => {
                assert_eq!(l.value(), "Alice");
                assert_eq!(l.language(), Some("en"));
            }
            other => panic!("expected Literal, got {other:?}"),
        }
    }

    #[test]
    fn regression_load_datasets_into_store_executes_real_sparql_query() {
        // This is the core proof that the scenario workload path now runs a
        // genuine SPARQL query (with real PREFIX + LIMIT handling via the
        // full oxirs-arq parser) against genuine, loaded RDF data, rather
        // than sleeping and reporting the sleep duration as "measured"
        // latency.
        let dataset = tiny_dataset();
        let store = load_datasets_into_store(&[&dataset]).expect("store should load");

        let row_count = execute_query(&dataset.query_templates[0].sparql, &store)
            .expect("real query execution should succeed against the loaded store");

        assert_eq!(
            row_count, 3,
            "query should return exactly the 3 real triples loaded for dbr:Person_1"
        );
    }

    #[test]
    fn regression_execute_query_real_query_with_prefix_and_limit() {
        // The dataset's own production query templates use PREFIX + LIMIT,
        // which oxirs-core's simplified placeholder parser cannot handle;
        // the real oxirs-arq parser must succeed on them.
        let dataset = tiny_dataset();
        let store = load_datasets_into_store(&[&dataset]).expect("store should load");

        let sparql = r#"
            PREFIX dbo: <http://dbpedia.org/ontology/>
            PREFIX dbr: <http://dbpedia.org/resource/>
            SELECT ?p ?o WHERE {
                dbr:Person_1 ?p ?o .
            } LIMIT 1
        "#;

        let row_count = execute_query(sparql, &store)
            .expect("PREFIX + LIMIT queries must be handled by the real arq parser");
        assert!(row_count > 0, "expected at least one real matching row");
    }

    #[test]
    fn regression_execute_query_malformed_sparql_fails_loud() {
        let dataset = tiny_dataset();
        let store = load_datasets_into_store(&[&dataset]).expect("store should load");

        let result = execute_query("NOT A REAL SPARQL QUERY", &store);
        assert!(
            result.is_err(),
            "an unparseable query must return a real Err, not a fabricated empty success"
        );
    }

    #[test]
    fn regression_load_datasets_into_store_rejects_unknown_prefix() {
        let mut dataset = tiny_dataset();
        dataset.triples.push(DatasetTriple {
            subject: "unknownprefix:Foo".to_string(),
            predicate: "dbo:label".to_string(),
            object: "dbr:Place_1".to_string(),
        });

        let result = load_datasets_into_store(&[&dataset]);
        assert!(
            result.is_err(),
            "an unrecognized CURIE prefix must fail loudly, not be silently dropped or guessed"
        );
    }
}
