#![forbid(unsafe_code)]
#![warn(missing_docs)]
//! Build-time proto compiler for OxiRPC — no `protoc` required.
//!
//! Uses `oxiproto-build` (which delegates to `protox`, a pure-Rust `.proto`
//! parser) to parse and resolve `.proto` files without spawning `protoc`.
//!
//! # Default codegen path (native `ServiceCodegen`)
//!
//! `Builder::compile()` now routes through [`codegen::ServiceCodegen`] by
//! default.  This emits **service stub modules** (`*_server` / `*_client`)
//! for every service declared in the `.proto` files.
//!
//! **Important:** the native path emits service stubs only — it does **not**
//! generate prost message types.  Downstream `build.rs` users that need
//! message type generation should either:
//!
//! 1. Run `prost_build` (or `tonic_prost_build`) separately for message types,
//!    then use `Builder::compile()` for service stubs.
//! 2. Enable the `legacy-tonic-codegen` feature (see below) to restore the
//!    previous all-in-one code generation via `tonic-prost-build`.
//!
//! # Legacy path (`tonic-prost-build`)
//!
//! Opt in with `features = ["legacy-tonic-codegen"]` in your
//! `[build-dependencies]`.  When active, `Builder::compile()` delegates to
//! `tonic_prost_build::compile_fds`, which generates both prost message types
//! and service stubs in a single pass.  All `Builder::type_attribute`,
//! `field_attribute`, `btree_map`, `bytes`, `extern_path`, and
//! `compile_well_known_types` settings apply exclusively to this path.
//!
//! # Example (`build.rs`) — default native path
//!
//! ```rust,ignore
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     oxirpc_build::compile_protos(&["proto/greeter.proto"], &["proto/"])?;
//!     Ok(())
//! }
//! ```
//!
//! # Example (`build.rs`) — legacy path (Cargo.toml: `features = ["legacy-tonic-codegen"]`)
//!
//! ```rust,ignore
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     // Both message types and service stubs generated by tonic-prost-build.
//!     oxirpc_build::compile_protos(&["proto/greeter.proto"], &["proto/"])?;
//!     Ok(())
//! }
//! ```

use std::path::Path;

// ---------------------------------------------------------------------------
// Incremental build cache
// ---------------------------------------------------------------------------

mod cache;

// ---------------------------------------------------------------------------
// Native codegen modules (public)
// ---------------------------------------------------------------------------

/// Native async Rust client and server stub code generator.
///
/// Generates gRPC service stubs directly from [`prost_types::ServiceDescriptorProto`]
/// without requiring `protoc` or external code-generation binaries.
pub mod codegen;

/// Integration helper: generate service stubs from a `FileDescriptorSet` and
/// write them to an output directory.
pub mod file_gen;

// Re-export the primary entry points for convenience.
pub use codegen::ServiceCodegen;
pub use file_gen::generate_services;

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors produced during build-time proto compilation.
#[derive(Debug)]
pub enum OxiRpcBuildError {
    /// A protobuf schema error, with optional source location.
    Proto {
        /// Source file path (if available).
        path: Option<String>,
        /// Line number (1-indexed, if available).
        line: Option<u32>,
        /// Column number (1-indexed, if available).
        col: Option<u32>,
        /// Human-readable error message.
        msg: String,
    },
    /// Code generation error.
    Codegen(String),
    /// I/O failure.
    Io(std::io::Error),
}

impl std::fmt::Display for OxiRpcBuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OxiRpcBuildError::Proto {
                path,
                line,
                col,
                msg,
            } => match (path, line, col) {
                (Some(p), Some(l), Some(c)) => write!(f, "{p}:{l}:{c}: {msg}"),
                (Some(p), Some(l), None) => write!(f, "{p}:{l}: {msg}"),
                (Some(p), None, _) => write!(f, "{p}: {msg}"),
                _ => write!(f, "proto parse error: {msg}"),
            },
            OxiRpcBuildError::Codegen(s) => write!(f, "codegen error: {s}"),
            OxiRpcBuildError::Io(e) => write!(f, "I/O error: {e}"),
        }
    }
}

impl std::error::Error for OxiRpcBuildError {}

impl From<std::io::Error> for OxiRpcBuildError {
    fn from(e: std::io::Error) -> Self {
        OxiRpcBuildError::Io(e)
    }
}
// ---------------------------------------------------------------------------
// oxiproto_core::OxiProtoError → OxiRpcBuildError conversion
// ---------------------------------------------------------------------------

/// Convert an [`oxiproto_core::OxiProtoError`] to [`OxiRpcBuildError`].
///
/// Parse errors are mapped to [`OxiRpcBuildError::Proto`] with structured
/// location info extracted from the `"file:line:col: message"` pattern.
/// I/O errors become [`OxiRpcBuildError::Io`]; codegen errors become
/// [`OxiRpcBuildError::Codegen`].
fn from_oxiproto_error(e: oxiproto_core::OxiProtoError) -> OxiRpcBuildError {
    match e {
        oxiproto_core::OxiProtoError::ParseError(ref msg) => {
            // Attempt to parse "file:line:col: message" prefix so we can
            // populate the structured Proto variant with location info.
            parse_proto_error_string(msg)
        }
        oxiproto_core::OxiProtoError::IoError(io_err) => OxiRpcBuildError::Io(io_err),
        oxiproto_core::OxiProtoError::CodegenError(msg) => OxiRpcBuildError::Codegen(msg),
        other => OxiRpcBuildError::Codegen(other.to_string()),
    }
}

/// Parse a `"file:line:col: message"` or `"file:line: message"` string into an
/// [`OxiRpcBuildError::Proto`] with structured location information.
///
/// Falls back to `Proto { path: None, line: None, col: None, msg }` when the
/// prefix is absent or malformed.
fn parse_proto_error_string(msg: &str) -> OxiRpcBuildError {
    // Strategy: split on ':' and try to read u32 segments at positions 1 and 2.
    // We must handle Windows drive letters like "C:\path\file.proto:3:5: …"
    // by skipping single-char segments as likely drive letters.
    let parts: Vec<&str> = msg.splitn(5, ':').collect();

    if parts.len() >= 3 {
        // Handle Windows drive letter prefix: if parts[0] is a single ASCII
        // alpha char, the "file" part is parts[0] + ":" + parts[1].
        let (file_raw, line_idx, col_idx) = if parts[0].len() == 1
            && parts[0]
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic())
        {
            if parts.len() >= 5 {
                let file = format!("{}:{}", parts[0], parts[1]);
                (Some(file), 2usize, 3usize)
            } else {
                return OxiRpcBuildError::Proto {
                    path: None,
                    line: None,
                    col: None,
                    msg: msg.to_owned(),
                };
            }
        } else {
            (Some(parts[0].to_owned()), 1usize, 2usize)
        };

        if let Ok(line) = parts[line_idx].trim().parse::<u32>() {
            if let Ok(col) = parts[col_idx].trim().parse::<u32>() {
                let message = parts[(col_idx + 1)..]
                    .join(":")
                    .trim_start_matches(' ')
                    .to_owned();
                return OxiRpcBuildError::Proto {
                    path: file_raw,
                    line: Some(line),
                    col: Some(col),
                    msg: if message.is_empty() {
                        msg.to_owned()
                    } else {
                        message
                    },
                };
            }
            let message = parts[(line_idx + 1)..]
                .join(":")
                .trim_start_matches(' ')
                .to_owned();
            return OxiRpcBuildError::Proto {
                path: file_raw,
                line: Some(line),
                col: None,
                msg: if message.is_empty() {
                    msg.to_owned()
                } else {
                    message
                },
            };
        }
    }

    OxiRpcBuildError::Proto {
        path: None,
        line: None,
        col: None,
        msg: msg.to_owned(),
    }
}

// ---------------------------------------------------------------------------
// CompileOutput
// ---------------------------------------------------------------------------

/// Output of a checked build compilation.
#[derive(Debug)]
pub struct CompileOutput {
    /// Non-fatal warnings about proto structure (e.g. missing package, potentially unused imports).
    pub warnings: Vec<String>,
}

// ---------------------------------------------------------------------------
// Progress callback type alias
// ---------------------------------------------------------------------------

/// Type alias for the progress callback used in [`Builder::on_progress`].
///
/// The callback receives a short human-readable status string at compilation
/// checkpoints such as `"parsing protos..."`, `"generating code..."`, or
/// `"writing output..."`.
pub type ProgressCallback = std::sync::Arc<dyn Fn(&str) + Send + Sync>;

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

/// Builder for configuring proto compilation.
///
/// # Note on receiver asymmetry
///
/// `compile()` consumes `self` (it was designed that way to avoid internal
/// cloning in the hot build-script path).  `compile_to_fds()`,
/// `compile_checked()`, and `compile_str()` all take `&self` and clone
/// internally.  New code should prefer the `&self` methods; `compile()` is
/// kept for back-compat.
#[derive(Clone)]
pub struct Builder {
    out_dir: Option<std::path::PathBuf>,
    build_client: bool,
    build_server: bool,
    type_attrs: Vec<(String, String)>,
    field_attrs: Vec<(String, String)>,
    extern_paths: Vec<(String, String)>,
    server_mod_attrs: Vec<(String, String)>,
    client_mod_attrs: Vec<(String, String)>,
    btree_maps: Vec<String>,
    bytes_paths: Vec<String>,
    fds_path: Option<std::path::PathBuf>,
    include_file: Option<std::path::PathBuf>,
    compile_well_known_types: bool,
    codec_path: Option<String>,
    progress_cb: Option<ProgressCallback>,
    disable_package_emission: bool,
}

impl Builder {
    /// Create a new builder with default settings.
    pub fn new() -> Self {
        Self {
            out_dir: None,
            build_client: true,
            build_server: true,
            type_attrs: Vec::new(),
            field_attrs: Vec::new(),
            extern_paths: Vec::new(),
            server_mod_attrs: Vec::new(),
            client_mod_attrs: Vec::new(),
            btree_maps: Vec::new(),
            bytes_paths: Vec::new(),
            fds_path: None,
            include_file: None,
            compile_well_known_types: false,
            codec_path: None,
            progress_cb: None,
            disable_package_emission: false,
        }
    }

    /// Set the output directory for generated files.
    pub fn out_dir(mut self, path: impl Into<std::path::PathBuf>) -> Self {
        self.out_dir = Some(path.into());
        self
    }

    /// Whether to generate client code (default: `true`).
    pub fn build_client(mut self, v: bool) -> Self {
        self.build_client = v;
        self
    }

    /// Whether to generate server code (default: `true`).
    pub fn build_server(mut self, v: bool) -> Self {
        self.build_server = v;
        self
    }

    /// Add a type-level attribute to a generated type.
    pub fn type_attribute(mut self, path: impl Into<String>, attr: impl Into<String>) -> Self {
        self.type_attrs.push((path.into(), attr.into()));
        self
    }

    /// Add a field-level attribute to a generated field.
    pub fn field_attribute(mut self, path: impl Into<String>, attr: impl Into<String>) -> Self {
        self.field_attrs.push((path.into(), attr.into()));
        self
    }

    /// Add an extern path mapping.
    pub fn extern_path(
        mut self,
        proto_path: impl Into<String>,
        rust_path: impl Into<String>,
    ) -> Self {
        self.extern_paths
            .push((proto_path.into(), rust_path.into()));
        self
    }

    /// Attach an attribute to the generated server module for `path`.
    ///
    /// Useful for e.g. `#[cfg(feature = "server")]` or `#[allow(...)]`.
    pub fn server_mod_attribute(
        mut self,
        path: impl Into<String>,
        attr: impl Into<String>,
    ) -> Self {
        self.server_mod_attrs.push((path.into(), attr.into()));
        self
    }

    /// Attach an attribute to the generated client module for `path`.
    pub fn client_mod_attribute(
        mut self,
        path: impl Into<String>,
        attr: impl Into<String>,
    ) -> Self {
        self.client_mod_attrs.push((path.into(), attr.into()));
        self
    }

    /// Generate map fields under `path` as `BTreeMap` instead of `HashMap`.
    pub fn btree_map(mut self, path: impl Into<String>) -> Self {
        self.btree_maps.push(path.into());
        self
    }

    /// Generate `bytes` fields under `path` as `bytes::Bytes` instead of `Vec<u8>`.
    pub fn bytes(mut self, path: impl Into<String>) -> Self {
        self.bytes_paths.push(path.into());
        self
    }

    /// Also generate Rust types for the protobuf well-known types
    /// (e.g. `google.protobuf.Timestamp`) instead of treating them as extern.
    pub fn compile_well_known_types(mut self, enable: bool) -> Self {
        self.compile_well_known_types = enable;
        self
    }

    /// Write the serialized `FileDescriptorSet` to `path` for runtime
    /// reflection (feed the bytes to `oxirpc-reflect`).
    pub fn file_descriptor_set_path(mut self, path: impl Into<std::path::PathBuf>) -> Self {
        self.fds_path = Some(path.into());
        self
    }

    /// Generate a single include file at `path` (relative to `out_dir`) listing
    /// `include!` statements for every generated module.
    pub fn include_file(mut self, path: impl Into<std::path::PathBuf>) -> Self {
        self.include_file = Some(path.into());
        self
    }

    /// Sets the codec path for generated gRPC service code.
    ///
    /// When set, generated client and server stubs will use `codec_path` as the codec
    /// implementation instead of the default `tonic::codec::ProstCodec`.
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// oxirpc_build::Builder::new()
    ///     .codec("my_crate::MyCodec")
    ///     .compile(&["proto/service.proto"], &["proto"])
    ///     .unwrap();
    /// ```
    pub fn codec(mut self, codec_path: impl Into<String>) -> Self {
        self.codec_path = Some(codec_path.into());
        self
    }

    /// Register a progress callback invoked at compilation checkpoints.
    ///
    /// The callback receives a short message string: `"parsing protos..."`,
    /// `"generating code..."`, or `"writing output..."`.
    pub fn on_progress<F>(mut self, cb: F) -> Self
    where
        F: Fn(&str) + Send + Sync + 'static,
    {
        self.progress_cb = Some(std::sync::Arc::new(cb) as ProgressCallback);
        self
    }

    /// Disable package module emission in generated code.
    ///
    /// When set, the code generator will **not** wrap generated types in Rust
    /// module declarations mirroring the proto `package` hierarchy.  All
    /// generated types are placed in the root module of the generated file
    /// rather than nested inside `pub mod my_package { … }`.
    ///
    /// **Native path (default):** this flag is silently ignored because
    /// [`codegen::ServiceCodegen`] never wraps service modules in a package
    /// hierarchy — service stubs are always emitted at the top level of the
    /// generated file.
    ///
    /// **Legacy path (`legacy-tonic-codegen` feature):** forwarded directly to
    /// `tonic_prost_build::Builder::emit_package(false)`.
    /// Requires `tonic-prost-build >= 0.14`.
    pub fn disable_package_emission(mut self) -> Self {
        self.disable_package_emission = true;
        self
    }

    // -----------------------------------------------------------------------
    // Core compilation methods
    // -----------------------------------------------------------------------

    /// Parse `.proto` files via `oxiproto-build` and return the raw
    /// [`prost_types::FileDescriptorSet`] without generating any code.
    ///
    /// Useful for downstream tooling (reflection, custom codegen) that needs
    /// the descriptor set directly.
    ///
    /// When called from inside a Cargo build script (`OUT_DIR` is set), this
    /// method checks the incremental build cache at
    /// `$OUT_DIR/.oxirpc-cache/fds-<hash>.bin`.  If the cache exists and is newer
    /// than all proto files and include directories the cached descriptor set
    /// is returned immediately, skipping the parse step entirely.
    pub fn compile_to_fds(
        &self,
        protos: &[impl AsRef<Path>],
        includes: &[impl AsRef<Path>],
    ) -> Result<prost_types::FileDescriptorSet, OxiRpcBuildError> {
        // ------------------------------------------------------------------
        // Attempt a cache hit before running protox.
        // ------------------------------------------------------------------
        let out_dir_path = std::env::var_os("OUT_DIR").map(std::path::PathBuf::from);

        if let Some(ref out_dir) = out_dir_path {
            if let Some(cached) = cache::try_load(out_dir, protos, includes) {
                return Ok(cached);
            }
        }

        // ------------------------------------------------------------------
        // Cache miss: parse via oxiproto-build.
        // ------------------------------------------------------------------
        let fds = oxiproto_build::compile_to_fds(protos, includes).map_err(from_oxiproto_error)?;

        // Write to cache (best-effort — don't fail the build on error).
        if let Some(ref out_dir) = out_dir_path {
            let _ = cache::write(out_dir, protos, &fds);
        }

        Ok(fds)
    }

    /// Compile proto files to tonic client/server stubs.
    ///
    /// Consumes `self`.  Uses `oxiproto-build` (pure Rust, no `protoc`) to
    /// parse and resolve `.proto` files, then feeds the resulting
    /// `FileDescriptorSet` to the active codegen backend:
    ///
    /// - **Default (native):** [`codegen::ServiceCodegen`] — emits service
    ///   stubs only (`*_server` / `*_client` modules).  Message types are NOT
    ///   generated; provide them via `prost_build` or enable
    ///   `legacy-tonic-codegen`.
    /// - **`legacy-tonic-codegen` feature:** `tonic_prost_build::compile_fds`
    ///   — generates both prost message types and service stubs.
    ///
    /// Prefer [`Builder::compile_checked`] for a `&self` variant that also
    /// returns import-validation warnings.
    pub fn compile(
        self,
        protos: &[impl AsRef<Path>],
        includes: &[impl AsRef<Path>],
    ) -> Result<(), OxiRpcBuildError> {
        // Parse + resolve .proto files via oxiproto-build — no protoc spawned.
        let fds = self.compile_to_fds(protos, includes)?;
        self.run_codegen(fds)
    }

    /// Compile proto files to tonic stubs, returning non-fatal
    /// import-validation [`warnings`](CompileOutput::warnings).
    ///
    /// This is the `&self` counterpart to [`compile()`](Builder::compile).
    /// It clones the builder internally so the receiver is not consumed.
    pub fn compile_checked(
        &self,
        protos: &[impl AsRef<Path>],
        includes: &[impl AsRef<Path>],
    ) -> Result<CompileOutput, OxiRpcBuildError> {
        if let Some(cb) = &self.progress_cb {
            cb("parsing protos...");
        }
        let fds = self.compile_to_fds(protos, includes)?;
        let warnings = validate_imports(&fds);
        if let Some(cb) = &self.progress_cb {
            cb("generating code...");
        }
        self.clone().run_codegen(fds)?;
        if let Some(cb) = &self.progress_cb {
            cb("writing output...");
        }
        Ok(CompileOutput { warnings })
    }

    /// Compile a `.proto` source string without needing a physical file.
    ///
    /// Writes `src` to a temporary file named `{name}.proto` inside a
    /// process-unique subdirectory of [`std::env::temp_dir()`], compiles it,
    /// and cleans up — even on error (via a drop guard).
    ///
    /// The `name` parameter is used as the proto file name (without the
    /// `.proto` extension).  Returns the same import-validation warnings as
    /// [`compile_checked`](Builder::compile_checked).
    pub fn compile_str(&self, name: &str, src: &str) -> Result<CompileOutput, OxiRpcBuildError> {
        let dir = std::env::temp_dir().join(format!("oxirpc-build-str-{}", std::process::id()));
        std::fs::create_dir_all(&dir).map_err(OxiRpcBuildError::Io)?;

        // Drop guard — cleans up the temp directory even on error.
        struct DirGuard(std::path::PathBuf);
        impl Drop for DirGuard {
            fn drop(&mut self) {
                let _ = std::fs::remove_dir_all(&self.0);
            }
        }
        let _guard = DirGuard(dir.clone());

        let proto_path = dir.join(format!("{name}.proto"));
        std::fs::write(&proto_path, src).map_err(OxiRpcBuildError::Io)?;

        self.compile_checked(&[&proto_path], &[&dir])
    }

    // -----------------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------------

    /// Run codegen from an already-resolved FDS.
    ///
    /// Consumes `self` so the builder settings can be forwarded without cloning.
    ///
    /// **Default path:** uses the native [`ServiceCodegen`] to emit service
    /// stubs into `out_dir` (or `$OUT_DIR`).  Settings such as `type_attrs`,
    /// `field_attrs`, `btree_maps`, `bytes_paths`, and `extern_paths` are
    /// silently ignored — they apply only to the legacy path.
    ///
    /// **`legacy-tonic-codegen` feature:** delegates to
    /// `tonic_prost_build::compile_fds`, forwarding all Builder settings.
    fn run_codegen(self, fds: prost_types::FileDescriptorSet) -> Result<(), OxiRpcBuildError> {
        #[cfg(feature = "legacy-tonic-codegen")]
        {
            self.run_codegen_legacy(fds)
        }
        #[cfg(not(feature = "legacy-tonic-codegen"))]
        {
            self.run_codegen_native(fds)
        }
    }

    /// Native codegen path: emit service stubs via [`ServiceCodegen`].
    #[cfg(not(feature = "legacy-tonic-codegen"))]
    fn run_codegen_native(
        self,
        fds: prost_types::FileDescriptorSet,
    ) -> Result<(), OxiRpcBuildError> {
        // Determine output directory: explicit override, or $OUT_DIR from Cargo.
        let out_dir = match self.out_dir {
            Some(d) => d,
            None => {
                let raw = std::env::var("OUT_DIR").map_err(|_| {
                    OxiRpcBuildError::Codegen(
                        "OUT_DIR is not set; call Builder::out_dir() or run inside a build script"
                            .into(),
                    )
                })?;
                std::path::PathBuf::from(raw)
            }
        };

        let mut codegen = ServiceCodegen::new();
        codegen.emit_client = self.build_client;
        codegen.emit_server = self.build_server;
        if let Some(ref codec) = self.codec_path {
            codegen.codec_path = codec.clone();
        }

        file_gen::generate_services(&fds, &out_dir, &codegen)?;

        // Write the serialised FileDescriptorSet if requested.
        if let Some(ref fds_path) = self.fds_path {
            use prost::Message as _;
            let encoded = fds.encode_to_vec();
            std::fs::write(fds_path, encoded)?;
        }

        Ok(())
    }

    /// Legacy codegen path: delegate to `tonic_prost_build::compile_fds`.
    #[cfg(feature = "legacy-tonic-codegen")]
    fn run_codegen_legacy(
        self,
        fds: prost_types::FileDescriptorSet,
    ) -> Result<(), OxiRpcBuildError> {
        let mut cfg = tonic_prost_build::configure()
            .build_client(self.build_client)
            .build_server(self.build_server)
            .compile_well_known_types(self.compile_well_known_types);

        if let Some(ref out) = self.out_dir {
            cfg = cfg.out_dir(out);
        }
        if let Some(ref fds_path) = self.fds_path {
            cfg = cfg.file_descriptor_set_path(fds_path);
        }
        if let Some(ref inc) = self.include_file {
            cfg = cfg.include_file(inc);
        }

        for (path, attr) in &self.type_attrs {
            cfg = cfg.type_attribute(path, attr);
        }
        for (path, attr) in &self.field_attrs {
            cfg = cfg.field_attribute(path, attr);
        }
        for (proto, rust) in &self.extern_paths {
            cfg = cfg.extern_path(proto, rust);
        }
        for (path, attr) in &self.server_mod_attrs {
            cfg = cfg.server_mod_attribute(path, attr);
        }
        for (path, attr) in &self.client_mod_attrs {
            cfg = cfg.client_mod_attribute(path, attr);
        }
        for path in &self.btree_maps {
            cfg = cfg.btree_map(path);
        }
        for path in &self.bytes_paths {
            cfg = cfg.bytes(path);
        }
        if let Some(ref path) = self.codec_path {
            cfg = cfg.codec_path(path);
        }
        if self.disable_package_emission {
            cfg = cfg.emit_package(false);
        }

        cfg.compile_fds(fds)
            .map_err(|e| OxiRpcBuildError::Codegen(e.to_string()))
    }
}

impl Default for Builder {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Import validation
// ---------------------------------------------------------------------------

/// Inspect a `FileDescriptorSet` for common proto structure problems.
///
/// Returns a list of human-readable warning strings.  These are non-fatal —
/// compilation already succeeded at this point.
///
/// Currently checks:
/// - Files without a `package` declaration.
/// - Imports of `google/protobuf/*.proto` when nothing in the file references
///   the `google.protobuf.*` namespace (likely unused import).
fn validate_imports(fds: &prost_types::FileDescriptorSet) -> Vec<String> {
    let mut warnings = Vec::new();

    for file in &fds.file {
        let file_name = file.name().to_owned();

        // --- missing package declaration ---
        if file.package().is_empty() && !file_name.is_empty() {
            warnings.push(format!(
                "{file_name}: no package declaration \
                 (consider adding 'package your.package;')"
            ));
        }

        // --- potentially unused google.protobuf.* imports ---
        for dep in &file.dependency {
            if !dep.starts_with("google/protobuf/") {
                continue;
            }

            // Check whether any field, message extension, or service method
            // references the "google.protobuf." prefix.
            let referenced = file_references_google_protobuf(file);
            if !referenced {
                warnings.push(format!(
                    "{file_name}: imports '{dep}' but no types from \
                     'google.protobuf.*' are referenced \
                     (possibly unused import)"
                ));
            }
        }
    }

    warnings
}

/// Returns `true` if any field, extension, or method in `file` references a
/// type whose name starts with `google.protobuf.`.
fn file_references_google_protobuf(file: &prost_types::FileDescriptorProto) -> bool {
    const PREFIX: &str = ".google.protobuf.";

    // Check message fields and nested messages (one level deep is enough for
    // the heuristic).
    for msg in &file.message_type {
        for field in &msg.field {
            if field.type_name().starts_with(PREFIX) {
                return true;
            }
            if field.extendee().starts_with(PREFIX) {
                return true;
            }
        }
        for ext in &msg.extension {
            if ext.type_name().starts_with(PREFIX) || ext.extendee().starts_with(PREFIX) {
                return true;
            }
        }
    }

    // Top-level extensions
    for ext in &file.extension {
        if ext.type_name().starts_with(PREFIX) || ext.extendee().starts_with(PREFIX) {
            return true;
        }
    }

    // Service method input/output types
    for svc in &file.service {
        for method in &svc.method {
            if method.input_type().starts_with(PREFIX) || method.output_type().starts_with(PREFIX) {
                return true;
            }
        }
    }

    false
}

// ---------------------------------------------------------------------------
// Convenience function
// ---------------------------------------------------------------------------

/// Compile proto files to tonic stubs. Convenience wrapper around [`Builder`].
///
/// Writes generated files to `OUT_DIR` (set by cargo during a build script).
pub fn compile_protos(
    protos: &[impl AsRef<Path>],
    includes: &[impl AsRef<Path>],
) -> Result<(), OxiRpcBuildError> {
    Builder::new().compile(protos, includes)
}
