[package]
name = "oxiphysics-fem"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Finite element method for the OxiPhysics engine"
readme = "README.md"
categories = ["science", "simulation", "mathematics"]
keywords = ["fem", "finite-element", "structural-analysis", "physics", "simulation"]

[dependencies]
thiserror = { workspace = true }
rayon = { workspace = true }
oxiphysics-core = { workspace = true }
oxiphysics-materials = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "amg_poisson"
harness = false

[[bench]]
name = "amg_elasticity"
harness = false
