//! Advanced `SubStation` Alpha (ASS) format parser and writer

use crate::error::{CaptionError, Result};
use crate::formats::{FormatParser, FormatWriter};
use crate::types::{Caption, CaptionTrack, Language, Timestamp};
use std::collections::HashMap;

/// ASS format parser
pub struct AssParser;

impl FormatParser for AssParser {
    fn parse(&self, data: &[u8]) -> Result<CaptionTrack> {
        let text = std::str::from_utf8(data).map_err(|e| CaptionError::Encoding(e.to_string()))?;

        parse_ass(text)
    }
}

/// ASS format writer
pub struct AssWriter;

impl FormatWriter for AssWriter {
    fn write(&self, track: &CaptionTrack) -> Result<Vec<u8>> {
        let mut output = String::new();

        // Script Info section
        output.push_str("[Script Info]\n");
        output.push_str("; Script generated by OxiMedia Captions\n");
        if let Some(title) = &track.metadata.title {
            output.push_str(&format!("Title: {title}\n"));
        }
        output.push_str("ScriptType: v4.00+\n");
        output.push_str("WrapStyle: 0\n");
        output.push_str("PlayResX: 1920\n");
        output.push_str("PlayResY: 1080\n");
        output.push_str("ScaledBorderAndShadow: yes\n\n");

        // V4+ Styles section
        output.push_str("[V4+ Styles]\n");
        output.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
        output.push_str("Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n");

        // Events section
        output.push_str("[Events]\n");
        output.push_str(
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
        );

        for caption in &track.captions {
            let start = format_timestamp(caption.start);
            let end = format_timestamp(caption.end);
            let speaker = caption.speaker.as_deref().unwrap_or("");
            let text = format_ass_text(&caption.text);

            output.push_str(&format!(
                "Dialogue: 0,{start},{end},Default,{speaker},0,0,0,,{text}\n"
            ));
        }

        Ok(output.into_bytes())
    }
}

fn parse_ass(text: &str) -> Result<CaptionTrack> {
    let mut track = CaptionTrack::new(Language::english());
    let mut in_events = false;
    let mut format_fields = Vec::new();

    for line in text.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("[Events]") {
            in_events = true;
            continue;
        }

        if trimmed.starts_with('[') && in_events {
            // New section, stop parsing events
            break;
        }

        if in_events {
            if trimmed.starts_with("Format:") {
                // Parse format line
                let fields = trimmed.strip_prefix("Format:").unwrap_or("");
                format_fields = fields.split(',').map(|s| s.trim().to_string()).collect();
            } else if trimmed.starts_with("Dialogue:") || trimmed.starts_with("Comment:") {
                if let Ok(caption) = parse_dialogue_line(trimmed, &format_fields) {
                    track.add_caption(caption)?;
                }
            }
        }
    }

    Ok(track)
}

fn parse_dialogue_line(line: &str, format_fields: &[String]) -> Result<Caption> {
    let _is_comment = line.starts_with("Comment:");
    let line = line
        .strip_prefix("Dialogue:")
        .or_else(|| line.strip_prefix("Comment:"))
        .ok_or_else(|| CaptionError::Parse("Invalid dialogue line".to_string()))?;

    let parts: Vec<&str> = line
        .splitn(format_fields.len(), ',')
        .map(str::trim)
        .collect();

    let mut fields_map = HashMap::new();
    for (i, field_name) in format_fields.iter().enumerate() {
        if let Some(value) = parts.get(i) {
            fields_map.insert(field_name.as_str(), *value);
        }
    }

    let start = parse_ass_timestamp(
        fields_map
            .get("Start")
            .ok_or_else(|| CaptionError::Parse("Missing Start field".to_string()))?,
    )?;

    let end = parse_ass_timestamp(
        fields_map
            .get("End")
            .ok_or_else(|| CaptionError::Parse("Missing End field".to_string()))?,
    )?;

    let text = (*fields_map
        .get("Text")
        .ok_or_else(|| CaptionError::Parse("Missing Text field".to_string()))?)
    .to_string();

    let text = clean_ass_text(&text);

    let mut caption = Caption::new(start, end, text);

    if let Some(speaker) = fields_map.get("Name") {
        if !speaker.is_empty() {
            caption.speaker = Some((*speaker).to_string());
        }
    }

    Ok(caption)
}

fn parse_ass_timestamp(s: &str) -> Result<Timestamp> {
    // Format: H:MM:SS.cc (centiseconds)
    let parts: Vec<&str> = s.split(':').collect();
    if parts.len() != 3 {
        return Err(CaptionError::Parse(format!("Invalid timestamp: {s}")));
    }

    let hours = parts[0]
        .parse::<u32>()
        .map_err(|e| CaptionError::Parse(e.to_string()))?;
    let minutes = parts[1]
        .parse::<u32>()
        .map_err(|e| CaptionError::Parse(e.to_string()))?;

    let sec_parts: Vec<&str> = parts[2].split('.').collect();
    let seconds = sec_parts[0]
        .parse::<u32>()
        .map_err(|e| CaptionError::Parse(e.to_string()))?;
    let centis = sec_parts
        .get(1)
        .unwrap_or(&"0")
        .parse::<u32>()
        .map_err(|e| CaptionError::Parse(e.to_string()))?;

    Ok(Timestamp::from_hmsm(hours, minutes, seconds, centis * 10))
}

fn format_timestamp(ts: Timestamp) -> String {
    let (h, m, s, ms) = ts.as_hmsm();
    let centis = ms / 10;
    format!("{h}:{m:02}:{s:02}.{centis:02}")
}

fn clean_ass_text(text: &str) -> String {
    // Remove ASS formatting tags
    let mut result = String::new();
    let mut in_tag = false;

    for ch in text.chars() {
        if ch == '{' {
            in_tag = true;
        } else if ch == '}' {
            in_tag = false;
        } else if !in_tag {
            result.push(ch);
        }
    }

    // Replace \N with actual newlines
    result.replace("\\N", "\n").replace("\\n", "\n")
}

fn format_ass_text(text: &str) -> String {
    // Replace newlines with \N
    text.replace('\n', "\\N")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_ass() {
        let ass = b"[Script Info]\nTitle: Test\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,Test caption\n";
        let parser = AssParser;
        let track = parser.parse(ass).expect("parsing should succeed");

        assert_eq!(track.captions.len(), 1);
        assert_eq!(track.captions[0].text, "Test caption");
    }

    #[test]
    fn test_clean_ass_text() {
        let text = "{\\i1}Italic{\\i0} normal {\\b1}bold{\\b0}";
        let cleaned = clean_ass_text(text);
        assert_eq!(cleaned, "Italic normal bold");
    }

    #[test]
    fn test_timestamp_parsing() {
        let ts = parse_ass_timestamp("1:30:45.50").expect("timestamp parsing should succeed");
        assert_eq!(ts.as_hmsm(), (1, 30, 45, 500));
    }
}
